### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [PowerDNS-Admin/PowerDNS-Admin#1001]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by zoeller-freinet** [comment]
Hi @JamieSlome, thank you for reaching out!

I'm planning to add official security contact details to a central location - until that's ready you can send a mail describing your findings to zoeller [at] freinet [dot] de, I'll try to answer in a timely fashion.

**Comment by JamieSlome** [comment]
@zoeller-freinet - apologies for the delayed response from me!

If it is easier, you can view the reports here:

https://huntr.dev/bounties/e16924fb-9964-4164-83e6-ce22e1210e4c/
https://huntr.dev/bounties/edee3f4c-5340-4766-982d-131b008a3b85/
https://huntr.dev/bounties/3fba7172-49ad-4de8-8210-982d0daa5343/

The reports are private, and only visible to maintainers with repository write permissions.

Let me know if there is anything I can do to support you further! 👍

**Comment by wdoekes** [comment]
Hi! :)

Was this followed up?

**Comment by jbe-dw** [comment]
I'm afraid it was not.

**Comment by zoeller-freinet** [comment]
Not by me, sorry – I quit my maintainer role in February after informing Khanh and RGanor because my situation changed and the time I could allot to PowerDNS-Admin unfortunately went from ~3h/week to basically none (see also https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1032#issuecomment-1049103506). I encourage the current team of collaborators to look into this issue.

**Comment by AzorianSolutions** [comment]
@JamieSlome thank you again for your reports on the matter. I can't set expectations of timing yet, but I have reviewed these reports and I will see too it they get addressed somehow.
