### ISSUE TITLE
zone display page showing all 90000 records without separting them by page causing powerdns-admin to crash.

### ISSUE THREAD

**Issue by thelegend3** [PowerDNS-Admin/PowerDNS-Admin#1009]
Hello !

I'm migrating my old pdns/poweradmin servers to a new pdns/powedns-admin.

I migrated all my 900 domains by creating the new zones as slaves on the new server directly in the powerdns database and doing a AXFR from my old master server.

Everything works perfectly except one of the biggest zones i migrated.

I have around 90k records on that zone.

At first when i clicked on the manage button of the zone i had a 502 Bad Gateway error on nginx and the following error in the logs: 

[webserver] bae0ee9c-0794-4d84-b01d-1f7ead4c56bf Result for "/api/v1/servers/localhost/zones/xxxx.net": 200, body length: 12339962
Sep 29 15:00:38 pdns2 pdns_server[781]: [webserver] bae0ee9c-0794-4d84-b01d-1f7ead4c56bf 127.0.0.1:46398 "GET /api/v1/servers/localhost/zones/xxxx.net HTTP/1.1" 200 12340323
Sep 29 15:01:06 pdns2 gunicorn[1119]: [2021-09-29 15:01:06 -0400] [1119] [CRITICAL] WORKER TIMEOUT (pid:1138)

After increasing the timeout to 120 for gunicorn in /gunicorn/config.py the zone page is loading and i can see the records. But instead of separating them by 15 records by page as defined in the default_record_table_size it tries to load the full 90k records in one page. Because of that i'm not able to make any modification to this zone without the GUI crashing again.

For this specific zone i also tried to delete the zone and import it with a bind zone file but at the end had the same result.

Is there any kind of limitation on the numbers of records in a single zone ?

Any kind of help would be greatly appreciated.

Thanks !

**Comment by jbe-dw** [comment]
Hello,

There is no coded limit about # of records, it is probably a limitation on the Javascript code used to display the tables and do pagination.

We can look further if you still have the issue.

Regards

**Comment by nitemayr** [comment]
I'm having the same problem with a zone I AXFR'd in

 grep ' IN A ' zonename.com |wc -l
135
grep ' IN PTR zonename.com |wc -l
1306

but when I try to view the zone in powerdns-admin it times out, is there a debug statement or log setting to help troubleshoot this?
