### ISSUE TITLE
Feature: Enable OTP on first Login for all User

### ISSUE THREAD

**Issue by a1d3s** [PowerDNS-Admin/PowerDNS-Admin#1010]
Hello,
how can i force OTP to all Users on first login?
So the User havn't to enable it by himself.
Old One: https://github.com/ngoduykhanh/PowerDNS-Admin/issues/550

**Comment by a1d3s** [comment]
@ngoduykhanh is there any option?

**Comment by a1d3s** [comment]
That it may doesn't exist is not what I ask. I need this as feature. 
Why should I close the issue? Maybe someone can add this option in the backend?

**Comment by seraphyn** [comment]
Cu
> Why should I close the issue?
Had I Said that?
😉

Stay safe and healthy

**Comment by zoeller-freinet** [comment]
This should be implemented now by #1051.
