### ISSUE TITLE
Bulk delete records from zone

### ISSUE THREAD

**Issue by samip5** [PowerDNS-Admin/PowerDNS-Admin#1015]
Hi,

I would love to be able to bulk delete records by first selecting all of the ones I want to delete, and then clicking final delete and then Apply Changes.

**Comment by mmaFR** [comment]
Hello,

Indeed, it would be very handy to be able to bulk delete records.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
