### ISSUE TITLE
Support IPv4 mapped IPv6 addresses

### ISSUE THREAD

**Issue by yggdr** [PowerDNS-Admin/PowerDNS-Admin#1023]
PowerDNS itself works fine with IPv6 addresses of the form `2001:db8:1:2::192.0.2.56`, but PowerDNS-Admin doesn't let one apply a AAAA record with such an address. And any address already in Postgres of that form gets displayed in the webinterface translated to a regular IPv6 address.

**Comment by AzorianSolutions** [comment]
@yggdr Granted I'm not a Python developer, I scanned the code and it appears the issue you are seeing is actually a PowerDNS API issue and not a PowerDNS Admin issue. Perhaps consider reporting this issue here: https://github.com/PowerDNS/pdns/issues
