### ISSUE TITLE
Updates & Looking for maintainers

### ISSUE THREAD

**Issue by ngoduykhanh** [PowerDNS-Admin/PowerDNS-Admin#1032]
Hello everyone,

This is Khanh, the creator of PowerDNS-Admin.
Sorry for being away for a long time. I would like to create this "issue" to update you on my current contribution status for PDA.

As I am not using PowerDNS anymore and have a new job, I have very little time that I can spend maintaining PowerDNS-Admin. However, I know there are still a lot of people who are using it and want to keep this project alive. So, I am looking for new maintainers for PowerDNS-Admin. If you are using it and interested in maintaining an open-source project, feel free to reach out to me at k[at]ndk.name. I am also thinking of transferring the project to an organization when it gets more maintainers.

There are still a lot of Pull Requests from you that need to be reviewed and merged. I will try to clear them this weekend.

Best,
Khanh

**Comment by AzorianSolutions** [comment]
I am currently not able to offer a regular and reliable commitment but I will gladly try help manage this a bit as time permits if you like.

**Comment by AzorianSolutions** [comment]
@ngoduykhanh I have reconsidered and decided I would really like to do a lot with this project. Will you please promote me to a maintainer?

**Comment by zoeller-freinet** [comment]
Regrettably, I do not have enough time to help maintain PowerDNS-Admin anymore - in contrast with last November, when I first contacted Khanh - and I don't feel comfortable being part of the group of collaborators any longer just for the hope that this might change, which is currently uncertain at best.

I've therefore handed back the collaborator role, but may still contribute on occasion.
