### ISSUE TITLE
Expired csrf token on login page

### ISSUE THREAD

**Issue by jbe-dw** [PowerDNS-Admin/PowerDNS-Admin#1062]
Hello,

I am often kicked out of PDA after the timeout. It then redirects me on the login page which has a token created at this moment. If I try to log in another timeout later, I have an unauthorized error and have to login again.

Is it a good idea to have an ajax call that request a new token every "timeout - 10s" on the login page or is it a security issue to do so ?

I'm not good on this point, just asking because it happens to me a lot to leave a tab open and have to login twice.

Regards

**Comment by zoeller-freinet** [comment]
I have been running into this issue as well, and have been meaning to work on a fix for this.

**Comment by jbe-dw** [comment]
Or is it even easier to have just a window.reload() loop on the login page ?
