### ISSUE TITLE
History: DynDNS Changes are not logged with details

### ISSUE THREAD

**Issue by Metrax** [PowerDNS-Admin/PowerDNS-Admin#1075]
It would be nice, if the DynDNS changes will also be logged with Details, like changes via WebUI and API.

![image](https://user-images.githubusercontent.com/1061866/145377156-ac0c3dd8-0def-49a3-8e14-3c20c4b6f41c.png)

**Comment by jbe-dw** [comment]
Hello @Metrax 

I don't have time to look at the code, but is the master branch giving more details now ?

Regards

**Comment by Metrax** [comment]
@jbe-dw nope, no change at master for this issue. Its still an inconsistancy in handling RR changes.
