### ISSUE TITLE
AD Authentication and Group Security case sensitivity

### ISSUE THREAD

**Issue by tardich** [PowerDNS-Admin/PowerDNS-Admin#1088]
Hi, I have been trying to find out what was wrong with the autorizations for more than two days (not easy to find out, as our ldap communications are all encrypted). But, finally, I observed that the groups are not all lowercase on our AD tree.

So I changed, in my ldap/AD configuration the groups definitions to look EXACTLY like what I see in the AD (mix of lowercase and uppercase) and it worked !!!

So I guess that everything received should be lowercased before the comparison to avoid a false positive.

**Comment by jbe-dw** [comment]
Hello,

Thanks for the feedback. The team should discuss this to decide if it is relevant or not.

Regards
