### ISSUE TITLE
Authentication redirect doesn't take server port into account

### ISSUE THREAD

**Issue by zyndok** [PowerDNS-Admin/PowerDNS-Admin#1094]
I configure

./etc/nginx/conf.d/pdns-admin.conf
with 

server {
  listen        0.0.0.0:8990;

When I attempted to connect, the port is dropped off 302 url.

root@powerdns:/# curl -I 192.168.200.1:8990
HTTP/1.1 302 FOUND
Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 04 Jan 2022 01:13:27 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 218
Connection: keep-alive
Location: http://192.168.200.1/login

same when I try off host of powerdns+admin

[zyn@fast ~]$ curl -I 192.168.200.1:8990
HTTP/1.1 302 FOUND
Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 04 Jan 2022 01:16:06 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 218
Connection: keep-alive
Location: http://192.168.200.1/login

See both cases, Location is to http://192.168.200.1/login rather than http://192.168.200.1:8990/login

thank you

**Comment by zyndok** [comment]
Note, I left off cookies when copy and pasting responses.

**Comment by jbe-dw** [comment]
Hello,

Could you fix your issue ?

Regards
