### ISSUE TITLE
[Feature request] Support for GeoIP backend

### ISSUE THREAD

**Issue by tompointexe** [PowerDNS-Admin/PowerDNS-Admin#1095]
Hey, would it be possible to have support for the PowerDNS geoip backend for easy to manage DNS for a custom / homemade CDN ??
Thanks

**Comment by jbe-dw** [comment]
Hello,

Sorry for the late answer. We can add your request to the long list of pending features, but it won't be added in priority. It will depend on the new PDA lifecycle.

Regards

**Comment by jbe-dw** [comment]
I'm closing this, you can check later if someone worked on it or propose a PR.

Regards
