### ISSUE TITLE
PowerDNS-Admin version missing

### ISSUE THREAD

**Issue by johnwc** [PowerDNS-Admin/PowerDNS-Admin#1096]
There is no way from the UI to see what version you are running of PowerDNS-Admin. Can we get a version number added to the footer or somewhere noticeable?

**Comment by Alestor** [comment]
Please considering reveal that kind of information **after** successful login, in case vulnerabilities may be discovered in the future associated with a specific version.

**Comment by subbink** [comment]
it seems to me that this has been fixed in v0.4.0 with commit dd867eb4e8fa10420f0b92bbc24913665f263457

**Comment by AzorianMatt** [comment]
@johnwc @Alestor this has indeed been taken care of in the recent 0.4.0 release so I'm closing the issue.
