### ISSUE TITLE
Bug: Special characters in Record data are altered

### ISSUE THREAD

**Issue by vmarkop** [PowerDNS-Admin/PowerDNS-Admin#1098]
When Applying Changes to a domain, if an HTML special character (<, & etc.) is present in a Record's data, the special character is replaced by its character reference, even if it was not modified.

This problem is exaggerated by the fact that the "&" character, which is found in all character references, is then recursively replaced with "&amp;" every time changes are applied, which can lead to infinitely long comments.

### Showcase:

Before state:
![Domain4](https://user-images.githubusercontent.com/83133031/149339298-4ebdcfb4-edec-4db4-98a1-ae0ffe0df43c.png)

A change to "testrecord" is applied, and record1's comment is corrupted.
![Domain6_AfterApplyChanges](https://user-images.githubusercontent.com/83133031/149339307-3a724927-f402-4ea7-ab4f-d034d7aec3fe.png)

"Apply Changes" is clicked once more, which again alters record1's comment
![Domain8_AfterApply](https://user-images.githubusercontent.com/83133031/149339314-a0f35b0b-a49d-4289-8551-b6a4ba164457.png)

After applying another change, the comment keeps growing...
![Domain9](https://user-images.githubusercontent.com/83133031/149339317-31734e92-a8b2-46c9-bc06-6119b71ee53f.png)

**Comment by AdvanticGmbH** [comment]
@vmarkop and @kkmanos could you please take a look if this pr helps with this issue, thanks.

**Comment by vmarkop** [comment]
Fixed by #1158.
Thanks @AdvanticGmbH!
