### ISSUE TITLE
Feature: Custom Roles

### ISSUE THREAD

**Issue by kkmanos** [PowerDNS-Admin/PowerDNS-Admin#1099]
Hello,
Our organization (https://www.gunet.gr/en/) is considering adding custom Roles to the application, which are built upon the limited User role, to give specific entities just enough control in the application.

Currently, user's access to powerful mechanisms such as History Access, or Domain Creation and Deletion, are controlled with global Settings. Also, all users, including Administrators, can modify all Record types, and there is no read-only mechanism implemented for records.

The granularity of PDA’s access control rules might not be sufficient in case of multi level dev-ops and helpdesk IT departments where you need finer control over who has access, to perform specific actions (e.g. read or write) on specific resource types.

Please let us know if our team should proceed with working on these features. Since this is a major change that would move PowerDNS-Admin to a new direction, any feedback or conversation is encouraged.

**Comment by kkmanos** [comment]
Hello!
There has been some progress since this issue was opened. 

The new roles, which are built upon the User role, give Users Read or Write access to some record types, in all Domains they can view. Additionally, the settings "DNSSEC Admins Only, Allow Users Add Domain, Allow Users Remove Domain, Allow Users View History", can now be configured per role.

The Read/Write permissions apply for all Roles, including administrative roles (Administrators and Operators), but the settings (Add/Remove Domain, View History, Change DNSSEC) are only modifiable for the User Role and new Custom Roles.

Issue #1098 is causing a lot of trouble, as it may cause changes on a Record's comment the user does not have access to, making it impossible to apply changes to the Domain.


API functions have been updated to comply with the permissions 
of the custom role they represent.


Last but not least, a proper database migration script has been produced
to adapt the databases to this feature.


One subjective detail that we cannot get right without receiving some feedback, are the differences between Administrators and Operators. Are there any features which Operators should be prevented from accessing or modifying, in order to separate their role from the Administrator role?

If you have any addition or comment about the implementation of this feature, please
let us know.

**Comment by arbaldin** [comment]
Hi there.

As far as I know, there are few things an Operator cannot do:

1. Clear the history;
2. Enable/Disable DNSSEC if the "dnssec_admins_only" option is enabled, and
even this one I'm in doubt.
3. Change PDNS-Admin settings.

Can't remember any other thing.

I think an Operator should not delete a Domain. They of course can delete
records inside a zone, but shouldn't be able to delete any domain. Instead,
an User that has admin rights over a domain could delete it.

Zone should only be deleted by an Administrator or User owner of it.


[]´s
Audrey

**Comment by kkmanos** [comment]
Hello! The Roles feature is on the final straight!
Therefore, we would like to sum up the feature to ensure we are all aligned on what PowerDNS-Admin really needs.

Everything mentioned in the main issue and the above reply still applies. However, we would like to further clear up the power of each Role below:
For each specific Role, Read-Write permissions for records are given separately.

Apart from record permissions, the settings
-  Allow History access
- Allow Domain creation
- Allow Domain removal
-  Allow DNSSEC configuration
- Allow to view/edit all domains

are customizable for each Role separately.
The Administrator Role always has access to all the features of the application. They may not have access to some DNS Records, but they can enable it themselves by editing their Role.

Roles can be edited by Administrators. For operators, a setting has been added to control whether they can edit Roles or not.

The new Custom Roles are non-administrative, based on the default, limited "User" Role. Administrator or Operator status cannot be mimicked by any new Role.

For non-administrative Roles, an option has been added to view and edit all Domains. This means they can view and edit Domain Records, but they still do not have Domain Ownership, meaning they cannot Remove the Domain or view its History.

If the above details are agreed upon by the community, we can proceed with submitting a Pull Request.

**Comment by adityaborgaonkar** [comment]
Hi there. @vmarkop @kkmanos @arbaldin 

We want to explore more features for custom roles mentioned in #1099. We want to restrict a role to only Add records to a domain but not Delete them. As seen in image (https://imgbb.com/qytHxyk) instead of R / W there would be Read / Add / Delete for diff record types. 

So can this be done and what other complexities will be there? 

Thanks

**Comment by kkmanos** [comment]
Hello @adityaborgaonkar , 

your suggestion is interesting, however disabling Record deletion is not straightforward, due to the way editing records is handled.

Specifically, editing a record is handled as a Deletion of the old record, and an Addition of a new record with the change made.

Therefore, restricting Record Deletions means that records cannot be edited either. Supposing we were to implement this, someone who adds a new Record and makes a typo would be unable to edit it, which could potentially cause more harm than good.

At the moment, the best workaround we can offer is to give a Custom Role Write access to a Record type and use the Changelog and History features to monitor record changes to a specific domain. If a record is deleted by someone who is instructed not to, detecting their action is straightforward this way.

Is there a use case in which the above behaviour cannot be applied, and it is vital to restrict record deletion, even with the danger that typos or other errors that cannot be undone could pose?


Is there a use case in which someone could truly benefit from an "Additions Only" permission setting for each Record Type?

**Comment by adityaborgaonkar** [comment]
Hey @kkmanos 

Our use case is for server build automation. So various teams are responsible for additions of new records for building new systems, But for deletion of record it has to go through a specific team for approval and only that team will delete the record.

If a user makes a typo while adding a new record, only that particular record is impacted which will be limited to the new system being built. But if a user accidentally deletes or modifies an existing record it will have a more severe impact as it can impact a system that is already in production.

In that case how is Addition of record handled? Can it be restricted per Record type so we can have something like Read Add Write. I think that might solve it for us.

**Comment by pixelrebel** [comment]
I would love a read-only role so we can share the zones as sort of an IPAM.  I don't see much value in separating edit and delete permissions, considering the same damage can be done with edit-only.  Just my 2¢.

**Comment by vmarkop** [comment]
Hello @pixelrebel,

Indeed, a read-only role can be created with this feature in its current state, as published in PR #1171.

You can create a Custom Role, toggle the options
'Allow to view and edit all domains for this role' and optionally
'Allow History access for this role',
and select Read-only access to all Records on the right, as so:

![Custom Roles img](https://user-images.githubusercontent.com/83133031/169990458-a5ead793-24ea-4979-8117-dfdefe19d5c9.png)
