### ISSUE TITLE
Enhancement request: Ability to change the font size of the records table

### ISSUE THREAD

**Issue by michielvisser** [PowerDNS-Admin/PowerDNS-Admin#110]
At the moment, the font size is quite large in the records table for a domain. Maybe it is possible to add a setting to PowerDNS-Admin to select font size in the tables? Personally I would prefer to have the font a little smaller so more records would fit in the screen.

I've tried this myself by editing the custom.css file. This does work but as the font size of the action buttons is not changed with this the records are still spaced the same.

**Comment by jbe-dw** [comment]
#944 is what you are looking for.

Regards
