### ISSUE TITLE
PowerDNS-admin can not work for ubuntu, phone(android, ios) Accept only windows

### ISSUE THREAD

**Issue by Pechsopha** [PowerDNS-Admin/PowerDNS-Admin#1102]
Could anyone help me please? When I set up Server PowerDNS-admin already and I assigned 2 DNS servers like PowerDNS-admin Server and 8.8.8.8 on my pfsence. For result, Ubuntu, phone(android, ios) can not access to all dns records Accept only Windows.

**Comment by a1d3s** [comment]
Do you have powerdns installed too? Powerdns-admin is only an administrator interface for that. And I think you need powerdns resolver too

**Comment by Pechsopha** [comment]
Dear Stefan Tabbert
Thank you for your email. I already installed powerdns-admin and also
powerdns resolver too(set up powerDNS recursor) in that time still not
working but when I check systecmctl to all both service is up. However
still dont know the root cause

Best Regards
Sopha Pech

**Comment by Metrax** [comment]
PowerDNS-Admin is management tool for the PowerDNS Authoritative Server, not for the Recursor.

**Comment by Pechsopha** [comment]
So we need to set up another Recursor server isolate from PowerDNS-Admin?

**Comment by Pechsopha** [comment]
Cloud you give me any reference or some guideline to solve ?

**Comment by Pechsopha** [comment]
Could you give me any reference or some guideline to solve this issue?

**Comment by a1d3s** [comment]
Powerdns admin is for administration your one DNS records in a powerdns server. Resolver is another product.

**Comment by jbe-dw** [comment]
Hello,

If what you need is to be able to host some private domains and still resolve internet domains, you can either:
- deploy at least one PowerDNS Recursor instance in which you would forward your private domains to a PowerDNS Authoritative instance (in the ini config file)
- deploy at least one PowerDNS Authoritative instance in which you enable the API
- Setup a PDA instance to query your  PowerDNS Authoritative instance
- Configure your servers/stations to use your PowerDNS Recursor instance as their resolver

or:
- buy a domain to a registrar and configure it to forward to your local instance, which should face internet with a public IP or some destination nat

That's general guidelines for you. 

Regards.

**Comment by jbe-dw** [comment]
No update in 30d, closing.
