### ISSUE TITLE
Feature Request: WebAuthn/Yubikey MFA Support

### ISSUE THREAD

**Issue by bcsanford** [PowerDNS-Admin/PowerDNS-Admin#1110]
not sure how it was implementation but Mesh Central Supports this works great with my Yubikey, would love to have it with PowerDNS-Admin, from what i understand hardware tokens are considered the most preferred form of MFA currently

**Comment by jbe-dw** [comment]
Hello @bcsanford 

We would like to add it but currently we don't have resources to work on it. Feel free to open a PR or wait some time, maybe another contributor will be interested.

Regards

**Comment by unixfox** [comment]
Bump, this is really useful!

**Comment by AzorianMatt** [comment]
@unixfox Please review our contribution guidelines [here](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/CONTRIBUTING.md) (no bumping issues, use reactions on feature proposals instead).

Thank you for your feedback.

**Comment by unixfox** [comment]
Why was this issue closed? Is the feature added to powerdns admin?

**Comment by AzorianMatt** [comment]
@bcsanford no, I'm just cleaning up old issues. It's unfortunate that the default close option when selecting multiple issues is to mark them as completed. This feature will likely not be addressed in the PDA legacy edition of the app. However, I will plan for support in the next-gen application.

**Comment by unixfox** [comment]
Thank you for the explanation
Is there another repository for the next-gen application? So that we can track this feature on the new app?

**Comment by AzorianMatt** [comment]
@unixfox you're welcome. If you look under this organization, you will find another repository named `pda-next` where you can follow progress. This repository is not meant for public consumption yet though, so please refrain from opening any issues, discussions, or any other types of interaction other than viewing.

Once we hit a point where it can make its first production release, the general public will be welcomed to interact as normal at that point.

Thanks!
