### ISSUE TITLE
Error 500 - manage domain

### ISSUE THREAD

**Issue by MarioC-IRL** [PowerDNS-Admin/PowerDNS-Admin#1112]
Hello,

When I want to manage the .arpa (ip6) domain on PowerDNS Admin, it returns a 500 error for no specific reason. I have tested with a standard domain and I don't have the problem, how can I solve this problem?

![image](https://user-images.githubusercontent.com/55061299/152743362-61e19d22-54ce-4032-8cdb-ac4357f7a82d.png)

**Comment by a1d3s** [comment]
In Forward Domain, I know if there was a txt record earlier without "" like Ms= instead of "Ms=" the the error occur. The only way was to change the entry in database.

**Comment by jbe-dw** [comment]
No answer in 30d, closing.
