### ISSUE TITLE
BUG: domain not able to load it 

### ISSUE THREAD

**Issue by MrMichou** [PowerDNS-Admin/PowerDNS-Admin#1119]
Hi there,

 Docker-compose : latest
 Distrib : CentOS 7.7
 Docker version 20.10.10

Since today, my container is not able to load domains.
I'm pulling the latest version got the kind of error, Am I missing something in the configuration, I can pull the data in HTTP but in not HTTPS by doing 

> curl https://172.17.0.1:8081
curl: (35) SSL received a record that exceeded the maximum permissible length

Does powerDNS_Admin got an option to deactivate this feature ? to after  reactivate it in a possible future migration to upgrade or do the changes 

Error in docker : 
> powerdns_admin | [2022-02-15 23:18:19 +0000] [12] [ERROR] Cannot update domain table. Error: HTTPSConnectionPool(host='172.17.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> powerdns_admin | [2022-02-15 23:18:19,779] [domain.py:168] ERROR - Cannot update domain table. Error: HTTPSConnectionPool(host='172.17.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> powerdns_admin | [2022-02-15 23:18:19 +0000] [12] [ERROR] Can not get server statistics. DETAIL: HTTPSConnectionPool(host='172.17.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/statistics (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> powerdns_admin | [2022-02-15 23:18:19,813] [server.py:60] ERROR - Can not get server statistics. DETAIL: HTTPSConnectionPool(host='172.17.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/statistics (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

Cheers,
Michael

**Comment by RGanor** [comment]
What did you put in dns API URL? did you tried to change it to http?

**Comment by MrMichou** [comment]
Hi @RGanor,
I tried to use HTTP, it's still forcing ssl anyway.
![Screenshot from 2022-03-08 06-56-07](https://user-images.githubusercontent.com/7550237/157233665-6efa309c-4aa9-46d6-a7db-1358237abce4.png)

I tried many configuration, with slash at the, without HTTP and tried to look into mysql if the were an escape character or it's forcing ssl but nothing.

After review, I forgot to paste this error,

> powerdns_admin |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
powerdns_admin |     httplib_response = self._make_request(
powerdns_admin |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
powerdns_admin |     six.raise_from(e, None)
powerdns_admin |   File "<string>", line 3, in raise_from
powerdns_admin |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
powerdns_admin |     httplib_response = conn.getresponse()
powerdns_admin |   File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
powerdns_admin |     response.begin()
powerdns_admin |   File "/usr/lib/python3.8/http/client.py", line 307, in begin
powerdns_admin |     version, status, reason = self._read_status()
powerdns_admin |   File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
powerdns_admin |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
powerdns_admin |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
powerdns_admin |     return self._sock.recv_into(b)
powerdns_admin | ConnectionResetError: [Errno 104] Connection reset by peer

Cheers,
Michael

**Comment by RGanor** [comment]
Where your pdns is installed? are you sure that it is reachable from inside the pdns-admin container?

**Comment by MrMichou** [comment]
Hey @RGanor,

Found the problem !
So yes the services pdns was setup, the port was opened, It was a misconfiguration of my PDNS.conf after review
`webserver-allow-from` didn't had the IP configured. Needed to add 172.18.0.1.

All good ! 
Thanks for the support @RGanor !

Have a great day, 
Cheers,
Michael
