### ISSUE TITLE
ERROR - Can not get server statistics.

### ISSUE THREAD

**Issue by lanhampr** [PowerDNS-Admin/PowerDNS-Admin#1130]
I am seeing this in the log:
[2022-02-23 15:25:08,292] [server.py:60] ERROR - Can not get server statistics. DETAIL: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/statistics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca65c505e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

curl 127.0.0.1:8081 is successful.  

I matched "# api-key       Static pre-shared authentication key for access to the REST API" with PDNS API KEY
#################################
# webserver-address     IP Address of webserver/API to listen on
#
webserver-address=0.0.0.0

#################################
# webserver-allow-from  Webserver/API access is only allowed from these subnets
#
webserver-allow-from=127.0.0.1,::1

#################################
# webserver-loglevel    Amount of logging in the webserver (none, normal, detailed)
#
webserver-loglevel=normal

**Comment by jbe-dw** [comment]
You can check in powerdns logs if there is an error. It may be because the python server is not sending request from the localhost.

Are you running a container setup or a full install ?

**Comment by lanhampr** [comment]
I am running a container setup. I have changed PowerDNS-Admin to use the IP of the server instead of 127.0.0.1 and I have modified PowerDNS config as so:
#################################
# webserver     Start a webserver for monitoring (api=yes also enables the HTTP listener)
#
webserver=yes

#################################
# webserver-address     IP Address of webserver/API to listen on
#
webserver-address=0.0.0.0

PowerDNS-Admin can no longer reach PDNS and I can no longer CURL to the IP.  What I have found and cannot figure out is the ACL settings of PDNS:

$systemctl status pdns
Feb 23 09:02:58 powerdns pdns_server[58844]: [webserver] Webserver closing socket: remote (x.x.x.x) does not match the set ACL(127.0.0.1/32, ::1/128)

**Comment by jbe-dw** [comment]
Is your PDNS server run from a container ?
Are both softwares running on the same host ?
It looks like you may run PDNS from host and PDA from a container. If the remote in the log starts with 172.21 it is the container's ip. You may want to allow 172.21.0.0/16 in the ACL to allow the communication.

**Comment by jbe-dw** [comment]
webserver-allow-from=127.0.0.1,::1,172.21.0.0/16

**Comment by lanhampr** [comment]
Thank you. I didn't realize if webserver-allow-from was commented out that the ACL defaulted to 127.0.0.1.
