### ISSUE TITLE
Opinion wanted on SQLite3 vs MariaDB

### ISSUE THREAD

**Issue by lanhampr** [PowerDNS-Admin/PowerDNS-Admin#1131]
I don't really see anybody using SQLite3 and mostly using MariaDB.  I choose SQLite because it was included in install, should I change to MariaDB?

**Comment by arbaldin** [comment]
I'm currently using MariaDB Galera cluster for both PDNS and PDNS-Admin.

I think that the DB choice is a matter of the resilience you want with your installation and how familiar you are with the system you choose.

Regards.

**Comment by jbe-dw** [comment]
Hello,

The database backend choice really depends on your setup. If you want a resilient with high availability database, you should definitely go for mysql/mariadb or postgres.

If it is a small setup and downtime is not an issue, you should stick with sqlite.

**Comment by lanhampr** [comment]
Yes. Sorry.

From: jbe-dw ***@***.***>
Date: Wednesday, April 27, 2022 at 12:16 PM
To: PowerDNS-Admin/PowerDNS-Admin ***@***.***>
Cc: Lanham Rattan ***@***.***>, Mention ***@***.***>
Subject: Re: [PowerDNS-Admin/PowerDNS-Admin] Opinion wanted on SQLite3 vs MariaDB (Issue #1131)

@lanhampr<https://github.com/lanhampr> If you have no more question regarding the database choice, can you close the issue ?
