### ISSUE TITLE
Cannot modify SOA record.

### ISSUE THREAD

**Issue by lanhampr** [PowerDNS-Admin/PowerDNS-Admin#1132]
When I edit an SOA record, it allows me to save and successfully apply changes but when the page refreshes it's back to it's original state.

**Comment by RGanor** [comment]
Can you share the values you try to edit?

**Comment by lanhampr** [comment]
I think I had a field that wasn't proper so thru trial and error I got it sorted.  It was just throwing me off because it would accept and let me save with no warning.
