### ISSUE TITLE
Add support to configure ALSO-NOTIFY per-zone metadata

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#1133]
PowerDNS allows you to set per-zone metadata for various purposes.  We already manage the `SOA-EDIT-API` setting via the pdns-admin GUI.

When updating a zone data, a `NOTIFY` packet will be sent to all NS hosts for that zone, plus all globally-defined also-notify hosts.  However, in some situations, it is desirable to set a per-zone list of hosts to receive additional notify packets -- such as in the case of unpublished secondary DNS servers.  That is what the per-zone `ALSO-NOTIFY` metadata is for, when you want to notify an additional non-NS server, but don't want to define this globally for all zones.

We may also want to tie this to the `ALLOW-AXFR-FROM` metadata since the only reason to set `ALSO-NOTIFY` is to trigger an AXFR, so adding an endpoint to the `ALSO-NOTIFY` should implicitly also add it to the `ALLOW-AXFR-FROM`.

These metadata settings can take multiple space-separated values.

I would envision these  being optionally set from the Zone Admin page, the same as for the `SOA-EDIT-API` setting.

On the commandline set these via:
```
pdnsutil set-meta powerdns.org ALSO-NOTIFY 192.0.2.1:5300
pdnsutil set-meta powerdns.org ALLOW-AXFR-FROM 192.0.2.1
```

It may also be useful to allow the `SLAVE-RENOTIFY` metadata flag to be set here, though that is only available from API version 4.3.x so may have compatibility issues for older PowerDNS installations

Relevant documentation: https://doc.powerdns.com/authoritative/domainmetadata.html#also-notify

**Comment by jbe-dw** [comment]
Hello @sshipway 

There's changes in PDA maintainers team and we can't work on new feature for now. You can work on a PR now or wait a bit as the project reorganizes.

Regards
