### ISSUE TITLE
MacOS returns recursive nslookup results from PowerDNS

### ISSUE THREAD

**Issue by lanhampr** [PowerDNS-Admin/PowerDNS-Admin#1135]
This isn't a PowerDNS-Admin issue but wanted to ask here as I know there are a lot of very smart people here.  I have confirmed on my PowerDNS server that recursive DNS does not work, I cannot lookup anything that PowerDNS is not authoritative nor do I get any results for say google.com from another server when issuing an NSLOOKUP using my PowerDNS server but I do when using my MacBook terminal.  Has anybody else seen this behavior from a Mac?

**Comment by arbaldin** [comment]
@lanhampr 

You are right, this is not related do PDNS, but to the operational system TCP/IP stack configuration.

When you are at the PDNS shell and use nslookup, if you issue the command server, what is the answer you got? If you do the same at the MacOS shell, what's the answer? Is it the same?

MacOS is probably using another server to do the recursion.

Regards.

**Comment by lanhampr** [comment]
Lanhams-MacBook-Pro:~ lanham$ nslookup 
> server 205.220.219.75
Default server: 205.220.219.75
Address: 205.220.219.75#53
> google.com
Server:		205.220.219.75
Address:	205.220.219.75#53

Non-authoritative answer:
Name:	google.com
Address: 142.250.138.113
Name:	google.com
Address: 142.250.138.101
Name:	google.com
Address: 142.250.138.100
Name:	google.com
Address: 142.250.138.138
Name:	google.com
Address: 142.250.138.102
Name:	google.com
Address: 142.250.138.139

On the PDNS Server:
lanham@powerdns:~$ nslookup
> google.com
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find google.com: REFUSED
> server 205.220.219.75
Default server: 205.220.219.75
Address: 205.220.219.75#53
> google.com
Server:		205.220.219.75
Address:	205.220.219.75#53

** server can't find google.com: REFUSED

**Comment by jbe-dw** [comment]
Just to be sure, you try to do a query from a server where you installed PowerDNS Recursor, or PowerDNS Authoritative ? Because PDA address the second one which does not do recursion.

**Comment by lanhampr** [comment]
That's the weirdness.  I am getting a response from (supposedly) 205.220.219.75 using terminal (nslookup) on my MacBook.  It should return nothing.  The MacBook is giving me false positive results, just curious if anybody else has seen this.  There was no PDNS Recursor setup at the time.  I have since installed the recursor to complete my install and did not include the MacBook network to the allow list.

I shut recursor down and from a Ubuntu shell:
lanham@cnethawk:~$ dig @205.220.219.75 google.com

; <<>> DiG 9.11.3-1ubuntu1.16-Ubuntu <<>> @205.220.219.75 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
lanham@cnethawk:~$ 

Perfect.

From MacOS Shell:

Lanhams-MacBook-Pro:downloads lanham$ dig @205.220.219.75 google.com

; <<>> DiG 9.10.6 <<>> @205.220.219.75 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62077
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		2	IN	A	142.250.138.101
google.com.		2	IN	A	142.250.138.113
google.com.		2	IN	A	142.250.138.102
google.com.		2	IN	A	142.250.138.100
google.com.		2	IN	A	142.250.138.139
google.com.		2	IN	A	142.250.138.138

;; Query time: 42 msec
;; SERVER: 205.220.219.75#53(205.220.219.75)
;; WHEN: Fri Feb 25 16:15:09 MST 2022
;; MSG SIZE  rcvd: 135

False positive.

**Comment by jbe-dw** [comment]
Hello,

Can you finally tell me if you were able to find out what is wrong ? As this is not related to PDA.

Please close the issue if you were.

**Comment by lanhampr** [comment]
No resolution, just hoping somebody else saw the same issue as it makes troubleshooting from a Mac inconclusive. I will just close it and keep searching Google.  Thank you.
