### ISSUE TITLE
The encoding on the returned API Keys is not accepted by decoder.

### ISSUE THREAD

**Issue by hmike96** [PowerDNS-Admin/PowerDNS-Admin#1137]
Hello it looks like whatever encoding in base64 for the returned API keys is not accepted by whatever process decrypts it in powerdns. Whenever I try to use the api key returned to me I get a 401 UNAUTHORIZED with this bug in the logs [decorators.py:379] ERROR - Invalid base64-encoded of credential. Error Incorrect padding

**Comment by RGanor** [comment]
How did you generated this API Key and how do you use it?

**Comment by jbe-dw** [comment]
@hmike96 any update on this issue ?

**Comment by jbe-dw** [comment]
No feedback in 20 days, i'm closing.
