### ISSUE TITLE
Auto PTR modifies PTR records it should not.

### ISSUE THREAD

**Issue by gizahNL** [PowerDNS-Admin/PowerDNS-Admin#1142]
With auto_ptr enabled on the domain level PTR records are changed when new A records are added, even though the original A record that the PTR references still exists.

This is a big nuisance, as there are legitimate reasons to have multiple A records pointing to the same IP, while wanting the PTR record not to point "to the last created record".

The desired operation would be that auto_ptr ONLY updates the PTR record when the matching A record is changed/deleted.

**Comment by jbe-dw** [comment]
I think that there's no relationship stored with the original A record, as it's a PowerDNS feature that may become deprecated. 

We will give an answer soon.

**Comment by gizahNL** [comment]
Yeah, makes sense there is no relationship stored.

Though such relationship could either be stored in powerdns-admin db itself.

Or a check could be fired beforehand; When modifying/adding A record check if PTR exists for that IP & only modify PTR record if the PTR points to the same A record.

**Comment by jbe-dw** [comment]
Hello,

I'll take a look at the code shortly to confirm PDA's behaviour.

Regards

**Comment by jbe-dw** [comment]
Sorry for the lack of follow up, our organization still needs improvment.

PDA does not do this check. But as I said we have not decided yet what to do with this function. There is a lot of issues arround it and we want to take the best decision about what it will be (or won't).

Regards.
