### ISSUE TITLE
Can not create new domain

### ISSUE THREAD

**Issue by trinv** [PowerDNS-Admin/PowerDNS-Admin#1143]
Mar 22 08:44:33 ns01 pdns_server[145457]: [webserver] 2caac540-46fd-4ce9-a2f6-03a337c083de HTTP ISE for "/api/v1/servers/localhost/zones": Exception: GSQLBackend unable to list keys: Could not prepare statement: select cryptokeys.id, flags, active, published, content from domains, cryptokeys where cryptokeys.domain_id=domains.id and name=?: Unknown column 'published' in 'field list'
Mar 22 08:44:33 ns01 gunicorn[142533]: [2022-03-22 08:44:33,528] [domain.py:252] ERROR - Cannot add domain test.com. Error while fetching http://10.0.1.9:8081/api/v1/servers/localhost/zones. Returned status 500 and content Internal Server Error

Mar 22 08:46:42 ns01 pdns_server[145457]: [webserver] d4416c68-8e6c-41f7-bc06-fa0580d66abb HTTP ISE for "/api/v1/servers/localhost/zones": Exception: GSQLBackend unable to list keys: Could not prepare statement: select cryptokeys.id, flags, active, published, content from domains, cryptokeys where cryptokeys.domain_id=domains.id and name=?: Unknown column 'published' in 'field list'
Mar 22 08:46:42 ns01 gunicorn[142533]: [2022-03-22 08:46:42,568] [domain.py:168] ERROR - Cannot update domain table. Error: Error while fetching http://10.0.1.9:8081/api/v1/servers/localhost/zones. Returned status 500 and content Internal Server Error

**Comment by jbe-dw** [comment]
Hello,

It looks like you updated the PDA version on a local deployment but did not run the database migration. See #1141

**Comment by trinv** [comment]
> Hello,
> 
> It looks like you updated the PDA version on a local deployment but did not run the database migration. See #1141

**Comment by jbe-dw** [comment]
Hello,

I read this log too much quickly, logs looks like it'a a PowerDNS backend issue, because it references GSQLBackend.

Regards

**Comment by trinv** [comment]
Hi,
Thanks. So any idea to fix this issue ?

**Comment by jbe-dw** [comment]
When using mysql backend, you must create a database from the schema available on Powerdns website matching the Powerdns version you are using. You need to check which version of Powerdns is installed, then get the corresponding database schema from their website, and compare it with your actual database. Please take a look at the release notes but you should know for which version of PowerDNS your actual database is to look for database layout changes.

If your data is not important a quicker way would be to drop the database and create from scratch. Else you can request for help on their IRC channel as well.

**Comment by trinv** [comment]
Hi, i found how to fix it:
exec this command in mysql: 

https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/4.2.0_to_4.3.0_schema.mysql.sql

ALTER TABLE cryptokeys ADD published BOOL NULL DEFAULT 1 AFTER active;
