### ISSUE TITLE
Support DNAME type

### ISSUE THREAD

**Issue by eLvErDe** [PowerDNS-Admin/PowerDNS-Admin#1151]
Hello,

It seems PowerDNS admin does not list/does not permit to create DNAME entries to alias an entire domain to another.
Here is how to create one from cli:

```
pdnsutil create-zone example.com
pdnsutil add-record example.com @ DNAME another-domain.com
```

Now any request to something.example.com will resolve to something.another-domain.com.

You might also want to issue a warning if user is creating DNAME entry and `dname-processing=yes` setting is not set, see: https://doc.powerdns.com/authoritative/settings.html#setting-dname-processing

Best regards, Adam.

**Comment by jbe-dw** [comment]
Hello,

You can enable DNAME record creation in Settings/Records, however there is no check about dname-processing at the time.

Regards

**Comment by jbe-dw** [comment]
Is enabling DNAME working for you or not ?
