### ISSUE TITLE
Add support for SVCB / HTTPS record types

### ISSUE THREAD

**Issue by Showfom** [PowerDNS-Admin/PowerDNS-Admin#1168]
https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-svcb-https-08

PowerDNS already support it since 4.4.0

https://doc.powerdns.com/authoritative/appendices/types.html#svcb-https
https://doc.powerdns.com/authoritative/guides/svcb.html

**Comment by jbe-dw** [comment]
Hello @Showfom 

As you may have read on latest announcements, we're focusing on bug fixes and include pending PRs now. We take a note to your request to add it later.

We will update your issue when we will have free time to add it.

Regards

**Comment by subbink** [comment]
This is related to #1287 , which asks for the addition of the APL record type. And both could be added at the same time.

**Comment by Martin22** [comment]
Hi. Has there been any progress on this request? Given the approved RFC9460, I should already have this in the interface so that I can use the records.

**Comment by josephofthebread** [comment]
Hello, can somebody implement this feature already ? Issue is more than 2 years old.
