### ISSUE TITLE
need docker verison's wiki thank you

### ISSUE THREAD

**Issue by wuyifan66** [PowerDNS-Admin/PowerDNS-Admin#1169]
I really need the wiki of the docker version.  like "mysql address", i don't know how to config in docker verison

**Comment by RGanor** [comment]
Hey @wuyifan66 , can you please translate this issue to English? this is the only supported language.

**Comment by RGanor** [comment]
Have you looked on the docker compose?

https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/e89133397105e0cb27dff9222b0ce7ec9fb24d8d/docker-compose.yml

Use SQLALCHEMY_DATABASE_URI environment variable

**Comment by jbe-dw** [comment]
Hi,

Can you elaborate your question, I'm not sure to understand your need ?

Thank you.
