### ISSUE TITLE
Domain Template Edit not working

### ISSUE THREAD

**Issue by obi12341** [PowerDNS-Admin/PowerDNS-Admin#1175]
Hello,

looks like editing template record is broken in latest release (v0.2.4). I get following error message if i want to edit a template record: ERROR - Cannot apply record changes to the template. Error: 'record_comment'

Looks like this is probably the line that throws this error:
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/94a923a965f0740aeb4d44c4abde9bb8c530bfc7/powerdnsadmin/routes/admin.py#L1825

**Comment by Metrax** [comment]
Please update to the latest git-master and check if the problem still exist.

**Comment by jbe-dw** [comment]
Hello @obi12341,

Could you try with a recent version (in master, not released yet) ?

thanks

**Comment by jbe-dw** [comment]
Hello @obi12341,

Could you try with a recent version (in master, not released yet) ?

thanks
