### ISSUE TITLE
how to get the right API version

### ISSUE THREAD

**Issue by WestFarmer** [PowerDNS-Admin/PowerDNS-Admin#1176]
Hi, how to get the right API version for the powerdns backend ?

**Comment by jbe-dw** [comment]
Hello,

Can you develop ? The PowerDNS API major version is v1 for a while.

**Comment by WestFarmer** [comment]
> 

you mean 4.1.1 ?

**Comment by jbe-dw** [comment]
4.1 is the PowerDNS version. PDA is compatible to versions over 4.1, but there were some changes in the API, you should upgrade to >4.3. Current version is 4.5
