### ISSUE TITLE
cant's specify powerdns api endpoint and key at startup ?

### ISSUE THREAD

**Issue by WestFarmer** [PowerDNS-Admin/PowerDNS-Admin#1177]
I can't find a config parameter to do this, why ?

**Comment by Metrax** [comment]
Because you have to configure it in the WebUI.
![image](https://user-images.githubusercontent.com/1061866/165075597-a2adf0f7-7866-44e9-8dd7-07cd861dc402.png)

**Comment by WestFarmer** [comment]
I knows this, for automation purpose I think it's better to have a option to set these configs at startup.

**Comment by Metrax** [comment]
In this case, your should do this with mysql:
```
UPDATE `setting` SET `value`='##URL##` WHERE `name`='pdns_api_url';
UPDATE `setting` SET `value`='##KEY##` WHERE `name`='pdns_api_key';
```

**Comment by jbe-dw** [comment]
Hello,

We planed to add  a config api in a future release. As it is not gonna land soon, a workarround is to set it up in SQL, like @Metrax proposed.

Regards
