### ISSUE TITLE
the latest revision from the git repository throws an error and when you click save A record itself adds a comment

### ISSUE THREAD

**Issue by hellEVIL-13** [PowerDNS-Admin/PowerDNS-Admin#1181]
Apr 27 17:26:16 webdns gunicorn[7904]: [2022-04-27 17:26:16,324] [app.py:1892] ERROR - Exception on /dashboard/ [GET]
Apr 27 17:26:16 webdns gunicorn[7904]: Traceback (most recent call last):
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Apr 27 17:26:16 webdns gunicorn[7904]:     response = self.full_dispatch_request()
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 27 17:26:16 webdns gunicorn[7904]:     rv = self.handle_user_exception(e)
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Apr 27 17:26:16 webdns gunicorn[7904]:     reraise(exc_type, exc_value, tb)
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Apr 27 17:26:16 webdns gunicorn[7904]:     raise value
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 27 17:26:16 webdns gunicorn[7904]:     rv = self.dispatch_request()
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Apr 27 17:26:16 webdns gunicorn[7904]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
Apr 27 17:26:16 webdns gunicorn[7904]:     return func(*args, **kwargs)
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/dashboard.py", line 192, in dashboard
Apr 27 17:26:16 webdns gunicorn[7904]:     detailedHistories = convert_histories(history)
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 914, in convert_histories
Apr 27 17:26:16 webdns gunicorn[7904]:     detailedHistories.append(DetailedHistory(histories[i], None))
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 766, in __init__
Apr 27 17:26:16 webdns gunicorn[7904]:     detail_dict = json.loads(history.detail)
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
Apr 27 17:26:16 webdns gunicorn[7904]:     return _default_decoder.decode(s)
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
Apr 27 17:26:16 webdns gunicorn[7904]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Apr 27 17:26:16 webdns gunicorn[7904]:   File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
Apr 27 17:26:16 webdns gunicorn[7904]:     obj, end = self.scan_once(s, idx)
Apr 27 17:26:16 webdns gunicorn[7904]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
![Screenshot 2022-04-27 at 17-39-43 m1cloud net - webdns](https://user-images.githubusercontent.com/19870084/165544453-a2f93e44-851a-4b3c-a758-190f44c9ed45.png)

**Comment by jbe-dw** [comment]
Hello @hellEVIL-13 

Can you try the two small changes proposed in #1182 ?

I can get the same error message in the logs with one of my test setup with the current master, but I couldn't reproduce the bug with the record edition.

I don't think they are related. Let me know if at least you can display the dashboard (and the history tab).

For the edition issue, let me know.

Regards.

**Comment by hellEVIL-13** [comment]
> Hello @hellEVIL-13
> 
> Can you try the two small changes proposed in #1182 ?
> 
> I can get the same error message in the logs with one of my test setup with the current master, but I couldn't reproduce the bug with the record edition.
> 
> I don't think they are related. Let me know if at least you can display the dashboard (and the history tab).
> 
> For the edition issue, let me know.
> 
> Regards.

this helped with the dashboard error but the main page is now without styles but didn't help with another error
![image](https://user-images.githubusercontent.com/19870084/165671239-29903a7b-8556-40e3-8098-e36e03c825ec.png)

**Comment by jbe-dw** [comment]
Can you provide the Javascript console log from your browser (hit F12 to open the development panel, then go to Console tab, click on the bin to clear the console then hit F5 to reload)

**Comment by hellEVIL-13** [comment]
> Can you provide the Javascript console log from your browser (hit F12 to open the development panel, then go to Console tab, click on the bin to clear the console then hit F5 to reload)
Some cookies are misusing the recommended “SameSite“ attribute 2

GEThttps://webdns.m1cloud.net/static/generated/login.css?2a708f5e
[HTTP/1.1 404 Not Found 10ms]

GEThttps://webdns.m1cloud.net/static/generated/login.js?ef820066
[HTTP/1.1 404 Not Found 9ms]

GEThttps://webdns.m1cloud.net/static/generated/validation.js?99acceba
[HTTP/1.1 404 Not Found 7ms]

Loading failed for the <script> with source “https://webdns.m1cloud.net/static/generated/login.js?ef820066”. [login:85:1](https://webdns.m1cloud.net/login)
Loading failed for the <script> with source “https://webdns.m1cloud.net/static/generated/validation.js?99acceba”. login:86:1
GEThttps://webdns.m1cloud.net/static/img/favicon.png
[HTTP/1.1 404 Not Found 0ms]

Found 6 logins for this site

**Comment by jbe-dw** [comment]
Hello,

Can you check that the mentionned files are present in powerdnsadmin/static/generated folder ?

If the files don't exist, you may have to run `flask assets build` like mentionned in    [the wiki](https://github.com/PowerDNS-Admin/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian#running-powerdns-admin)

Else, if `webdns.m1cloud.net` is the dns name of your PDA instance, you have to ensure that files are correctly served.

**Comment by hellEVIL-13** [comment]
> Hello,
> 
> Can you check that the mentionned files are present in powerdnsadmin/static/generated folder ?
> 
> If the files don't exist, you may have to run `flask assets build` like mentionned in [the wiki](https://github.com/PowerDNS-Admin/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian#running-powerdns-admin)
> 
> Else, if `webdns.m1cloud.net` is the dns name of your PDA instance, you have to ensure that files are correctly served.

I wrote myself I made a mistake with the nginx settings, everything is working correctly now, and I ask you to upload your patch to git.

**Comment by jbe-dw** [comment]
Hello,

Glad to hear that it works for you. We are discussing internally about this, because in the end it would be cleaner to provide a patch that replaces single quotes in this column by double quotes, rather than doing it in the code.

I'll give you an update about this soon, until then keep the patch.

Regards

**Comment by jbe-dw** [comment]
Hello,

I've pushed an alembic script to update the history table in the same PR. It would be nice if you could test it and revert the changes L766 altogether.

You should definitely dump the history table before, then run "flask db upgrade" from within the flask virtualenv.

Regards

**Comment by hellEVIL-13** [comment]
> Hello,
> 
> I've pushed an alembic script to update the history table in the same PR. It would be nice if you could test it and revert the changes L766 altogether.
> 
> You should definitely dump the history table before, then run "flask db upgrade" from within the flask virtualenv.
> 
> Regards

I did everything, your patch fixes the issue not in the database and not in nginx

**Comment by jbe-dw** [comment]
Hello,

I'm not sure to understand. You applied the db upgrade with the script pulled from the Branch, and the problem is still occuring if you disable the python change in the same PR ?

Can you describe your tests ?

Thank you

**Comment by hellEVIL-13** [comment]
> Hello,
> 
> I'm not sure to understand. You applied the db upgrade with the script pulled from the Branch, and the problem is still occuring if you disable the python change in the same PR ?
> 
> Can you describe your tests ?
> 
> Thank you

I just took the update to the old one from a clean slate, the database was old because I didn’t want to lose the data, everything works, everything has been updated
