### ISSUE TITLE
Ability to use DynDNS via api keys

### ISSUE THREAD

**Issue by samip5** [PowerDNS-Admin/PowerDNS-Admin#1185]
I would love to see PDA to have an functionality to allow DynDNS to be used via api keys rather than user credentials directly.

If I were to code it myself, should it be via a configuration setting or how it should be?

**Comment by jbe-dw** [comment]
Hello,

I've not checked at the dyndns functionality yet. At a first glance, it looks like you should:

-  check at decorators, to have an hybrid one like `apikey_or_basic_auth`
-  update `def dyndns_update` function to check domain permissions based on your new decorator return value via the apikey perms or the user perms.

It's not something for a beginner to do, but with good skills in python you should be able to achieve this, if apikey authentication is supported by dyndns.

Regards
