### ISSUE TITLE
Disabling check for domain validity

### ISSUE THREAD

**Issue by Nim1com** [PowerDNS-Admin/PowerDNS-Admin#1186]
I am not using ICAAN. And need to disable the check for domains.

**Comment by jbe-dw** [comment]
Hello,

I don't get it, which check are you talking about ?

Regards

**Comment by Nim1com** [comment]
![image](https://user-images.githubusercontent.com/57798165/166888576-45efe237-ec48-41c3-8dc9-2aaf81b54f67.png)

**Comment by Nim1com** [comment]
the sld.tld or tld field there
how do i disable checks for that field

**Comment by Metrax** [comment]
@Nim1com give us an example, what you are trying the enter there, please

**Comment by Nim1com** [comment]
as i am using a custom dns witch has non icaan domains aka there is domains like site.whateveriswrittenhere and only tld sites.

**Comment by Metrax** [comment]
I've tried to create "site.whateveriswrittenhere" and "test" (for just tld), and didn't get an error.
Are on the latest master-commit?

**Comment by Nim1com** [comment]
i am on 4.6.1
and am i supposed to get a 400?

**Comment by Nim1com** [comment]
this is where i tried it also without the webgui https://doc.powerdns.com/md/httpapi/README/

{
  "account": "",
  "api_rectify": false,
  "dnssec": false,
  "edited_serial": 2022050501,
  "id": "example.org.",
  "kind": "Native",
  "last_check": 0,
  "master_tsig_key_ids": [],
  "masters": [],
  "name": "example.org.",
  "notified_serial": 0,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [
    {
      "comments": [],
      "name": "example.org.",
      "records": [
        {
          "content": "a.misconfigured.dns.server.invalid. hostmaster.example.org. 2022050501 10800 3600 604800 3600",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "SOA"
    },
    {
      "comments": [],
      "name": "example.org.",
      "records": [
        {
          "content": "ns1.example.org.",
          "disabled": false
        },
        {
          "content": "ns2.example.org.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "NS"
    }
  ],
  "serial": 2022050501,
  "slave_tsig_key_ids": [],
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
  "url": "/api/v1/servers/localhost/zones/example.org."
}

**Comment by Metrax** [comment]
This is the PowerDNS-Version.
We need to know, with which PowerDNS-Admin Version you are working?

**Comment by Nim1com** [comment]
ngoduykhanh/powerdns-admin:latest

**Comment by Nim1com** [comment]
the one updated 8 days ago latest commit

**Comment by Metrax** [comment]
I think i've found your problem ... are you trying to enter the Domain name with a dot at the end? ex.: site.
If yes, PDA is adding this automatically when creating the domain at PDNS. You can create it simply without the dot.

**Comment by Metrax** [comment]
Just for example:
I've tried to create "test.". PDA is trying the create "test..", and got this error:
`ERROR - Unable to parse DNS Name 'test..'`

So, this is not a bug, this is a feature :-D

**Comment by Nim1com** [comment]
i did nto add a . at the end

**Comment by Nim1com** [comment]
![image](https://user-images.githubusercontent.com/57798165/166901504-d45b2fcb-96fb-4264-ab73-4364462d0f6e.png)
![image](https://user-images.githubusercontent.com/57798165/166901628-f4d3af29-a11e-4508-9fb6-9755fb2a177a.png)
![image](https://user-images.githubusercontent.com/57798165/166901683-e9b53018-30e3-4ca1-9258-8a0045a4ab6b.png)
anything i do returns this
im not sure if this is my original problem anymore but

**Comment by jbe-dw** [comment]
Hello,

I can create both TLD domains and registered domains like google.com

![pda_tld](https://user-images.githubusercontent.com/50663045/166902120-961b09fa-91bb-4e95-8fb6-51b88d84f22a.png)

**Comment by jbe-dw** [comment]
You need to provide PDA logs to figure out what happens. Which kind of setup do you use ? (docker, full install with systemd ..)

**Comment by jbe-dw** [comment]
You can also enable PowerDNS webserver logs and check what happens in the background. (webserver-loglevel = detailed, loglevel = 5)

**Comment by Nim1com** [comment]
docker?

● pdns.service - PowerDNS Authoritative Server
     Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-05-05 09:16:45 UTC; 54min ago
       Docs: man:pdns_server(1)
             man:pdns_control(1)
             https://doc.powerdns.com
   Main PID: 582166 (pdns_server)
      Tasks: 10 (limit: 1132)
     Memory: 51.5M
     CGroup: /system.slice/pdns.service
             └─582166 /usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=n>

**Comment by jbe-dw** [comment]
How did you install PowerDNS Admin ?

**Comment by jbe-dw** [comment]
You can check the logs from the container with docker logs. Please provide logs when the error 400 happens

Ex:
`docker ps`
CONTAINER ID   IMAGE                COMMAND                  CREATED        STATUS                  PORTS                                                                                                                     **NAMES**
c35e461f3e1f   powerdns-admin-dev   "entrypoint.sh gunic…"   12 hours ago   Up 12 hours (healthy)   0.0.0.0:9191->80/tcp, :::9191->80/tcp                                                                                     **powerdns_admin_dev**
`docker logs powerdns_admin_dev -f`

**Comment by Nim1com** [comment]
logs shows this all the time [2022-05-05 11:03:52,741] [server.py:60] ERROR - Can not get server statistics. DETAIL: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/statistics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d363523d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Nim1com** [comment]
yep on 400 it is 
[2022-05-05 11:07:29,027] [domain.py:252] ERROR - Cannot add domain 0xnim.xyz. HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d36294460>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Nim1com** [comment]
i cant connect to it but can curl locally

**Comment by Nim1com** [comment]
host

**Comment by Nim1com** [comment]
LOCAL:
[nim1com@TheIncinirator ~]$ curl -v -H 'X-API-Key: pa8J810Jia0' http://178.62.250.39:8081/api/v1/servers/localhost/zones/example.org | jq .
*   Trying 178.62.250.39:8081...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connect to 178.62.250.39 port 8081 failed: Connection refused
* Failed to connect to 178.62.250.39 port 8081 after 67 ms: Connection refused
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (7) Failed to connect to 178.62.250.39 port 8081 after 67 ms: Connection refused

HOST:
root@pageifyns:~# curl -v -H 'X-API-Key: pa8J810Jia0' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.org | jq .
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /api/v1/servers/localhost/zones/example.org HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.68.0
> Accept: */*
> X-API-Key: pa8J810Jia0
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 824
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Content-Type: application/json
< Server: PowerDNS/4.6.1
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
< 
{ [824 bytes data]
100   824  100   824    0     0  58857      0 --:--:-- --:--:-- --:--:--  114k
* Closing connection 0
{
  "account": "",
  "api_rectify": false,
  "dnssec": false,
  "edited_serial": 2022050501,
  "id": "example.org.",
  "kind": "Native",
  "last_check": 0,
  "master_tsig_key_ids": [],
  "masters": [],
  "name": "example.org.",
  "notified_serial": 0,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [
    {
      "comments": [],
      "name": "example.org.",
      "records": [
        {
          "content": "a.misconfigured.dns.server.invalid. hostmaster.example.org. 2022050501 10800 3600 604800 3600",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "SOA"
    },
    {
      "comments": [],
      "name": "example.org.",
      "records": [
        {
          "content": "ns1.example.org.",
          "disabled": false
        },
        {
          "content": "ns2.example.org.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "NS"
    }
  ],
  "serial": 2022050501,
  "slave_tsig_key_ids": [],
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
  "url": "/api/v1/servers/localhost/zones/example.org."
}

**Comment by Nim1com** [comment]
and curl -v -H 'X-API-Key: pa8J810Jia0' http://178.62.250.39:8081/api/v1/servers/localhost/zones/example.org | jq . on host returs same as local

**Comment by Metrax** [comment]
You have to give PDA the 178.62.250.39 (docker host ip?) for connecting.
With 127.0.0.1 you can not connect from container to the host.

**Comment by Nim1com** [comment]
?

**Comment by jbe-dw** [comment]
Hello,

What happens is that you are querying the loopback address of the host from the container, which has its own loopback. You need to ensure that PowerDNS webserver is listening on another host interface:

* does PowerDNS run on TheIncinirator machine ?
* does PowerDNS Admin Docker run on TheIncinirator machine ?
* is 178.62.250.39 the ip adress of TheIncinirator machine ?

If so please configure PowerDNS Admin (Settings > PDNS) to query http://178.62.250.39:8081

**Comment by Nim1com** [comment]
TheIncinirator is my local machine
178.62.250.39  is host

**Comment by Nim1com** [comment]
changing the ip to 178.62.250.39  did not fix the 400 error

**Comment by Nim1com** [comment]
it seems i cannot connect to the api from other than localhost

**Comment by Nim1com** [comment]
]: [webserver] Listening for HTTP requests on 127.0.0.1:8081
how do i change that

**Comment by jbe-dw** [comment]
You need to configure PowerDNS webserver to bind on the external IP, by setting [webserver-address](https://doc.powerdns.com/authoritative/settings.html#webserver-address) to the host ip address (and restart the pdns service)

Then once you could be able to use curl on its ip address it should work from the container.

**Comment by Nim1com** [comment]
i thonk that broke it Webserver closing socket: remote (172.17.0.3) does not match the set ACL(178.62.250.39/32, ::1/128)

**Comment by Nim1com** [comment]
config:
#################################
# webserver-address     IP Address of webserver/API to listen on
# 
webserver-address=178.62.250.39

#################################
# webserver-allow-from  Webserver/API access is only allowed from these subnets
# 
webserver-allow-from=178.62.250.39,::1

**Comment by Nim1com** [comment]
okay removed the lowerone
progress:
curl: (56) Recv failure: Connection reset by peer

**Comment by jbe-dw** [comment]
Can you curl 178.62.250.39 from your machine ?

curl -v -H 'X-API-Key: pa8J810Jia0' http://178.62.250.39:8081/api/v1/servers/localhost/zones/example.org

**Comment by jbe-dw** [comment]
Either it is not listening, or you have a firewall somewhere

`sudo ss -tulpn | grep LISTEN` on the PowerDNS server should show you if it listens on 178.62.250.39:8081

**Comment by Nim1com** [comment]
yep 
tcp     LISTEN   0        10         178.62.250.39:8081          0.0.0.0:*       users:(("pdns_server",pid=2134,fd=9))                                          
tcp     LISTEN   0        128              0.0.0.0:53            0.0.0.0:*       users:(("pdns_server",pid=2134,fd=7))

**Comment by Nim1com** [comment]
uhh that last bit is a bit hard to understand but uhh like smth abt priv address and yes it has 1

**Comment by Nim1com** [comment]
changed to this
tcp     LISTEN   0        10            10.110.0.2:8081          0.0.0.0:*       users:(("pdns_server",pid=23612,fd=9))                                         
tcp     LISTEN   0        128              0.0.0.0:53            0.0.0.0:*       users:(("pdns_server",pid=23612,fd=7))

**Comment by Nim1com** [comment]
from this to this
root@pageifyns:~# curl -v -H 'X-API-Key: pa8J810Jia0' http://10.110.0.2:8081/api/v1/servers/localhost/zones/ | jq .
*   Trying 10.110.0.2:8081...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 10.110.0.2 (10.110.0.2) port 8081 (#0)
> GET /api/v1/servers/localhost/zones/ HTTP/1.1
> Host: 10.110.0.2:8081
> User-Agent: curl/7.68.0
> Accept: */*
> X-API-Key: pa8J810Jia0
> 
* Empty reply from server
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host 10.110.0.2 left intact
curl: (52) Empty reply from server
root@pageifyns:~# curl -v -H 'X-API-Key: pa8J810Jia0' http://127.0.0.1:8081/api/v1/servers/localhost/zones/ | jq .*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connect to 127.0.0.1 port 8081 failed: Connection refused
* Failed to connect to 127.0.0.1 port 8081: Connection refused
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 8081: Connection refused

**Comment by jbe-dw** [comment]
Better, but you have an empty reply, what do the PowerDNS logs tells ? (you should remove the trailing slash from the request url)

**Comment by Nim1com** [comment]
how do i check pdns logs?

**Comment by Nim1com** [comment]
May  6 00:00:05 pageifyns rsyslogd: [origin software="rsyslogd" swVersion="8.2001.0" x-pid="677" x-info="https://www.rsyslog.com"] rsyslogd was HUPed
May  6 00:00:05 pageifyns systemd[1]: logrotate.service: Succeeded.
May  6 00:00:05 pageifyns systemd[1]: Finished Rotate log files.
May  6 00:00:05 pageifyns systemd[1]: man-db.service: Succeeded.
May  6 00:00:05 pageifyns systemd[1]: Finished Daily man-db regeneration.
May  6 00:17:01 pageifyns CRON[37182]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 01:17:01 pageifyns CRON[39970]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 01:38:28 pageifyns systemd[1]: Starting Daily apt download activities...
May  6 01:38:31 pageifyns dbus-daemon[664]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.31' (uid=0 pid=41379 comm="/usr/bin/gdbus call --system --dest org.freedeskto" label="unconfined")
May  6 01:38:31 pageifyns systemd[1]: Starting PackageKit Daemon...
May  6 01:38:31 pageifyns PackageKit: daemon start
May  6 01:38:31 pageifyns dbus-daemon[664]: [system] Successfully activated service 'org.freedesktop.PackageKit'
May  6 01:38:31 pageifyns systemd[1]: Started PackageKit Daemon.
May  6 01:38:46 pageifyns systemd[1]: apt-daily.service: Succeeded.
May  6 01:38:46 pageifyns systemd[1]: Finished Daily apt download activities.
May  6 01:43:37 pageifyns PackageKit: daemon quit
May  6 01:43:37 pageifyns systemd[1]: packagekit.service: Succeeded.
May  6 02:03:59 pageifyns systemd[1]: Starting Ubuntu Advantage Timer for running repeated jobs...
May  6 02:03:59 pageifyns systemd[1]: ua-timer.service: Succeeded.
May  6 02:03:59 pageifyns systemd[1]: Finished Ubuntu Advantage Timer for running repeated jobs.
May  6 02:17:01 pageifyns CRON[43168]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 02:45:42 pageifyns snapd[680]: storehelpers.go:721: cannot refresh: snap has no updates available: "core18", "core20", "docker", "lxd", "snapd"
May  6 02:45:42 pageifyns snapd[680]: autorefresh.go:539: auto-refresh: all snaps are up-to-date
May  6 03:10:01 pageifyns CRON[45460]: (root) CMD (test -e /run/systemd/system || SERVICE_MODE=1 /sbin/e2scrub_all -A -r)
May  6 03:17:01 pageifyns CRON[45779]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 04:17:01 pageifyns CRON[48259]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 05:17:01 pageifyns CRON[50642]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 06:17:01 pageifyns CRON[53227]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 06:25:01 pageifyns CRON[53614]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily ))
May  6 06:26:00 pageifyns systemd[1]: Starting Daily apt upgrade and clean activities...
May  6 06:26:09 pageifyns systemd[1]: Reloading.
May  6 06:26:09 pageifyns systemd-udevd[597]: Network interface NamePolicy= disabled on kernel command line, ignoring.
May  6 06:26:09 pageifyns systemd[1]: Starting A high performance web server and a reverse proxy server...
May  6 06:26:09 pageifyns nginx[53833]: nginx: [emerg] open() "/etc/nginx/sites-enabled/smartface" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62
May  6 06:26:09 pageifyns nginx[53833]: nginx: configuration file /etc/nginx/nginx.conf test failed
May  6 06:26:09 pageifyns systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May  6 06:26:09 pageifyns systemd[1]: nginx.service: Failed with result 'exit-code'.
May  6 06:26:09 pageifyns systemd[1]: Failed to start A high performance web server and a reverse proxy server.
May  6 06:26:10 pageifyns dbus-daemon[664]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.36' (uid=0 pid=53890 comm="/usr/bin/gdbus call --system --dest org.freedeskto" label="unconfined")
May  6 06:26:10 pageifyns systemd[1]: Starting PackageKit Daemon...
May  6 06:26:10 pageifyns PackageKit: daemon start
May  6 06:26:10 pageifyns dbus-daemon[664]: [system] Successfully activated service 'org.freedesktop.PackageKit'
May  6 06:26:10 pageifyns systemd[1]: Started PackageKit Daemon.
May  6 06:26:18 pageifyns systemd[1]: apt-daily-upgrade.service: Succeeded.
May  6 06:26:18 pageifyns systemd[1]: Finished Daily apt upgrade and clean activities.
May  6 06:31:21 pageifyns PackageKit: daemon quit
May  6 06:31:21 pageifyns systemd[1]: packagekit.service: Succeeded.
May  6 06:37:19 pageifyns dbus-daemon[664]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.40' (uid=0 pid=54745 comm="/usr/bin/gdbus call --system --dest org.freedeskto" label="unconfined")
May  6 06:37:19 pageifyns systemd[1]: Starting PackageKit Daemon...
May  6 06:37:19 pageifyns PackageKit: daemon start
May  6 06:37:19 pageifyns dbus-daemon[664]: [system] Successfully activated service 'org.freedesktop.PackageKit'
May  6 06:37:19 pageifyns systemd[1]: Started PackageKit Daemon.
May  6 06:37:23 pageifyns systemd[1]: Reloading.
May  6 06:37:24 pageifyns systemd[1]: Starting Message of the Day...
May  6 06:37:24 pageifyns systemd[1]: motd-news.service: Succeeded.
May  6 06:37:24 pageifyns systemd[1]: Finished Message of the Day.
May  6 06:37:24 pageifyns systemd-udevd[597]: Network interface NamePolicy= disabled on kernel command line, ignoring.
May  6 06:37:24 pageifyns systemd[1]: Starting A high performance web server and a reverse proxy server...
May  6 06:37:24 pageifyns nginx[54875]: nginx: [emerg] open() "/etc/nginx/sites-enabled/smartface" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62
May  6 06:37:24 pageifyns nginx[54875]: nginx: configuration file /etc/nginx/nginx.conf test failed
May  6 06:37:24 pageifyns systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May  6 06:37:24 pageifyns systemd[1]: nginx.service: Failed with result 'exit-code'.
May  6 06:37:24 pageifyns systemd[1]: Failed to start A high performance web server and a reverse proxy server.
May  6 06:37:31 pageifyns CRON[53613]: (CRON) info (No MTA installed, discarding output)
May  6 06:42:29 pageifyns PackageKit: daemon quit
May  6 06:42:29 pageifyns systemd[1]: packagekit.service: Succeeded.
May  6 07:17:01 pageifyns CRON[57229]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 08:17:01 pageifyns CRON[60918]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 08:43:38 pageifyns systemd[1]: Starting Ubuntu Advantage Timer for running repeated jobs...
May  6 08:43:38 pageifyns systemd[1]: ua-timer.service: Succeeded.
May  6 08:43:38 pageifyns systemd[1]: Finished Ubuntu Advantage Timer for running repeated jobs.
May  6 09:07:40 pageifyns systemd[1]: Starting Refresh fwupd metadata and update motd...
May  6 09:07:40 pageifyns dbus-daemon[664]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.44' (uid=62803 pid=63598 comm="/usr/bin/fwupdmgr refresh " label="unconfined")
May  6 09:07:40 pageifyns systemd[1]: Starting Firmware update daemon...
May  6 09:07:40 pageifyns dbus-daemon[664]: [system] Successfully activated service 'org.freedesktop.fwupd'
May  6 09:07:40 pageifyns systemd[1]: Started Firmware update daemon.
May  6 09:07:40 pageifyns fwupdmgr[63598]: Updating lvfs
May  6 09:07:41 pageifyns fwupdmgr[63598]: Successfully downloaded new metadata: 0 local devices supported
May  6 09:07:41 pageifyns systemd[1]: fwupd-refresh.service: Succeeded.
May  6 09:07:41 pageifyns systemd[1]: Finished Refresh fwupd metadata and update motd.
May  6 09:17:01 pageifyns CRON[64061]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 09:33:01 pageifyns CRON[64762]: (root) CMD (   test -x /etc/cron.daily/popularity-contest && /etc/cron.daily/popularity-contest --crond)
May  6 09:48:21 pageifyns systemd[1]: Created slice User Slice of UID 0.
May  6 09:48:21 pageifyns systemd[1]: Starting User Runtime Directory /run/user/0...
May  6 09:48:21 pageifyns systemd[1]: Finished User Runtime Directory /run/user/0.
May  6 09:48:21 pageifyns systemd[1]: Starting User Manager for UID 0...
May  6 09:48:21 pageifyns systemd[65475]: Reached target Paths.
May  6 09:48:21 pageifyns systemd[65475]: Reached target Timers.
May  6 09:48:21 pageifyns systemd[65475]: Starting D-Bus User Message Bus Socket.
May  6 09:48:21 pageifyns systemd[65475]: Listening on GnuPG network certificate management daemon.
May  6 09:48:21 pageifyns systemd[65475]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
May  6 09:48:21 pageifyns systemd[65475]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
May  6 09:48:21 pageifyns systemd[65475]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
May  6 09:48:21 pageifyns systemd[65475]: Listening on GnuPG cryptographic agent and passphrase cache.
May  6 09:48:21 pageifyns systemd[65475]: Listening on debconf communication socket.
May  6 09:48:21 pageifyns systemd[65475]: Listening on REST API socket for snapd user session agent.
May  6 09:48:21 pageifyns systemd[65475]: Listening on D-Bus User Message Bus Socket.
May  6 09:48:21 pageifyns systemd[65475]: Reached target Sockets.
May  6 09:48:21 pageifyns systemd[65475]: Reached target Basic System.
May  6 09:48:21 pageifyns systemd[1]: Started User Manager for UID 0.
May  6 09:48:21 pageifyns systemd[1]: Started Session 31 of user root.
May  6 09:48:21 pageifyns systemd[65475]: Reached target Main User Target.
May  6 09:48:21 pageifyns systemd[65475]: Startup finished in 168ms.
May  6 10:17:01 pageifyns CRON[66663]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 10:23:56 pageifyns systemd[1]: Starting Daily apt download activities...
May  6 10:23:57 pageifyns systemd[1]: apt-daily.service: Succeeded.
May  6 10:23:57 pageifyns systemd[1]: Finished Daily apt download activities.
May  6 11:07:42 pageifyns systemd[1]: fwupd.service: Succeeded.
May  6 11:17:01 pageifyns CRON[69087]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May  6 11:50:38 pageifyns systemd[1]: Starting Cleanup of Temporary Directories...
May  6 11:50:38 pageifyns systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
May  6 11:50:38 pageifyns systemd[1]: Finished Cleanup of Temporary Directories.
May  6 11:50:42 pageifyns snapd[680]: storehelpers.go:721: cannot refresh: snap has no updates available: "core18", "core20", "docker", "lxd", "snapd"
May  6 11:50:42 pageifyns snapd[680]: autorefresh.go:539: auto-refresh: all snaps are up-to-date
May  6 12:17:01 pageifyns CRON[71858]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by Nim1com** [comment]
what else can i try?

**Comment by jbe-dw** [comment]
You can get help on PowerDNS IRC channel to configure your system for correct logging and interface binding.

Once it will be configured, and you can query the PowerDNS API via it's ip address correctly, we can continue this discussion.

Regards

**Comment by jbe-dw** [comment]
No update yet, please reopen if you still need more help
