### ISSUE TITLE
Error 500 on /dashboard/ | Docker (docker-compose)

### ISSUE THREAD

**Issue by tkorves** [PowerDNS-Admin/PowerDNS-Admin#1191]
``Hi there,

I ran (as a test pre-migrating) PowerDNS-Admin with docker-compose against the same DB we're using with a locally "installed" git clone of PowerDNS-Admin.

Login is possible, same API-Key and Hash are used with docker-compose like we use it in our "installed" PowerDNS-Admin.

But on /dashboard/ it greets us with a 500 Error.

docker-compose logs -f has this for us:
`powerdns_admin  | [2022-05-11 21:04:19,376] [app.py:1891] ERROR - Exception on /dashboard/ [GET]`
`powerdns_admin  | Traceback (most recent call last):`
`powerdns_admin  |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app`
`powerdns_admin  |     response = self.full_dispatch_request()`
`powerdns_admin  |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request`
`powerdns_admin  |     rv = self.handle_user_exception(e)`
`powerdns_admin  |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception`
`powerdns_admin  |     reraise(exc_type, exc_value, tb)`
`powerdns_admin  |   File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise`
`powerdns_admin  |     raise value`
`powerdns_admin  |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request`
`powerdns_admin  |     rv = self.dispatch_request()`
`powerdns_admin  |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request`
`powerdns_admin  |     return self.view_functions[rule.endpoint](**req.view_args)`
`powerdns_admin  |   File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view`
`powerdns_admin  |     return func(*args, **kwargs)`
`powerdns_admin  |   File "/app/powerdnsadmin/routes/dashboard.py", line 192, in dashboard`
`powerdns_admin  |     detailedHistories = convert_histories(history)`
`powerdns_admin  |   File "/app/powerdnsadmin/routes/admin.py", line 914, in convert_histories`
`powerdns_admin  |     detailedHistories.append(DetailedHistory(histories[i], None))`
`powerdns_admin  |   File "/app/powerdnsadmin/routes/admin.py", line 766, in __init__`
`powerdns_admin  |     detail_dict = json.loads(history.detail)`
`powerdns_admin  |   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads`
`powerdns_admin  |     return _default_decoder.decode(s)`
`powerdns_admin  |   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode`
`powerdns_admin  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
`powerdns_admin  |   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode`
`powerdns_admin  |     obj, end = self.scan_once(s, idx)`
`powerdns_admin  | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

OS: Ubuntu 22.04
Docker-Version: 20.10.15, build fd82621
Docker-Compose-Version: v2.5.0

It's running unprivileged under a normal useraccount (not root). All other pages within PowerDNS-Admin are working, connection to our PDNS server is also working.

Any ideas? Maybe I'm just dumb and blind - I just don't know.

BR
Tim

**Comment by tkorves** [comment]
Magically, without changing anything, it now is functional, no further errors. Sorry for disturbing. :-D

**Comment by cwchristerw** [comment]
I have similar issue

**Comment by jbe-dw** [comment]
Hello,

Do you also use the docker image to run PDA ? You need to use v0.2.5 or later, as well as upgrading your 'not containerized' app and then run 'flask db upgrade' otherwise.

Regards
