### ISSUE TITLE
Email confirmation has unchangeable link to localhost:9191

### ISSUE THREAD

**Issue by falz** [PowerDNS-Admin/PowerDNS-Admin#1193]
The confirmation email email template at **templates/emails/account_verification.html** uses the **site_url** variable which doesn't appear to be configureable (also mentioned in issue https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/866). Because of this, the bottom part of the email always links to localhost:9191 as that's what's hard coded in **models/settings.py**

We've temporarily worked around this by manually editing the account_verification.html email template. Is there a cleaner workaround available that will know the public hostname if the site is behind a reverse proxy?

A small handful of the settings in models/settings.py are visible at the URL **/admin/setting/basic**. Perhaps making site_url changeable there would be a clean fix.

**Comment by jbe-dw** [comment]
Hello,

Until we make it configurable, there is no better workaround.

Regards

**Comment by AzorianSolutions** [comment]
Caching a reference to the [feature list](https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1178).
