### ISSUE TITLE
bad request cannot add this domain help Plz

### ISSUE THREAD

**Issue by elheme** [PowerDNS-Admin/PowerDNS-Admin#1197]
i have this error help plz
cannot add this domain 
![image](https://user-images.githubusercontent.com/105807219/169087626-e9e59d8a-8f59-4c84-b1dd-c45287773465.png)

**Comment by Metrax** [comment]
Please have a look to the PDA logs and show us the correspoding error.

**Comment by Metrax** [comment]
@elheme unfortunately, your reply includes no information. Please show us the logs, than we can try to help you.

**Comment by elheme** [comment]
I don't have a pdns.log
in pda i don't have any error

**Comment by Metrax** [comment]
@elheme Are you using docker or systemd for PDA?
