### ISSUE TITLE
Announcement: Looking for a Frontend developper

### ISSUE THREAD

**Issue by jbe-dw** [PowerDNS-Admin/PowerDNS-Admin#1207]
Hello,

We strongly need some help on the frontend side. We currently have very limited skills in JS technologies, which limit us from moving the project forward. 

A good starting point could be an upgrade of used libraries.

If any of you has skills in this domain, please let us know.

Regards
PowerDNS Admin Team

**Comment by AzorianSolutions** [comment]
What is the real long-term vision here for the app? If you recall, I had previous started a discussion about a potential overhaul of the app in this respect. Of course, my proposal did involve a more complicated implementation but I'm not so sure you truly get one without the other.

My vote is toward a Vue based app as the latest generation of design with components is pretty snazzy for code organization.

**Comment by jbe-dw** [comment]
Hello,

I'll remind you that we believe that we should try to achieve a bug-free (or something close to) v1 of the project in its current implementation. It means fixing opened issues and include the last remaining feature PR and make it stable.

The long term view, which is not realistic today because of the large work it requires is not compatible with the current size of the team, is to provide a new implementation of PDA. I think that we agree that a modern architecture based on the app's API is the way to go, but it requires a lot of work on the backend first.

About the JS framework, I have nothing I can argue for or against, as I really don't know about this.

**Comment by AzorianSolutions** [comment]
@jbe-dw so based on the immediately desired direction, what exactly would you like to achieve with the current code base as it relates to the UI? I realize you listed the upgrading of current packages but I'm sure there is more to the list than that.

**Comment by jbe-dw** [comment]
Hello,

We need help to check and fix all UI related issues. I have make an effort to cleanup the tracker but we still stick arround ~100. There are some issues tagged with "ui" and "javascript" labels that you can look at.

I'll also appreciate your feedback on #485. It is open for a long time, but I'm not sure if it is really doing ui testing and if it is reliable.

Thank you

**Comment by AzorianSolutions** [comment]
I'll take a gander and see if I might be able to help with this. I can't say I'm familiar with this particular framework but on the surface, it seems somewhat self-explanatory.
