### ISSUE TITLE
Feature request: add option to disable OTP

### ISSUE THREAD

**Issue by pschiffe** [PowerDNS-Admin/PowerDNS-Admin#122]
It would be great, if administrator has option to disable OTP auth. If disabled, no OTP field on login page would be displayed and user wouldn't be able to enable 2fa in my profile page.

**Comment by zmsp** [comment]
My hacky way around it was https://github.com/zmsp/PowerDNS-Admin/commit/fdcf9b69bfdfd4da496724b13c5ee356b05ebac7

**Comment by brainwarped69** [comment]
Adds new setting enable_otp which controls the display of the otp token field on the login page.
[fix122.txt](https://github.com/ngoduykhanh/PowerDNS-Admin/files/2643954/fix122.txt)

**Comment by vmarkop** [comment]
Fixed by #942.

Regards
PowerDNS Admin Team
