### ISSUE TITLE
OIDC logout URL isn't compatible with Keycloak 18.0.0+

### ISSUE THREAD

**Issue by cwchristerw** [PowerDNS-Admin/PowerDNS-Admin#1222]
1. Login with OpenID Connect
2. Logout
3. Browser redirects to https://{subdomain}.cwinfo.net/realms/{realm}/protocol/openid-connect/logout?redirect_uri=https://{subdomain2}.cwinfo.net/login

```
Invalid parameter: redirect_uri
```

**Comment by cwchristerw** [comment]
https://github.com/keycloak/keycloak/issues/12002

**Comment by jbe-dw** [comment]
Hello,

Thanks for reporting. We will have a look at it soon

Regards

**Comment by cstisa** [comment]
Dear all,

I have the same issue with invalid parameter : redirect_url on Keycloak 21.1.1.

Is there any update on this ? 

Thank you for the support.

Have a nice day.

**Comment by teunis90** [comment]
Keycloak expects these two values:
- post_logout_redirect_uri (and not redirect_uri)
- id_token_hint (which is recommended by the spec: https://openid.net/specs/openid-connect-rpinitiated-1_0.html, but required by keycloak)

Tested on Keycloak version: 20.0.5

This is where the redirect is set:

https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/8108caf96a03fb87e9a42ae85d4dc1000822f1a3/powerdnsadmin/routes/index.py#L656-L658

Is there a guide how to start powerdns-admin in development modus (pycharm)? I would like to play around with the `id_token_hint` parameter and see if I can get this working.
