### ISSUE TITLE
Is there a way to update NS across all domains at once

### ISSUE THREAD

**Issue by wartw** [PowerDNS-Admin/PowerDNS-Admin#1223]
Is there a way to update NS across all domains at once

**Comment by jbe-dw** [comment]
Hello,
There is no way to do such a thing
Regards

**Comment by Metrax** [comment]
> Is there a way to update NS across all domains at once

With low level bash experiences, you can write a simple script using the pdnsutil to do this.
Alternatively with coding expieriences you can do this with the PDNS API or PDA API. But we would not write this code for you ;-)
