### ISSUE TITLE
Responsive Tables

### ISSUE THREAD

**Issue by JustinBack** [PowerDNS-Admin/PowerDNS-Admin#1239]
This has been an issue for a while (at least on my 11" iPad), that all tables are not responsive and extend way beyond the screen (I am unable to edit anything on the ipad)

Maybe its fixed by adding `table-responsive` as it looks like bootstrap is used?

![image](https://user-images.githubusercontent.com/40178814/182168926-d58e6ef9-942e-4ad7-bbe5-066ebeba78c7.jpeg)

(This issue has persisted since iPadOS 15 throughout iPadOS 16)

**Comment by Metrax** [comment]
Currently there is some work at the UI, i.E. the adaption to AdminLTE3.
After these works are done, we can think about to implement some enhancements to the UI.

**Comment by AzorianMatt** [comment]
@JustinBack I'm please to report that many updates have been made recently involving a more responsive, mobile-first UI approach so editing on tablets and mobile phones is now feasible.
