### ISSUE TITLE
Missing info in README.md about initial install

### ISSUE THREAD

**Issue by ppbrown** [PowerDNS-Admin/PowerDNS-Admin#1243]
Please add following lines, at line 38, to README.md

```
You can then use your brower to connect to http://localhost:9191 and create an account for
yourself, which will automatically be made the admin account.

``` 

Also.. it references some "SECRET_KEY"... but as far as I can tell, that now does nothing?

**Comment by lovilak** [comment]
I had to do something like `source flask/bin/activate
export FLASK_APP=./powerdnsadmin/__init__.py
python -c 'import bcrypt; print(bcrypt.gensalt().decode())'` to change the salt var. It was not in the doc as far.

**Comment by jbe-dw** [comment]
@dmcken fyi

**Comment by AzorianMatt** [comment]
This documentation modification has been fulfilled.
