### ISSUE TITLE
PowerDNS-Admin Docker with nginx proxy

### ISSUE THREAD

**Issue by douglagm** [PowerDNS-Admin/PowerDNS-Admin#1245]
Hi All,

I followed the following tutorial: [https://computingforgeeks.com/running-powerdns-and-powerdns-admin-in-docker-containers/](url) 
I am using the docker-compose example and it works like a charm as I can access the PowerDNS url via port 8080.

As I have several containers, I decided to use nginx installed on the server as a reverse proxy to proxy the various applications:
[https://server.domain.com/pdnsadmin/](url)
[https://server.domain.com/portainer/](url)

My nginx reverse proxy to the PowerDNS-Admin container does not work at all (Error 404). I have tried several different configurations, even the configuration in the tutorial, but none seem to work. For now, I am just trying the most basic of configuration to remove complexity, hence no SSL, below is my current config:

`upstream pdnsadmn {
        server 127.0.0.1:8080;
}`

`location /pdnsadmin/ {
                        
                        #proxy_set_header Host $host;
                        #proxy_set_header X-Real-IP $remote_addr;
                        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        #proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_pass http://pdnsadmn;
                        #index  index.html index.htm;
                        proxy_buffering off;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-Host $host;
                        proxy_set_header X-Forwarded-Port $server_port;
        }`

Is there perhaps someone that can assist me with the nginx reverse proxy config for the PowerDNS-Admin Docker container. 

Thank-you very much

**Comment by absynth47215** [comment]
>                     proxy_pass http://pdnsadmn;

Maybe try this:
proxy_pass http://pdnsadmn/;

I think what happens without a trailing slash is that the path /powerdns/ is passed into the proxied service, and powerdns-admin doesn't know about a path /powerdns/. 
As far as I know, adding a trailing / to the proxy_pass statement mitigates this.

**Comment by AzorianSolutions** [comment]
Given that the OP hasn't responded in some time, I'm closing this question as resolved.
