### ISSUE TITLE
Problem to replace a register type

### ISSUE THREAD

**Issue by vhsantos** [PowerDNS-Admin/PowerDNS-Admin#1251]
Hello,

we have found that the last version of PDA don't allow a change of RRSet, for example, if I want to change this register:
```
the-cat-say-miau-miau PTR  Active 300 10.11.12.13
```
to this:
```
the-cat-say-miau-miau CNAME Active 300 my-server.mydomain.com.
```

It generates an error **RRset the-cat-say-miau-miau.lab. IN CNAME: Conflicts with pre-existing RRset**

Probably this come with this [PR 1201](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1201), where the PDA try to replace the register first and delete later. Maybe a delete first and replace later should fix the problem ??

**Comment by vhsantos** [comment]
For now, a workaround is to delete the register, apply the changes, create the register and apply the changes. :-(

**Comment by jbe-dw** [comment]
Hello,

I let @corubba give you an answer. I'll take a look into this shortly

Regards

**Comment by vhsantos** [comment]
Hi again.

Thanks for the quick fix.
