### ISSUE TITLE
IDN search does not work

### ISSUE THREAD

**Issue by domXmob** [PowerDNS-Admin/PowerDNS-Admin#1252]
Hello!

Just found out that it's hard to find IDN Domains by the search.

The Interface itself shows the domains by IDN Name.
It is possible to find the domain by typing the ACE Name (which user usually don't know).
But there will be nothing found by the IDN Name.

### example-data:
```
ACE: xn--exmple-cua.com
IDN: exämple.com
```

### Ideas how to solve it:
- a converter back to ACE from IDN for the query string
- an additional cached column/table in the database with all IDN Names ready that can be used during the search

**Comment by AzorianSolutions** [comment]
Hi @domXmob!

I'm confused by your statement. Are you saying the search doesn't work for you? As far as I can tell from a test I just did, it's working just as expected on the dashboard page (in the table header).

Could you provide more context?

**Comment by domXmob** [comment]
Hey @AzorianSolutions,

I pulled the latest master branch and did this test now:

when I type in "xn" I get results
![image](https://user-images.githubusercontent.com/56199291/207116305-a9244f62-28d0-4abf-9e6e-0f5dd984e209.png)

when I type in "mö" I get no results.
![image](https://user-images.githubusercontent.com/56199291/207116494-9388e49e-69d4-4987-ba83-961a0eb6b372.png)

And I've verified to have the changes in my running docker:
![image](https://user-images.githubusercontent.com/56199291/207117042-d08d58c0-9fad-4d48-8a6b-d074f2faf41c.png)

I you can reproduce this issue. I don't even get an error, just no results.

**Comment by AzorianSolutions** [comment]
@domXmob,

Thank you, this is great context! I don't know if it relates to a character encoding issue or what, but I would say you definitely found a bug here. Would you mind submitting the photos and report in a new issue labeled as a bug to maintain workflow? I would hope this is a fairly simple fix with some good diagnosis but we shall see.
