### ISSUE TITLE
Update systemd documentation

### ISSUE THREAD

**Issue by bastelfreak** [PowerDNS-Admin/PowerDNS-Admin#1263]
Hi,
the wiki has a few pages about systemd units. I did some hardening which results in the following service file:

```
[Install]
WantedBy=multi-user.target

[Unit]
Description=PowerDNS-Admin
Requires=pdns.service
After=pdns.service

[Service]
Environment="FLASK_CONF=../configs/production.py"
Environment="FLASK_APP=powerdnsadmin/__init__.py"
User=powerdns-admin
Group=powerdns-admin
WorkingDirectory=/opt/powerdns-admin/PowerDNS-Admin/
ExecStart=/opt/powerdns-admin/PowerDNS-Admin/prod/bin/python run.py
PrivateTmp=true
RestrictSUIDSGID=true
NoNewPrivileges=true
RemoveIPC=true
PrivateDevices=true
PrivateMounts=true
ProtectProc=invisible
ProcSubset=pid
ProtectHostname=true
ProtectClock=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
RestrictAddressFamilies=AF_INET
RestrictRealtime=true
SystemCallArchitectures=native
ProtectHome=true
ProtectSystem=strict
MemoryDenyWriteExecute=true
LockPersonality=true
CapabilityBoundingSet=
SystemCallFilter=
SystemCallFilter=@network-io @file-system @basic-io @system-service
SystemCallFilter=~@aio @chown @clock @cpu-emulation @debug @keyring @memlock @module @mount @obsolete @privileged @raw-io @reboot @resources @setuid @swap userfaultfd mincore
RestrictNamespaces=~user pid net uts mnt cgroup ipc
UMask=0077

[Install]
WantedBy=multi-user.target
```

* for testing purposes, this uses the builtin webserver, but gunicorn would work as well
* this allows IPv4 traffic to the services, meaning it has to connect to postgresql/mysql and powerdns via IPv4. And a Webserver needs to be configured in front of it
* Allowed syscalls are reduced to a minium

you can analyze this on your own with `systemd-analyze security $unit`. I would have added it to the wiki, but I think I need write permisions for that? Maybe this unit file will help others. It has a systemd security score of 1.2.

**Comment by jbe-dw** [comment]
Hello,

Thanks for your feedback. We will add it to the documentation later. Keep this issue opened, we'll close it once it's in the docs.

Regards

**Comment by Alestor** [comment]
This config is way to hard for a productive deployments. It's like in German High School - with an average grade of 1.2, you won't make many friends :-)  On the other hand, the suggested systemd config on the project wiki sucks hard, if taken security into account. It only considers functionality.
Anyway, SystemCallFilter=~@aio will most likely prevent a gunicorn deployment from starting and ProtectSystem=strict without a ReadWritePaths statement will cause issues as well.

**Comment by dmcken** [comment]
Any reason the [Install] section is there twice?

**Comment by bastelfreak** [comment]
ups, that was a copy and paste error.

**Comment by dmcken** [comment]
Ok, anyone able to confirm this all works before I update the docs?

**Comment by WhatshallIbreaktoday** [comment]
Hello, tested with gunicorn, (on latest 0.4.1 where gunicorn is installed inside venv) [wiki page](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/wiki/install/Running-PowerDNS-Admin-on-Ubuntu-or-Debian.md)
... and got a complain about readonly filesystem and thus not starting.

can test further .. but have no clue where to tweak this file to make it work.. any clue?

**Comment by AzorianMatt** [comment]
@WhatshallIbreaktoday this is not the appropriate place to start a conversation for help on deployment. Please start a discussion instead.
