### ISSUE TITLE
Connecting PowerDNS Admin to PDNS via PDNS Recursor

### ISSUE THREAD

**Issue by TheFrisianClause** [PowerDNS-Admin/PowerDNS-Admin#1264]
Hello,

I have a question regarding using PowerDNS Admin in Docker (on a seperate Docker VM), connecting via the PDNS-Recursor to PDNS Authoritative. As it looks like when I connect the PDNS Admin via the PDNS-Recursor to the PDNS Authoritative server  the API times out and give a maximum tries exceeded. But when I connect the Docker VM with PowerDNS directly to PDNS Authoritative without the PDNS-Recursor in between it works like a charm. Is there some kind of setting in the PDNS-Recursor config which is in the way?

This is the error:

```
Max retries exceeded with url: /api/v1/servers/localhost/statistics (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f044bcfd580>, 'Connection to 10.1.1.100 timed out. (connect timeout=30)'))
```

Does someone have a similar approach, how did you resolve this?

**Comment by jbe-dw** [comment]
Hello,

PowerDNS Admin is a proxy (API + GUI) to the PowerDNS Authoritative Server. It can manage any PDNS Auth through its API.

PowerDNS Recursor is a cache/resolver that communicates directly with PDNS Auth with DNS protocol. It provides an API that can show statistic and trigger resolver-related actions.

PDNS Admin can't use PDNS Recursor's API. People asked if PDNS Admin could trigger recursor's actions (like refreshing it's cache) but it's something not iplemented yet.
You should stick to the PDNS Admin > PDNS Auth setup and configure your recursor independently.

Regards
