### ISSUE TITLE
Feature request: auto-save for resource records

### ISSUE THREAD

**Issue by direktorn** [PowerDNS-Admin/PowerDNS-Admin#128]
Hi, 
1. I would like to see an auto-save feature for the entries. Lets say I want to add 10 records I would like to be able to do that quite quickly and when I'm done I can apply the changes. Also saving data is not really true as if you move to another part of the GUI without Applying changes all your changes are lost. 
1. The GUI does not support SRV records. I'd also like that PTR records are handled differently, as your options are different. 

3.. It would be nice that you can actually see the DNS Zone (Even if its storted in Pdns) - just so you can review that it looks alright.

**Comment by trenb** [comment]
For multiple issues, it's best to log multiple requests. With regards to editing SRV and other records, look at this [https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/config_template.py#L78](url) - You can add other record types you'd like to edit. 

Can't really speak to your other questions. 

HTH

**Comment by jallakim** [comment]
1. Auto-save should be opt-in in that case. With a BIG warning sign. Being able to do (multiple) changes, and then review them, before saving/pushing the changes, is quite nice and non-disruptive.

2. See comment from @trenb (the URL is wrong, try [this one]( https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/config_template.py#L78)). It's in the documentation. Regarding PTR; what should be "handled differently"? What "other" options?

3. What do you mean? The records you see, are parsed from the raw zone file via the API of pdns. Not sure what info you think is "missing"? If you want to display the NS/SOA/whatever-records as well, see the same option as in 2) (the `RECORDS_ALLOW_EDIT` parameter).
