### ISSUE TITLE
Disable Google Fonts or save the fonts locally in the system.

### ISSUE THREAD

**Issue by micneon** [PowerDNS-Admin/PowerDNS-Admin#1280]
Hello,

is there any way to disable Google Fonts or save this Local. In the login they are not present but if you call an invalid page on the URL an external visitor gets a 404 page with the fonts.

If necessary it would be great if you could either disable the fonts and install them locally if needed or a fix for this 404 and any other pages that can be called without access.

Greetings Micneon

**Comment by seraphyn** [comment]
@meineerde Thanks, good to know.
I've already forgotten this feature
