### ISSUE TITLE
PowerDNS Admin Project is looking for new maintainers

### ISSUE THREAD

**Issue by jbe-dw** [PowerDNS-Admin/PowerDNS-Admin#1285]
Dear community,

I had recent changes in my life that drew me away from this project. The other maintainers have changed their priorities. As consequence, the project is left unmaintained for weeks. I tried to recruit more person in the project without any success, and our small team could fix and improve a little bit PDA, but can no longer succeed at this task.

If any adopter wants to step up to continue, I'd be happy to let him/her in. I hope so, because I'd be sad if this project would die.

Please let me know if you want to take up the torch.

Regards
J.

**Comment by g1zm0e** [comment]
I would be interested

**Comment by jasonmacer** [comment]
I would not use it. I use this on a daily basis of my only servers. Love the application

**Comment by Archef2000** [comment]
I would be interested as i have made a python backend personally.

**Comment by dmcken** [comment]
I would also be interested in assisting.

**Comment by pneb** [comment]
I'd like to contribute to this project on a daily basis, not completely maintain it.

**Comment by AdvanticGmbH** [comment]
We would certainly be also interested in actively contributing to this project.

**Comment by jbe-dw** [comment]
Hello,

I'm pleased to see that you answered my call. Some of you said that they want to contribute but they don't want to be maintainers. Which is fine. For the others, I'd like to remember what is being a maintainer (which you may know), because it is not only about writing code. Being a maintainer is:

- Assisting people with their issues (sometimes with your knowledge, sometimes by taking time to test the conditions of the issue on your side)
- Reviewing and testing PR 
- Contributing as well (to fix a bug or add a new functionality)
- Participating to the project housekeeping

Please, let me know if you are ready to engage on all these topics.

I'd like to know about your skills too:
- Python
- REST APIs
- Databases
- JavaScript / Jquery
- Third party auth plugins (LDAP/AD/Azure/Oauth/OTP)
- DNS
- Familiar with Docker

This project is built from Python Flask with SQLAlchemy and AdminLTE frontend. Skills in these domains are required. You don't have to be an expert in all domains, but if we could cover all of them it would be a plus.

Thanks

**Comment by dmcken** [comment]
I'm an ISP engineer for the past 17 years.

- Python for automation for about 15 of those years. More familiar with Django than Flask but should be able to adapt easily enough.
- Consume REST APIs quite often.
- MySQL / Postgres (mostly with TimescaleDB underlying Zabbix), custom development for primary job. Not really a fan of NoSQL although I have used Mongo 
- Basic / Intermediate Javascript (to be honest I'm not very good at front-ends).
- Familiar with auth plugins (LDAP / OTP), not as familiar with Azure and Oauth.
- Been doing DNS at ISP level (forward and reverse) for most of my working time.
- Quite familiar with Docker, created custom Docker files for deploying my custom apps and am now working on kurbernetes (k3s specifically mainly for edge deployments).

I would be happy to help with the management tasks, I've not done that many public PRs but I have made some contributions to the netbox device library and the supporting scripts for it. I'm a bit green with full fledged CI/CD pipelines but they seem simple enough especially with containers.

As far as I have seen almost everything sits within github, don't think I've seen an official docker image (I've been using ngoduykhanh/powerdns-admin, seems heavily used and kept up to date) or a readthedocs page so I guess we need to define the complete scope of what external systems would also need to be maintained as well.

**Comment by Archef2000** [comment]
I have some small project that are mainly docker images.
But I have also created a python backend over the last two month.
I would like to help with the maintaining tasks.

  * Nearly my whole infastructure is packed in docker containers and i build many containers by myself
  * My javascript skills are ok but i could still learn some front-end skills
  * I the devoloping of the python backend i have learned OAuth2 for google drive and made a new rest api for an existing UI
  * For my own server i use LDAP and 2FA (not only OTP) for AUTH
  * When it comes to databases i have learnd and used SQL in some small projects
  * I know the concept of dns servers and the diffrent entry types

**Comment by jbe-dw** [comment]
@jasonmacer @AdvanticGmbH can you contact me at powerdnsadm <at> gmail <dot> com ?

I invited others to a chatroom but I can't add you too.

**Comment by jbe-dw** [comment]
@g1zm0e @Archef2000 @pneb I've sent you an invite to our Gitter room. It can be accessed via your browser with your github account. We are waiting for you to start.

This won't make you a maintainer, but we can discuss further an exchange some intels about you and the team there privately.

Please get some time to show up there, Final call.

**Comment by jbe-dw** [comment]
Can you send me an email to the previously mentioned address ? I'm not able to cast a new invite in the chatroom.

**Comment by pneb** [comment]
> Can you send me an email to the previously mentioned address ? I'm not able to cast a new invite in the chatroom.

You can use my contact email: contact@bern.codes

**Comment by pneb** [comment]
Thanks! I've received the mail.

**Comment by AzorianSolutions** [comment]
Hi everyone,

For those of you still interested in contributing to the rebirth of this project and many great things to come, then please join us in the project's new Mattermost deployment (OSS Slack essentially). It is by invite only so to get an invite, please email me at "admin@powerdnsadmin.org" and I will provide a registration link for you.

@pneb @Archef2000 @g1zm0e @AdvanticGmbH
