### ISSUE TITLE
Add support for APL record type

### ISSUE THREAD

**Issue by urobasa** [PowerDNS-Admin/PowerDNS-Admin#1287]
The page admin/setting/dns-records has a link to a list of supported powerdns record types
https://doc.powerdns.com/authoritative/appendices/types.html
there is a supported APL record type

But in the list of types on the admin/setting/dns-records page there is no support record type APL

added APL to powerdns - https://github.com/PowerDNS/pdns/pull/8638

**Comment by Metrax** [comment]
I've put this to the feature request list:
https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1178
Currently we have a lack of contributors, i cannot give an ETA for this issue.
