### ISSUE TITLE
Allow to use api keys for PowerDNS-Admin API calls

### ISSUE THREAD

**Issue by samip5** [PowerDNS-Admin/PowerDNS-Admin#1290]
I would love to be able to use API keys to call the pda api, but it seems that it only supports basic auth which makes it quite difficult to do programmatically while also using LDAP auth.

Would this be something that an PR would be accepted for?

**Comment by MrGeneration** [comment]
I'm using `acme.sh` with PDA API-Tokens.
I don't the API only allows basic authentication due to that.

How does your payload look like...?

**Comment by samip5** [comment]
> I'm using `acme.sh` with PDA API-Tokens. I don't the API only allows basic authentication due to that.
> 
> How does your payload look like...?

I'm talking about endpoints like `https://dns.<snip>.fi/api/v1/pdnsadmin/accounts` or `https://dns.<snip>.fi/api/v1/pdnsadmin/zones`.

Aka pda specific ones.

**Comment by dorancemc** [comment]
The API via /powerdnsadmin only allows Basic Auth, and does not work for the users with AD authentication. I got the error `[decorators.py:174] ERROR - Error: Invalid salt`
