### ISSUE TITLE
can't add any api key at all.

### ISSUE THREAD

**Issue by sa7aux** [PowerDNS-Admin/PowerDNS-Admin#1294]
Hi i got this error, and i try to add a api key
that says invalid salt, and have change it and recompile flask and try to find where the problem is and don't can figure out where

//bjorne

Dec  5 13:50:09 speed gunicorn[2559]: [2022-12-05 13:50:09,688] [app.py:1891] ERROR - Exception on /admin/key/edit [POST]
Dec  5 13:50:09 speed gunicorn[2559]: Traceback (most recent call last):
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
Dec  5 13:50:09 speed gunicorn[2559]:     response = self.full_dispatch_request()
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
Dec  5 13:50:09 speed gunicorn[2559]:     rv = self.handle_user_exception(e)
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
Dec  5 13:50:09 speed gunicorn[2559]:     reraise(exc_type, exc_value, tb)
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
Dec  5 13:50:09 speed gunicorn[2559]:     raise value
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
Dec  5 13:50:09 speed gunicorn[2559]:     rv = self.dispatch_request()
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
Dec  5 13:50:09 speed gunicorn[2559]:     return self.view_functions[rule.endpoint](**req.view_args)
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
Dec  5 13:50:09 speed gunicorn[2559]:     return func(*args, **kwargs)
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/powerdnsadmin/decorators.py", line 33, in decorated_function
Dec  5 13:50:09 speed gunicorn[2559]:     return f(*args, **kwargs)
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/powerdnsadmin/routes/admin.py", line 341, in edit_key
Dec  5 13:50:09 speed gunicorn[2559]:     apikey = ApiKey(desc=description,
Dec  5 13:50:09 speed gunicorn[2559]:   File "<string>", line 4, in __init__
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
Dec  5 13:50:09 speed gunicorn[2559]:     manager.dispatch.init_failure(self, args, kwargs)
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
Dec  5 13:50:09 speed gunicorn[2559]:     compat.raise_(
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Dec  5 13:50:09 speed gunicorn[2559]:     raise exception
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
Dec  5 13:50:09 speed gunicorn[2559]:     return manager.original_init(*mixed[1:], **kwargs)
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/powerdnsadmin/models/api_key.py", line 36, in __init__
Dec  5 13:50:09 speed gunicorn[2559]:     self.key = self.get_hashed_password(rand_key).decode('utf-8')
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/powerdnsadmin/models/api_key.py", line 109, in get_hashed_password
Dec  5 13:50:09 speed gunicorn[2559]:     return bcrypt.hashpw(pw.encode('utf-8'),
Dec  5 13:50:09 speed gunicorn[2559]:   File "/var/www/html/pdns/flask/lib/python3.9/site-packages/bcrypt/__init__.py", line 84, in hashpw
Dec  5 13:50:09 speed gunicorn[2559]:     return _bcrypt.hashpass(password, salt)
Dec  5 13:50:09 speed gunicorn[2559]: ValueError: Invalid salt

**Comment by jbe-dw** [comment]
https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/938#issuecomment-853837503
