### ISSUE TITLE
module 'ldap' has no attribute 'OPT_X_TLS' after upgrade

### ISSUE THREAD

**Issue by mastermueller** [PowerDNS-Admin/PowerDNS-Admin#1306]
Hi!
Just updated my docker container today, now LDAP Login throws the error 
_module 'ldap' has no attribute 'OPT_X_TLS'_
The LDAP login worked before the upgrade.
I can still login with LOCAL auth, LDAP-Settings seem fine to me.

**Comment by pneb** [comment]
Would you mind pasting the whole traceback error here?

**Comment by jbe-dw** [comment]
Hello,

This is due to a patch upgrading to python-ldap 3.4.2, this version removed this deprecated option. We will release an update quickly.

**Comment by jbe-dw** [comment]
@mastermueller Can you try to remove the line targeted by this PR #1323 ?

You can do it by editing the file in the app folder of the container in an interactive shell. You must restart the container to load the change.

**Comment by mastermueller** [comment]
Hi!
I can confirm this fix does the trick, thank you!

 

Von: jbe-dw ***@***.***> 
Gesendet: Montag, 12. Dezember 2022 16:03
An: PowerDNS-Admin/PowerDNS-Admin ***@***.***>
Cc: mastermueller ***@***.***>; Mention ***@***.***>
Betreff: Re: [PowerDNS-Admin/PowerDNS-Admin] module 'ldap' has no attribute 'OPT_X_TLS' after upgrade (Issue #1306)

 

@mastermueller <https://github.com/mastermueller>  Can you try to remove the line targeted by this PR #1323 <https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1323>  ?

You can do it by editing the file in the app folder of the container in an interactive shell. You must restart the container to load the change.

**Comment by AzorianSolutions** [comment]
@mastermueller thank you for pointing this out and my apologies for any complications caused. The current project's stability is low so it's an expected pain unfortunately.
