### ISSUE TITLE
IDN search does not work

### ISSUE THREAD

**Issue by domXmob** [PowerDNS-Admin/PowerDNS-Admin#1325]
Hello,

I pulled the latest master branch and did this test now:

when I type in "xn" I get results
![image](https://user-images.githubusercontent.com/56199291/207116305-a9244f62-28d0-4abf-9e6e-0f5dd984e209.png)

when I type in "mö" I get no results.
![image](https://user-images.githubusercontent.com/56199291/207116494-9388e49e-69d4-4987-ba83-961a0eb6b372.png)

And I've verified to have the changes in my running docker:
![image](https://user-images.githubusercontent.com/56199291/207117042-d08d58c0-9fad-4d48-8a6b-d074f2faf41c.png)

I hope you can reproduce this issue. I don't even get an error, just no results.

_Originally posted by @domXmob in https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1252#issuecomment-1346949455_

**Comment by pneb** [comment]
> Hello,
> 
> I pulled the latest master branch and did this test now:
> 
> when I type in "xn" I get results ![image](https://user-images.githubusercontent.com/56199291/207116305-a9244f62-28d0-4abf-9e6e-0f5dd984e209.png)
> 
> when I type in "mö" I get no results. ![image](https://user-images.githubusercontent.com/56199291/207116494-9388e49e-69d4-4987-ba83-961a0eb6b372.png)
> 
> And I've verified to have the changes in my running docker: ![image](https://user-images.githubusercontent.com/56199291/207117042-d08d58c0-9fad-4d48-8a6b-d074f2faf41c.png)
> 
> I hope you can reproduce this issue. I don't even get an error, just no results.
> 
> _Originally posted by @domXmob in [#1252 (comment)](https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1252#issuecomment-1346949455)_

It's just a function and the function of has not been implemented to the static yet. I don't know where's that HTML file, would you mind sending me the file path here? I know it's in this Github, but can yoh please send me the full path of the GitHub file here?

**Comment by domXmob** [comment]
@pneb 

for me it also looks like this function is not used at the moment:
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/powerdnsadmin/models/domain.py#L113

Maybe the pretty domain name needs to be available and added here for the search?
https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/powerdnsadmin/routes/dashboard.py#L104
