### ISSUE TITLE
Some navigation breaks when app ran from sub-directory

### ISSUE THREAD

**Issue by droszler** [PowerDNS-Admin/PowerDNS-Admin#1337]
If SCRIPT_ROOT is not /, then
- the Changlog button in domain page don't work
- the Manage button in Changelog page don't work.
[commit.txt](https://github.com/PowerDNS-Admin/PowerDNS-Admin/files/10277559/commit.txt)

**Comment by AzorianMatt** [comment]
Related to #1149
