### ISSUE TITLE
Keeps adding tld to the entry

### ISSUE THREAD

**Issue by Oratorian** [PowerDNS-Admin/PowerDNS-Admin#1344]
Whenever I need to update my domain it keeps adding the TLD to all entries in the database whenever i press Apply Changes

**Comment by AzorianMatt** [comment]
@Oratorian please take time to provide more information such as expected behaviors and examples. You must understand that we don't get enthusiastic about trying to provide support to a one line "bug report."

**Comment by Oratorian** [comment]
I am so sorry  ... I just remember i should provide some informations :/

I am running the powerdnsadmin\pda-legacy:latest docker container. on ubuntu 
I also recieve the following error when ever i hit the Dashboard with the domain overview.

`dnsadmin  | [2022-12-23 14:25:28,851] [utils.py:111] WARNING - UTF-8 content.decode failed, switching to slower .json method
`
I switched to the v0.3.0 in the docker container to check if this still happens there.

**Comment by Oratorian** [comment]
I did some checking, this only occurs on the

**Comment by Oratorian** [comment]
My docker somehow mixed up the old dockerhub repo with the new one and always pulled the wrong images, fixed now after a purge :/

**Comment by AzorianMatt** [comment]
@Oratorian no worries friend, just trying to keep things manageable with minimum resources!

Glad to hear you got the confusion worked out. I knew the Docker Hub change would cause some confusion but it's par for the course! Thank you for being a PDA user!
