### ISSUE TITLE
[Bug] The "Name" column is always supplemented by the domain 

### ISSUE THREAD

**Issue by christianbur** [PowerDNS-Admin/PowerDNS-Admin#1345]
I am using the docker images from powerdns-admin, but with the current "latest" image, I have just broken my DNS environment. 

In the first column "Name" the current "latest" image always adds the domain (e.g. www.example.com), excluded from this are @ entries. If you confirm the change with "Apply Changes" the domain is appended again (e.g. www.example.com.example.com). 
I then used the "v0.3.0" image and had to manual remove the domains in each resource record line.

ngoduykhanh/powerdns-admin:latest -> ERROR
ngoduykhanh/powerdns-admin:v0.3.0 -> OK

**Comment by AzorianMatt** [comment]
@christianbur so much for pinned issues and announcements!

You're still using the old Docker Hub repository that is not being updated any longer and is now broke.

See this announcement: https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1317

**Comment by christianbur** [comment]
powerdnsadmin/pda-legacy:latest is OK.

**Comment by AzorianMatt** [comment]
@christianbur great, thank you for verifying! So many reports recently with this Docker Hub change that I can't make heads or tails of whether or not an actual issue exists.
