### ISSUE TITLE
[BUG] Multiple editing of a zone cause data lost

### ISSUE THREAD

**Issue by mijeycgn** [PowerDNS-Admin/PowerDNS-Admin#1346]
Hi,

there is an issue which was already solved a long time ago. The thread is: https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/183

A colleague told me, there was already commit with a fix of that bug:
https://github.com/PowerDNS-Admin/PowerDNS-Admin/commit/52b6966c83a1c0d53557af2362c6d2cd8c1549df#diff-9cec7b11237bc29d77a439e81c9b7acfac003d8e8855731eb6bc130b5a8ce602

But it seems, in the actual version of PDNS Admin the bug still exist. The behaviour is like following:

User A open on PDNS Admin a view of the zone example.com
User A edit or add some records of the zone

On the same time, User B open the zone example.com
User B added or edit additional Records

User A save the changes and applied them.

Later User B save his own changes and applied them

Problem:
User B overwrites all other changes of the zone which was done by User A.

The reason of the problem is, during a session the web gui load the complete zone and purge the zone on the PDNS Host before committing. There was a check of the serial of the zone when the user clicks on apply changes which show the message "The zone has been changed by another session or user. Please refresh this web page to load updated records."

**Comment by AzorianMatt** [comment]
Hi @mijeycgn,

The current application is not designed for this kind of use and it's a big leap to get there on the current code base (when done cleanly and reliably). I will definitely add this to the design requires of the next-gen application that is being actively planned now, but this will not likely make it to this current legacy application.

I realize that even a quick alert to the other user would be more useful than nothing at all, but the current code base is rather delicate and completely lacks automated testing across the board. For this reason, it has become very difficult to introduce any changes without constantly breaking existing functionality. This situation is being heavily scrutinized and I will eventually have a plan for whether or not the current legacy application will get an overhaul to solve this. The answer is likely not since I will spend most of my efforts on the next-gen application to replace it.

**Comment by lovilak** [comment]
Hello,
As this question bumped in my head too, I was wondering if a quick move would be to add in the interface an add/remove record/ptr without loading the entire zone. A single change or a list of change panel could be nice. This could avoid overwrite session and in the same time a quick solution long load issue when the zone is very big ..

**Comment by AzorianMatt** [comment]
@lovilak while that is a valid point generally speaking and specifically here as well, the "quick move" mentality is exactly what brought this project many of the problems it now faces today and specifically why I'm here to change that.

It seems that most contributors are interested in getting their needs in, but often without consideration to how those changes are executed or how they affect the long-term viability of the project. It's time for the project to take an architectural point of view in efforts which means limiting these knee-jerk reactions.

Make no mistake, I agree that in general, zone editing should be done in a more specific way that doesn't involve bulk updates which would have likely avoided this issue in the first place.

**Comment by mijeycgn** [comment]
Hello AzorianMatt,
thanks for the reply :-)
And yes, i understand you fully. PDNS Admin get a little mess in the code base and it is good to hear, that you take the opportunity to solve it with a nextgen application.

So, i've spend a bit time to check the issue and it i've made a little workaround to avoid the problem.
First: I've created a PHP File: dnslookup.php and make a exclude in the apache reverse config.
It gives the serial of the domain from dig as plaintext output

Then i've added following code lines to 
powerdnsadmin/templates/domain.html

Should be approx at line 252:

   ` function SerialLookup(host) {

        var xhr = new XMLHttpRequest();
        var url = "https://hostname.net/api/dnslookup.php?host=" + host
        xhr.open("GET", url, false);
        xhr.send();
        return xhr.responseText;

    }

// handle apply changes button
  $(document.body).on("click",".button_apply_changes", function() {
        var domainname = "{{domain.name}}"
        var domainsn_webclient = "{{domain.serial}}";
        var domainsn_server = SerialLookup(domainname);

        if ( domainsn_webclient <= domainsn_server ) {
            showErrorModal( "Domain: " + domainname + " Actual: " + domainsn_server + " ClientSide: " + domainsn_webclient + " The zone has been changed by another session or user. Please refresh this web page to load updated records.");
            return;
        }
`

It is not the best workaround but it works generally and can be easy applied after an update of PDNS Admin. 
The only thing is, that my idea with dig @localhost was not very well because the serial of the SOA is changing every 20seconds without editing the zone. Is that normal on PDNS? The serial is still the same in the configuration but dig get always a different one.

I assumed that is maybe a normal behaviour for the replication but even if i stop the secondary, it is still change the serial...
Im thinking about to change the php script which get the SOA directly from the API. When i've finish it, i post it here :-)

**Comment by AzorianMatt** [comment]
@mijeycgn This seems like a reasonable enough approach to handle it in your situation. I think in general, it's probably best to always lean on the API for a source of truth vs a query through the DNS server itself for the reasons you have discovered.

**Comment by mijeycgn** [comment]
Another addition to this case:
I've made a php script which reads the current domain serial directly from the mysql database:

`<?php
//parse the mysql.ini file
$ini = parse_ini_file("mysql.ini");

//get the values from the ini file and store them in variables
$servername = $ini['SQLA_DB_HOST'];
$username = $ini['SQLA_DB_USER'];
$password = $ini['SQLA_DB_PASSWORD'];
$dbname = $ini['SQLA_DB_NAME'];

//get the value of 'zone' from the URL query string
$zone = $_GET['zone'];

//create a connection to the database
$mysql = new mysqli($servername, $username, $password, $dbname);

//run the SQL query
$sql = "SELECT notified_serial FROM domains WHERE name = '$zone'";
$result = mysqli_query($mysql, $sql);

//check if the query was executed successfully
if (!$result) {
    die("Query failed: " . mysqli_error($mysql));
}

//store the result in the $serial variable
$row = mysqli_fetch_assoc($result);
$serial = $row["notified_serial"];

//output the $serial variable as an integer
echo intval($serial);

//close the database connection
$mysql->close();
?>`

The Ini file contains the credentials:

`SQLA_DB_USER = pdns_domains
SQLA_DB_PASSWORD = ******
SQLA_DB_HOST = 127.0.0.1
SQLA_DB_NAME = pdns`

The mysql user has only permissions to the table domains.
