### ISSUE TITLE
Add support for Catalog Zones

### ISSUE THREAD

**Issue by martijngoorman** [PowerDNS-Admin/PowerDNS-Admin#1348]
Hi,

A feature called "catalog zones" is added recently in PowerDNS.
It would be great if PowerDNS-Admin supports this feature.
Options like:
- Show catalogs
- Show zones in catalog
- Add/Remove zones to/from catalog
- Add zone to catalog while adding new zone

[PowerDNS - Docs - Catalog Zones](https://doc.powerdns.com/authoritative/catalog.htmll)

**Comment by Metrax** [comment]
Hi, i'm working on that in one of my local branches. But it will need some time, due to big projects at work atm ;-)

I will release a PR during the next 2 Weeks, that zone list update will not fail when producer or consumer zones are in your zone list.

**Comment by subbink** [comment]
@Metrax do you have an indication when this should be available as PR?

**Comment by Metrax** [comment]
Unfortunately not :-/
One thing is, that my main you is stressing me a lot at the moment, the other thing is, that i need to overwork all my changes, due to the latest Design change in the main branch.

**Comment by martijngoorman** [comment]
@Metrax any update on this?

**Comment by AzorianMatt** [comment]
@martijngoorman @subbink PR 1641 apparently addresses this but I have no gotten to review the work yet. Hopefully it all checks out and I can maybe even get it into the next release.

Closing this issue in favor of issue 1607 that lead the charge on the first PR.
