### ISSUE TITLE
Add support for Response Policy Zones

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [PowerDNS-Admin/PowerDNS-Admin#1351]
Hi there, 

While testing  to use Response Policy zones management (via APIs), which is perfectly working for me. 
 I discovered that UI does not allow to create a CNAME to '.'  only .

If you are unfamiliar with Reponse Policy zones , please have a look [here](https://doc.powerdns.com/recursor/lua-config/rpz.html)

And please find some zone examples of policy zone  [here](https://www.zytrax.com/books/dns/ch7/rpz.html)

If you try to add a CNAME manually that has a '.' for destination, you will end up with an error (if I remember well).

I think it could be fixed easily by adding a simple test on [utils.py](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/powerdnsadmin/lib/utils.py#L260)   : like  
test if value is '.' .. and return value  else .. perfom the rest of the function...

If you think there is a better way to handle this, please feel free to suggest.

Best regards,

**Comment by AzorianMatt** [comment]
@WhatshallIbreaktoday you're welcome to submit a PR but I don't know exactly when I'll get to reviewing it. January is a busy month for me so I will possibly lag behind a bit.

Thank you for participating!
