### ISSUE TITLE
Allow API key authentication for DynDNS API

### ISSUE THREAD

**Issue by janderedev** [PowerDNS-Admin/PowerDNS-Admin#1353]
Hi there,

As far as I can tell, the DynDNS endpoint only supports user authentication. My instance uses SAML authentication, so it's currently not possible for me to use it.

Having the option to use an API key for this would be great. I tried implementing this myself, but frankly I have no idea what I'm doing (it took me over an hour to even get a development environment set up), and I don't trust myself with touching authentication related code.

**Comment by AzorianMatt** [comment]
Hi @janderedev, this matter has already been discussed and the feature is being planned for the next-gen project that will replace the current PDA legacy project. This will not likely make it in to the last release of PDA legacy but there's always a chance.

Thanks for being a PDA user @janderedev!
