### ISSUE TITLE
History Details modal content overflow for long records

### ISSUE THREAD

**Issue by bluikko** [PowerDNS-Admin/PowerDNS-Admin#1358]
Displaying "History Details" modal dialog has the content overflowing from dialog to background if there is a long string in the change.

Steps to duplicate:
1. Make a change with a long string, for example add a "DS" RR with data "12345 12 1 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef".
2. Go to "History", click on the "Info" button for this record changes item.

Example screenshot (the black boxes due to redacting):
![image](https://user-images.githubusercontent.com/14869000/212050346-b0be8097-a6b4-48b8-9e3e-c6dae8c8dd78.png)

As can be seen the change data table overflows to the right and the whole "Comment" column is outside of the dialog.

**Comment by Metrax** [comment]
Thanks for reporting.
WebUI Issue confirmed, i will fix it now.
