### ISSUE TITLE
OIDC Logout URL isn't compatible with Okta

### ISSUE THREAD

**Issue by reg0bs** [PowerDNS-Admin/PowerDNS-Admin#1361]
I saw there is a similar issue open for Keycloak (https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1222) and it seems the same is true for Okta.

1. Login using OIDC
2. Logout
3. `{"errorCode":"invalid_client","errorSummary":"A client_id must be provided in the request.","errorLink":"invalid_client","errorId":"oaersUeY1fESbqwm4DaGN3Ytw","errorCauses":[]}`

HTH!
Thanks!

**Comment by AzorianMatt** [comment]
@reg0bs you're welcome to supply a pull request if you wish for this support to be present. At this time, bringing in additional third party support is not high on the priorities list given the lack of overall project contribution.

**Comment by reg0bs** [comment]
Hi @AzorianMatt! Thanks for getting back to me!

What do mean with "additional 3rd party support"? Okta is in this case just another standard compliant OIDC provider. And since there is a similar behavior with another IDP,  my guess would be that pdns admin is not OIDC compliant or has a general issue with logout when using OIDC.

HTH

**Comment by AzorianMatt** [comment]
Hi @reg0bs,

You're welcome first and foremost! So to clarify as I should have originally done, what I'm communicating is that the current legacy application will not likely receive a lot of attention to addressing scenarios with additional providers that don't work (for what ever the reason). Unfortunately, the project does not have a lot of active contribution and I'm working to change that in the long-term. For the time being though, I can not promise any internal resources will work on this problem necessarily. This is not to say that someone won't pick it up voluntarily in the mean time.

This is why I welcome any PR's that want to address these types of issues, but our resources are limited for testing currently so it may take some time to process such PRs if they do come.

Thank you for being a PDA user @reg0bs!
