### ISSUE TITLE
PowerDNS-Admmin docker mariadb sql scripts

### ISSUE THREAD

**Issue by lzy192251** [PowerDNS-Admin/PowerDNS-Admin#1367]
Hello, I used docker to run PowerDNS-Admmin and created the database and user, but I did not find the database table structure, may I ask where to check the table structure, thank you.

**Comment by jbe-dw** [comment]
Hello,

There is no table structure in SQL format. The database is built from the ORM objects and applied by cumulative patches made by alembic.

**Comment by lzy192251** [comment]
已经收到您的邮件，我会尽快处理。
