### ISSUE TITLE
Zone removal activity logging fails due to `history` table constraint for zone

### ISSUE THREAD

**Issue by raunz** [PowerDNS-Admin/PowerDNS-Admin#1372]
There's a minor issue with domain deletion via api. Due to constraint in the MySQL schema, the logging of deletion event fails, as the domain_id is not welcome in history table after zone has been removed from domain table.

```
# delete domain
curl -L -vvv -H 'Content-Type: application/json' -H 'Authorization: Basic *************=' -X DELETE http://powerdns.admin:9191/api/v1/pdnsadmin/zones/soust.com

# delete domain log in history table. note the differences in "detail" and "domain_id" column.
# delete via api (after removing constraint)
| 109 | Delete domain soust4.com |      | dnsadmin   | 2023-02-02 09:29:10 |      1558 |
# delete via gui
| 106 | Delete domain soust4.com | NULL | dnsadmin   | 2023-02-02 09:26:32 |      NULL |

Received domain name: soust.com
[2023-02-02 08:09:11,266] [api.py:308] ERROR - Error: (MySQLdb._exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`powerdnsadmin`.`history`, CONSTRAINT `fk_domain_id` FOREIGN KEY (`domain_id`) REFERENCES `domain` (`id`))')
[SQL: INSERT INTO history (msg, detail, created_by, created_on, domain_id) VALUES (%s, %s, %s, %s, %s)]
[parameters: ('Delete domain soust.com', '', 'dnsadmin', datetime.datetime(2023, 2, 2, 8, 9, 11, 265383), 1553)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

I resolved the issue by dropping the foreign key. Our goal is also to retain full history log for deleted zones.
`alter table history drop foreign key fk_domain_id;`
I'd suggest to remove the contraint from schema. Workaround is to change API domain deletion logging to insert NULL instead of actual domain_id.

**Comment by JanKoppe** [comment]
Same issue here. It's not possible to delete a zone from PowerDNS-Admin currently, which is pretty annoying.

```
[2023-03-17 08:30:35,289] [domain.py:514] ERROR - Cannot delete domain asdf123.de
[2023-03-17 08:30:35,289] [domain.py:516] ERROR - (MySQLdb._exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`pdnsadmin`.`history`, CONSTRAINT `fk_domain_id` FOREIGN KEY (`domain_id`) REFERENCES `domain` (`id`))')
[SQL: DELETE FROM domain WHERE domain.name = %s]
[parameters: ('asdf123.de',)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

**Comment by raunz** [comment]
I have no idea, how to prepare alembic migrations, but I would like to see something like to following for the 0.4.1 release:
```
def upgrade():
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_domain_id', type_='foreignkey')
        
def downgrade():
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_domain_id', 'domain', ['domain_id'], ['id'])
```

**Comment by raunz** [comment]
> @raunz wasn't this issue addressed with a semi-recent PR? Any idea if it's still a valid issue or not?

@AzorianMatt - issue is still valid. Someone, who has some experience with alembic schema change deployment, should make a PR to drop the unnecessary constraint as I stated above.
In my deployment I've dropped the constraint manually.

**Comment by AzorianMatt** [comment]
@raunz duly noted and thank you for the prompt follow-up. I'll see what I can do to get the issue addressed as part of my big push to put a lot to bed on this project.

**Comment by pomland-94** [comment]
are there any progress on this issue? I have the same problem.

**Comment by AzorianMatt** [comment]
@pomland-94 no, and there won't be. Please see the latest project announcement.

**Comment by pomland-94** [comment]
I can‘t find the announcement, do you have a link?

**Comment by AzorianMatt** [comment]
@pomland-94 it's literally pinned at the top of the issues, at the top of the discussions, and on the project readme at the top.

**Comment by pomland-94** [comment]
Ah ok, Thank’s found it. Oh It’s Bad to hear that the Project hast stopped. Then i have to find an alternative or Update PowerDNS admin by myself.
