### ISSUE TITLE
Per-record changelog does not show changes made through API 

### ISSUE THREAD

**Issue by khayalhus** [PowerDNS-Admin/PowerDNS-Admin#1375]
When looking at the history of a domain record (Dashboard -> Select Domain -> Click on the clock icon of a record), only changes made by Accounts from the web UI are present.

I believe this is because actions made from UI are logged with "add_rrsets" and "del_rrsets" keys, while actions from the API are logged as the PowerDNS Authoritative API format which is "rrsets". Below are the database entries for API and UI, respectively.

```sql
id         | 248
msg        | replace zone A record of test.example.com
detail     | {"rrsets": [{"name": "test.example.com.", "type": "A", "ttl": 86400, "changetype": "REPLACE", "records": [{"content": "10.25.25.29", "disabled": false}]}]}
created_by | api-test
created_on | 2023-02-08 12:13:08.229078
domain_id  | 3
-[ RECORD 234 ]-
id         | 250
msg        | Apply record changes to domain example.com
detail     | {"domain": "example.com", "add_rrsets": [{"name": "test.example.com.", "type": "A", "ttl": 86400, "records": [{"content": "10.25.25.30", "disabled": false}], "comments": [{"content": "", "account": ""}], "changetype": "REPLACE"
}], "del_rrsets": [{"comments": [{"content": "", "account": ""}], "name": "test.example.com.", "records": [{"content": "10.25.25.29", "disabled": false}], "ttl": 86400, "type": "A", "changetype": "DELETE"}]}
created_by | khayalhus@example.com
created_on | 2023-02-08 12:28:38.131618
domain_id  | 3
-[ RECORD 236 ]
```

Looks like the following function is responsible for this display. When retrieving logs per record, it only looks for the "add_rrsets" and "del_rrsets" keys.

https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/c5b9e2460498e28baad214afc8c9217a25d1f4d5/powerdnsadmin/routes/admin.py#L906

My Setup:
- Environment: _Docker_
- PowerDNS-Admin image version: _powerdnsadmin/pda-legacy:latest_
- PowerDNS-Admin backend: _postgres:15.1_
- PowerDNS-Authoritative image version: _powerdns/pdns-auth-47:latest_

**Comment by raunz** [comment]
Well the API logging has been broken since the new history format was introduced. I stumbled into it too.
Here's my patch to provide decent logging for API replace/delete operations. I'll do a pull request too.

https://github.com/raunz/PowerDNS-Admin/commit/02700ee7b0b53c7adb5b35f03efc6e4382cacd31

**Comment by khayalhus** [comment]
Thank you for the quick response @raunz . I have tested your commit and all seems to be good! History table entry for API request is now as below.
```sql
id         | 262
msg        | Apply record changes to domain example.com
detail     | {"domain": "example.com", "add_rrsets": [{"name": "test.example.com.", "type": "A", "ttl": 86400, "changetype": "REPLACE", "records": [{"content": "10.25.25.32", "disabled": false}]}], "del_rrsets": []}
created_by | api-test
created_on | 2023-02-09 09:32:43.888249
domain_id  | 3
```
I am now able to see changes made by both UI and API.
![image](https://user-images.githubusercontent.com/43758778/217774754-c19b788c-ae86-43fe-b455-8fa7a508d6e0.png)
