### ISSUE TITLE
Missing Font Awesome fonts

### ISSUE THREAD

**Issue by Pacerino** [PowerDNS-Admin/PowerDNS-Admin#1394]
Running the latest PDNS Admin via Docker gives me missing fonts within the frontend.
I've searched within the Container for the files and couldn't find them. I've also tried another browser to exclude a cache, also there the erro 404 is still present. PDNS is not behind a reverse proxy or something else, im calling the IP and the Port directly!

![image](https://user-images.githubusercontent.com/22194063/220201962-0b4a1cb8-6611-4bea-a7ce-1f14590df41f.png)

**Comment by AzorianMatt** [comment]
@Pacerino I will look into this, but as I have told others, please do not use the latest or report on it if you do have an issue. This is directly tied to the primary branch of the project which is not guaranteed to be stable or for production use.

Thanks,

**Comment by Pacerino** [comment]
> Is this on a particular page?

On every page



> @Pacerino I will look into this, but as I have told others, please do not use the latest or report on it if you do have an issue. This is directly tied to the primary branch of the project which is not guaranteed to be stable or for production use.
> 
> Thanks,

I'm sorry, i've missed that! Will change the Tag of the Container.

**Comment by AzorianMatt** [comment]
@Pacerino no worries, thanks for the report!

**Comment by AzorianMatt** [comment]
@Pacerino this has been fixed in the primary branch FYI. I also pushed a bug fix that was introduced by the mobile first PR. The updated Docker image is building now and should be available within a matter of minutes.

**Comment by xword9009** [comment]
Hi, 

I'm not sure if this is related but while installing on a clean Debian 11.6 server I've just run into
`FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/pdns/powerdnsadmin/static/node_modules/@fortawesome/fontawesome-free/css/all.css``

The `/node_modules/@fortawesome/fontawesome-free/css/all.css' part of the path doesn't exist. 

If this is the wrong forum could someone point me at the right one?

Many thanks

N

**Comment by AzorianMatt** [comment]
@xword9009 it seems like you haven't completed all of the deployment steps such as the module installation process. Please consult the project wiki for Debian / Ubuntu installation to view these steps which include the use of the `yarn install` command.

**Comment by macrokernel** [comment]
I am having a similar issue with PowerDNS-Admin version 0.4.1 built in Docker based on Debian bullseye:
nodejs version: v20.10.0
yarn version: 1.22.19

Any help is much appreciated.

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/9429051/125672a6-0c02-4364-b71b-7afae7d15673)

```
 => => # + yarn install --pure-lockfile --production                                                                                                     
 => => # yarn install v1.22.19                                                                                                                           
 => => # [1/4] Resolving packages...                                                                                                                     
 => => # warning Resolution field "@fortawesome/fontawesome-free@6.3.0" is incompatible with requested version "@fortawesome/fontawesome-free@^5.15.4"   
 => => # [2/4] Fetching packages...
 => => # warning " > bootstrap@4.6.2" has unmet peer dependency "popper.js@^1.16.1".                                                                     
 => => # warning "admin-lte > bootstrap-switch@3.3.4" has incorrect peer dependency "bootstrap@^3.1.1".                                                  
 => => # warning " > jquery-validation@1.19.5" has unmet peer dependency "jquery@^1.7 || ^2.0 || ^3.1".                                                  
 => => # warning "admin-lte > tempusdominus-bootstrap-4@5.39.2" has unmet peer dependency "moment-timezone@^0.5.31".                                     
 => => # warning "admin-lte > tempusdominus-bootstrap-4@5.39.2" has unmet peer dependency "tempusdominus-core@5.19.3".                                  
 => => # warning "admin-lte > bootstrap-colorpicker > bootstrap@5.2.3" has unmet peer dependency "@popperjs/core@^2.11.6".                              
```

[Dockerfile-builder.txt](https://github.com/PowerDNS-Admin/PowerDNS-Admin/files/13600704/Dockerfile-builder.txt)

**Comment by AzorianMatt** [comment]
@macrokernel you're much more likely to get helpful feedback if you post output with an actual failure. Unfortunately, what you have shared doesn't show any issues as those are just warnings. If you're trying to build your own custom Docker image, we don't have the time/capacity to help support any issues you may have created in doing so. Thanks @macrokernel.

**Comment by macrokernel** [comment]
@AzorianMatt, thanks for looking into this. The actual issue can be seen in the screenshot attached to my previous message: Font awesome icons are not working and it seems like something is wrong with auto-generated CSS.

**Comment by AzorianMatt** [comment]
@macrokernel you're welcome. Have you done the more obvious things such as verifying whether the files needed actually exist where they should be? Review your browser console for all 404's to see what else may be missing. You shouldn't be getting any 404's on font files so that is a starting point to focus on.

**Comment by macrokernel** [comment]
@AzorianMatt, thanks for the advise. It is weird that the only 404 listed in console is the one I mentioned above regarding `glyphicons-halflings-regular.woff2`. I can see that `main.css` references both `glyphicons-halflings-regular.woff2` and `glyphicons-halflings-regular.woff`, so this shouldn't be a real issue.

**Comment by AzorianMatt** [comment]
@macrokernel you're welcome. It seems like to me, the last time this happened it was because the asset building process was not being ran or completing successfully. My memory is vague right now without looking, but I do believe that process copies the font files into a final location for production. That is to say, if they aren't where they need to be when the process runs, then they may not even get referenced in the production output which could create false positives where there are no 404s.

Have you checked the asset building step?

**Comment by macrokernel** [comment]
@AzorianMatt, yes, the fonts are copied to where they should be. This is the bit in my Dockerfile where it is done, it does not differ much from the one in the original Dockerfile:
```
# Prepare assets
RUN set -x && \
    yarn install --pure-lockfile --production && \
    yarn cache clean && \
    sed -i -r -e "s|'rcssmin',\s?'cssrewrite'|'rcssmin'|g" /build/powerdnsadmin/assets.py && \
    export LC_ALL=C.UTF-8 && \
    export LANG=C.UTF-8 && \
    export FLASK_CONF=../configs/development.py && \
    flask assets build

RUN mv /build/powerdnsadmin/static /tmp/static && \
    mkdir /build/powerdnsadmin/static && \
    cp -r /tmp/static/generated /build/powerdnsadmin/static && \
    cp -r /tmp/static/assets /build/powerdnsadmin/static && \
    cp -r /tmp/static/img /build/powerdnsadmin/static && \
    find /tmp/static/node_modules -name 'webfonts' -exec cp -r {} /build/powerdnsadmin/static \; && \
    find /tmp/static/node_modules -name 'fonts' -exec cp -r {} /build/powerdnsadmin/static \; && \
    find /tmp/static/node_modules/icheck/skins/square -name '*.png' -exec cp {} /build/powerdnsadmin/static/generated \;

RUN { \
      echo "from flask_assets import Environment"; \
      echo "assets = Environment()"; \
      echo "assets.register('js_login', 'generated/login.js')"; \
      echo "assets.register('js_validation', 'generated/validation.js')"; \
      echo "assets.register('css_login', 'generated/login.css')"; \
      echo "assets.register('js_main', 'generated/main.js')"; \
      echo "assets.register('css_main', 'generated/main.css')"; \
    } > /build/powerdnsadmin/assets.py
```

I have verified that the fonts are present in the Docker image and I am able to download, for example, this font `/static/webfonts/fa-regular-400.woff2` from the running docker container.

**Comment by macrokernel** [comment]
@AzorianMatt, my Dockerfile is attached to the first message posted yesterday. I had to re-base the Dockerfile on Debian Bullseye in order to be able to install a specific version of PowerDNS server and other stuff, as I am building an all-in-one Docker image with  DNS server, DBMS and GUI. 

I had to change PyYAML version from 5.4 to 5.3.1 in Python `requirements.txt` , as the requirements won't install otherwise. It might be because Debian's Python version is 3.9 while in the original Alpine 3.17 Docker image it is 3.10. I was going to try a newer version of Debian to see if it helps.

I have not modified `powerdnsadmin/assets.py`.

**Comment by AzorianMatt** [comment]
@macrokernel yep, that all makes sense now. Making these changes might seem rather minor on the surface, but this is the very reason I have froze this edition of the project. It is far too delegate to develop with effectively and leads to many issues the moment seemingly anything is changed. I wish I could offer you further help on this endeavor, but this is precisely why I recently froze this code base. It's costing me too much time to continue any efforts on it at all (including support) which is stealing from the project's future.
