### ISSUE TITLE
"Allow automatic reverse pointer creation on record updates?" fails with  Error: 'NoneType' object has no attribute 'add_setting'`

### ISSUE THREAD

**Issue by pentiumoverdrive** [PowerDNS-Admin/PowerDNS-Admin#1405]
When checking the box for  "Allow automatic reverse pointer creation on record updates?" under settings in a zone, there is a popup saying "There is something wrong, please contact Administrator."

And the following is logged:
`domain.py:915] ERROR - Cannot change domain setting. Error: 'NoneType' object has no attribute 'add_setting'`

Anyone have any clues what's causing this?

Edit: same with " Allow on-demand creation of records via DynDNS updates?"

**Comment by AzorianMatt** [comment]
@pentiumoverdrive I'll take a look in the next few days. I may have broke it with some of my recent updates on the mobile-first PR.

I can't much give a lot of advice without knowing more details about what version of the application you're running though...

**Comment by pentiumoverdrive** [comment]
I cloned the repo last day (24th). But how can I see which version? The web ui doesn't give much away regarding version or I'm simply blind :P

**Comment by AzorianMatt** [comment]
@pentiumoverdrive if you're working off of the primary Branch then you have the dev version that is known to be unstable.

If you're trying this for a production application, I recommend pulling the 0.3.0 release which is stable.

I do have a task to add the current version to the application footer very soon.

**Comment by AzorianMatt** [comment]
@pentiumoverdrive I found the issue and indeed, when I updated the UI to be more UX friendly, it broke the legacy code that was poorly implemented. I have just pushed a fix to the primary branch for this.

**Comment by arthur-leung-MSE** [comment]
Hello, I am on Version 0.4.1, and have what I believe to be similar error. 

As soon as I enabled "Auto PTR creation" under "Edit Zone", when I go back to the "Changelog" on the noted zone, I get a HTTP 500 Error. 

The following is a section from the /var/log/syslog

Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]: [2024-08-06 00:44:09,543] [app.py:1449] ERROR - Exception on /domain/testtest/changelog [GET]
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]: Traceback (most recent call last):
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/flask/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     response = self.full_dispatch_request()
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/flask/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     rv = self.handle_user_exception(e)
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/flask/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     rv = self.dispatch_request()
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/flask/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/flask/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     return current_app.ensure_sync(func)(*args, **kwargs)
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/powerdnsadmin/decorators.py", line 75, in decorated_function
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     return f(*args, **kwargs)
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/powerdnsadmin/decorators.py", line 48, in decorated_function
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     return f(*args, **kwargs)
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/powerdnsadmin/routes/domain.py", line 227, in changelog
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     changes_set = extract_changelogs_from_history(histories)
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:   File "/var/www/html/pdns/powerdnsadmin/routes/admin.py", line 122, in extract_changelogs_from_history
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]:     if "add_rrsets" in entry.detail:
Aug  6 00:44:09 ip-172-32-10-226 gunicorn[612]: TypeError: argument of type 'NoneType' is not iterable
