### ISSUE TITLE
Text in SOA editor is white against white background

### ISSUE THREAD

**Issue by pentiumoverdrive** [PowerDNS-Admin/PowerDNS-Admin#1407]
I pulled the latest master today and noticed that the SOA editor has white text against white background, tried both firefox and safari.

Had select the text to make it visible.

![image](https://user-images.githubusercontent.com/17021956/221431144-c5a8b595-6790-4aef-85c3-dfe5f9e7a8eb.png)

Cheers for keeping PowerDNS-Admin alive! 🥇  :)

**Comment by AzorianMatt** [comment]
@pentiumoverdrive A fix for this has been pushed to the primary branch.
