### ISSUE TITLE
Unifiy Nomenclature for Zone / Domain References

### ISSUE THREAD

**Issue by Metrax** [PowerDNS-Admin/PowerDNS-Admin#1412]
At some places, we call Zones "Zone(s)", at other places we call it "Domain(s)". We should unify this to "Zone(s)"

**Comment by AzorianMatt** [comment]
@Metrax agreed. I wasn't sure if I got all of the places yet or not but I wasn't very thorough on my efforts during the change. I do want to unify on the appropriate nomenclature of zone though instead of the slang domain.

**Comment by AzorianMatt** [comment]
This has been completed by [PR 1441](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1441).
