### ISSUE TITLE
Filter Block and Redirect

### ISSUE THREAD

**Issue by beryindo** [PowerDNS-Admin/PowerDNS-Admin#1415]
How to make sample filter and block domain porn, and redirect to domain eksternal ?

**Comment by AzorianMatt** [comment]
@beryindo please elaborate further. From the little I was able to gather from your question, it sounds like you're asking about features that don't exist.

**Comment by AzorianMatt** [comment]
@beryindo you seem to be inquiring about specific configuration strategies related to the PowerDNS recursor and not any feature specific to the PowerDNS Admin tool which is not affiliated with the makers of the PowerDNS server suite itself. For this reason, I am closing this issue as this is the wrong project to ask this question under.
