### ISSUE TITLE
OpenID Connect OAuth Issue (Authentik)

### ISSUE THREAD

**Issue by MDXDave** [PowerDNS-Admin/PowerDNS-Admin#1419]
I got the following exception when I try to login via OIDC with Authentik:

> powerdns_admin                 | [2023-03-02 10:39:30,119] [app.py:1449] ERROR - Exception on /oidc/authorized [GET]
> powerdns_admin                 | Traceback (most recent call last):
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
> powerdns_admin                 |     response = self.full_dispatch_request()
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
> powerdns_admin                 |     rv = self.handle_user_exception(e)
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
> powerdns_admin                 |     rv = self.dispatch_request()
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
> powerdns_admin                 |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> powerdns_admin                 |   File "/app/powerdnsadmin/services/oidc.py", line 35, in oidc_authorized
> powerdns_admin                 |     token = oidc.authorize_access_token()
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
> powerdns_admin                 |     userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
> powerdns_admin                 |     claims = _jwt.decode(
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
> powerdns_admin                 |     data = self._jws.deserialize_compact(s, load_key, decode_payload)
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
> powerdns_admin                 |     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
> powerdns_admin                 |     key = key(header, payload)
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 38, in load_key
> powerdns_admin                 |     jwk_set = JsonWebKey.import_key_set(self.fetch_jwk_set())
> powerdns_admin                 |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7517/jwk.py", line 55, in import_key_set
> powerdns_admin                 |     raise ValueError('Invalid key set format')
> powerdns_admin                 | ValueError: Invalid key set format
> 

Thats the payload of the JWT token i received from Authentik:

```json
{
    "iss": "https://sso.example.com/application/o/powerdns-admin/",
    "sub": "12345",
    "aud": "12345",
    "exp": 1677756394,
    "iat": 1677754594,
    "auth_time": 1677417927,
    "acr": "goauthentik.io/providers/oauth2/default",
    "amr": [
        "user"
    ],
    "email": "user@example.com",
    "email_verified": true,
    "id": 123,
    "name": "Max Mustermann",
    "given_name": "Max Mustermann",
    "family_name": "",
    "preferred_username": "mmustermann",
    "nickname": "mmustermann",
    "groups": [
        "Admin",
        "User",
        "PowerDNS"
    ]
}
```

**Comment by AzorianMatt** [comment]
@MDXDave please provide environmental details such as how the app was deployed (Docker or otherwise), what version you're running, etc...

**Comment by MDXDave** [comment]
@AzorianMatt I use the latest docker version with postgres:

`powerdnsadmin/pda-legacy:latest `

**Comment by mrinc** [comment]
From a quick review, i think claims is the key here. 
I'll have a look more indepth later, but a starting part would be to look specifically how claims are handled from this provider.
They return groups, but no claims property.

**Comment by mrinc** [comment]
Ref : https://github.com/lepture/authlib/blob/169c7dcfc47478c8d55553cc95fb0f5578162b77/authlib/integrations/base_client/sync_openid.py#L66

**Comment by mrinc** [comment]
`fetch_jwk_set` I think we have jtwks issues with this as well.

**Comment by mrinc** [comment]
@MDXDave - Based on the authentik domain, please try get the jwks url and enter it in manually to the configuration.  

Ref : https://goauthentik.io/integrations/sources/oauth/#jwks 

Go to `{your domain/instance of authentik}/.well-known/openid-configuration` < just to make sure you've got the correct path.
If good, then go to `{same as above}/.well-known/jwks.json` < and see if you get data back.  
If good, add the above jwks url to the admin config and let us know if it works.

**Comment by MDXDave** [comment]
Where should I put the jwks url value? 🤔

![Screenshot_20230318-124211](https://user-images.githubusercontent.com/6099976/226103502-00008845-bb01-4200-82af-0bf8a4f3b983.png)

**Comment by MDXDave** [comment]
@mrinc this documentation shows only how to specify external Oauth source for authentik itself.

Do I need to set the jwks url from authentik for the powerdns-admin config and if yes, where do I need to set it?

**Comment by mrinc** [comment]
@MDXDave - set the jkws uri in pdnsadmin that points to the authentik jkws uri.

authentik signs the jwt tokens from my understanding so you'll need the authentik jkws uri for the verification to occur

**Comment by MDXDave** [comment]
Hm there is no jwks url field 🤔

![Screenshot_20230318-124211](https://user-images.githubusercontent.com/6099976/226104625-732cdc3c-4da4-4f4b-93eb-ee5f5f105a6a.png)

**Comment by AzorianMatt** [comment]
@MDXDave you don't see the field because you don't have the dev version of the app I would presume which is the only place this new setting exists.

With that being said, this setting is pointless from what I can tell because I didn't even realize that the underlying library didn't support it when I implemented it. Ergo, it won't do anything from what I can tell.

@mrinc

**Comment by mrinc** [comment]
authlib does from what i can tell, which is interesting.... lemme dig down the rabbit hole some more and will revert

**Comment by AzorianMatt** [comment]
@mrinc based on the version of the library the legacy app currently uses, it didn't appear to have any method parameters for the setting I implemented. By all means, let me know if I overlooked something here. This was based on introspection of the local module only.

**Comment by mrinc** [comment]
@AzorianMatt - For simplistic tests - see if you can change the algorithm on authentik and see if that works?
