### ISSUE TITLE
Add support PowerDNS API for pdns-recursor

### ISSUE THREAD

**Issue by HLFH** [PowerDNS-Admin/PowerDNS-Admin#144]
Hi,

According to [the API spec](https://doc.powerdns.com/md/httpapi/api_spec/), it would be interesting to support the PowerDNS API for `pdns-recursor`.
For example, we could modify the `allow_from` directive... I'm sure that we can do a lot with the API for `pdns-recursor`.
Could you support it?
In fact, if you do that, `PowerDNS-Admin` will be the great leader of the WebFrontends for PowerDNS. IMHO, `PowerDNS-Admin` is the best, but with that new feature, it would be so much awesome.

Thanks,
HLFH

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later if you're still interested in this functionality.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
