### ISSUE TITLE
OTP Setup for LDAP users

### ISSUE THREAD

**Issue by allahshukur-ahmadzada** [PowerDNS-Admin/PowerDNS-Admin#1448]
I have just tried to setup OTP for logged in LDAP user from profile section but it does not work, expected or it is a bug? it would be nice if it is possible. Just to not we  still use v0.3.0

**Comment by AzorianMatt** [comment]
@jbe-dw any idea if OTP is intended to work with LDAP auth?

**Comment by jbe-dw** [comment]
I'm not 100% sure but it should work with any authentication.

**Comment by AzorianMatt** [comment]
@allahshukur-ahmadzada I can not be certain if this is intended to work as a supported feature per se, but according to @jbe-dw, it likely should. If you wish to file this as a bug, then please update this issue with the appropriate information to clarify steps of reproduction and any exceptions / error messages received to support the issue. At that point, I'll re-open the issue or you can as well.

Thanks!
