### ISSUE TITLE
check if replication succcess from poweradmin ui

### ISSUE THREAD

**Issue by allahshukur-ahmadzada** [PowerDNS-Admin/PowerDNS-Admin#1449]
Is there any possibility to check if replication to secondary nameservers successful or not from UI after updating/adding records? at the moment we need to check it manually by going to secondaries

**Comment by AzorianMatt** [comment]
There is no direct feature for this right now but you can check with one of two work-arounds. Either update your PDA settings to point to the API of the secondary server or deploy a second instance that is configured for your secondary server and then you can synchronize zone information from them just as you can with a primary.
