### ISSUE TITLE
How do i determine from the UI, what version of PDNS Admin I am running?

### ISSUE THREAD

**Issue by clsmyth** [PowerDNS-Admin/PowerDNS-Admin#1455]

**Comment by AzorianMatt** [comment]
@clsmyth before the most recent 0.4.0 release, there was no way to tell. Following that release, the app's version has been added to the footer, floating on the right.

**Comment by clsmyth** [comment]
Thank you very much!  I now know I need to update! :-)

**Comment by AzorianMatt** [comment]
@clsmyth you're welcome!
