### ISSUE TITLE
Internal Server Error release 0.4.0

### ISSUE THREAD

**Issue by acheglakov** [PowerDNS-Admin/PowerDNS-Admin#1456]
Hello! 
Got just installed latest docker release (0.4.0). It worked fine for a several hours, but now I get Internal Server Error. How to diagnose why it happened? Restart doesn't help. I do not see any logs.

docker container ls -l
CONTAINER ID   IMAGE                             COMMAND                  CREATED       STATUS                    PORTS                                   NAMES
42d3141d8324   powerdnsadmin/pda-legacy:latest   "entrypoint.sh gunic…"   9 hours ago   Up 33 minutes (healthy)   0.0.0.0:9191->80/tcp, :::9191->80/tcp   nostalgic_haibt
 docker image ls
REPOSITORY                   TAG       IMAGE ID       CREATED        SIZE
powerdnsadmin/pda-legacy     latest    e9b943c35616   4 days ago     187MB
ngoduykhanh/powerdns-admin   latest    987ad25307ed   3 months ago   154MB
df -h
Filesystem               Size  Used Avail Use% Mounted on
udev                     470M     0  470M   0% /dev
tmpfs                     98M  596K   98M   1% /run
/dev/mapper/ns--vg-root  2.6G  1.9G  593M  76% /
tmpfs                    489M     0  489M   0% /dev/shm
tmpfs                    5.0M     0  5.0M   0% /run/lock
/dev/sda1                470M   86M  360M  20% /boot
/dev/mapper/ns--vg-home  4.7G   76K  4.5G   1% /home
/dev/mapper/ns--vg-tmp   238M   13K  222M   1% /tmp
/dev/mapper/ns--vg-var   994M  835M   91M  91% /var
tmpfs                     98M     0   98M   0% /run/user/1000
overlay                  994M  835M   91M  91% /var/lib/docker/overlay2/f69e353d733641b8a3637791ea28970d7a661d0bb81e5d7d144734c997d3768e/merged

**Comment by AzorianMatt** [comment]
@acheglakov without seeing any logs, my first guess is that you're hitting a recently exposed Flask Session library bug which is about to be addressed in the next patch release and dev branch.

Try [checking the logs](https://docs.docker.com/engine/reference/commandline/container_logs/) of the container.

**Comment by acheglakov** [comment]
AzorianMatt, thank you! That helped!

**Comment by AzorianMatt** [comment]
@acheglakov you're welcome!
