### ISSUE TITLE
Problem saving LDAP settings using the Group Security option and only entering a single group in

### ISSUE THREAD

**Issue by nkukard** [PowerDNS-Admin/PowerDNS-Admin#1462]
### PDA version

0.4.0

### Python version

3.11

### Steps to Reproduce

1. Browse to Settings => Authentication
2. Setup ADMINISTATOR INFO  & FILTERS
3. Enable "Status = On" under GROUP SECURITY
4. Enter in only "Admin group"
5. Save settings is blocked
![groupsec](https://user-images.githubusercontent.com/2354782/226136270-62533105-3bf0-49d9-b735-38f4a1e87d69.png)

### Expected Behavior

The ability to enter in a single group and not have to supply an Admin group, Operator group and User group all at once.

Not everyone has multiple groups they wish to configure.

I'm sure many have admins responsible for their DNS infra and may not have other users who need access.

While one can configure the admin group in all 3 fields and it will work correctly, that is more of a workaround than a fix.

### Observed Behavior

Saving of configuration is prevented if one does not enter the Admin group, Operator group and User group.

**Comment by nkukard** [comment]
I"ll submit a patch shortly for this. The change is pretty trivial and most of the code (at least for AD) makes provision for blank fields after MR 1238 was merged. Its just the normal ldap code that needs a slight modification.

**Comment by AzorianMatt** [comment]
This has been resolved by [PR 1463](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1463).
