### ISSUE TITLE
Fresh installation of latest/0.4.0 version fails with SQL errors

### ISSUE THREAD

**Issue by dedeckerni** [PowerDNS-Admin/PowerDNS-Admin#1477]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

1. Deploy with docker of "latest" or "0.4.0" version.
2. when container starts it goes into error and exists because of SQL error: All MySQL CHANGE/MODIFY COLUMN operations require the existing type.

To fix: run docker with v0.3.0 first => works fine.
Then update the stack/container with latest or 0.4.0 version => keeps working.

So looks like something goes wrong when it has to create the initial database scheme for a fresh setup.

### Expected Behavior

Expected: starting from scratch with latest version should also work.

### Observed Behavior

INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
INFO  [alembic.runtime.migration] Running upgrade 59729e468045 -> 1274ed462010, Change setting.value data type
INFO  [alembic.runtime.migration] Running upgrade 1274ed462010 -> 4a666113c7bb, Adding Operator Role
INFO  [alembic.runtime.migration] Running upgrade 4a666113c7bb -> 31a4ed468b18, Remove all setting in the DB
INFO  [alembic.runtime.migration] Running upgrade 31a4ed468b18 -> 654298797277, Upgrade DB Schema
INFO  [alembic.runtime.migration] Running upgrade 654298797277 -> 0fb6d23a4863, Remove user avatar
INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
INFO  [alembic.runtime.migration] Running upgrade 856bb94b7040 -> b0fea72a3f20, Update domain serial columns type
INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column
ERROR [root] Error: All MySQL CHANGE/MODIFY COLUMN operations require the existing type.

**Comment by AzorianMatt** [comment]
@dedeckerni I appreciate your issue report but please try to follow the new [contribution guidelines](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/CONTRIBUTING.md) a bit better. If you were to have looked at the last issue closed, you would find [this issue](https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1464) which is the same issue as what you just reported.

A fix for this has already been pushed to the `dev` branch and the `dev` tag of the Docker image accordingly. This fix will be in the next patch release `0.4.1` hopefully, by the end of the month.
