### ISSUE TITLE
Internal server error when using invalid X-API-KEY encoding

### ISSUE THREAD

**Issue by nkukard** [PowerDNS-Admin/PowerDNS-Admin#1478]
### PDA version

0.4.0

### Python version

3.11

### Steps to Reproduce

1. Submit an invalid UTF-8 encoded X-API-KEY

### Expected Behavior

Log message stating that the X-API-KEY is invalid

### Observed Behavior

Exception raised and "Internal Server Error" returned.
```
File "/app/powerdnsadmin/decorators.py", line 462, in decorated_function
     apikey_val = str(base64.b64decode(auth_header), 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 0: invalid start byte
```

**Comment by AzorianMatt** [comment]
Resolved by [PR 1479](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1479).
