### ISSUE TITLE
PDA appends domain name to all records even though it exists on Apply Changes

### ISSUE THREAD

**Issue by vias79** [PowerDNS-Admin/PowerDNS-Admin#1482]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

docker run --name powerdns-admin --restart always -d -v pda-data:/data -p 9191:80 ngoduykhanh/powerdns-admin:latest

Then just try to add or update a record in your domain and press Apply Changes.

PDA bug then adds domain to end of all records.

![image](https://user-images.githubusercontent.com/4582087/227951944-9cbd7302-71be-4a6c-a67b-d8a3aa9d6078.png)

### Expected Behavior

A new record should have been created without all the existing ones being bricked

### Observed Behavior

Bug in code adds domain to end of all records when pressing Apply Changes

**Comment by AzorianMatt** [comment]
@vias79 are you certain you chose the right PDA version for this report? This is an old bug that does not occur for me in the current version (0.4.0).

What database engine are you using? Is this deployed on bare metal or through docker containers?

**Comment by AzorianMatt** [comment]
@vias79 you are still using the old image repository on Docker hub and that image is not up to date.

Please read the announcements posted on the project for it.

**Comment by vias79** [comment]
Thanks, you are correct. Pulled new docker image and all worked as intended :)

**Comment by AzorianMatt** [comment]
@vias79 you're welcome, enjoy the project!
