### ISSUE TITLE
default_domain_table_size does not work correctly for values higher than 100

### ISSUE THREAD

**Issue by JanKoppe** [PowerDNS-Admin/PowerDNS-Admin#1485]
### PDA version

0.4.0

### Python version

3.10

### Steps to Reproduce

1. Create more than 100 zones.
2. Go to Settings -> Basic
3. Enter a higher value than 100 (e.g. 200) in default_domain_table_size and save.
4. Go to Dashboard

### Expected Behavior

A single dashboard page should show the configured amount of zones per page, as set in default_domain_table_size.

### Observed Behavior

There will only ever be 100 zones shown per page. The pagination at the bottom seems to respect the new value in calculating the amount of available pages. Going to page two then only shows the zones 101-200, not the actual offset that should be used.

It seems that the value of default_domain_table_size is not being respected at all in the frontend.

**Comment by JanKoppe** [comment]
Short investigation shows that PDA seems to be doing everything right - the `pageLength` option for the DataTables plugin is correctly being filled from the setting. I can verify that the correct setting is showing up in the rendered template. Still it does not work. This might be an issue with DataTables itself?

**Comment by JanKoppe** [comment]
I think I found the issue.

https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/v0.4.0/powerdnsadmin/routes/dashboard.py#L144

PDA caps the search result at 100 rows. DataTables is correctly requesting 1000 rows, but only getting 100 back. When switching to "all", the `length` parameter to the `dashboard.domains_custom`   route is set to `-1`, which will be respected.

Solution IMO would be to tie that hard cap to the default_domain_table_size setting, instead of hardcoding it to 100.

**Comment by AzorianMatt** [comment]
@JanKoppe thank you for your work on this! I am preparing to do a rebuild on the zone editor features to clean up a lot of poorly written functionality as it relates to this very area.

Stay tuned for big updates on that in a semi near future release!

**Comment by JanKoppe** [comment]
Would you be willing to accept a tiny patch for this with my suggested change, to make it more usable until the rework? :)

**Comment by JanKoppe** [comment]
Would you be willing to accept a tiny patch for this with my suggested change, to make it more usable until the rework? :)

**Comment by AzorianMatt** [comment]
@JanKoppe I welcome it!

All I ask is that when you make the change, be mindful of the fact that many current users are dealing with very large data sets, so change accordingly!
