### ISSUE TITLE
error 400 when creating zone

### ISSUE THREAD

**Issue by darkfritz2** [PowerDNS-Admin/PowerDNS-Admin#1490]
### PDA version

0.4.0

### Python version

3.10

### Steps to Reproduce

I followed this tutorial: https://phoenixnap.com/kb/powerdns-ubuntu

and after succesfully installement i want to create a zone:
1. create zone
2. enter valid zone name
3. click create zone button

OR

use cli: pdnsutil create-zone ZONENAME

### Expected Behavior

zone created and can be used

### Observed Behavior

error 400 - bad request - cannot add this domain
![Untitled](https://user-images.githubusercontent.com/9511979/228527822-f701d520-672e-4124-88fc-1047bbd7c18a.png)

The issue is that if i search for it in global search then i can find it but can't use it because then i get error 404: The page you requested could not be found

i can only delete the zone using CLI: pdnsutil delete-zone ZONENAME

here is the full debug of NGINX:
https://pastebin.com/XdZTNPTc

my /etc/nginx/conf.d/pdns-admin.conf
https://pastebin.com/zd0FrGiy

and my: /etc/powerdns/pdns.conf
api=yes
api-key=@@@APIKEY@@@
include-dir=/etc/powerdns/pdns.d
launch=
security-poll-suffix=
webserver=yes
webserver-address=127.0.0.1
webserver-allow-from=0.0.0.0/0,::/0
webserver-port=8081

curl http://localhost:8081 | grep PowerDNS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
10<title>PowerDNS Authoritative Server Monitor</title>
<div class="headl columns"><a href="/" id="appname">PowerDNS 4.5.3</a></div>
0 18973  100 18973    0     0  3965k      0 --:--:-- --:--:-- --:--:-- 4632k
<footer class="row">PowerDNS Authoritative Server 4.5.3<br>&copy; 2013 - 2021 <a href="https://www.powerdns.com/">PowerDNS.COM BV</a>.</footer>

my guess: missconfiguration of nginx but i don't know where

**Comment by AzorianMatt** [comment]
@darkfritz2 try using one of the guides provided in the projects wiki instead of what is almost certainly an outdated tutorial on a third party site.
