### ISSUE TITLE
Unassigned zones automatically selected following account add attempt with invalid name

### ISSUE THREAD

**Issue by kolonuk** [PowerDNS-Admin/PowerDNS-Admin#1495]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

1. Install docker container v0.4.0 and configure with PDNS.
2. On account creation screen, enter an account name that will error - for example "An Account".
3. Add no domains to account.
4. Click Create Account

### Expected Behavior

An error message under the account name, all other fields unchanged as when I entered data in them.

### Observed Behavior

The name will cause an error, but if you check the list of domains, all of them have been added to the account.

If the user doesn't check or notice, customers will have complete access to all domains, and any existing accounts will be stripped of their domains.

For a few hundred, this would be a nightmare.

**Comment by kolonuk** [comment]
Also, any reason why we can't have spaces in the name??

**Comment by AzorianMatt** [comment]
> Also, any reason why we can't have spaces in the name??

I would assume this is because PDNS server doesn't allow them either. This feature of PDA is merely an extension of the core account feature of PDNS server.

Thanks for the report on the other issue!

**Comment by AzorianMatt** [comment]
@kolonuk I found that this was caused by a simple oversight in logic on the `admin_edit_account.html` template on line `136`. A very simple correction has fixed the issue. This will be rolled into the `dev` branch shortly and will be made available in the next formal release of `0.4.2`.

Thanks!
