### ISSUE TITLE
OpenID Connect OAuth Issue (Authentik): Proper JWKS Algorithm Configuration

### ISSUE THREAD

**Issue by caraar12345** [PowerDNS-Admin/PowerDNS-Admin#1497]
### PDA version

0.4.0

### Python version

3.10

### Steps to Reproduce

1. Set up PowerDNS-Admin 0.3.1 with Authentik 
2. Upgrade to PowerDNS-Admin 0.4.0
3. Fail to log in 

```sql
SELECT * FROM setting;
```

<table>
    <tr>
        <td>id</td>
        <td>name</td>
        <td>value</td>
    </tr>
    <tr>
        <td>47</td>
        <td>pdns_api_url</td>
        <td>http://host.docker.internal:8081</td>
    </tr>
    <tr>
        <td>48</td>
        <td>pdns_api_key</td>
        <td>apikey</td>
    </tr>
    <tr>
        <td>49</td>
        <td>pdns_version</td>
        <td>4.7.2</td>
    </tr>
    <tr>
        <td>50</td>
        <td>oidc_oauth_enabled</td>
        <td>True</td>
    </tr>
    <tr>
        <td>51</td>
        <td>oidc_oauth_key</td>
        <td>key</td>
    </tr>
    <tr>
        <td>52</td>
        <td>oidc_oauth_secret</td>
        <td>secret</td>
    </tr>
    <tr>
        <td>53</td>
        <td>oidc_oauth_scope</td>
        <td>openid email profile</td>
    </tr>
    <tr>
        <td>54</td>
        <td>oidc_oauth_api_url</td>
        <td>https://sso.authentik/application/o/</td>
    </tr>
    <tr>
        <td>55</td>
        <td>oidc_oauth_token_url</td>
        <td>https://sso.authentik/application/o/token/</td>
    </tr>
    <tr>
        <td>56</td>
        <td>oidc_oauth_authorize_url</td>
        <td>https://sso.authentik/application/o/authorize/</td>
    </tr>
    <tr>
        <td>57</td>
        <td>oidc_oauth_logout_url</td>
        <td>https://sso.authentik/if/session-end/powerdns-admin/</td>
    </tr>
    <tr>
        <td>58</td>
        <td>oidc_oauth_username</td>
        <td>preferred_username</td>
    </tr>
    <tr>
        <td>59</td>
        <td>oidc_oauth_firstname</td>
        <td>given_name</td>
    </tr>
    <tr>
        <td>60</td>
        <td>oidc_oauth_last_name</td>
        <td>family_name</td>
    </tr>
    <tr>
        <td>61</td>
        <td>oidc_oauth_email</td>
        <td>email</td>
    </tr>
    <tr>
        <td>62</td>
        <td>oidc_oauth_account_name_property</td>
        <td></td>
    </tr>
    <tr>
        <td>63</td>
        <td>oidc_oauth_account_description_property</td>
        <td></td>
    </tr>
    <tr>
        <td>64</td>
        <td>local_db_enabled</td>
        <td>False</td>
    </tr>
    <tr>
        <td>65</td>
        <td>signup_enabled</td>
        <td>False</td>
    </tr>
    <tr>
        <td>66</td>
        <td>oidc_oauth_metadata_url</td>
        <td>https://sso.authentik/application/o/powerdns-admin/.well-known/openid-configuration</td>
    </tr>
</table>

### Expected Behavior

- Authentication should work fine
- Access granted

### Observed Behavior

- Error 500
```
powerdns_admin  | [2023-03-31 11:28:54 +0000] [9] [ERROR] Exception on /oidc/authorized [GET]
powerdns_admin  | Traceback (most recent call last):
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
powerdns_admin  |     response = self.full_dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
powerdns_admin  |     rv = self.handle_user_exception(e)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
powerdns_admin  |     rv = self.dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
powerdns_admin  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
powerdns_admin  |   File "/app/powerdnsadmin/services/oidc.py", line 35, in oidc_authorized
powerdns_admin  |     token = oidc.authorize_access_token()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
powerdns_admin  |     userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
powerdns_admin  |     claims = _jwt.decode(
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
powerdns_admin  |     data = self._jws.deserialize_compact(s, load_key, decode_payload)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
powerdns_admin  |     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 257, in _prepare_algorithm_key
powerdns_admin  |     key = algorithm.prepare_key(key)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7518/jws_algs.py", line 124, in prepare_key
powerdns_admin  |     raise ValueError(f'Key for "{self.name}" not supported, only "{self.curve}" allowed')
powerdns_admin  | ValueError: Key for "ES256" not supported, only "P-256" allowed
powerdns_admin  | [2023-03-31 11:28:54,061] [app.py:1449] ERROR - Exception on /oidc/authorized [GET]
powerdns_admin  | Traceback (most recent call last):
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
powerdns_admin  |     response = self.full_dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
powerdns_admin  |     rv = self.handle_user_exception(e)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
powerdns_admin  |     rv = self.dispatch_request()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
powerdns_admin  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
powerdns_admin  |   File "/app/powerdnsadmin/services/oidc.py", line 35, in oidc_authorized
powerdns_admin  |     token = oidc.authorize_access_token()
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
powerdns_admin  |     userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
powerdns_admin  |     claims = _jwt.decode(
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
powerdns_admin  |     data = self._jws.deserialize_compact(s, load_key, decode_payload)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
powerdns_admin  |     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 257, in _prepare_algorithm_key
powerdns_admin  |     key = algorithm.prepare_key(key)
powerdns_admin  |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7518/jws_algs.py", line 124, in prepare_key
powerdns_admin  |     raise ValueError(f'Key for "{self.name}" not supported, only "{self.curve}" allowed')
powerdns_admin  | ValueError: Key for "ES256" not supported, only "P-256" allowed
```

**Comment by AgentTNT** [comment]
Hey @caraar12345 - What method did you use to deploy PDA?

**Comment by caraar12345** [comment]
Hey @AgentTNT 👋 
Docker Compose

**Comment by AgentTNT** [comment]
Thanks! And which version of authentik? Is it also possible to provide a censored version of the JWS, mainly the KTY and CRV fields

**Comment by caraar12345** [comment]
Not a prob:
- Authentik [b097cf4](https://github.com/goauthentik/authentik/commit/b097cf4d7e74a9e95bad7f2dd1a520becc59c3da) (Based on 2023.3.1)
- JWKS:
```json
{
  "keys": [
    {
      "kid": "",
      "kty": "EC",
      "alg": "ES256",
      "use": "sig",
      "x": "",
      "y": "",
      "crv": "P-521",
      "x5c": [
        ""
      ],
      "x5t": "",
      "x5t#S256": ""
    }
  ]
}
```

**Comment by AgentTNT** [comment]
Can you change your curve to P-256? This combination does not appear to be supported - https://docs.authlib.org/en/latest/specs/rfc7518.html - Under Digital Signature with ECDSA, option 1. 

You're trying to following the ES256, which would also be the P-256, which is what the error is calling out. 

You can try to take the alg to ES512 and keep your curve what it is (P-521) and see if that is also successful.
