### ISSUE TITLE
Feature Correction: OAuth Metadata URL & JWKS URL Settings

### ISSUE THREAD

**Issue by AzorianMatt** [PowerDNS-Admin/PowerDNS-Admin#1499]
### Proposed Changes

I am going to update the authlib instantiation code to only include the metadata URL parameter if the corresponding PDA setting actually contains a usable value.

Furthermore, I will completely remove the JWKS URL setting that I recently introduced in an effort to correct a new issue. At this time, this is not even a supported parameter of authlib from what I can tell so it's a useless addition that creates confusion.

### Justification

Following the recent release of PDA 0.4.0, a notable number of bug reports came in regarding various OAuth issues that seem somewhat related. We are still unclear if this is because of a library upgrade (authlib itself), or perhaps the additional settings that were added with default empty values.

**Comment by AdvanticGmbH** [comment]
@AzorianMatt From my understanding the JWKS Url should be discovered from the data of the metadata URL. That's why adding it as a settable arg did break things, because now it had to be set manually which most didn't do, because it wasn't expected.

**Comment by AzorianMatt** [comment]
@AdvanticGmbH how certain of that are you?

I ask because when introspecting the authlib interface for this, I couldn't find any references to that parameter which leads me to believe it was totally ignored just as if I had made up other name.

Thoughts?

**Comment by AdvanticGmbH** [comment]
@AzorianMatt They at least mention it here:  [Authlib](https://github.com/lepture/authlib/blob/70a6bfa92aa1007515465a7af1a60a4518abe699/docs/client/frameworks.rst#parsing-id_token). Another thing that is currently wrong is, that if you set the metadata URL you shouldn't have to set:
```
* authorize_url
* access_token_url
* jwks_uri
```
Because they should be discovered over the metadata URL. I also think calling the userinfo this way: [PDA](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/powerdnsadmin/routes/index.py#L370) is not the best way

**Comment by AdvanticGmbH** [comment]
@AzorianMatt  I think making the the metadata URL mandatory and removing they other fields would be much less confusing and could also fix most of the current problems.

**Comment by AdvanticGmbH** [comment]
> @AzorianMatt They at least mention it here: [Authlib](https://github.com/lepture/authlib/blob/70a6bfa92aa1007515465a7af1a60a4518abe699/docs/client/frameworks.rst#parsing-id_token). Another thing that is currently wrong is, that if you set the metadata URL you shouldn't have to set:
> 
> ```
> * authorize_url
> * access_token_url
> * jwks_uri
> ```
> 
> Because they should be discovered over the metadata URL. I also think calling the userinfo this way: [PDA](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/powerdnsadmin/routes/index.py#L370) is not the best way

Adding to this there is an extra [UserInfo](https://github.com/lepture/authlib/blob/169c7dcfc47478c8d55553cc95fb0f5578162b77/authlib/oidc/core/claims.py#L208) class, which takes the metadata URL into account [here](https://github.com/lepture/authlib/blob/169c7dcfc47478c8d55553cc95fb0f5578162b77/authlib/integrations/base_client/async_openid.py#L26)

**Comment by AzorianMatt** [comment]
@AdvanticGmbH do you have a good environment to test these proposed changes? I'm all for it if I can finally put this OAuth issue to bed but I have yet to get a good test environment going to support any changes I do to it.

**Comment by AdvanticGmbH** [comment]
@AzorianMatt Currently we only have an own OIDC implementation running with which we are testing the generic OIDC part. Sadly we have no way to test the Google, Azure and Github implementations currently. But for Google and Github I'm sure from reading their docs that they have support for a metadata URL.

**Comment by AdvanticGmbH** [comment]
@AzorianMatt I could create a commit for the generic OIDC part at least.

**Comment by AzorianMatt** [comment]
@AdvanticGmbH this has been completed and included in the latest release of `0.4.1`>
