### ISSUE TITLE
Invalid OIDC OAuth token after session expiration

### ISSUE THREAD

**Issue by benshalev849** [PowerDNS-Admin/PowerDNS-Admin#1503]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

1. Log in via OIDC oauth.
2. Wait a long time till token expires.
3. Try to log into the interface again.

### Expected Behavior

Reaching the log out page and then being able to log in again with a new token.

### Observed Behavior

The observed behavior i get is that after a long while the cookies and session "expires".
This causes the client to send a token which expires.
This means the server returns a "500 http error"
And in the logs i see:

`authlib.integrations.base_client.errors.OAuthError: invalid_grant: Token is not active`

This means that i have no way of logging out, logging in again, or doing anything in the admin, only way to "Fix" this is manually clear cookies which is a bad practice.

The line in powerdnsadmin code that "calls" this error is:

Exception on /login [GET]
Traceback (most recent call last):
....
File "/app/powerdnsadmin/routes/index.py", line 372, in login
me = json.loads(oidc.get('userinfo').text)
...
```

Cannot supply the entire trace due to the machine being in an isolated network.

**Comment by AzorianMatt** [comment]
@benshalev849 I realize you need to relax some information, but it seems you have removed the actual exception information which makes it hard to determine what actually went wrong here.

I'm assuming this is a decoding issue where the value is empty when it's otherwise expected not to be. However, I have no way of being certain of that based on what you have provided.

**Comment by AzorianMatt** [comment]
@benshalev849 I updated a possibly related app method for clearing sessions to include azure and oidc tokens that were not previously included. I wonder if this might help resolve this issue. The possible fix is included with the latest release of `0.4.1` that I just put out today.

**Comment by benshalev849** [comment]
@AzorianMatt 

Okay i will try to test it and let you know :)

**Comment by benshalev849** [comment]
Any updates on this? :D

**Comment by AzorianMatt** [comment]
> Any updates on this? :D

Nil
