### ISSUE TITLE
PRETTY_IPV6_PTR and Wildcard records

### ISSUE THREAD

**Issue by dupondje** [PowerDNS-Admin/PowerDNS-Admin#151]
Hi,

In PowerDNS you can add \* as record for IPv6 DNS records.
This so you don't have to add all PTR's for each IP in the database.

This works fine, but if you enable PRETTY_IPV6_PTR, the code seems to go nuts :)

Can this be fixed?

Thx

**Comment by jallakim** [comment]
PRETTY_IPV6_PTR was a quick "hack" to avoid dealing with dotted strings from hell. I don't think I'll get the motivation to fix interoperability between PRETTY_IPV6_PTR and wildcard-PTR's any time soon, as it's kinda a very, very specific corner case (tbh. I've "never" heard of people actually using wildcards for their IPv6 reverse -- "add PTR's to whatever is in use, and leave the rest be" has been my approach to IPv6 PTR's).

**Comment by dupondje** [comment]
Well indeed :) but I tought it might be easy to just check if there is a '*' in the string, and if this is the case, just don't do the PRETTY_IPV6_PTR stuff :)

**Comment by jallakim** [comment]
The problem with doing that approach is that there is (currently) no input-validation in PDA, so if you open an IPv6 reverse zone that has no wildcard-entries, it will do the PRETTY_IPV6_PTR (which is done on load), and it would go haywire trying to update the zone. But I guess at least you'd be able to view the zone. Not sure what is better :-P

**Comment by jallakim** [comment]
I guess we can do validation on '*', and if so, disable/remove the "Add Record"-button. It's ugly, but I think we're past that point regarding PRETTY_IPV6_PTR :-D
