### ISSUE TITLE
Warning: Do not update to ngoduykhanh/powerdns-admin:latest from dockerhub!

### ISSUE THREAD

**Issue by alm-nl** [PowerDNS-Admin/PowerDNS-Admin#1511]
### PDA version

I'm Not Sure

### Python version

3.0

### Steps to Reproduce

I updated the docker container to [ngoduykhanh/powerdns-admin:latest](https://hub.docker.com/r/ngoduykhanh/powerdns-admin) (which is 3 or 4 months old) and ran into the bug that adds the domain to every record when updating a zone using powerdns-admin:
www.example.com became www.example.com.example.com making the zone unreachable.

The problem with using this docker image is that it does not show a version number in the GUI so it's kind of unclear to what you are updating. When issuing the command 'docker ps -a' it shows a name "nice_wu". Previously I was running a version of 11 months ago.

I'd recommend to remove this docker image from dockerhub and use powerdnsadmin/pda-legacy:latest instead.

This is a warning to all people that use a previous version of this docker image to not update to the latest version. It causes headache and stress.

### Expected Behavior

Not adding domain suffix to records that already have the suffix.

### Observed Behavior

Zone unreachable due to double suffixes.

**Comment by AzorianMatt** [comment]
@alm-nl I take it by this submission that you haven't looked through the project repository, documentation, issues, or discussions.

This submission is very unnecessary as I have made numerous announcements and documentation updates about these changes to the Docker Hub repository location. If this mistake costed you some production down time, perhaps you should have consulted with an official source of truth (the project repository), before deploying it.

**Comment by alm-nl** [comment]
@AzorianMatt Thank you for your time to respond. I did check out some issues and even closed issues before posting the message above even though you think I did not.

The reason for posting the message was the text in https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1317:

_It's important to take notice that all previous official releases have NOT been been transferred to this Docker Hub repository at the time of this post. I will continue working on a solution to get all of the previous releases built and published to the new repository as soon as possible. In the mean time, the best solution if you're using an image from a specific release, would be to continue using the old references until a further announcement has been made for this. The old repository should remain for quite some time until the transition is complete._

If the message in #1317 would have stated it is highly recommended to use the new Docker hub repository even for older installations then I would not even have tried updating with the ngoduykhanh/powerdns-admin:latest repo. Since it is a sticky message that is what I read.

I'm just trying to be helpfull so that others after me don't fall in the same trap. Since there are others who still use the old repo it might be worth improving the message so it is more clear. If it is possible to remove the old latest image in the old repo and put the tag to a version that does not have the bug that would also be welcome ofcourse though...

I'm a very happy user of PowerDNS-Admin and hope others will be as well. Preventing negative experiences do help to accomplish that.

Please consider what I wrote. Thank you.

**Comment by AzorianMatt** [comment]
@alm-nl That's a very fair point you made and I can appreciate where the confusion could be created as a result. Taking that into consideration, I went ahead and did a hard copy of all versions previous to 0.4.0 from the original repository as a starting point. I will contact Khanh and speak with him about removing the tag in efforts to reduce confusion.

Thank you for taking the time to elaborate on this and thank you for being a continued PDA user.
