### ISSUE TITLE
Can not create secondary zone 

### ISSUE THREAD

**Issue by BadikovVV** [PowerDNS-Admin/PowerDNS-Admin#1539]
### PDA version

0.4.0

### Python version

3.8

### Steps to Reproduce

1. Click on 'create zone'
2. Fill Zone name like myzone1.test.org 
   Zone Type Secondary  and point primary dns IP  , SOA-EDIT-API as DEFAULT
   
![изображение](https://user-images.githubusercontent.com/6616409/232446322-3e7d670d-859a-4d08-bf3c-7f79c109abb0.png)

via pdnsutils zone with the same values created correctly 

### Expected Behavior

   A new zone record should have been created with the specified values

### Observed Behavior

![изображение](https://user-images.githubusercontent.com/6616409/232445415-cb64c3ca-0d3d-462e-a00b-aa3680c95a63.png)
Zone created without Primary IP

**Comment by Metrax** [comment]
This has been fixed in 0.4.1, see #1502

**Comment by BadikovVV** [comment]
Tested 
 all OK!
