### ISSUE TITLE
Add IPv6 Support To Docker

### ISSUE THREAD

**Issue by zhuzejie** [PowerDNS-Admin/PowerDNS-Admin#1540]
### PDA version

0.4.1

### Feature type

Data model modification

### Proposed functionality

Hope to add support for dual stack of IPv4/IPv6

### Use case

IPv6 usage requirements

**Comment by AzorianMatt** [comment]
@zhuzejie if you want a feature, you'll have to put in some more effort than a single sentence. I'm not even sure what you're asking for here, since IPv6 is already manageable in PDA.

**Comment by AzorianMatt** [comment]
@zhuzejie you're welcome. That makes more sense. I'll look into it.

**Comment by zhuzejie** [comment]
@AzorianMatt Thank you very much
