### ISSUE TITLE
flask db upgrade

### ISSUE THREAD

**Issue by iam-Robo** [PowerDNS-Admin/PowerDNS-Admin#1543]
### Change Type

Correction

### Area

Installation/upgrade

### Proposed Changes

Im getting the following error while running "flask db upgrade"

  File "/var/www/html/pdns/flask/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 253, in init_app
    raise RuntimeError(
RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.

**Comment by iam-Robo** [comment]
Also the same error on running "**flask assets build**"

  raise RuntimeError(
RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.

**Comment by AzorianMatt** [comment]
@iam-Robo you didn't file the issue with the appropriate template. Please try again.
