### ISSUE TITLE
Instructions for updating PowerDNS-Admin

### ISSUE THREAD

**Issue by cseres3** [PowerDNS-Admin/PowerDNS-Admin#155]
Hi!
A short description what is the recommended way to keep PowerDNS-Admin up-to-date in production environment would be nice addition in the documentation. At least I did not notice instructions in Wiki or README.md.

**Comment by jallakim** [comment]
`git update` (-:

**Comment by rodehoed** [comment]
Git pull indeed for now. the db_* scripts are not being used yet. Also be sure that your config.py is updated with the newest config keys.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.
We will work on the software documentation soon.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
