### ISSUE TITLE
Account Quotas

### ISSUE THREAD

**Issue by mbevc1** [PowerDNS-Admin/PowerDNS-Admin#1561]
### PDA version

0.4.1

### Feature type

New functionality

### Proposed functionality

As an admin I'd like to set domains limitations per account (i.e. account can only have x domains).

### Use case

Expand on current account groupping of domains.

**Comment by AzorianMatt** [comment]
@mbevc1 based on my review of the current database model this morning, this would certainly be doable without resistance on the persistence side of things. I can't speak for the implementation of the front-end / back-end side of things though as there is still a large amount of clean-up work to be done in the relevant areas.

I will keep this open and inquire if anyone on the contribution team feels like handling it.

Thank you for being a PDA user!

**Comment by mbevc1** [comment]
Thanks for reviewing the codebase @AzorianMatt :+1:

**Comment by mbevc1** [comment]
Has this been implemented? Sorry, but couldn't see any related PRs

**Comment by AzorianMatt** [comment]
@mbevc1 no, just doing house keeping.

**Comment by AzorianMatt** [comment]
@mbevc1 yeah, unfortunately that's just the status it gives issues with mass closing. I really wish it provided a better approach for this scenario.

You would be correct to assume that no additional features are intended to be worked on for the legacy edition while producing a replacement. It's not to say that we won't be opportunistic on low hanging fruit, but we aren't making any promises.

**Comment by mbevc1** [comment]
Thanks for the explanation and transparency and appreciate all your work so far!

**Comment by AzorianMatt** [comment]
@mbevc1 you're welcome and thank you for the sentiment!
