### ISSUE TITLE
CNAME Record Validation

### ISSUE THREAD

**Issue by mbevc1** [PowerDNS-Admin/PowerDNS-Admin#1562]
### PDA version

0.4.1

### Feature type

Change to existing functionality

### Proposed functionality

When adding a new CNAME record without the domain suffix it automatically adds a `.` where it should assume same domain suffix. For example providing:
```
b  IN  CNAME test
test  IN  A 127.0.0.1
```

Should still be valid.

### Use case

Using local CNAMEs in the current domain.

**Comment by mbevc1** [comment]
Has this been implemented? Sorry, but couldn't see any related PRs

**Comment by AzorianMatt** [comment]
@mbevc1 no, just doing house keeping.
