### ISSUE TITLE
No JWKS_URL environment variable

### ISSUE THREAD

**Issue by benshalev849** [PowerDNS-Admin/PowerDNS-Admin#1564]
### PDA version

0.4.1

### Feature type

App Setting Addition

### Proposed functionality

Add OIDC_OAUTH_JWKS_URL as a valid environment variable

### Use case

Input all OIDC settings via environment variables and not saved in DB due to different SSO for reach region.
In addition to be in line with other OIDC settings which allow this behaviour.

**Comment by AzorianMatt** [comment]
@benshalev849 as of the release of `0.4.1`, all current application settings can be defined through environment variables.

**Comment by benshalev849** [comment]
@Azorian

> @benshalev849 as of the release of `0.4.1`, all current application settings can be defined through environment variables.
> 
> It's worth noting that the setting you're referring to should have never existed. It was not a valid setting that was actually doing anything from what I can tell. It has since been removed.

Since it's mandatory waht can i do?
When i put the env variable

OIDC_OAUTH_JWKS_URL it does not get changed in the setting like other OIDC_OAUTH env variables.

**Comment by AzorianMatt** [comment]
@benshalev849 give me a bit to review this as I've made a mistake somewhere. I've either not properly included a remaining setting or forgot to remove it where it shouldn't be.
