### ISSUE TITLE
SOA Serial# missmatch by 1, Zone Type also incorrect

### ISSUE THREAD

**Issue by Znuff** [PowerDNS-Admin/PowerDNS-Admin#1570]
### PDA version

0.4.1

### Python version

3.10

### Steps to Reproduce

1. Add a new Domain, with `Zone Type: Primary` and `SOA-EDIT-API: DEFAULT`:
![chrome_2023-05-12_20-08-15](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/496793/d69b7149-4cde-468c-9213-7549a2f99343)
2. Domain gets serial `2023051202` and zone type `NATIVE`:
![chrome_2023-05-12_20-10-03](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/496793/9a93a719-3207-4e40-a040-6def00160729)
3. Query local DNS server:
```
# dig @localhost test-domain.com soa +short
ns1.REDACTED.TLD. hostmaster.test-domain.com. 2023051203 10800 3600 604800 3600
```
Serial# is off by 1 in the SOA.

### Expected Behavior

Zone should be added with the proper type selected in the previous menu, specifically **Primary**.

Also, SOA Serial# should reflect the actual serial that the authoritative server responds with.

### Observed Behavior

Serial# is off by 1.

Zone type is not added properly.

**Comment by AzorianMatt** [comment]
@Znuff please verify the version of PDA that you are running. You reported this as `0.4.1` but the issue you reported, has long since been fixed and is only present in much older versions.

If you deployed using a Docker image, please comment back with the full repository path and image tag to verify that you're using the correct image.

**Comment by Znuff** [comment]
Yes, this is under Docker. I just did a fresh pull on the :latest on the pda-legacy image:

```json
                "org.opencontainers.image.created": "2023-04-12T12:16:28.991Z",
                "org.opencontainers.image.description": "A PowerDNS web interface with advanced features",
                "org.opencontainers.image.licenses": "MIT",
                "org.opencontainers.image.revision": "8108caf96a03fb87e9a42ae85d4dc1000822f1a3",
                "org.opencontainers.image.source": "https://github.com/PowerDNS-Admin/PowerDNS-Admin",
                "org.opencontainers.image.title": "PowerDNS-Admin",
                "org.opencontainers.image.url": "https://github.com/PowerDNS-Admin/PowerDNS-Admin",
                "org.opencontainers.image.version": "0.4.1"
```

From docker-compose:

```yml
image: powerdnsadmin/pda-legacy:latest
```

**Comment by AzorianMatt** [comment]
@Znuff thank you for the quick response. I'll dig into this further once I get a bit more time to put more effort on the project this month.

**Comment by Znuff** [comment]
For what it's worth, I've done more digging after posting this ticket, and it's probably not something related to PowerDNS Admin:

```
# pdnsutil increase-serial test-domain.com
May 12 20:20:27 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
SOA serial for zone test-domain.com set to 2023051203

# dig @localhost test-domain.com soa +short
ns1.REDACTED.TLD. hostmaster.test-domain.com. 2023051204 10800 3600 604800 3600
```

**Comment by AzorianMatt** [comment]
@Znuff that much wouldn't surprise me. However, the other issue with the zone type was a self-induced issue presumably that I thought had been rectified everywhere.
