### ISSUE TITLE
Invalid SQL on Postgres Database

### ISSUE THREAD

**Issue by remyd74** [PowerDNS-Admin/PowerDNS-Admin#1573]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

Activate email validation 
Create an account
send OK.
On link click, Internal Error.
Validation not applied.

### Expected Behavior

Need email validation to be True

### Observed Behavior

The SQL query do not match the correct type :
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "confirmed" is of type boolean but expression is of type integer
May 17 09:12:36 dns-panel gunicorn[953]: LINE 1: UPDATE "user" SET confirmed=1 WHERE "user".id = 2
May 17 09:12:36 dns-panel gunicorn[953]:                                     ^
May 17 09:12:36 dns-panel gunicorn[953]: HINT:  You will need to rewrite or cast the expression.
May 17 09:12:36 dns-panel gunicorn[953]: [SQL: UPDATE "user" SET confirmed=%(confirmed)s WHERE "user".id = %(user_id)s]
May 17 09:12:36 dns-panel gunicorn[953]: [parameters: {'confirmed': 1, 'user_id': 2}]
May 17 09:12:36 dns-panel gunicorn[953]: (Background on this error at: http://sqlalche.me/e/13/f405)
May 17 09:12:36 dns-panel gunicorn[953]: During handling of the above exception, another exception occurred:

In Postgres, you need to cast integer to boolean to update the value.

**Comment by AzorianMatt** [comment]
@remyd74 how did you deploy the application? Are you using the docker container? If so, please provide the full repository and image path including the tag for the image you have deployed.

**Comment by remyd74** [comment]
No, it's via the Git repo (yesterday)
`git clone https://github.com/PowerDNS-Admin/PowerDNS-Admin.git`
And no docker running.

**Comment by dblanque** [comment]
I'm having the same issue!
