### ISSUE TITLE
HTTP 400 error on PDNS Auth 4.8.0

### ISSUE THREAD

**Issue by mtnetronik** [PowerDNS-Admin/PowerDNS-Admin#1594]
### PDA version

0.4.1

### Python version

3.9

### Steps to Reproduce

1. Fresh install of Debian 11.
2. Fresh install of PowerDNS Auth 4.8.0.
3. PDNS Config: enable only API and set API key.
4. Fresh install of PowerDNS Admin using your wiki guide with MariaDB-server.

### Expected Behavior

I tried to create new zone via PowerDNS Admin website.

### Observed Behavior

I got error: HTTP 400 Error Creating domain 'example.net.' failed: backend refused", on debug console:
`[2023-06-22 12:24:56,425] [domain.py:270] ERROR - Creating domain 'example.net.' failed: backend refused`
`[2023-06-22 12:24:56,507] [_internal.py:224] INFO - x.x.x.x - - [22/Jun/2023 12:24:56] "POST /domain/add HTTP/1.1" 400 -`

**Comment by AzorianMatt** [comment]
@mtnetronik I'm rejecting this bug report as I don't believe it's a bug at all. You seem to have made it pretty clear that you set up a new PDNS server without configuring any backends. Now you have an error about a misconfigured backend.

**Comment by mtnetronik** [comment]
@AzorianMatt  Thank you for sugestion. Previously I was running on 4.6.x version with backend-bind. It turned out that from 4.7.x version this backend-bind stop working with PowerDNS Admin. For tests I switched to MySQL and it work properly.

**Comment by AzorianMatt** [comment]
@mtnetronik you're welcome and thank you for any efforts to identify these issues. If you're confident that it's a back-end compatibility issue with PDA that started at that version, I would more than welcome a bug report right up that specifically identifies that.

Based on what was provided though, I don't believe it's a reasonable assertion so it seems more documentation on the matter is necessary.
