### ISSUE TITLE
Provide support for catalog zones

### ISSUE THREAD

**Issue by feldsam** [PowerDNS-Admin/PowerDNS-Admin#1607]
### PDA version

0.4.1

### Feature type

New functionality

### Proposed functionality

I tested catalog zone with pdns 4.7.3 and dev branch of pda. Figured out, that only few things should be added to pda app:

- when creating new zone:
  - additional zone type `PRODUCER` - identiffies catalog zone - probably not needed here, can be created one time using CLI
  - add new dropdown to select catalog zone - show only if there is any
  - add new dropdown to select tsig key to use - to use secure transfers

That is all for minimal implementation. On dashboard, pda is properly showing type `producer` for catalog zone, so no more work is needed.

I can take care of it and submit pull request.

### Use case

I like to use it with non-pdns slave server, I want to use bind for slave. DNS system will be more resilent, when I use different software.

Catalog Zones is a feature allowing easy provisioning of zones to secondary servers. A "catalog zone" is a special DNS zone that contains a list of other zones to be served, along with their configuration parameters.  The zones listed in a catalog zone are called "member zones".  When a catalog zone is loaded or transferred to a secondary server that supports this functionality, the secondary server creates the member zones automatically.  When the catalog zone is updated (for example, to add or delete member zones, or change their configuration parameters) those changes are immediately put into effect. Because the catalog zone is a normal DNS zone, these configuration changes can be propagated using the standard AXFR/IXFR zone transfer mechanism.

### Database changes

none, type field is varchar(8) so it fits

### External dependencies

none

**Comment by AzorianMatt** [comment]
@feldsam splendid work on this! I appreciate the efforts and it sounds like you did your homework.

One of our contribution team members is currently working on some changes related to The zone editor, so I want to involve him in the conversation as well as there will be impacts both ways.

@AgentTNT thoughts?

**Comment by martijngoorman** [comment]
I just commented on https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1348 for a status, but this issue looks prommising.
Maybe add @Metrax to this issue?

**Comment by Metrax** [comment]
There is a little bit more todo than the points at "Proposed functionality"
Catalog Zones should be only available for PDNS Versions > 4.7, we need to introduce a new version detection system here, else we will get too much support requests here.
Also since 4.7.4 there is a function "list-member-zones" which we should implement.

**Comment by feldsam** [comment]
Hello @Metrax, I means **minimal functionality**, where I think we don't need to list member zones. Regarding pdns version, there is already version in Server settings, manualy entered by admin, so we can offer proposed functionality only if version is set to 4.7+

**Comment by Metrax** [comment]
Implementing an automatic version detection should be realy easy. For example we can do it before the domain update process. When done, we can disable the version field in the pdns settings.

For my personal use, it would be nice to have a list of the members. We have >20 Producer zones at our hidden primary pdns and it would be helpful for me to click on a producer zone and see its members, without waiting for the background domain update.

I'm not a friend of "half solution". If i would code it, we will offer the full range of functionality, we can get from the product. But thats the next point "if i would code it", i will need some months for this, due to a high workload at the moment :-(

**Comment by feldsam** [comment]
Hi, yes, it would be fine, but it should have separate issue. Anyway, this catalog zones functionality can be also split to more issues and develop it in steps. It is better that have one big issue/feature to develop.

**Comment by feldsam** [comment]
Hi @AzorianMatt, would you check my PR? There is Catalog zones implementation only. I do ttsig keys in another PR

**Comment by martijngoorman** [comment]
Problem solved!
PDNS Added a feature in there latest version
https://doc.powerdns.com/authoritative/changelog/4.8.html#change-4.8.3-New-Features

If you add this to your config and set a default catalog zone, all new domains added via API where no explicit zone is defined will use this default catalogzone.

https://doc.powerdns.com/authoritative/settings.html#default-catalog-zone

**Comment by feldsam** [comment]
What problem is solved?

**Comment by Metrax** [comment]
> https://doc.powerdns.com/authoritative/settings.html#default-catalog-zone

If you have a simple setup with just 1 catalog, it helps you without catalog support in PDA.
If you have multiple catalog zones, this feature will not help you.

**Comment by feldsam** [comment]
OK, so what is point of this comment? I did implementation of catalog zones to PDA. Or you don't value it and rather want to go way without support?

**Comment by martijngoorman** [comment]
Sorry @feldsam, no intent to disrespect your work. I should have mention it otherwise.
As @Metrax said; for 1 catalog this is the perfect option in the meantime.
For multiple catalog we all love to see this option in PDA.

**Comment by AzorianMatt** [comment]
@feldsam I will try to get to reviewing this work finally. Thank you again for your efforts.

**Comment by AzorianMatt** [comment]
Resolved by #1747
