### ISSUE TITLE
Add option for reading custom header for /nic/checkip.html

### ISSUE THREAD

**Issue by madpsy** [PowerDNS-Admin/PowerDNS-Admin#161]
Just now it seems that /nic/checkip.html simply reads the remote_addr header. It would be really useful to be able to set what header should be read (no point in fixing it to 'X-Forwarder-For' like some software, because e.g. CloudFlare use 'CF-Connecting-IP'). 

Use case is when running the web server behind a proxy.

Note that headers are only as reliable as the upstream proxies make them - that's not pdns admin's problem though. If multiple values are passed for said header I would suggest the user is doing it wrong but RFC7239 contains info on the matter specifically for X-Forwarded-* headers.

**Comment by madpsy** [comment]
Acutally, I presume it's not just checkip.html which would need changed but rather whatever method it is using so the actual update works too!

**Comment by ivanfilippov** [comment]
The code for checkip.html is very simple, you can check it out [here](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/views.py#L738). Basically we would need to check for presence of every type of "proxy" header (X-Forwarded-*, CF-Connecting-IP, X-Real-IP,etc) and pick one that's available.

Should be an easy fix and I'll try to look at it but patches are welcome. :)

**Comment by ivanfilippov** [comment]
Oh and the code relies on the 'myip' parameter being present in the DynDNS request.

**Comment by madpsy** [comment]
Having the header read from plugin options or a config file might be better than looking for multiple headers given it can be completely custom.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. This feature request is tracked in #1178

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
