### ISSUE TITLE
DNSSEC feature breaks for zones that contain improperly escaped slashes

### ISSUE THREAD

**Issue by ravizhan** [PowerDNS-Admin/PowerDNS-Admin#1630]
### PDA version

0.4.1

### Python version

3.10

### Steps to Reproduce

1. Click the  `Create Zone`
2. Creat a Zone named `1/27.1.1.1.in-addr.arpa`
3. Click `Enable DNSSEC` of `1/27.1.1.1.in-addr.arpa` in Dashboard

### Expected Behavior

It should create DNSSEC correctly.
I try to run `pdnsutil secure-zone 1/27.1.1.1.in-addr.arpa` on the powerdns server, and it works fine.
And after that the `Enable DNSSEC` button changes from red to green.
Thus, I'm sure it's a problem with PowerDNS-Admin.

### Observed Behavior

It prompted me that There was something wrong, please contact administrator

**Comment by ravizhan** [comment]
By the way, I am using the latest docker image

**Comment by AzorianMatt** [comment]
A quick reproduction of your issue makes the problem very apparent. The zone name is currently sent to the back-end as part of the URL path instead of a query string or body parameter. Naturally, that forward slash wasn't being properly escaped which leads to the request being directed at a non-existent back-end path.

**Comment by AzorianMatt** [comment]
Resolved by 1707.

**Comment by AzorianMatt** [comment]
@ravizhan I spoke too soon. After further investigation, the mistake that lead to this flaw is widely scattered through-out the app. While trying to rectify the issue, I am finding the that fix is actually a huge problem. For this reason, I am doing what I can for now, but many features will simply remain broken from this.

You are however the first person that I know of to have brought a scenario where the zone name contains a forward slash so this isn't going to be a priority.
