### ISSUE TITLE
Zone type comparison logic creates false-positive abort scenario

### ISSUE THREAD

**Issue by corelgott** [PowerDNS-Admin/PowerDNS-Admin#1639]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

PDA-Version: 4.2 but could also confirm with older versions.
I'm using mariadb as backend for the powerdns server as well as for powerdns-admin. (Same server, separate Databases, separate credentials)

Create a new zone named "test.com" via PDA, resulting in the db entry being:
{"id":"5","name":"test.com","master":"['9.9.9.9']","type":"Slave","serial":"0","notified_serial":"0","last_check":"0","dnssec":"0","account_id":null}

Note, that the "type" of this entry is "Slave" starting with a capital "S".

When now opening this zone to view the entries things go south:

[domain.py:66](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/8108caf96a03fb87e9a42ae85d4dc1000822f1a3/powerdnsadmin/routes/domain.py#L69C46-L69C46)
```python
    # API server might be down, misconfigured
    if not rrsets and domain.type != 'slave':
        abort(500)
```

Since "Slave" != "slave". After changing it within the database I am able to view the entries.

### Expected Behavior

the db entry should be created as "type" = "slave"

### Observed Behavior

```python
domain.type != 'slave':
        abort(500)
```

**Comment by corelgott** [comment]
very hacky solution:

```sql
DELIMITER //

CREATE TRIGGER before_update_trigger
BEFORE UPDATE ON domain
FOR EACH ROW
BEGIN
  SET NEW.type = LOWER(NEW.type);
END;
//

DELIMITER ;
```
wouldn't recommend, but seems to work.

**Comment by AzorianMatt** [comment]
Resolved by PR 1706.
