### ISSUE TITLE
Duplicate id error while creating 2 domains in parrallel.

### ISSUE THREAD

**Issue by OriOhayon18** [PowerDNS-Admin/PowerDNS-Admin#1644]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

Create 2 domains in parrallel using the API

### Expected Behavior

Both domains should be created both in PowerDNS Authoritative server's database and in PowerDNS Admin's database

### Observed Behavior

Both domains were created in PowerDNS Authoritative server's database but only one of the domains was created in PDA's database, while looking at the logs I saw that there was a uniqueViolation error: dpulicate key value violates unique constraint idx_353898_ix_domain_name

**Comment by OriOhayon18** [comment]
might be related to #1116

**Comment by AzorianMatt** [comment]
This is a duplicate of issue 1116 as you have recognized.
