### ISSUE TITLE
Custom TTL setting

### ISSUE THREAD

**Issue by whitepiratebaku** [PowerDNS-Admin/PowerDNS-Admin#1648]
### PDA version

0.4.1

### Feature type

Default App Setting Change

### Proposed functionality

Currently TTL only allows choosing prexisting  values from list and lowest TTL is 1m there.  Because we use LUA records for fail over we use lower TTLs for those records like 10s. It would be more flexible if we can set custom TTL.

### Use case

Setting lower TTL for  LUA records

**Comment by meineerde** [comment]
After #123 (and implemented in #409), PowerDNS-Admin already provides an option to (globally) configure the list of values shown in the TTL dropdown in the UI according to your own requirements. Here, you can also include a value such as `10 seconds` or even just a bare integer (representing seconds).

You can configure this in **Settings** -> **Basic** -> **ttl_options**.

Afterwards, your custom TTL options should show up in the TTL drop downs for each record.
