### ISSUE TITLE
update readme about docker image

### ISSUE THREAD

**Issue by ftoledo** [PowerDNS-Admin/PowerDNS-Admin#1649]
### Change Type

Correction

### Area

Installation/upgrade

### Proposed Changes

please update readme and wiki install page that still point to old docker image: powerdnsadmin/pda-legacy:latest

thanks!

**Comment by AzorianMatt** [comment]
@ftoledo perhaps you should ready project information more closely. The `powerdnsadmin/pda-legacy:latest` image is the latest image that represents the current release of the project.

**Comment by ftoledo** [comment]
hi @AzorianMatt thanks ! I think that at that moment I must have had an old version of the readme when it pointed to ngoduykhanh/powerdns-admin:latest
Saludos!

**Comment by AzorianMatt** [comment]
@ftoledo you're welcome! I figured it had to be something like this.
