### ISSUE TITLE
It is recommended to add multilingual function

### ISSUE THREAD

**Issue by wxtewx** [PowerDNS-Admin/PowerDNS-Admin#1651]
### PDA version

0.4.1

### Feature type

Data model modification

### Proposed functionality

It is recommended to add multilingual function

### Use case

I hope that the front end is not only English, but can add multiple languages, so that users can have more choices

**Comment by AzorianMatt** [comment]
@wxtewx Thank you for your request. The project has too many much more important priorities that aren't able to be addressed currently so this request can not be accepted.
