### ISSUE TITLE
Local user setup utilizes case-sensitive verification of username and email

### ISSUE THREAD

**Issue by ronanac3** [PowerDNS-Admin/PowerDNS-Admin#1657]
### PDA version

0.4.1

### Python version

3.7

### Steps to Reproduce

1. In PowerDNS Web Interface, goto Application -> Users
2. For a given test user, edit their email to case usage e.g first.last@email.com.au -> First.Last@email.com.au
3. Now an additional user can be created with the email first.last@email.com.au (following the example above)

This occurred for me when moving our PowerDNS-Admin to a Kubernetes pod. In this process, Azure OAuth was set up which auto creates accounts for users using our new company email domain as their username. However, although the new users had new usernames, many users had the same email. Of these users, many had the same case email (thus a new account could not be created as their email is already in use) and many had the same email but with a different case (e.g. first.last@email.com.au -> First.Last@email.com.au, thus allowing them to have a new account created). 

### Expected Behavior

It is expected that multiple user accounts cannot have the same email with different casing. The check for an existing email (and username too?) should be case insensitive. This should be able to be solved simply using .lower() on the strings when comparing the two.

### Observed Behavior

Accounts are allowed to be created with duplicate usernames and emails if the string casing is not equal. Thus, a user with an email equal to first.last@email.com.au can coexist with a user having an email equal to First.Last@email.com.au despite the emails being the same.

**Comment by ronanac3** [comment]
Additionally, can we/I replace 
`current_app.logger.warning('Unable to create ' + azure_username)` 
with  
`current_app.logger.warning('Unable to create ' + azure_username + 'Reasoning:' + result['msg'])`

To add further information when debugging.

**Comment by AzorianMatt** [comment]
This has been resolved by PR 1658.
