### ISSUE TITLE
Documentation lacks information about "DNSSEC Enable" feature

### ISSUE THREAD

**Issue by whitepiratebaku** [PowerDNS-Admin/PowerDNS-Admin#1659]
### Change Type

Addition

### Area

Configuration

### Proposed Changes

Currently It is possible to enable DNSSEC from UI but rest of actions not clear, I know it is required to add some DS records to domain registerer and know How to get required data from server but is it also possible to get those information from UI? imagine there is a non admin user and he wants to enable DNSSEC for domain he controls, after enabling DNSSEC on zone how he can get required DS information to be published on domain registerer?

**Comment by righter83** [comment]
Hi just look into the PowerDNS Doc: https://doc.powerdns.com/authoritative/dnssec/pdnsutil.html

Generate Keys:
`pdnsutil secure-zone yourdomain.com`

View Keys:
`pdnsutil show-zone yourdomain.com`

Then add the keys to your registrar.

**Comment by AzorianMatt** [comment]
@whitepiratebaku it is not within the scope or responsibility of this project to teach users about DNS fundamentals. Please use search engines if you wish to learn more.
