### ISSUE TITLE
The domain name will be automatically added to all records when submit "apply changes"

### ISSUE THREAD

**Issue by jerryqzhang** [PowerDNS-Admin/PowerDNS-Admin#1661]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

When I modify a record, after submit "apply changes",  the domain name will be automatically added to all records. This can cause a bad experience. Can this function be turned off?

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/30404657/630a79f3-ae9b-4da7-97ce-a37d3ff992cc)

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/30404657/fe8a79ab-f66a-4a73-97bb-505de0857970)

### Expected Behavior

Only submit modified records

### Observed Behavior

submit all records

**Comment by brodo97** [comment]
Hi @jerryqzhang,
how do you solved this anomaly? I'm experiencing the same behaviour

**Comment by jerryqzhang** [comment]
Use this image: https://hub.docker.com/r/powerdnsadmin/pda-legacy
```
$ docker run -d \
    -e SECRET_KEY='a-very-secret-key' \
    -v pda-data:/data \
    -p 9191:80 \
    powerdnsadmin/pda-legacy:latest
```

**Comment by brodo97** [comment]
Thank you, searching through the various issues I found the solution. I was in fact using a different image than the official one.
