### ISSUE TITLE
SubFolders for subdomains

### ISSUE THREAD

**Issue by bab5470** [PowerDNS-Admin/PowerDNS-Admin#1669]
### PDA version

0.4.1

### Feature type

New functionality

### Proposed functionality

On other DNS Server UI's I've used subdomains are grouped by folders which makes it much easier to work with large zones with lots of records. 

Here's an example from windows DNS:
![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/8186104/7a4fc7b2-d377-4bf1-9ab8-2caefbafbaa5)

It makes it much easier to organize/see all the records under a subdomain. I find how PowerDNS admin clumps them all together a little difficult to work with with large zones with many records and subdomains. 

### Use case

Makes the application more user freindly. Improves usability. 

### Database changes

Probably not? 

### External dependencies

None?

**Comment by AzorianMatt** [comment]
@bab5470 forgive me for not getting excited about a proposed change to be more like Microsoft-style disasters. The app may get better with usability in the future, but it certainly won't be taking this approach.
