### ISSUE TITLE
Postgresql database setup documentation refers to outdated third-party image

### ISSUE THREAD

**Issue by WestFarmer** [PowerDNS-Admin/PowerDNS-Admin#1671]
### Change Type

Cleanup (formatting, typos, etc.)

### Area

Database Setup

### Proposed Changes

Please update

**Comment by AzorianMatt** [comment]
@WestFarmer the project doesn't have enough resources right now to even cover critical priorities. For that reason, please don't submit a documentation update request that doesn't directly offer help with the solution. It's unproductive.

Thank you for your report.
