### ISSUE TITLE
PowerDNS Admin Losing API Key?

### ISSUE THREAD

**Issue by bab5470** [PowerDNS-Admin/PowerDNS-Admin#1675]
### PDA version

0.4.1

### Python version

3.9

### Steps to Reproduce

1. I've noticed from time to time power-dns admin seems to stop working. To fix it I go to settings -> server and re-enter the API key and it resumes working. But certainly having to do this repeatedly is not normal. 
2. My API key is very long (65 characters long). Is there any limit to the length of the API key. Also are there any restrictions to the characters in the API key. So upper, lower alpha, numeric, are symbols allowed? 

### Expected Behavior

API key shouldn't have to be re-entered

### Observed Behavior

API key has to be re-entered or powerdns-admin can't communicate with powerdns.

**Comment by bab5470** [comment]
It would be nice to know if there is a maximum API key size and what the maximum is but I changed my key and this seems to have stopped happening. For others my key size is ~60 characters long - alpha numeric.

**Comment by bab5470** [comment]
I was too quick to dismiss this. It's still happening. Perodically our key no longer works and we have to re-enter it. 

Its a quick fix but super annoying it keeps happening. 

If the issue is with my API key length I can shorten it but the question is how short do I have to make it. 

I don't want to make it too simple and thus make it easy to crack but I may have err'd towards making it too long.

**Comment by AzorianMatt** [comment]
@bab5470 you will have to do further work to prove and locate the issue. Fortunately, I've never heard of this issue and have never seen it in all the years of running multiple deployments of PDA. If you can locate an actual bug and provide enough details to reproduce, then I would be more than happy to consider addressing it. It's just not common so this is not a priority for the project to potentially hunt a ghost.
