### ISSUE TITLE
Fields aren't readable when editing zone templates

### ISSUE THREAD

**Issue by bab5470** [PowerDNS-Admin/PowerDNS-Admin#1676]
### PDA version

0.4.1

### Python version

3.9

### Steps to Reproduce

When you clock on "zone templates" and then edit a template some of the fields aren't readable. Here's a screenshot demonstrating the issue:

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/8186104/15569cf7-1dfc-4e5f-9e58-44245bb82fab)

### Expected Behavior

Fields should be viewable/readable. Ideally, the data field should be shrunk a bit to make room for the Name, Type, Status, TTL fields 

### Observed Behavior

The fields are smushed together. See screenshot in steps to reproduce.

**Comment by bab5470** [comment]
I've found if you collapse the navigation it helps a little (but they're still unreadable until after you hit save)

**Comment by AzorianMatt** [comment]
@bab5470 we are well aware of the many styling issues the project currently has. It's just not a priority right now.
