### ISSUE TITLE
Ability to set default TTL for record

### ISSUE THREAD

**Issue by bab5470** [PowerDNS-Admin/PowerDNS-Admin#1677]
### PDA version

0.4.1

### Feature type

New functionality

### Proposed functionality

As far as I can tell when you create a new DNS record manually it defaults to the first item in the drop down (60 seconds) unless you change it. It would be nice if in the settings there was a way to specify a default TTL for each record type. Maybe in settings -> zone records have a third column that says default TTL

### Use case

Ensures zone records are setup consistently and allows users to use a more sane default than a TTL of 60 seconds. 

### Database changes

A change would be required to the settings table to track the default TTLs for each record type.  That same field would have to be queried each time the user wanted to generate a new record to know what the default TTL should be set to. 

### External dependencies

None?

**Comment by alm-nl** [comment]
If you set the desired TTL as the first option in the list of ttl_options you get exactly what you require. It's kind of work-around perhaps, but it works.

**Comment by bab5470** [comment]
Awesome!! That does help - thank you so much @alm-nl!
