### ISSUE TITLE
Add change comment feature to produce helpful changelogs

### ISSUE THREAD

**Issue by mpiscaer** [PowerDNS-Admin/PowerDNS-Admin#1681]
### PDA version

0.2.4

### Feature type

New functionality

### Proposed functionality

A remark / commit message when a commit has been done. This way it is possible to log in the changelog why a change has been done.

### Use case

To view in the changelog why changes has been made.

**Comment by bab5470** [comment]
This is a great idea - it would be very helpful in troubleshooting. 

Until that's in place could you use the "comment" field for the record? I know there not exactly the same purpose but maybe a way to work around lack of a commit comment feature.

**Comment by mpiscaer** [comment]
Yes you could use the comment field of the record as workaround. This was one workarounds we discussed internally.

The downside is that you can not delete the record only disable it.

**Comment by AzorianMatt** [comment]
@mpiscaer I appreciate you taking the time to submit this request. However, the project has too many issues and other priorities and I'm unwilling to add to this problem further currently. The project's future is in jeopardy and many in the community are struggling to appreciate that it's past mistakes are becoming incredibly costly to the future of the project.

**Comment by AgentTNT** [comment]
@mpiscaer - Would you like for this to be reconsidered with current efforts of the v0.5.1 release?
