### ISSUE TITLE
Option in settings to set records of secondary(slave) zones to read-only to prevent changes through PowerAdmin

### ISSUE THREAD

**Issue by trooster** [PowerDNS-Admin/PowerDNS-Admin#1682]
### PDA version

0.4.1

### Feature type

New functionality

### Proposed functionality

When a zone is set to slave instead of native or master, I would like to have the option to disable changing the records. In that case the records for this zone should be set to read-only.

### Use case

A use case is where an end user manages their zone through a hidden master, for example, in Plex. In the public nameserver, the zone will be set to slave and receive updates from the hidden master (Plesk).
To prevent accidental changes in the slave through PowerAdmin (because changes should be made in the hidden master), a read-only option would be needed.

### Database changes

One setting field in settings->basic
secondary_zones_readonly: yes/no
Default = no, for backwards compatibility

**Comment by AzorianMatt** [comment]
@trooster I appreciate your efforts to document this request. However, this is not how the product was intended to be used and thus, this approach is not on the road map for support. I realize this wouldn't be a huge change to make, but there are too many other issues and priorities so I don't want to continue adding to the nearly infinite list.
