### ISSUE TITLE
Upgrade issues leading to incompatible schema of `sessions` table

### ISSUE THREAD

**Issue by jacotec** [PowerDNS-Admin/PowerDNS-Admin#1683]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

I've updated my PowerDNS / PowerDNSAdmin installation, PowerDNSAdmin was running a 0.2-version before.

As mentioned here I've changed the old docker image path to

`image: powerdnsadmin/pda-legacy:latest`

did the docker-compose pull and docker-compose up - but unfortunately, I'm getting only HTTP 500 errors after the update. Docker log shows repeated:

```
powerdns_admin | sqlalchemy.exc.DataError: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'session_id' at row 1")
powerdns_admin | [SQL: INSERT INTO sessions (session_id, data, expiry) VALUES (%s, %s, %s)]
powerdns_admin | [parameters: ('session:.eJw9js1qAzEMhN_F50JtWfJPbqXXQB9hkWWJhNJN2PVCS-m716HQ48w3A9-3W2TfbBm3d13dyaEFjrkX6k1SUk6ZuxBXAODGTFYYvWZyT26xTfeLO43t0Jmu_XGPEKJJkgJCHpA1BqyJ ... (29 characters truncated) ... 2CIGjsSIwoDhNzNZh1CkQrNsxDG1hVAe4JKVLRSYIMahWPS9tC66_bBq67jX-3YdfvzC3PAx7hMehUe19u6jK-7TnJ-e305T7rq5zy6Z_fzC2EHVGg.ZS5TbA._HLO8Xpz-zscqEAaDhQwdrIE_m0', b'\x80\x04\x95d\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\n_permanent\x94\x88\x8c\x0b_csrf_token\x94\x8c@2221cda0571382e0cd6af9823515cf7461144d241e9627e22a324761b94961a7\x94u.', datetime.datetime(2023, 10, 17, 10, 53, 19, 218182))]
powerdns_admin | (Background on this error at: http://sqlalche.me/e/13/9h9h)
powerdns_admin |
powerdns_admin | During handling of the above exception, another exception occurred:
powerdns_admin |
powerdns_admin | Traceback (most recent call last):
powerdns_admin |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1541, in finalize_request
powerdns_admin |     response = self.process_response(response)
powerdns_admin |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1888, in process_response
powerdns_admin |     self.session_interface.save_session(self, ctx.session, response)
powerdns_admin |   File "/usr/lib/python3.10/site-packages/flask_session/sessions.py", line 554, in save_session
powerdns_admin |     session_id=store_id).first()
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3429, in first
powerdns_admin |     ret = list(self[0:1])
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
powerdns_admin |     return list(res)
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
powerdns_admin |     return self._execute_and_instances(context)
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
powerdns_admin |     conn = self._get_bind_args(
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
powerdns_admin |     return fn(
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
powerdns_admin |     conn = self.session.connection(**kw)
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1142, in connection
powerdns_admin |     return self._connection_for_bind(
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
powerdns_admin |     return self.transaction._connection_for_bind(
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
powerdns_admin |     self._assert_active()
powerdns_admin |   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
powerdns_admin |     raise sa_exc.InvalidRequestError(
powerdns_admin | sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'session_id' at row 1") 
```

I can't find any solution in the issues or proposed docker upgrade actions in the readme, so snapshotting everything back to the old versions for now until I can get a solution for the issue.

### Expected Behavior

I expect the docker-setup to run ;-)

### Observed Behavior

See the error above

**Comment by jacotec** [comment]
I did a step-by-step update from version to version:

- 0.24 --> 0.25: Fine
- 0.25 --> 0.3: Fine
- 0.3 --> latest: Breaks

So the issue must me introduced in 0.4.1 (latest). As there are no intermediate docker tags between 0.3 and latest, I have no clue how to get around the issue.

I also tried dev, but the issue persists.

**Comment by alm-nl** [comment]
Did you also try with a new database file? As far as I remember the docker container uses a sqllite3 database file and it's stored on the host filesystem. If you rename it, it will recreate it and you'll have to reconfigure the application.
At least, that's what I remember when testing out different versions...

**Comment by AzorianMatt** [comment]
@jacotec @MartinVerges try replacing your database. I believe since you're coming from such an old version, that your database schema is incompatible. This likely wasn't handled gracefully.

**Comment by MartinVerges** [comment]
I had to clean my cookies and stuff to be able to use it again. Something
with the old login session pre upgrade seems to be the issue in my case.

Best regards
Martin Verges

Matt Scott ***@***.***> schrieb am Fr., 24. Nov. 2023, 09:25:

**Comment by AzorianMatt** [comment]
@MartinVerges This isn't surprising because I don't believe sessions were being stored in the database prior to semi-recent releases of PDA. I thought I remember the `sessions` table showing up when we switched to using SQAlchemy as a storage provider for Flask-Session but I may be misremembering.

**Comment by jacotec** [comment]
> Did you also try with a new database file? As far as I remember the docker container uses a sqllite3 database file and it's stored on the host filesystem. If you rename it, it will recreate it and you'll have to reconfigure the application. At least, that's what I remember when testing out different versions...

@alm-nl Sorry to jump back in that late ... back to this project.
I really don't want to reconfigure everything from scratch, that's a nightmare. Is there any way to dump the database and reimport it later?
