### ISSUE TITLE
dns.exception.SyntaxError: Text input is malformed

### ISSUE THREAD

**Issue by HotelMoted** [PowerDNS-Admin/PowerDNS-Admin#1688]
### PDA version

0.4.1

### Python version

3.8

### Steps to Reproduce

Clicking on an ipv6 reverse dns zone, I get a HTTP 500

### Expected Behavior

The webpage to load

### Observed Behavior

Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]: Received zone name:[2023-11-03 16:31:57,323] [app.py:1449] ERROR - Exception on /domain/0.0.0.0.1.0.f.0.0.0.3.4.4.0.1.1.ip6.arpa [GET]
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]: Traceback (most recent call last):
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     response = self.full_dispatch_request()
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     rv = self.handle_user_exception(e)
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     rv = self.dispatch_request()
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     return current_app.ensure_sync(func)(*args, **kwargs)
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/powerdnsadmin/decorators.py", line 75, in decorated_function
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     return f(*args, **kwargs)
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/domain.py", line 100, in domain
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     r_name = dns.reversename.to_address(
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/dns/reversename.py", line 103, in to_address
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     return dns.ipv6.inet_ntoa(dns.ipv6.inet_aton(text))
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:   File "/opt/web/powerdns-admin/flask/lib/python3.8/site-packages/dns/ipv6.py", line 167, in inet_aton
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]:     raise dns.exception.SyntaxError
Nov 03 16:31:57 rdns1.oi.io gunicorn[2543]: dns.exception.SyntaxError: Text input is malformed.

**Comment by AzorianMatt** [comment]
@HotelMoted you did not provide nearly enough information on reproducing this issue. Simply following your one-liner in my installation, everything works fine. Please put in more effort to this report or nothing will be done with it.
