### ISSUE TITLE
Support Path in Docker Health Check

### ISSUE THREAD

**Issue by ashneilson** [PowerDNS-Admin/PowerDNS-Admin#1690]
### PDA version

0.4.1

### Feature type

Change to existing functionality

### Proposed functionality

We're running PowerDNS Admin (Docker) behind HA Proxy and for our particular use-case, we make PowerDNS Admin accessible via a path `/powerdns`

In order to make this work correctly, we set the Flask Environment Variable `SCRIPT_NAME`

It would be fantastic if we could change the following `HEALTHCHECK` line in the Dockerfile to support this use case.

https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/8108caf96a03fb87e9a42ae85d4dc1000822f1a3/docker/Dockerfile#L95

Proposed solution
```Dockerfile
HEALTHCHECK CMD ["wget","--output-document=-","--quiet","--tries=1","http://127.0.0.1${SCRIPT_NAME:-/}"]
```

### Use case

This would enable other users to specify the Flask `SCRIPT_NAME` Environment Variable, serve PowerDNS Admin under a path of their chosing and avoid Health Checks failing when deploying as a Docker Container.

**Comment by AzorianMatt** [comment]
@ashneilson This is a reasonable and simple enough request. However, after implementing it and testing it locally, it is not a working solution for reasons I haven't not been able to determine. It may work to solve your particular issue, but it is however failing a default deployment that uses the root path.

If you want to put in the time to work out that problem, I would be happy to give it another go to get this into the next release.

Thanks!

**Comment by AzorianMatt** [comment]
@ashneilson The time is nearing very soon for me to make the final release of this edition of PDA. If you would like to see this make it in, I urge you to provide the additional feedback. Thanks!

**Comment by ashneilson** [comment]
Apologies @AzorianMatt for not responding sooner!

I'll make sure I have a PR submitted by the 15th December if that's suitable?

**Comment by AzorianMatt** [comment]
@ashneilson No worries! I just want to make sure you get your opportunity to slip this in there. That date is fine. Thanks for following up!

**Comment by ashneilson** [comment]
Thanks @AzorianMatt.

I noticed you already had a branch open for this - should I still submit a PR myself?

Otherwise the following is tested and working as expected. I believe the problem was the Environment Variable not being handled correctly inside the string:

```Dockerfile
HEALTHCHECK CMD wget --output-document=- --quiet --tries=1 http://127.0.0.1${SCRIPT_NAME:-/}
```

**Comment by AzorianMatt** [comment]
@ashneilson thank you for following up on this. I have tested the latest suggestion and it appears to be good.

I have merged this into the `dev` branch and it will be available in the next and final release of `pda-legacy`.
