### ISSUE TITLE
LDAP Authentication proposed change

### ISSUE THREAD

**Issue by hmmmfctunlpt** [PowerDNS-Admin/PowerDNS-Admin#1697]
### PDA version

0.4.1

### Feature type

Change to existing functionality

### Proposed functionality

LDAP Authentication should not need elevated LDAP access. As a matter of fact, user authentication should not need LDAP credentials at all. User credential verification through LDAP should be done using LDAP Bind using the authenticating user credentials.
In the event there is a need for LDAP authentication for reading user and group attributes, one should be able to specify an LDAP user, with read access for the required attributes and no more. Instead of "LDAP admin username" and "LDAP admin password" there sould be "LDAP username" and "LDAP password" containing the LDAP user creds with the required read access. In the event that one doesn't need authenticated access for attribute reading, one should be able to leave these fields blank and initial LDAP binding would be done anonymously.

### Use case

This proposed change would benefit from elevated LDAP user access credentials being stored on PDA. That would also prevent possible PDA bugs allowing unwanted accidental/malicious LDAP changes wich could greatly impact and infrastructure where LDAP is used as SSO backend.

**Comment by AzorianMatt** [comment]
@hmmmfctunlpt you have done an excellent job at writing up this request by properly elaborating of the key driving factors for the request. For that reason, I have flagged this as accepted. However, with no resources and an extensive list of problems and challenges on the project, I can not give you any expectation of delivery on this, or if it will ever be delivered for that matter.

Thank you for your effort on this, I will keep this is mind if the day comes to rebuild a latest list of feature requests and updates.
