### ISSUE TITLE
Provide access control at the record level

### ISSUE THREAD

**Issue by lovelord83** [PowerDNS-Admin/PowerDNS-Admin#1699]
### PDA version

0.4.1

### Feature type

Change to existing functionality

### Proposed functionality

It could be nice to create a permission user/account based to limit user/account to be able to modify specific record types, but not all. 

### Use case

Actually, if a user is allowed to modify records for a zone, can change everything but I don't want, for instance, to let them modify NS records.

**Comment by AzorianMatt** [comment]
@lovelord83 Thank you for your request. While this particular topic has already been discussed, the current project faces too many other issues for this to be considered anytime soon. It has already been planned for the `pda-next` project, but I don't know where that is truly going at this point.
