### ISSUE TITLE
Bug: Docker Health Check Filling Sessions Table

### ISSUE THREAD

**Issue by AzorianMatt** [PowerDNS-Admin/PowerDNS-Admin#1750]
Version: `0.4.0`, `0.4.1`, `0.4.2`

Problem:

The Docker health check calls the application in such a way that a new session is created with each check. This is quite problematic as it leads to a very large sessions table unnecessarily.

Solution:

I'm going to look at implementing a specific health check sub-path in the application that will immediately expire the session. Additionally, I am going to fix the non-functioning session reaper and add it's execution to the `@domain_bp.before_request` trigger of each router, as it's only currently triggered on the `user` router.

**Comment by AzorianMatt** [comment]
Resolved by #1751

**Comment by osos** [comment]
When is this fix planned to be released? We using the docker images.

The sessions table fills up very quickly. Thus, this is an important fix.

**Comment by DaanSelen** [comment]
If its only the healthcheck, I can make a healthcheck that checks the process. Let me check.

**Comment by DaanSelen** [comment]
It should already be in the latest code... from a year ago, is it still running on old code?

**Comment by greenaar** [comment]
@DaanSelen no - 3 second sample.

```
mysql> select count(*) from sessions;
+----------+
| count(*) |
+----------+
|    39995 |
+----------+
1 row in set (0.01 sec)

mysql> select count(*) from sessions;
+----------+
| count(*) |
+----------+
|    40000 |
+----------+
1 row in set (0.02 sec)
```

Looks like it merged into dev, but didn't make it into master, and isn't in the last built image.

This did give me the impetus to disable the healthcheck, as well as ensuring I wasn't querying the login page anywhere else.  Every hit to the login page generates a session id (it looks like) so even status pages were incrementing that table.

**Comment by DaanSelen** [comment]
If you are open for it, I can maintain a fork for the image.

**Comment by osos** [comment]
I would prefer to use the official docker image or a workaround, e.g. in docker-compose.yml overwriting the health check.

The fix is in 0.4.3 which is not released.

Why not just release version 0.4.3 which should contain the update? The remaining PR on milestone 0.4.3 seems to already be asking to merge into the 0.5.0-dev branch and *not* 0.4.3, thus I presume it is a legacy on the milestone.

**Comment by That-Guy-Jack** [comment]
Just come across this as i have a similar issue, My sessions table is just over 4.1gb for some reason, seems to go up even without anything accessing it

running `powerdnsadmin/pda-legacy:latest`

<img width="178" alt="Image" src="https://github.com/user-attachments/assets/31d04604-3f88-42c6-bfb2-512a85e2d7ae" />


<img width="362" alt="Image" src="https://github.com/user-attachments/assets/ef39ed13-210b-4aec-b7ef-174e718d745c" />

**Comment by greenaar** [comment]
> Just come across this as i have a similar issue, My sessions table is just over 4.1gb for some reason, seems to go up even without anything accessing it
> 

@That-Guy-Jack I ended up overriding the healthcheck and truncating the sessions table.

```
    healthcheck:
      disable: true
```

Not a perfect solution, but an ok stop-gap.
