### ISSUE TITLE
Correct SAML Scope Documentation

### ISSUE THREAD

**Issue by C0mmanderCrud** [PowerDNS-Admin/PowerDNS-Admin#1763]
In the docs/oauth.md file the scope said in the documentation lists _mail_ as the category alongside _User.Read openid profile_
when setting the scope this must be _email_ other wise you will get a error when it is forwarded to EntraID. This caused me and a few members of my organization a bit of head scratching but can be solved with a simple letter added to the documentation.
With the scope set as the documentation provides 

It gives the following error in the url _User.Read mail openid profile_
The+application+%27Cyber-PowerDNS-TEST%27+asked+for+scope+%27_**mail**_%27+that+doesn%27t+exist+on+the+resource+

Changing the scope to url _User.Read email openid profile_ Resolves the issue
![Scope-Screenshot](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/49397424/d02fa46f-989d-428f-a687-943ee11bfce9)
![ErrorScreenshot](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/49397424/e3a2ab8f-b0ba-4530-8434-419f036730ba)
![ScopeFixedScreenshot](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/49397424/ded15b27-f080-4f46-83dc-1b8a818d4027)

**Comment by AzorianMatt** [comment]
@C0mmanderCrud perhaps there's a misunderstanding with the contribution guidelines here. You can't just create an issue and then a follow-up PR with zero interaction from the maintainers. Furthermore, your PR contains boilerplate without the actual issue reference attached. Additionally, the PR is against the master branch and not the dev branch. Finally, this project has been put on a freeze.

So if you would really like to see this simple change added, please make the necessary changes and I will push it through.

**Comment by C0mmanderCrud** [comment]
@AzorianMatt  Sorry for the incorrect submission i have just been over to the dev branch and it seems you have already corrected this in Documentation Fix: Azure Authentication Scope Setting #1745. This issue can be closed as you have already made the same commit i was trying to make.
Thanks a lot for taking the time to message back what i had done wrong not just a blanket close. 
Thanks for all the work you do with this project.
Looking forward to the new release.
C0mmanderCrud

**Comment by AzorianMatt** [comment]
@C0mmanderCrud apology accepted and apologies all the same if I come across a bit harsh. If you can imagine, this is a repeating pattern of sorts that never ends.

With that being said, I'm glad you caught that PR as well. I had forgotten about it at this point. I don't believe I deserve many kudos as I could be doing a lot better, but I'm facing my own struggles right now.

Nevertheless, the sentiment is greatly appreciated!
