### ISSUE TITLE
Azure OAuth Authentication Issues in v 0.4.2

### ISSUE THREAD

**Issue by reckart-everstream** [PowerDNS-Admin/PowerDNS-Admin#1770]
I seam to be experiencing some Azure AD auth issues when setting things up, I've tried opening up the firewall and keeping it locked down to just Azure inbound data centers. Nothings seams to help.
Below is the error trace:
File "/opt/web/powerdns-admin/venv/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
Apr 24 19:26:48 ns1 gunicorn[52881]:     response = self.full_dispatch_request()
Apr 24 19:26:48 ns1 gunicorn[52881]:   File "/opt/web/powerdns-admin/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
Apr 24 19:26:48 ns1 gunicorn[52881]:     rv = self.handle_user_exception(e)
Apr 24 19:26:48 ns1 gunicorn[52881]:   File "/opt/web/powerdns-admin/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
Apr 24 19:26:48 ns1 gunicorn[52881]:     rv = self.dispatch_request()
Apr 24 19:26:48 ns1 gunicorn[52881]:   File "/opt/web/powerdns-admin/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
Apr 24 19:26:48 ns1 gunicorn[52881]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Apr 24 19:26:48 ns1 gunicorn[52881]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/index.py", line 237, in login
Apr 24 19:26:48 ns1 gunicorn[52881]:     azure_username = user_data["userPrincipalName"]
Apr 24 19:26:48 ns1 gunicorn[52881]: KeyError: 'userPrincipalName'

**Comment by reckart-everstream** [comment]
After configuration of Azure AD, attempting to navigate the UI brings up a HTTP 500 Error after successfully authenticating to the Azure AD tenant.
![Screenshot 2024-04-24 at 4 03 40 PM](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/100418910/ecb1d737-4c74-4310-9e94-85491989f5c3)

**Comment by reckart-everstream** [comment]
![Screenshot 2024-04-24 at 4 05 35 PM](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/100418910/3743a5b9-3b58-48ca-95dd-70ae1c47a4f0)

**Comment by akito2001** [comment]
Im having the same issue.  Azure auth is setup correctly as far as I can tell and it generates an account for the user but they get the 500 error every time they attempt to login
