### ISSUE TITLE
Multiple installations using same PDNS back-end?

### ISSUE THREAD

**Issue by aloonj** [PowerDNS-Admin/PowerDNS-Admin#193]
Would it be possible to have multiple PowerDNS-Admin installations and configure one in such a way to totally disable Admin console with restricted feature public facing access?

Public facing: Users can log in and edit records for their own assigned domains only.
Private facing: Admins can login (LDAP etc.) to administrate the system, add new domains, add/edit other users.

Thanks,

A

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later (there are roles for such needs now).

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
