### ISSUE TITLE
Request to queue notification for domain '1.1.1.in-addr.arpa' was processed, but no valid nameservers or ALSO-NOTIFYs found. Not notifying!

### ISSUE THREAD

**Issue by ErrorSnaKe** [PowerDNS-Admin/PowerDNS-Admin#258]
Hello,

I create new template with correct SOA and NS record and everything are ok when I create a new domain.

Also when I create new ptr domain like 1.1.1.in-addr.arpa and use same template as above also everything good.

But when I set auto_ptr to true, ptr domain created only with "a.misconfigured.powerdns.server" or with value what I set in default-soa-name=

Its possible to use same template during auto create ptr?

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to clean up this project, we are closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
