### ISSUE TITLE
Restict user access by IP address

### ISSUE THREAD

**Issue by tmuncks** [PowerDNS-Admin/PowerDNS-Admin#279]
Add an option to restrict user access by IP address, subnet list etc.

This could help increase security and pave the way for something that would fix #210 as well.

**Comment by ngoduykhanh** [comment]
Actually they are 2 difference features. #210 just requests for the ip address in the log so Fail2ban can parse and ban user's ip address automatically, no manual work. :).

**Comment by p53** [comment]
i don't think restricting access by IP should be in app responsibility...

**Comment by tmuncks** [comment]
For a larger setup it's a confidence factor, that I know my account can only be used to access my account and my domains, from my own office IP or some such. This type of thing can ONLY be handled by the app.

**Comment by tmuncks** [comment]
This would still be a super useful feature to me and our customers, as an added security measure. The fail2ban thing would help too, but would not help preventing unauthorized access when a user has been laid off etc. Users are routinely blocked from accessing company network through AD, but often not as quickly to services such as PDA. Requiring the company's public IP to access PDA serves as a quick fix to this problem and others.

**Comment by tmuncks** [comment]
Also, it cannot be solved elsewhere - For this to work, it must be implemented in the application.

**Comment by zoeller-freinet** [comment]
I don't think blocking HTTP requests based on their source IP address should be in the scope of PowerDNS-Admin, please use a reverse proxy server or firewall for that. For making sure that nobody except you can access your PowerDNS-Admin user account, please follow general password security recommendations and consider using 2FA.

**Comment by tmuncks** [comment]
This is a bit hard to implement in firewall or reverse proxy when hosting DNS for a bunch of users

**Comment by zoeller-freinet** [comment]
> This is a bit hard to implement in firewall or reverse proxy when hosting DNS for a bunch of users

It should not be hard to use e.g. fail2ban to automatically update your firewall rules in that case.

**Comment by tmuncks** [comment]
Correct, but that doesn't help with regulatory stuff such as "this domain can only legally be managed from these 5 IP addresses"... Or from a specific country or something of that nature.

**Comment by zoeller-freinet** [comment]
> Correct, but that doesn't help with regulatory stuff such as "this domain can only legally be managed from these 5 IP addresses"... Or from a specific country or something of that nature.

I'd argue that something like this shouldn't be implemented by black-/whitelisting IP addresses/ranges in PowerDNS-Admin. A more general mechanism, for example an optional user-definable callback function that hooks into access permissions to e.g. domains, should be more flexible and also easier to maintain if done right.

What do you think? I'll give it some thought - feel free to open an issue or PR for such a feature.
