### ISSUE TITLE
soa mname or rname does not end with a period

### ISSUE THREAD

**Issue by Edwin-Hoff** [PowerDNS-Admin/PowerDNS-Admin#318]
If I create a new domain the soa MNAME or RNAME does not end with a period. Also if I update the SOA and add a period it ends up without a period in the powerdns database.

My powerdns and powerdns-admin are up-to-date.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
