### ISSUE TITLE
Authentication to AD gives bad filter error - Bug in the code(?)

### ISSUE THREAD

**Issue by ptselios-inmarsat** [PowerDNS-Admin/PowerDNS-Admin#344]
Hello, 
I need to authenticate my users against the AD of the company. We have created a specific AD Group for them. 
The configuration I have is: 
```
LDAP_ENABLED = True
# with LDAP_BIND_TYPE you can specify 'direct' or 'search' to use user credentials
# for binding or a predefined LDAP_USERNAME and LDAP_PASSWORD, binding with non-DN only works with AD
LDAP_BIND_TYPE= 'direct' # direct or search
LDAP_GROUP_SECURITY = False
LDAP_TYPE = 'ad'
LDAP_URI = 'ldaps://ldaps.domain.local:636'
LDAP_SEARCH_BASE = 'dc=domain,dc=local'
## You may prefer 'userPrincipalName' instead
LDAP_USERNAMEFIELD = 'sAMAccountName'
## AD Group that you would like to have accesss to web app
#LDAP_FILTER = 'memberof=CN=PDNSAdmin,OU=PowerDNS,OU=Group,OU=DS,DC=domain,DC=local'
LDAP_FILTER = ''
```
Now the problems.
When I set anything in the LDAP_FILTER, I get an error:`

` {'desc': 'Bad search filter'}`

If I keep the LDAP_FILTER empty, users can login and they are created in the local DB BUT:
1. I give access to ALL AD users in the app (not acceptable)
2. Users are not admins!

I searched in the code (models.py) and found this:
```

           # user already exists in database, set their admin status based on group membership (if enabled)
            if LDAP_GROUP_SECURITY:
                self.set_admin(isadmin)
            self.update_profile()
            return True
```
Now, I am lost. My understanding of the LDAP_SECURITY is that **all** users will be admins if I don't use this variable, not the other way around. In my opinion, if you don't apply group "policy", then all users should be admins. 

Now to the point: 
The first problem is the user filter. 
Looking at the code the search is constructed as:  
```
AD searchFilter:
"(&(objectcategory=person)(sAMAccountName=Username)memberof=CN=PDNSAdmin,OU=PowerDNS,OU=Group,OU=DS,DC=domain,DC=local)"
```
It is obvious that the search is wrong!  
So, I went into the code (models.py) and changed this:
`searchFilter = "(&(objectcategory=person)({0}={1}){2})".format(LDAP_USERNAMEFIELD, self.username, LDAP_FILTER)
`
to this:
`searchFilter = "(&(objectcategory=person)({0}={1})({2}))".format(LDAP_USERNAMEFIELD, self.username, LDAP_FILTER)`

Checking the code it looks like the AD authentication is completely changed in the last couple of months, so I don't dare to update the software.

The second issue is with the admin users. In our AD, users belong to a number of different groups in different OUs etc. So, it's not easy to select one specific group. So, I have the admin group set but the users group is just ''. 
This results to an exception error. The problem is in the code. 
Specifically, the code is: 
(Line 253 in my version): 

```
                   try:
                        if LDAP_TYPE == 'ldap':
                            ldap_user_dn = ldap.filter.escape_filter_chars(result[0][0][0])
                            logging.info(result[0][0][0])
                        if (self.ldap_search('(member={0})'.format(ldap_user_dn) ,LDAP_ADMIN_GROUP)):
                            allowedlogin = True
                            isadmin = True
                            logging.info('User {0} is part of the "{1}" group that allows admin access to PowerDNS-Admin'.format(self.username,LDAP_ADMIN_GROUP))
                        if (self.ldap_search('(member={0})'.format(ldap_user_dn) ,LDAP_USER_GROUP)):
                            #if (group == LDAP_USER_GROUP):
                            allowedlogin = True
                            logging.info('User {0} is part of the "{1}" group that allows user access to PowerDNS-Admin'.format(self.username,LDAP_USER_GROUP))
                        if allowedlogin == False:
                            logging.error('User {0} is not part of the "{1}" or "{2}" groups that allow access to PowerDNS-Admin'.format(self.username,LDAP_ADMIN_GROUP,LDAP_USER_GROUP))
                            return False
                    except Exception as e:
                        logging.error('LDAP group lookup for user "{0}" has failed. Authentication request from {1}'.format(self.username, src_ip))

```
As you can clearly see, this works only for LDAP, no AD. Also, there is a single exception for 3 "if". 
Also, using the logging.debug does not write the actual error in the logs (in which case was that the variable ldap_user_dn was used before defined.
That led me to the slight change in code:
From 
`if LDAP_TYPE == 'ldap'`
to:
`if LDAP_TYPE == 'ldap' or LDAP_TYPE == 'ad':`

**Comment by ngoduykhanh** [comment]
Have you tried it, how is the result?

**Comment by ptselios-inmarsat** [comment]
Well yes, although I haven't tried the newer version and I have no idea if it works well or not.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
