### ISSUE TITLE
Update the documentation to reflect an installation procedure that actually works

### ISSUE THREAD

**Issue by vogelfreiheit** [PowerDNS-Admin/PowerDNS-Admin#359]
The documentation at the moment is completely out of sync, in some cases referring to no longer existing files (ex. in the Fedora case). Right now, following the steps for Ubuntu results in a non working installation process.

There are multiple issues reflecting this, yet no changes whatsoever have been made to the documentation.

```
(flask) powerdnsadmin@lab-miscweb:~/powerdns-admin$ rm pdns.db
(flask) powerdnsadmin@lab-miscweb:~/powerdns-admin$ flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
INFO  [alembic.runtime.migration] Running upgrade 59729e468045 -> 1274ed462010, Change setting.value data type
Traceback (most recent call last):
  File "/home/powerdnsadmin/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/powerdnsadmin/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "ALTER": syntax error

The above exception was the direct cause of the following exception:
....
thon3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ALTER": syntax error [SQL: 'ALTER TABLE setting ALTER COLUMN value TYPE TEXT'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

The Fedora guide also references a "create_db.py" file that does not exist. I'm only giving this a go because LDAP as used by Opera's PowerDNS UI, is a PITA to maintain and configure properly, and overkill for this purpose, but at this point, it would have taken about the same time it took to figure out where the current repo of PDNSA is broken.

**Comment by ngoduykhanh** [comment]
Hi, The guide for Fedora is out-date. Please refer to CentOS guide instead.
Currently the migration only works for MySQL and PostgreSQL. The ALTER query doesn't work for SQLite. However SQLite is good for the development environment so i am going to improve the flask migration scripts with batch mode to work with SQLite.

**Comment by ptselios-inmarsat** [comment]
Generally speaking, following just one document doesn't work. 
You need the combination of 2-3 documents to make it happen. Also, in the majority of the RHEL related documents, the SELinux is not even considered, which is a big issue. 

I have promised a detailed document for CentOS 7 + Apache + SELinux but I haven't got the time to write it yet.

**Comment by Ramalama2** [comment]
I can do one with nginx/centos7/selinux and python 3.6 if you want...
Selinux is really simple... you can debug the rights if you got some permission problems...
Sry cant call it better in english...

Cheers :-)

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it.

PS: The doc has changed since, if you encounter any difficulty to install the software, lets us know in a new issue.

Regards
PowerDNS Admin Team
See #1153 for the policy
