### ISSUE TITLE
Records are treated as case sensitive in PowerDNS-admin

### ISSUE THREAD

**Issue by W9CR** [PowerDNS-Admin/PowerDNS-Admin#365]
We have a domain, AllStarLink.org in the domains table, and the records are a mix of host.allstarlink.org and host.AllStarLink.org.  

When you go in to edit a domain, if the domain part is no stored in the database record as matching the case of the domain record, PowerDNS-Admin will not reconzise the host portion, and save it as host.allstarlink.org.allstarlink.org in the database.  pdnsutil edit-zone doesn't care about case and DNS is case insensitive.  This is a fairly major bug in PowerDNS-Admin as it caused the entire zone to be rewritten and we had to revert by scripting.

I've attached an example screen shot showing this in the domain edit page.
![screen shot 2018-09-22 at 1 23 51 am](https://user-images.githubusercontent.com/33268238/45913720-47e3e900-be06-11e8-8aa2-6d3909d87767.png)

**Comment by rkerr** [comment]
Finding it a bit hard to understand what it is you're trying to do that gets you to this point? PowerDNS-Admin won't let you create mixed case domains, so I guess the database is pre-existing and created with another tool? And you are then trying to add a new record? or edit an existing record? and apply changes corrupts the record you added/changed? or all records?

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to clean up this project, we're closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
