### ISSUE TITLE
LDAP search bind since v0.1

### ISSUE THREAD

**Issue by tbe** [PowerDNS-Admin/PowerDNS-Admin#372]
Hi, 

we used PowerDNS-Admin for a while now. Since release v0.1 there seems to be no support for LDAP "search" bind.

The configuration in `config.py` is getting ignored, and there is no way in the webinterface to add an LDAP server without credentials.

Our LDAP uses anonymous bind for systems and does not need or have an login for systems that make use of LDAP for authentication.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
