### ISSUE TITLE
Allow memberOf attribute on OpenLDAP

### ISSUE THREAD

**Issue by tbe** [PowerDNS-Admin/PowerDNS-Admin#373]
Currently, the memberOf attribute is only used on AD.

OpenLDAP has also support for this attribute.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we're closing it. Feel free to open a new issue later.

Also, note that there is a filter field in the latest versions that allow you to write any LDAP filter, including memberOf.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
