### ISSUE TITLE
DynDNS 2 not working when using subdomain root

### ISSUE THREAD

**Issue by jaapjolman** [PowerDNS-Admin/PowerDNS-Admin#381]
Hey,

i run into and issue when i have a client network i ussually make a new zone like clientsname.locations.example.com

these has records like
@ SOA ns-01.example.com. support.example.com. 2018100506 3600 600 604800 3600
@ NS ns-01.example.com.
@ NS ns-02.example.com. 
@ NS ns-03.example.com.
@ NS ns-04.example.com.
@ A 1.1.1.1
rtr-01 A 192.168.1.1
sw-01 A 192.168.1.2
ap-01 A 192.168.1.3

etc

now when it tried to update this A record is actually tried to change the first record which is the SOA

DynDNS update: updated record clientsname.locations.example.com in zone clientsname.locations.example.com, it changed from ns-01.example.com. support.example.com. 2018100506 3600 600 604800 3600 to 1.1.1.2

how can i fix it without having to redo like 500+ records into one huge zone file?

**Comment by jaapjolman** [comment]
it litterally takes the first record not even checking if its even a A type

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
