### ISSUE TITLE
Domain templating not working (was: better clarification of domain templates)

### ISSUE THREAD

**Issue by johnnybubonic** [PowerDNS-Admin/PowerDNS-Admin#384]
are these intended to be actually templatable? e.g. in poweradmin, one could do:

sub.[ZONE]

for a name, and it'd populate in the DB as "sub.domain1.tld", "sub.domain2.tld", etc. for each of the domains associated to the template.

is that sort of substitution supported with PowerDNS-Admin as well? because i'm not seeing any documentation indicating so, and even looking through the code i don't see an indication as such.

if not, please support it. should be pretty easy with a .format() in the backend, at the very least.

**Comment by tmuncks** [comment]
If I understand your question correctly, just add `sub` as a record and it will do exactly that. Or perhaps I misunderstand?

**Comment by johnnybubonic** [comment]
yes, sorry - it is useful to actually specify where the substitution should take place in the record or content - for instance, in SOA records (MNAME and RNAME, specifically) and MX records - not to mention things like SRV records; any record that would self-reference.

to expound upon this in detail, let us suppose we have two zones, **foo.tld** and **bar.tld**.

i want to be able to specify records such as:

```
{ZONE}.	414	IN	SOA	ns1.{ZONE}. dnsadmin.{ZONE}. 2018101600 7200 7200 2419200 86400
{ZONE}.	3600	IN	MX	0 mail.{ZONE}.
_xmpp-server._tcp.{ZONE}. 3600 IN SRV	10 0 5269 xmpp.{ZONE}.
```

this would then render to:

- SOA records **foo.tld.	414	IN	SOA	ns1.foo.tld. dnsadmin.foo.tld. 2018101600 7200 7200 2419200 86400** and **bar.tld.	414	IN	SOA	ns1.bar.tld. dnsadmin.bar.tld. 2018101600 7200 7200 2419200 86400**
- MX records **foo.tld.	3600	IN	MX	0 mail.foo.tld.** and **bar.tld.	3600	IN	MX	0 mail.bar.tld.**
- **_xmpp-server._tcp.foo.tld. 3600 IN SRV	10 0 5269 xmpp.foo.tld.** and **_xmpp-server._tcp.bar.tld. 3600 IN SRV	10 0 5269 xmpp.bar.tld.**

does this make sense? in this way, the records generated by [Poweradmin](https://github.com/poweradmin/poweradmin) had the advantage of being much more flexible, supporting arbitrary string position and even templated content. their templates allowed one to use the following:
```

[ZONE] - substituted with current zone name
[SERIAL] - substituted with current date and 2 numbers (YYYYMMDD + 00)
```

does this make sense?

**Comment by tmuncks** [comment]
Yes - Now it makes perfect sense! Unfortunately I don't believe that kind of thing is supported at this time, but I agree it would be pretty awesome.

**Comment by johnnybubonic** [comment]
i see. well, hopefully at some point in the future i'll be able to use this feature and perhaps even submit a suggested patch to implement it - but for right now, i'm in the middle of a nameserver upgrade/transfer so i'll need to script around the lack of support for this. thanks anyways!

**Comment by johnnybubonic** [comment]
actually, doing some more testing, it turns out that domain templating does not seem to work at all (using commit 4540d9a2936e4683a988b1b1ba427e107d5095ab).

i've tried creating new domains from a template but the records in the template never populate, ever.

i've confirmed that they do in fact write to the DB.

i'd recommend an approach where one can perform the above inline/arbitrary substitutions in both name and content/data fields, and also supporting applying a template to an existing domain (rather than only applying one at creation).

**Comment by tmuncks** [comment]
Templates seem to work here (I use the feature in production once in a while), so there's a chance what you're seeing is a local issue or simply a misalignment between expectations and how this is currently implemented, which is totally valid.

Could you share a step-by-step guide to reproduce the problem you're experiencing? That would go a long way to actually getting it fixed.

**Comment by johnnybubonic** [comment]
interesting...

yeah. here's my setup. note that all services are running on the same host and use the local address, so it shouldn't be networking issues. (obviously, the below configs have been slightly scrubbed and stripped of comments/empty lines)

```
[root@sauron ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
```

```
[root@sauron ~]# rpm -qa | grep pdns
pdns-3.4.11-4.el7.x86_64
pdns-backend-mysql-3.4.11-4.el7.x86_64
pdns-backend-ldap-3.4.11-4.el7.x86_64
pdns-backend-remote-3.4.11-4.el7.x86_64
pdns-backend-sqlite-3.4.11-4.el7.x86_64
```

```
[root@sauron ~]# rpm -qa | grep mariadb
mariadb101u-config-10.1.35-1.ius.centos7.x86_64
mariadb101u-errmsg-10.1.35-1.ius.centos7.x86_64
mariadb101u-common-10.1.35-1.ius.centos7.x86_64
mariadb101u-10.1.35-1.ius.centos7.x86_64
mariadb101u-server-10.1.35-1.ius.centos7.x86_64
mariadb101u-server-utils-10.1.35-1.ius.centos7.x86_64
mariadb101u-libs-10.1.35-1.ius.centos7.x86_64
mariadb101u-devel-10.1.35-1.ius.centos7.x86_64
```

```
[root@sauron ~]# rpm -qa | egrep -E '(uwsgi|python36)'
python36u-3.6.5-1.ius.centos7.x86_64
python36u-lxml-4.2.0-1.ius.centos7.x86_64
python36u-libs-3.6.5-1.ius.centos7.x86_64
python36u-setuptools-39.0.1-1.ius.centos7.noarch
python36u-tools-3.6.5-1.ius.centos7.x86_64
python36u-pip-9.0.1-1.ius.centos7.noarch
uwsgi-2.0.17.1-1.el7.x86_64
uwsgi-plugin-python36u-2.0.17.1-1.ius.centos7.x86_64
uwsgi-plugin-common-2.0.17.1-1.el7.x86_64
python36u-tkinter-3.6.5-1.ius.centos7.x86_64
python36u-devel-3.6.5-1.ius.centos7.x86_64
```

```
[root@sauron ~]# rpm -qa | grep nginx
nginx-mod-http-perl-1.12.2-2.el7.x86_64
nginx-all-modules-1.12.2-2.el7.noarch
php72u-fpm-nginx-7.2.10-1.ius.centos7.noarch
nginx-mod-http-geoip-1.12.2-2.el7.x86_64
nginx-mod-stream-1.12.2-2.el7.x86_64
nginx-mod-mail-1.12.2-2.el7.x86_64
nginx-mod-http-image-filter-1.12.2-2.el7.x86_64
python2-certbot-nginx-0.27.1-1.el7.noarch
nginx-filesystem-1.12.2-2.el7.noarch
nginx-mod-http-xslt-filter-1.12.2-2.el7.x86_64
nginx-1.12.2-2.el7.x86_64
```

```
[root@sauron ~]# cat /etc/uwsgi.ini 
[uwsgi]
uid = uwsgi
gid = uwsgi
pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
stats = /run/uwsgi/stats.sock
chmod-socket = 660
emperor-tyrant = true
cap = setgid,setuid
vacuum
```

```
[root@sauron ~]# cat /etc/uwsgi.d/pdnsadmin.ini 
[uwsgi]
plugins = python36u
chdir = /var/lib/uwsgi/pdnsadmin
pythonpath = /var/lib/uwsgi/pdnsadmin
virtualenv = /var/lib/uwsgi/pdnsadmin/flask
mount = /pdns=run.py
manage-script-name = true
callable = app
harakiri = 20
buffer-size = 32768
post-buffering = 8192
socket = /run/uwsgi/%n.socket
chmod-socket = 660
pidfile = /run/uwsgi/%n.pid
daemonize = /var/log/uwsgi/app/%n.log
```

```
[root@sauron ~]# cat /etc/nginx/conf.d/main.conf
server {
listen [::]:80 ipv6only=off default_server;
listen [::]:443 ssl http2 ipv6only=off default_server;
server_name [SCRUBBED];
access_log /var/log/nginx/vhost/pdns/access.log main;
error_log /var/log/nginx/vhost/pdns/error.log;
include /etc/nginx/includes/tls.inc;
include /etc/nginx/includes/LE.inc;
error_page 403 $scheme://[SCRUBBED];
location /pdns/static {
alias /var/lib/pdns/pdnsadmin/app/static/;
}
location / {
try_files $uri @pdns_admin;
}
location @pdns_admin {
include uwsgi_params;
uwsgi_pass unix:/run/uwsgi/pdnsadmin.socket;
}
}
```

```
[root@sauron ~]# cat /etc/pdns/pdns.conf
setuid=pdns
setgid=pdns
experimental-api-key=[SCRUBBED]
experimental-dnsupdate=yes
experimental-json-interface=yes
launch=gmysql
webserver=yes
gmysql-host=localhost
gmysql-user=[SCRUBBED]
gmysql-password=[SCRUBBED]
gmysql-dbname=[SCRUBBED]
```

```
[root@sauron ~]# cat /var/lib/uwsgi/pdnsadmin/config.py
import os
basedir = os.path.abspath(os.path.dirname(__file__))
WTF_CSRF_ENABLED = True
SECRET_KEY = '[SCRUBBED]'
BIND_ADDRESS = '0.0.0.0'
PORT = 9191
TIMEOUT = 10
LOG_LEVEL = 'DEBUG'
LOG_FILE = 'logfile.log'
UPLOAD_DIR = os.path.join(basedir, 'upload')
SQLA_DB_USER = 'pdns'
SQLA_DB_PASSWORD = '[SCRUBBED]'
SQLA_DB_HOST = 'localhost'
SQLA_DB_NAME = '[SCRUBBED]'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_DATABASE_URI = 'mysql://'+SQLA_DB_USER+':'+SQLA_DB_PASSWORD+'@'+SQLA_DB_HOST+'/'+SQLA_DB_NAME
SAML_ENABLED = False
SAML_DEBUG = True
SAML_PATH = os.path.join(os.path.dirname(__file__), 'saml')
SAML_METADATA_URL = 'https://<hostname>/FederationMetadata/2007-06/FederationMetadata.xml'
SAML_METADATA_CACHE_LIFETIME = 1
SAML_ATTRIBUTE_ACCOUNT = 'https://example.edu/pdns-account'
SAML_SP_ENTITY_ID = 'http://<SAML SP Entity ID>'
SAML_SP_CONTACT_NAME = '<contact name>'
SAML_SP_CONTACT_MAIL = '<contact mail>'
SAML_SIGN_REQUEST = False
SAML_LOGOUT = False
```

**Comment by tmuncks** [comment]
Cool - I was thinking more along the lines of what you are trying to do and the steps you take to achieve it, with info about what you would expect should happen and what actually happens...

**Comment by johnnybubonic** [comment]
well, it seems it just silently fails if the record name contains invalid chars, despite reporting success.

**Comment by MarcelWaldvogel** [comment]
What are those invalid chars? I am having the same problem and have been shrinking the template to

```DNS
[ZONE] SOA 86400 ns1.example.com admin.example.com [SERIAL] 86400 7200 1209600 300
```
or
```DNS
@ SOA 86400 ns1.example.com admin.example.com 2019010101 86400 7200 1209600 300
```
In either case, when creating a new domain and selecting that (or any other) template, the result is an empty domain with just the `a.misconfigured.powerdns.server` SOA record. Everything else seems to work OK (i.e., editing existing zones, creating/editing templates, assigning zones to accounts, …).

Is there an example template which is supposed to work flawlessly? Any clue, what else I could try to narrow down the problem?

**Comment by macrokernel** [comment]
> i want to be able to specify records such as:
> 
> ```
> {ZONE}.	414	IN	SOA	ns1.{ZONE}. dnsadmin.{ZONE}. 2018101600 7200 7200 2419200 86400
> {ZONE}.	3600	IN	MX	0 mail.{ZONE}.
> _xmpp-server._tcp.{ZONE}. 3600 IN SRV	10 0 5269 xmpp.{ZONE}.
> ```
> 
> this would then render to:
> 
> * SOA records **foo.tld.	414	IN	SOA	ns1.foo.tld. dnsadmin.foo.tld. 2018101600 7200 7200 2419200 86400** and **bar.tld.	414	IN	SOA	ns1.bar.tld. dnsadmin.bar.tld. 2018101600 7200 7200 2419200 86400**
> * MX records **foo.tld.	3600	IN	MX	0 mail.foo.tld.** and **bar.tld.	3600	IN	MX	0 mail.bar.tld.**
> * **_xmpp-server._tcp.foo.tld. 3600 IN SRV	10 0 5269 xmpp.foo.tld.** and **_xmpp-server._tcp.bar.tld. 3600 IN SRV	10 0 5269 xmpp.bar.tld.**


It would be really great to have the substitution feature - it could make templates much more powerful.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
