### ISSUE TITLE
Feature request : domainmetadata

### ISSUE THREAD

**Issue by Rico29** [PowerDNS-Admin/PowerDNS-Admin#395]
Hello,
Related to #82, it would be very useful to be able to create domainmetadata for domains, like TSIG-ALLOW-DNSUPDATE or TSIG-ALLOW-AXFR.

Would be even better to have it in domain templates.
Actually you have to use pdnsutil to set them.

Regards
Cédric

**Comment by cbgsy** [comment]
+1 on this feature request please

**Comment by Metrax** [comment]
+1

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy

**Comment by pinocc01** [comment]
when pdns act as slave, new domains gen from  catalog, but may not transfer zone data without tsigkey if master need
so i need defaut tisgkey set for catalog
another request setting is defautl IXFR for all domains
