### ISSUE TITLE
Edit template: cannot change name or description

### ISSUE THREAD

**Issue by prupert** [PowerDNS-Admin/PowerDNS-Admin#402]
When editing a template it is currently not possible to change the template name or template description.

**Comment by ngoduykhanh** [comment]
The feature hasn't implemented yet. PR is welcome.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. This feature request is tracked in https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1178

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
