### ISSUE TITLE
Security: 2FA page shows secret token and can be disabled directly

### ISSUE THREAD

**Issue by prupert** [PowerDNS-Admin/PowerDNS-Admin#413]
I have a couple of concerns regarding the security of the current 2FA implementation in the web interface for the end-user. 

1. Under the Authentication tab the 2FA secret token (QR image) is always shown. Ideally it should not show when 2FA has been set up. 
2. 2FA can be easily disabled when logged in. Ideally there should be some form of confirmation, e.g. confirm with password when disabling 2FA. 
3. 2FA can be easily disabled by the user. Ideally when a 2FA enforcement policy is in place, it should not be possible for an end-user to disable 2FA.

**Comment by ngoduykhanh** [comment]
Hi,

> Under the Authentication tab the 2FA secret token (QR image) is always shown. Ideally it should not show when 2FA has been set up.
Yes, Agree

> 2FA can be easily disabled when logged in. Ideally there should be some form of confirmation, e.g. confirm with password when disabling 2FA.
Yes, Can double check with password or 2FA.

>2FA can be easily disabled by the user. Ideally when a 2FA enforcement policy is in place, it should not be possible for an end-user to disable 2FA.
Yes, it might helpful in case PDA is deployed in an Organization where the Administrator want to enforce the 2FA on their staff...

**Comment by rkerr** [comment]
I have also been eyeing this area:

In addition to a confirmation when disabling there should probably be a confirmation when enabling, It's very unusual for an app to just present the QR and hope you scanned it and reasonably easy to get locked out if you're not paying attention.

There should be some review of the 'Remember Me' function - Flask-Login seems to recommend you require a fresh login for password changes, which PowerDNS-Admin doesn't seem to do, but would also apply to 2FA.

It's unclear to me if 2FA is meant to work with LDAP or not - most of the python code seems to accept 2FA with LOCAL or LDAP, but in the template the code for 2FA on LDAP is commented out?

Also I'd like to have U2F/Webauthn as an option.

Regarding have an administrator option to enforce 2FA - I think this is maybe the tip of the iceberg, in a security conscious organisation you probably also want options to enforce password complexity, change frequency and a lockout after a number of failed logins.

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Forcing 2FA and enforcing stronger passwords are covered in PRs #1051 and #1054. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
