### ISSUE TITLE
Can the language package of the program be independent?

### ISSUE THREAD

**Issue by m1911** [PowerDNS-Admin/PowerDNS-Admin#415]
Language packs are independently and easily translated into other languages.

**Comment by ngoduykhanh** [comment]
We can use flask-babel to support multiple languages. Will take time to revise the current html templates :).

**Comment by m1911** [comment]
@ngoduykhanh 
Does it take a long time to complete?

**Comment by pcevela** [comment]
Bump :)
Is this still on the table?

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy

**Comment by jbe-dw** [comment]
@pcevela Yes but its priority should be evaluated later. For me it is a good idea.
