### ISSUE TITLE
[Request] IPv6 Reverse notation / Additional column

### ISSUE THREAD

**Issue by Tygera** [PowerDNS-Admin/PowerDNS-Admin#418]
Hi guys,

as we have a lot /64 ipv6 reverse dns zones, I wanted to add a column to the DataTable (dashboard).
Next to the Column "Name" there should be the normal ipv6 notation of the reverse zone.
e.g.

Name :                                                                  
1.0.0.0.0.0.0.0.4.3.7.a.2.6.5.a.ip6.arpa          

and next to the column :

CIDR:
a562:a734:0:1::/64

i already wrote a function which converts the name to the CIDR notation.
I never wrote s.th. with django/flask or in python.
But I'm too dump to add a column correctly, since I can't find any column definition in the main.js or else.

Someone has an example on how to correctly add a column and fill it with data not from the database but from a function instead?

**Comment by falz** [comment]
Came searching for something like this. All of the html is rendered in html using a jinja2 template, so its basically html with some `{{ include }}` options.

consider posting your code (python function i presume)? and someone may be more motivated to help add it.

Also make sure your function takes in to account all prefix lengths - we have no /64s for example, but use /32, /48, /56 frequently.

**Comment by dmcken** [comment]
This paste can perform those conversions:
https://pastebin.com/rgq2dVh2

I still have to document it and run through some better testing but for these cases its returning correct data.
