### ISSUE TITLE
Feature: set default zone type

### ISSUE THREAD

**Issue by prupert** [PowerDNS-Admin/PowerDNS-Admin#431]
When adding a new domain the default zone type is set to "native". Feature request to make this a setting, so you can set it to default to "master".

**Comment by lucianlazar1983** [comment]
I would also like to see this implemented. Is there a way to force it to be MASTER by default?
Thank you!

**Comment by prupert** [comment]
You could edit the HTML to have `MASTER` selected by default in this code:
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/2f39512b658aae6ce229f1cc94b4205b34d25a05/app/templates/domain_add.html#L43-L55

**Comment by lucianlazar1983** [comment]
Thank you, that did the trick. Is there a way to ignore the file in order to be able to pull commits in the future? Because if i try to merge will be denied. 

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/templates/domain_add.html

**Comment by prupert** [comment]
I would think manually editing the file is only a stop-gap measure. If you really want to go that way you should fork and frequently merge. 

But that is really bad advise if you simply want this feature to be added. Better to make a patch or pull request so everyone is better off! ;-)

**Comment by lucianlazar1983** [comment]
Thank you, i will try a pull request to see if it gets approved.
Have a nice day!

**Comment by a1d3s** [comment]
would be nice if this option is read from pdns.conf
# master        Act as a master
#
master=yes
# slave Act as a slave
#
slave=no

i think if booth no or not set it is a nativ install

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy

**Comment by Exchizz** [comment]
Hi,

I need this feature as well. I have previous experience with django and python, so I would like to give it a go.


\Exchizz
