### ISSUE TITLE
Restrict Domain Templates to a User

### ISSUE THREAD

**Issue by rmaxwell72** [PowerDNS-Admin/PowerDNS-Admin#438]
This is a request, not an issue.  We have PowerDNS-Admin working without issue, but would like to restrict Domain Templates to a specific user (i.e. - User1 is assigned template CorpDNSTemplate1, and User2 will not be able to see this template in their list.)

I wasn't able to find any information in prior issues/requests or in the configuration to be able to this.  Can this be added to the application?

Best,
Bobby

**Comment by prupert** [comment]
+1, however more logical would be to link Templates to Accounts, not Users.

**Comment by rmaxwell72** [comment]
Accounts or Users would be fine either way, just need a way to restrict templates so that all are not seen by all users/accounts.

Bobby

**Comment by rmaxwell72** [comment]
So if I was to put a bounty on this feature of let say $100 USD, would that help to get this going?  

Bobby

**Comment by rmaxwell72** [comment]
Khanh,

What would it take to get this feature built into an upcoming release?  I really need this feature, and I'm willing to increase the bounty (within reason) to make this happen.

Bobby

**Comment by rmaxwell72** [comment]
If I was to increase a bounty to $250 USD, would that get some traction on this request?

Bobby

**Comment by marcello-lupo** [comment]
Hello,
I can put 100$ more on this feature request. It is very important for us too.
Thank you

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
