### ISSUE TITLE
LDAP issue after upgrading

### ISSUE THREAD

**Issue by peetasan** [PowerDNS-Admin/PowerDNS-Admin#456]
After upgrading to bc2b57e47570c682262e52feb07393b26ebdc4e3 we've experienced the following error: 
```
[ERROR] {'desc': 'No such object'}
[ERROR] User "username" input a wrong LDAP password. Authentication request from 10.xxx.xxx.xxx
```

We've tried to run the migrations with `flask db upgrade` but it seems not all of the migrations ran, e.g. there is no `view` column in the settings table (from https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/migrations/versions/59729e468045_add_view_column_to_setting_table.py#L74)

```
04/02/2019 17:21:49INFO  [alembic.runtime.migration] Running upgrade 1274ed462010 -> 4a666113c7bb, Adding Operator Role
04/02/2019 17:21:49INFO  [alembic.runtime.migration] Running upgrade 4a666113c7bb -> 31a4ed468b18, Remove all setting in the DB
```

It would be nice if the above error message would be more detailed. Also what is the proper way to run all the (necessary) migrations? Thanks!

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
