### ISSUE TITLE
Bulk add reverse records

### ISSUE THREAD

**Issue by TheGreatDoc** [PowerDNS-Admin/PowerDNS-Admin#460]
Hi all,

Im moving from bind to pdns with this awesome admin tool.

I've been searching but found nothing about having a way to add bulk PTR records for reverse zones

Like the $generate from bind.

For example, I have like 10 reverse zones for /22 prefixes. That means ~10k PTR records.

Thanks in advance!

**Comment by openmsk** [comment]
https://doc.powerdns.com/md/authoritative/migration/
zone2sql --named-conf=/path/to/named.conf --gmysql | mysql -u pdns -p pdns-db

**Comment by TheGreatDoc** [comment]
@openmsk Thanks for your answer, but I mean after the first migration.

If tomorrow I need to generate reverses, or the forward for a new prefix, there is no way.

Also, I cant load our main forward zone (10k+ records), after some time loading, nginx throw an error

**Comment by openmsk** [comment]
PowerDNS-Admin is a backend for managing pdns-daemon and communicating with him over the API.
for this you should not try to load into the control panel, I gave an example from the documentation for pens-daemon where work with the load goes to the mysql of the zone values.

If tomorrow you need to create a new empty zone, then you can do it through the web interface PowerDNS-Admin


![image](https://user-images.githubusercontent.com/3602406/53259272-bc85c100-36df-11e9-8804-5fb6bfba7214.png)
![image](https://user-images.githubusercontent.com/3602406/53259296-ce676400-36df-11e9-91ed-d6e7cbf25039.png)

**Comment by TheGreatDoc** [comment]
As my english is very poor, I may expressed it incorrectly.

I know I can import named zones to sql. And I know I can create empty zones, but how can I bulk polulate it like the $generate from bind?

I mean, our main forward domain has arround 12k records that corresponds with 12 reverse zones that has the PTR records. 

So IP 55.66.77.88 resolves to 88.77-66-55.mydomain.net and vice-versa. And same with all our prefixes.

In bind, you can just add a $generate line. Is there something similar in powerdns-admin?

**Comment by openmsk** [comment]
my english is also not native :) but I think I understand you.
https://doc.powerdns.com/authoritative/manpages/zone2sql.1.html
zone2sql understands the Bind master file extension $GENERATE and will also honour $ORIGIN and $TTL.

in other words, you can create a BIND file, then zone2sql send it to the database.

**Comment by TheGreatDoc** [comment]
Ooook, now I did understood you. You are saying that instead of creating it from powerdns-admin, just create a "fake" bind zone and then import...

Its perfectly valid, but such an option in powerdns-admin would be awesome

**Comment by openmsk** [comment]
I think this is not the task of the management interface =)

**Comment by TheGreatDoc** [comment]
Why not? Its adding records, in a bulk way but adding records.

**Comment by openmsk** [comment]
at least for this:
''' Also, I cant load our main forward zone (10k+ records), after some time loading, nginx throw an error'''

По-русски я бы объяснил что если есть инструменты упрощающие жизнь, для чего усложнять схему, и жаловаться что не работает

**Comment by TheGreatDoc** [comment]
Well... I have mixed one question with one problem.

The question was if there were any way to add bulk records. There isnt, its ok. Just though it could be a nice feature, as adding records is part of the management.

The problem, or issue, is in an already imported zone with 10k+ records, Im unable to manage from powerdns-admin. In error log it shows `...upstream prematurely closed connection while reading response header from upstream...`

Im not complaining, and if it sounds like that Im sorry.

**Comment by openmsk** [comment]
show me an example of your config using the 10 million record $generate
I will try to reproduce your terms

**Comment by TheGreatDoc** [comment]
Not 10 million!! 10 thousands.

They are just a bunch of $generate, one for each /24 reverse we manage. So each reverse has 255 records and our main forward 255 records for each reverse, making it with thousands records

**Comment by openmsk** [comment]
oh, 10,000 entries - not a lot :)
solution for you :)
bash script:
```
pdnsutil create-zone 168.192.in-addr.arpa

for i in {1..254}; do 
    for o in {1..254}; do 
        pdnsutil add-record 168.192.in-addr.arpa $o.$i PTR test.example.com
        done;
done; 

```
Its long
Start create 10000 records Sat Feb 23 23:25:20 MSK 2019
Finish Sat Feb 23 23:30:56 MSK 2019

If it is long, then you can write a MySQL request that will make it a little faster :D

**Comment by TheGreatDoc** [comment]
Oh, thats really nice for our new zones!

But that was not the point. I can just do it in php to insert directly in database. Sorry for making you work due to my poor english :(

When I say load error, I mean in the already imported zone with zone2sql, I get that nginx error when I try to edit that zone from powerdns-admin.

I think is for the time it takes to load all the records. Is there any kind of timeout? I've used the nginx tutorial.

**Comment by openmsk** [comment]
I think that the problem is not in the PowerDNS-Admin, but in the size of the responses from the pdns.service API

![image](https://user-images.githubusercontent.com/3602406/53291764-90df0580-37c9-11e9-92fc-ff3e703df2a2.png)

**Comment by keimond** [comment]
@TheGreatDoc I am currently in the stages of migrating from bind to pdns.. what a headache with 20+ years of domains which may or may not be valid anymore!! Anyways... our backend is mysql, which I gather yours is too because I think you used zone2sql... at any rate another idea would be that you could use a script to generate your records and then insert them to mysql db instead of using the powerdns-admin api.

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
