### ISSUE TITLE
AD Auth Fails

### ISSUE THREAD

**Issue by mghicas** [PowerDNS-Admin/PowerDNS-Admin#478]
Having an issue with AD Auth and either getting a failure or a timeout:

I chopped out a ton of the debug - but this is what i am getting now:

Groups are created as universal security groups (tried as a distribution group as well)

Have tried using both LDAP and AD as options for Auth, neither seem to work.

2019-03-04 21:58:45,309 - root - ERROR - User mghicas is not part of the "CN=dnsadmin,OU=dnsadmin,OU4=Applications,OU=Groups,DC=ip-soft,DC=net", "CN=dnsoperator,OU=dnsadmin,OU=Applications,OU=Groups,DC=ip-soft,DC=net" or "CN=dnsuser,OU=dnsuser,OU=Applications,OU=Groups,DC=ip-soft,DC=net" groups that allow access to PowerDNS-Admin

2019-03-04 21:55:58,223 - root - DEBUG - Ldap search result: [[('CN=Mike Ghicas,OU=NY2,OU=Global,OU=Staff,DC=ip-soft,DC=net', <SNIPPED> 'memberOf': [b'CN=dnsadmin,OU=dnsadmin,OU=Applications,OU=Groups,DC=ip-soft,DC=net', 

Of I get a timeout:
2019/03/04 22:00:29 [error] 10502#0: *29 upstream prematurely closed connection while reading response header from upstream, client: 192.168.5.128, server: dnsmaster-int.prod.ipsoft.com, request: "POST /login HTTP/2.0", upstream: "http://unix:/apps/powerdns-admin-int/powerdns-admin.sock:/login", host: "dnsmaster-int.prod.ipsoft.com", referrer: "https://dnsmaster-int.prod.ipsoft.com/login"

But not both.

![image](https://user-images.githubusercontent.com/6484656/53766114-f1440600-3e9f-11e9-8522-d29004970df0.png)

Any thoughts?

**Comment by mghicas** [comment]
nevermind - just saw a typo in the config

**Comment by mghicas** [comment]
Re-opening - after fixing my config typos - i am still getting timeouts - looks like it is due to how many groups, nested group and such we have.

I modified app/model.py line 174 👍 
    def ad_recursive_groups(self, groupDN):
        """
        Recursively list groups belonging to a group. It will allow checking deep in the Active Directory
        whether a user is allowed to enter or not
        """
        **LDAP_BASE_DN = 'ou=groups,dc=ip-soft,dc=net'**
        #@#LDAP_BASE_DN = Setting().get('ldap_base_dn')

Would if be possible to have a LDAP GROUP SEARCH BASE added to the config?

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. There have been many patches arround authentication since. Feel free to open a new issue after upgrading to the latest version.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
