### ISSUE TITLE
[Question] What happened to app/static/adminlte2? (specifically natural sorting from #72)

### ISSUE THREAD

**Issue by epers** [PowerDNS-Admin/PowerDNS-Admin#486]
I like how #72 added natural sorting of records, but that plugin (along with all the others?) seems to have disappeared since then. 
Is there any way to enable natural sorting with the way the project is now?
If not, is there any plans to reintroduce this into the current codebase?

**Comment by tingvold** [comment]
This is fixed in #557.

@ngoduykhanh, you can close this one as well.

**Comment by vmarkop** [comment]
Fixed by PR #557.

Regards
PowerDNS Admin Team
