### ISSUE TITLE
[API] Auto create PTR records

### ISSUE THREAD

**Issue by blakkheimgw** [PowerDNS-Admin/PowerDNS-Admin#493]
Hello,

I have a question about the API : is it possible to add the same function as it exists in the GUI, to allow auto creating reverse record (PTR) when adding an A record ? At the moment, the only solution is to give rights on the corresponding PTR zones to the user account, which is undesirable in some cases.

Regards.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
