### ISSUE TITLE
Automatic update DS key on DNSSEC enable

### ISSUE THREAD

**Issue by ZeZombini** [PowerDNS-Admin/PowerDNS-Admin#495]
Hello,

Are there any way to update automaticly DS entries on TLD registrar when I enable DNSSEC?
I though about adding a plugin functionnality to easily plug my own script without much modification on PowerDNS-Admin code (wich can make PDNS-Admin update easy), but maybe there is a better way already implemented.

**Comment by Russell-IO** [comment]
@ZeZombini would you be able to share a little bit about how you implemented this?

**Comment by zarlo** [comment]
i would make an interface with like
`
name
set_ds(domain, record_data)
get_ds(domain)
`
and make class' for registrars that implement that interface 
store the configs for the registrar' in the settings table with the name as a prefix

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
