### ISSUE TITLE
Error with ALIAS record type: "Not in expected format (parsed as 'www.domain.com.')"

### ISSUE THREAD

**Issue by nanathlor** [PowerDNS-Admin/PowerDNS-Admin#496]
Enabled ALIAS as a record in the web interface
Added a record in the web interface:
Name   Type     Data
@         ALIAS    www.domain.com
APPLY give this error
Record domain.com./ALIAS 'www.domain.com': Not in expected format (parsed as 'www.domain.com.')

**Comment by nanathlor** [comment]
Sorry, almost forgot, version 4.1.8

**Comment by epipheus** [comment]
no comments on this for 4months?

**Comment by zoeller-freinet** [comment]
It needs to be a FQDN - it should work if you add the trailing dot to the domain name.
