### ISSUE TITLE
Allow editing of allow-axfr-from

### ISSUE THREAD

**Issue by primoz** [PowerDNS-Admin/PowerDNS-Admin#506]
Powerdns allows specifying allow-axfr per domain:

https://doc.powerdns.com/md/authoritative/domainmetadata/#allow-axfr-from

It would be nice to either be able to specify possible destinations or have a checkbox ( AUTO-NS yes / no).

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. Feel free to open a new issue later.

We have #1133 issue opened for future options arround domains metadata, not handled yet.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
