### ISSUE TITLE
Bad performance, no visual indication that PDA is busy, exception raised after hitting 'apply' w/o record modifications

### ISSUE THREAD

**Issue by tangby** [PowerDNS-Admin/PowerDNS-Admin#509]
1、My domain have 554 records, When I submit apply after update records, I get an 400 error, I find a timeout for request powerdns api in logs. When I change timeout to 100s in function "fetch_remote", I found that request spent 13 seconds; (Why so slow?)
2、When I submit apply after update records, It have not a prompt to tell me wait the result.
3、If I submit apply without any modify, it can still submit successfully and with a history record, but this record can not get "Info" with an Exception "Uncaught SyntaxError: Unexpected end of JSON input".

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to clean up this project, we're closing it. Feel free to open a new issue later if the problem persists in the latest version.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy (edited)
