### ISSUE TITLE
Assigning users/accounts permissions to individual records

### ISSUE THREAD

**Issue by amit177** [PowerDNS-Admin/PowerDNS-Admin#511]
Hey,
Is there a way to assign just a few records to a user instead of all of them? (reverse zones)
So for example, if you have a client and you would give him access to change the rDNS to his IPs.

Could that be added in the future if it is not a feature?

**Comment by Armadill0** [comment]
As the "account" feature currently is limited to zones I don't think this is possible at the moment.

**Comment by AmiT177** [comment]
Not necessarily using the account feature, could be just a normal user. (each record would have permissions).
that's less efficient than accounts, but yeah it's an option

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. PDA doesn't store any content, it just interacts with PowerDNS. Such feature is not gonna happen any soon.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
