### ISSUE TITLE
posixGroup support for LDAP_GROUP_SECURITY

### ISSUE THREAD

**Issue by Armadill0** [PowerDNS-Admin/PowerDNS-Admin#513]
I just checked out PR #512 which allows LDAP_GROUP_SECURITY with groupOfNames.

My problem is, that we only use posixGroups which differ in using only the username instead of the full FDN of the LDAP user.

I now want to suggest to add a drop down element on the LDAP settings page where you can choose between "posixGroup" and "groupOfNames" layout to use for the group security feature.

The code itself should be pretty straight forward because the only difference is the usage of self.username instead of ldap_username in the groupSearchFilter. This could be easy achieved by an intersection which uses the value from the formerly introduced group layout dropdown field.

I'm not a great developer myself, but I think I could provide the code for this after #512 has been merged.

Any other suggestions or ideas?

**Comment by johnwarburton** [comment]
Have you tried putting this as the Group Filter? I've never used it but I think this should work but I do not have posixgroups to check
```(objectClass=posixGroup)```

**Comment by Armadill0** [comment]
I tried that, but it doesn't work because the username which is being used is in the FDN format (uid=<username>,ou=people,cn=example,cn=org) and the posixGroup format needs <username> only.

**Comment by tingvold** [comment]
Any chance #512 could get merged? Just hit this issue today.

**Comment by jbe-dw** [comment]
As said in the linked PR you're not using the software anymore. Closing.
