### ISSUE TITLE
SECURITY: Anyone can create a subdomain of a registered domain

### ISSUE THREAD

**Issue by r3d-f0x** [PowerDNS-Admin/PowerDNS-Admin#514]
If user A creates example.tld but doesn't set subdomain.example.tld in the zone for example.tld, user B can come along and register subdomain.example.tld.  Is there a way to prevent this without allowing users do do something like register .tld and thereby lock everyone else out of that TLD?

**Comment by vmarkop** [comment]
Hello, PR #1127 solves your issue.

Regards
PowerDNS Admin's team
