### ISSUE TITLE
Feature Request: Add domain content version control

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#518]
It would be very useful to be able to
1) Add a comment (e.g. a change reference) when applying pending changes
2) Have this comment and the changes displayed in the history (currently the history shows only a generic title and the whole JSON parameters submitted)
3) Be able to revert a change by clicking a button in the history (some changes may not be revertable).  This revert should undo any record add/change/delete and then increment the serial number again.

**Comment by jbe-dw** [comment]
Hello,

There is a lot of work involved here. The history get more detailed but storing changes is like having a full dump revision. I'll list it anyway but it will not happen any soon.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
