### ISSUE TITLE
auto_ptr setting should give option to NOT create zones

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#523]
Currently, auto_ptr will automatically create the required reverse zones.  This is not desirable, particularly if a user has an A record pointing to a subnet we do not own, since then the zone will be created as a master and end up taking priority over the real zone.

Probably "auto_ptr_zone" should be a separate option with a default of "false"

**Comment by sshipway** [comment]
This is getting more important for us now, as we run a split DNS for some zones and do not want to have split DNS on the reverse zones (because Reasons).  However editing the forwards zones keeps creating unwanted reverse zones.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
