### ISSUE TITLE
New local user creation workflow?

### ISSUE THREAD

**Issue by Codebreaker101** [PowerDNS-Admin/PowerDNS-Admin#527]
What is the desired workflow when creating local users?

**I**
I am able to create one user without an email address. But then I can't create a second one with error  `Email address is already in use` because its an empty string just like the first created user. Is email mandatory? There is HTML5 field validation but as far as I can see but no server side nor is the field required. 

**II**
I am able to create a user without a username with just email and password. But then I am not able to login. Is username mandatory?

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
