### ISSUE TITLE
Export / Import features

### ISSUE THREAD

**Issue by Caez83** [PowerDNS-Admin/PowerDNS-Admin#528]
Hello,

It's possible to add an export / import feature to bind9 or csv format ?

Some powedns admin tools provides this functionnality

**Comment by mans39** [comment]
Hi,

This would be easily achievable by adding the native export button to Datatable.

Eg : https://datatables.net/extensions/buttons/examples/html5/simple.html

With it, it's possible to export in CSV.

Regards,

**Comment by Daniel15** [comment]
I'd love import/export to/from BIND9 format. IMO this is the only major feature that's missing from PowerDNS-Admin, and it exists in other web frontends like nsedit and Opera DNS UI.

**Comment by sbeccato** [comment]
I love PowerDNS-Admin but this is a major feature that cannot be missing.
Is it in roadmap?

**Comment by Caez83** [comment]
In the powerdns API there is the export feature :
/api/v1/servers/server/zones/zone_id/export
Can you add it ?

It's great to have an Import / Export feature

**Comment by mateusz75** [comment]
> I love PowerDNS-Admin but this is a major feature that cannot be missing.
> Is it in roadmap?

I strong agree with Simone.    Import/Export is a primary feature !

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
