### ISSUE TITLE
Excessive API calls when adding record to large domain with 'auto_ptr' enabled

### ISSUE THREAD

**Issue by gplechuck** [PowerDNS-Admin/PowerDNS-Admin#530]
Hi there,

Like the GUI, having an issue with it at the moment though .

There seems to be some inefficiencies in how the 'auto_ptr' feature is implemented, or perhaps there is a misconfiguration somewhere I've overlooked.

Currently experiencing a problem where adding a single record to a domain (a root domain with many subdomains) when auto_ptr feature is enabled is takes a very long to complete, causing timeouts to occur on a proxy used to access the  PowerDNS admin GUI . Adding a record without the auto_ptr feature completes immediately.

A workaround in this case is to increase the proxy timeout of course, but I just wanted to check whether the behaviour that's observed is expected - 

After adding an A record for example, PowerDNS admin begins updating PTR records for every address in the domain as well as every address in all subdomains of this domain. It first sends a GET request to the API to retrieve a list of all entries in the zone it is operating on, and then it sends a PATCH request instructing PowerDNS to replace the value for a SINGLE PTR record. After every single PATCH request , another GET request is sent, again requesting a list of all addresses in the domain, even if we are still operating on the same zone. 

It continues to iterate through all PTR records in each subdomains, each time requesting a list of all addresses in the zone it is adding a PTR record for, and then issuing a replace command. 

In the example I'm looking at, this is resulting in literally thousands of API calls when all that was needed is to add an A record and its respective PTR record.

Does this sound like a misconfiguration, or is this by design, and if so, are there any plans to optimise this behaviour at some point?

Any further info or examples needed, let me know and I'll post some. 

Thanks

**Comment by ngoduykhanh** [comment]
Hi,

This is no special configuration for this. I think your issue is related to PDA performance issue itself.
Can you share your number of domain/records in your test?

**Comment by gplechuck** [comment]
Thanks for the reply.... some approx figures - 

1 root domain ( ~1200 records) 
~50 subdomains ( totalling ~1800 records)
~400 reverse zones (totalling ~2000 PTR records)

So just to reiterate, after adding an A record to the root domain, the auto_ptr functionality appears to be updating any corresponding PTR records for the root domain and all subdomains one at a time and requesting record info for the current zone in between each operation. 

Any other info needed, shout. 

Cheers

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to clean up this project, we're closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy.
