### ISSUE TITLE
Feature Request: Ability to clone a domain

### ISSUE THREAD

**Issue by Daniel15** [PowerDNS-Admin/PowerDNS-Admin#537]
I'd love to have the ability to clone a domain - that is, copy all the records of an existing domain into a new one. I know that I can create a template then create a new domain based on that template, but that's a lot of effort compared to just having a "clone" button to do a once-off copy.

**Comment by xTrekStorex** [comment]
I implemented that on an earlier version of this project: https://github.com/ngoduykhanh/PowerDNS-Admin/pull/239  

But like you said, it was ignored in favor of templates.
Frankly the code would probably have to be rewritten entirely now with Python3 support etc etc.

**Comment by jbe-dw** [comment]
Hello,

We are cleaning the issue tracker and closing your issue. You can follow the status here: https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1178

Regards
PowerDNS Admin Team
