### ISSUE TITLE
Username not differentiating scandinavian letters

### ISSUE THREAD

**Issue by Nillkki** [PowerDNS-Admin/PowerDNS-Admin#539]
I am using OpenID Connect to authenticate user and I found out that PowerDNS-Admin does not recognize the difference between for example admin and ädmin. So if I login as user A whose username is ädmin it actually uses the username admin which is not the correct account. PowerDNS-Admin seems to only use add one account based on which ever user logged in first.

**Comment by ngoduykhanh** [comment]
I didn't have much time to take a look at this. The issue may be related to the DB/python encoding of the username field. I will try to reproduce and make a fix if needed.

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to clean up this project, we're closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin's Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
