### ISSUE TITLE
Feature request: update all slaves from masters

### ISSUE THREAD

**Issue by flames** [PowerDNS-Admin/PowerDNS-Admin#544]
When managing slave zones, there is a button "Update from Master" to force an update w/o notify. It would be nice to have such a button in dashboard to force an update of all slave zones from their masters at once.

**Comment by ngoduykhanh** [comment]
Make sense. If this feature is implemented, it is only available to the administrator/operator role I think.

**Comment by splog123** [comment]
+1

I like this feature request.
