### ISSUE TITLE
Support DHCID records

### ISSUE THREAD

**Issue by xjuric29** [PowerDNS-Admin/PowerDNS-Admin#549]
Hello. It would be nice to show DHCID records to. We use DDNS and in PowerDNS-Admin I only see A records, so when I want remove some dynamic created records, I need to use some DB manager. Is there any quick fix, like add lines to some configuration file? I looked to DNS record settings but there this type of record is missing.

**Comment by johnwarburton** [comment]
We use ISC DHCP which writes to pdns the DHCID records. They appear as TXT
`

pc-024 | TXT | Active | 3600 | "31d09cb3ba2f79ffab3b5bbe6bade91d1f" 
pc-024 | A | Active | 3600 | 10.17.88.45

`

**Comment by xjuric29** [comment]
We use ISC KEA and there is probably no way to store records as TXT. :/
![Screenshot_20190730_101612](https://user-images.githubusercontent.com/26231120/62112602-4fd8a900-b2b3-11e9-96e3-e6e53e2cf934.png)

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we're closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy

**Comment by xjuric29** [comment]
What the hell is that?? There is clearly reported bug, no one replied for almost three years and finally you just mark it as too old? Is it example of correct issue managing? Ofcourse not! -_-

**Comment by vmarkop** [comment]
Hello @xjuric29,

we understand your frustration, but there has been a change in the maintenance staff recently. The number of older open issues, many of which may have been resolved in later releases, or may be deprecated and/or no longer required, is not manageable. Unfortunately, along with the deprecated issues, there may be a few decent ones which still require attention. If you believe this bug should still be resolved, please open a new Issue.

Thank you,
on behalf of PowerDNS Admin's Team.

**Comment by xjuric29** [comment]
In other words, you are just saying you have such mess in what were done and anyone do not want to check it that it is easier to start again from scratch and if someone really wants to, they need to do it again by themselves and then it might be possible that after next several years it can be solved.

Okay, I will not swear anymore. I just do not have now a running instance to check it again. I wish you to be more able to manage this next time.
