### ISSUE TITLE
First login requires OTP

### ISSUE THREAD

**Issue by epipheus** [PowerDNS-Admin/PowerDNS-Admin#550]
So I just got through installing PowerDNS and then PowerDNSAdmin and was happy to see the login.  But OTP is enable even for the first admin login, until I get an OTP QR I can't login. So What's the work around?

**Comment by epipheus** [comment]
Nevermind.   Apparently until it's set a space will work.  It should probably work without anything until it is actually set.

**Comment by tmuncks** [comment]
I believe the `OTP Token` field on the login page is simply always there, regardless of it being enabled or not. It it is not enabled, I further believe the contents are simply ignored.
I consider this a security bonus so we don't advertise whether or not two factor authentication is actually enabled.
Perhaps a small comment on the login page would help though?

**Comment by admoca60** [comment]
Anyway, I could see in this issue https://github.com/ngoduykhanh/PowerDNS-Admin/issues/646 that the first user is the admin so you have to create an account to start using it.

**Comment by a1d3s** [comment]
is there a way to force OTP enabled to all users at first login?

**Comment by zoeller-freinet** [comment]
A basic setting that forces OTP on all users is now implemented by #1051.

Display of the OTP input field on the login page can be controlled via the 'otp_field_enabled' basic setting. By default the field is shown, but can be ignored if no OTP is required for the user that is to be authenticated.
