### ISSUE TITLE
CSRF token missing or incorrect

### ISSUE THREAD

**Issue by prupert** [PowerDNS-Admin/PowerDNS-Admin#552]
We noticed that applying changes to a zone sometimes gives the following error:

```
flask.app - WARNING - Forbidden (CSRF token missing or incorrect.): /domain/redacted-domain-name.ext/apply
```

And found the following at https://flask-wtf.readthedocs.io/en/v0.12/csrf.html#troubleshooting

> When you define your forms, if you make the mistake of importing Form from wtforms instead of from flask.ext.wtf, most features besides CSRF protection will work (aside from form.validate_on_submit()), but CSRF protection will fail. Upon submitting forms, you’ll get Bad Request/CSRF token missing or incorrect (and the form.csrf_token in your template will produce no output). The problem is in your broken import statements, not your configuration.

Unsure about the exact fix necessary, but this looks like a bug in PowerDNS-Admin.

**Comment by rkerr** [comment]
The message will be coming from Flask-SeaSurf rather than wtf, but you'd generally expect it to happen either all the time or not at all. It's a bit hard to guess how you might be getting the error only sometimes. Are there any patterns to what you're doing when you get the error, or the zones you get the error on? Do you have a zone that will always give you an error? Are these particularly large zones we're talking about?

**Comment by paradoxni** [comment]
I am getting the same randomly upon login. I get a 403 forbidden in nginx and the following in the logfile.log:

`2019-08-08 17:06:42,886 - flask.app - WARNING - Forbidden (CSRF token missing or incorrect.): /login
`

**Comment by rkerr** [comment]
Something very odd going on for that to happen... for some of the other bigger more complicated pages with lots of javascript it's more understandable, but not for the login page. Each time the flask app restarts it generates a random token. When you load the login page that token is served up to you, and when you click login the browser sends the token, user and password back to the server. The only obvious way the token could be incorrect in that case is if the app restarted between you loading the login page and hitting the login button.

**Comment by prupert** [comment]
We too are seeing the `flask.app - WARNING - Forbidden (CSRF token missing or incorrect.)` error for different pages on and off:

- /template/create
- /admin/manageuser
- /domain/<name-here>/apply
- /login
- /template/<name-here>/apply
- /admin/setting/dns-records

It happens too rarely to find a pattern and/or make it reproducible.

**Comment by rkerr** [comment]
This looks to be a similar issue: https://github.com/plotly/dash/issues/132

Could you see if passing `--preload` makes it go away? It looks like PowerDNS-Admin might not be managing the secret key properly - there's a SECRET_KEY configuration option but it doesn't appear to get used for anything that I can see...

**Comment by prupert** [comment]
>  there's a SECRET_KEY configuration option but it doesn't appear to get used for anything that I can see...

Haha, the only reference to the `SECRET_KEY` is in the config. 

So I guess using a single worker or `--preload` in gunicorn is a possible work-around for now.

**Comment by paradoxni** [comment]
Interesting. I did increase workers to 4. I will try the preload setting and report back.

________________________________

**Comment by paradoxni** [comment]
I have been using the system for a few hours so far and have not had a repeat of the CSRF problem with --preload gunicorn setting.

**Comment by prupert** [comment]
We did see a reoccurrence of the error when using `--preload`, but only on the `/login` URI.

**Comment by ngoduykhanh** [comment]
I experienced this issue on the login process as well. However, it only happens when the session is expired.

Looking at the code of Flask-Seasurf, the toke is stored in the [session](https://github.com/maxcountryman/flask-seasurf/blob/2ec4cee44e4a703a51e2739091184f044e6d2df5/flask_seasurf.py#L328), so when it does the [comparison](https://github.com/maxcountryman/flask-seasurf/blob/2ec4cee44e4a703a51e2739091184f044e6d2df5/flask_seasurf.py#L314) between the user's token and server's token, it won't match if the session has expired.

**Comment by johnwarburton** [comment]
@ngoduykhanh - just testing an upgrade and can confirm it only happens when the session is expired. It does not happen when I logout

**Comment by jvleminc** [comment]
We see this continuously happening as well with Kubernetes deployments:

```
Error en pod whitedns-powerdns-admin=xxxxxyyyyyzzz

2022-03-29 10:05:51,952] [flask_seasurf.py:282] WARNING - Forbidden (CSRF token missing or incorrect.): /login
[2022-03-29 10:06:24,670] [flask_seasurf.py:282] WARNING - Forbidden (CSRF token missing or incorrect.): /login
[2022-03-29 10:06:31,385] [flask_seasurf.py:282] WARNING - Forbidden (CSRF token missing or incorrect.): /login
[2022-03-29 10:07:02,566] [flask_seasurf.py:282] WARNING - Forbidden (CSRF token missing or incorrect.): /register
[2022-03-29 10:07:11,878] [flask_seasurf.py:282] WARNING - Forbidden (CSRF token missing or incorrect.): /login
```

**Comment by vmarkop** [comment]
Hello,

PR #1124 has fixed the problem on first login. Regarding our policy to clean up this project, we're closing this issue. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy

**Comment by lgwapnitsky** [comment]
Sorry to resurrect a dead thread, but a fresh installation, and receiving the CSRF issue. Have tried all of the above with no luck.  Unable to register a new account for admin purposes

```
Nov 22 10:37:15 pdns01 gunicorn[2590]: [2024-11-22 10:37:15 -0500] [2590] [INFO] Starting gunicorn 20.1.0
Nov 22 10:37:15 pdns01 gunicorn[2590]: [2024-11-22 10:37:15 -0500] [2590] [INFO] Listening at: unix:/run/pdnsadmin/socket (2590)
Nov 22 10:37:15 pdns01 gunicorn[2590]: [2024-11-22 10:37:15 -0500] [2590] [INFO] Using worker: sync
Nov 22 10:37:15 pdns01 gunicorn[2593]: [2024-11-22 10:37:15 -0500] [2593] [INFO] Booting worker with pid: 2593
Nov 22 10:37:42 pdns01 gunicorn[2593]: [2024-11-22 10:37:42,132] [flask_seasurf.py:344] WARNING - Forbidden (CSRF token missing or incorrect.): /register
```

Service file
```
[Unit]
Description=PowerDNS-Admin
Requires=pdnsadmin.socket
After=network.target

[Service]
PIDFile=/run/pdnsadmin/pid
User=pdns
Group=pdns
WorkingDirectory=/var/www/html/pdns
ExecStart=/var/www/html/pdns/flask/bin/gunicorn --pid /run/pdnsadmin/pid --bind unix:/run/pdnsadmin/socket 'powerdnsadmin:create_app()' --preload
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

Service override file
```
### Editing /etc/systemd/system/pdnsadmin.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file

[Service]
Environment="FLASK_CONF=../configs/production.py"

### Lines below this comment will be discarded

### /etc/systemd/system/pdnsadmin.service
# [Unit]
# Description=PowerDNS-Admin
# Requires=pdnsadmin.socket
# After=network.target
#
# [Service]
# PIDFile=/run/pdnsadmin/pid
# User=pdns
# Group=pdns
# WorkingDirectory=/var/www/html/pdns
# ExecStart=/var/www/html/pdns/flask/bin/gunicorn --pid /run/pdnsadmin/pid --bind unix:/run/pdnsadmin/socket 'powerdnsadmin:create_app()' --preload
# ExecReload=/bin/kill -s HUP $MAINPID
# ExecStop=/bin/kill -s TERM $MAINPID
# PrivateTmp=true
#
# [Install]
# WantedBy=multi-user.target
```
