### ISSUE TITLE
openid using gitlab

### ISSUE THREAD

**Issue by vquiering** [PowerDNS-Admin/PowerDNS-Admin#554]
Hi,

I am trying to use gitlab as openid provider which ends in http 500 response.

    Traceback (most recent call last):
      File "/opt/web/powerdns-admin/flask/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
        response = self.full_dispatch_request()
      File "/opt/web/powerdns-admin/flask/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/opt/web/powerdns-admin/flask/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/web/powerdns-admin/flask/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
        raise value
      File "/opt/web/powerdns-admin/flask/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
        rv = self.dispatch_request()
      File "/opt/web/powerdns-admin/flask/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/opt/web/powerdns-admin/app/views.py", line 456, in login
        oidc_username = me["preferred_username"]
    KeyError: 'preferred_username'
    
Is there any documentation I can refer to?

Thanks in advance.

**Comment by vquiering** [comment]
Found the solution to my issue in app/views.py

Just in case someone else is facing this issue, here's what I did.

    diff --git a/app/views.py b/app/views.py
    index b94cbff..535251f 100755
    --- a/app/views.py
    +++ b/app/views.py
    @@ -451,8 +451,8 @@ def login():
             return redirect(url_for('index'))
    
         if 'oidc_token' in session:
    -        me = json.loads(oidc.get('userinfo').text)
    -        oidc_username = me["preferred_username"]
    +        me = json.loads(oidc.get('user').text)
    +        oidc_username = me["username"]
             oidc_givenname = me["name"]
             oidc_familyname = ""
             oidc_email = me["email"]

**Comment by ngoduykhanh** [comment]
`preferred_username` should be in the OpenID `userinfo` response. Do you have any idea why it is not with Gitlab?

**Comment by mvdkleijn** [comment]
@ngoduykhanh `preferred_username` is not in the userinfo response for a lot of providers... I ran into this issue while trying to use Dex as a provider. Being able to set what field is used similar to scopes, would be very appreciated.

**Comment by opentokix** [comment]
Same problem when using keycloak as an identity provider.

**Comment by itxworks** [comment]
Hello,
Same issue with Keycloak 17.0.0   KeyError: 'preferred_username'  with this 
Mappers set:

![image](https://user-images.githubusercontent.com/73403258/160563440-7b30d504-a4f4-4abc-8acc-85607335d48f.png)

Thank you.

**Comment by rtoenniges** [comment]
Samle Problem with Keycloak 18.0.0

`May 28 17:27:01 gunicorn[1886]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/index.py", line 369, in login
May 28 17:27:01  gunicorn[1886]:     oidc_username = me[Setting().get('oidc_oauth_username')]
May 28 17:27:01 gunicorn[1886]: KeyError: 'preferred_username'`

preferred_username is defintily mapped and for testing username is also mapped but nothing works.
I may have set the wrong API URL in PDNS-Admin... Can anyone tell me what URL is expected there?

**Comment by jbe-dw** [comment]
@vmarkop @RGanor 

Have you checked the keycloak notes ?

**Comment by RGanor** [comment]
This issue is very old an it using fixed oidc claims, since then claims can now be changed so its needed to be tested again.

**Comment by RGanor** [comment]
Updated in #717

**Comment by RGanor** [comment]
If other people having problems i think it is better to create a new issue since this is very old and not relevant anymore.

Anyway, as a first step, i need @rtoenniges to dump the content of 'me'

**Comment by AzorianSolutions** [comment]
I'm closing this issue since it has been addressed with [this PR](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/717).
