### ISSUE TITLE
idn support ? 

### ISSUE THREAD

**Issue by rebjan** [PowerDNS-Admin/PowerDNS-Admin#556]
next releases are available for manage IDN domains ?

**Comment by rwx2019** [comment]
I join a question

**Comment by glomazdov** [comment]
+1 , need idn

**Comment by ngoduykhanh** [comment]
I didn't have time to visit this topic before...

As I know, PDNS stores the IDN domains in Punycode format so if you create a domain name with that format in PDA, it should be fine.

Or, you guys are looking for a way to input the domain name in its raw format and let PDA converts/displays to/in Punycode for you?

**Comment by glomazdov** [comment]
what need to commit this code ?  It is very cool

**Comment by mrsrvman** [comment]
+1

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still have an issue with idn support.

Regards
PowerDNS Admin Team
See #1153 for the policy
