### ISSUE TITLE
Possibility to use "All" as default record table size

### ISSUE THREAD

**Issue by roelschroeven** [PowerDNS-Admin/PowerDNS-Admin#560]
I can set default_record_table_size in table settings to 5, 15 or 20 to use that number as the default table size. But that doesn't work when I set it to "All": in that case I can indeed see all records in one page (which is good) but the whole bar with table size chooser and search field disappears (which is not good).

It's not terribly important but it would be nice to have.

**Comment by vlitvin** [comment]
Looks like "-1" works fine enough, not rendered as "All", thou.

**Comment by jbe-dw** [comment]
Hello,

Is the problem still present ?

Regards
