### ISSUE TITLE
Feature request: reapply template to a domain

### ISSUE THREAD

**Issue by EasyNetDev** [PowerDNS-Admin/PowerDNS-Admin#566]
Hello,

I'm new in PowerDNS-Admin and I've found it very nice piece of software and I'm starting to move from PowerAdmin to this interface.
I've notice something that I couldn't do it: after changing a template I wanted to reapply to a domain. I don't know if is a good idea or not, but PowerAdmin had such option.

What do you think?

Best regards,
Adrian

**Comment by ngoduykhanh** [comment]
It makes sense to me. I will mark it as a _feature request_ but will be in low priority :)

**Comment by AdrianBan** [comment]
Thanks! Sure it can be low priority. But I'm glad that is a good feature.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
