### ISSUE TITLE
WSGI Apache example error

### ISSUE THREAD

**Issue by Mystery-X** [PowerDNS-Admin/PowerDNS-Admin#624]
Hello,

I'm trying to follow your guide on enableing powerdns-admin via apache wsgi.
But i'm getting the following errorcode : 
```
[Fri Dec 27 21:14:47.391710 2019] [wsgi:error] [pid 27780] [remote 0.0.0.0:20016] mod_wsgi (pid=27780): Failed to exec Python script file '/srv/vhosts/dyndns.home-ip.eu/powerdnsadmin.wsgi'.
[Fri Dec 27 21:14:47.391772 2019] [wsgi:error] [pid 27780] [remote 0.0.0.0:20016] mod_wsgi (pid=27780): Exception occurred processing WSGI script '/srv/vhosts/dyndns.home-ip.eu/powerdnsadmin.wsgi'.
[Fri Dec 27 21:14:47.391871 2019] [wsgi:error] [pid 27780] [remote 0.0.0.0:20016] Traceback (most recent call last):
[Fri Dec 27 21:14:47.391907 2019] [wsgi:error] [pid 27780] [remote 0.0.0.0:20016]   File "/srv/vhosts/dyndns.home-ip.eu/powerdnsadmin.wsgi", line 5, in <module>
[Fri Dec 27 21:14:47.391913 2019] [wsgi:error] [pid 27780] [remote 0.0.0.0:20016]     from powerdnsadmin import create_app
[Fri Dec 27 21:14:47.391933 2019] [wsgi:error] [pid 27780] [remote 0.0.0.0:20016] ModuleNotFoundError: No module named 'powerdnsadmin'
```

Can you help me what went wrong.

**Comment by sshipway** [comment]
I've just fought through similar.  The module name and function have changed in v0.2.1.  If you're using an older version then you use `app:app` instead of `powerdnsadmin:create_app(config='config.py')`.  Make sure the app is installed into the new name directory.

**Comment by jasonmacer** [comment]
@sshipway, i'm trying to follow here, but somehow i'm missing something. I just followed the instructions you guy's have for Running PowerDNS Admin on Centos 7 and got it working, but now i'm trying to get it to start with WSGI through apache. So I followed WSGI Apache example for CentOS and ended up finally getting it to start apache without issue, but the powerdnsadmin app is not running that I can tell, but then again i'm not seeing an error in the apache logs either.

Machine is running CentOS 7

my install is in /var/www/html/pdnsadmin/

Here is my powerdnsadmin.conf for httpd
> <VirtualHost *:1138>
>         ServerName sdnsadmin.bwell.local
>         ServerAlias sdnsadmin.bwell.local
>         ServerAdmin webmin@42iso.com
> 
>         ErrorLog /etc/httpd/logs/error-sdnsadmin.httpd.log
>         CustomLog /etc/httpd/logs/access-sdnsadmin.httpd.log combined
> 
>         DocumentRoot /var/www/html/pdnsadmin/
> 
>         WSGIDaemonProcess pdns user=pdns group=pdns threads=5
>         WSGIScriptAlias / /var/www/html/pdnsadmin/powerdnsadmin.wsgi
> 
>         # pass BasicAuth on to the WSGI process
>         WSGIPassAuthorization On
> 
>         <Directory "/var/www/html/pdnsadmin/">
>                 WSGIProcessGroup pdns
>                 WSGIApplicationGroup %{GLOBAL}
> 
>                 AllowOverride None
>                 Options +ExecCGI +FollowSymLinks
>                 AllowOverride None
>                 Require all granted
>         </Directory>
> </VirtualHost>


Here is my /var/www/html/pdnsadmin/powerdnsadmin.wsgi file 
> #!/usr/bin/env python3
> import sys
> sys.path.insert(0, '/var/www/html/pdnsadmin')
> 
> from pdnsadmin import create_app
> application = create_app()

In my httpd.conf file i have added the following to the end 
> WSGISocketPrefix /var/run/wsgi
> IncludeOptional sites-enabled/*.conf

A couple of things to note:
1.) httpd was installed but I did also install httpd-devel
2.) I followed the "centos" instructions on the wiki page for this setup
3.) I did notice that /var/run/wsgi does not exist

Can you tell what if anything i'm missing here?

Any help is greatly appreciated

**Comment by Rolli2005** [comment]
I have currently exact the same problem as described above:

`mod_wsgi (pid=654): Failed to exec Python script file '/srv/vhosts/powerdns.example.com/powerdnsadmin.wsgi'.
mod_wsgi (pid=654): Exception occurred processing WSGI script '/srv/vhosts/powerdns.example.com/powerdnsadmin.wsgi'.
Traceback (most recent call last):
File "/srv/vhosts/powerdns.example.com/powerdnsadmin.wsgi", line 5, in <module>
from powerdnsadmin import create_app
ModuleNotFoundError: No module named 'powerdnsadmin'
`

Did anyone make it run? Because this is the only error I got - so I don't know where I should continue searching :-(

**Comment by falz** [comment]
Also experiencing original issue, but I cannot get "app:app" to work either. 

Note if i run manually without service, it implies that the app is named powerdnsadmin:

```
./run.py
 * Serving Flask app "powerdnsadmin" (lazy loading)
 * Environment: production
```

I'm running from current git master as of the time of writing.
