### ISSUE TITLE
Feature Request: Hide Accounts/Templates based on user association 

### ISSUE THREAD

**Issue by AgentTNT** [PowerDNS-Admin/PowerDNS-Admin#628]
If there is public user registration open and allow_user_create_domain = ON, when users go to create domains, they have the ability to see all accounts(groups) and templates. 

I believe this behavior should be reserved to the Administrator/Operator level for the be-all-see-all. 

Templates could be associated with the Accounts, and users should only be able to see the accounts they are members of. 

This restrictive behavior could be set under the settings like a normal toggle to not disturb the current workflow of existing implementations. 

Open for discussion and thoughts.

**Comment by ngoduykhanh** [comment]
Agree. I wanted to make an adjustment for that :).

**Comment by nvmng** [comment]
Supported

**Comment by jbe-dw** [comment]
#1171 Should fit your needs.

Regards
