### ISSUE TITLE
Feature Request: move the record helper from a universal value to a per-user option

### ISSUE THREAD

**Issue by AgentTNT** [PowerDNS-Admin/PowerDNS-Admin#629]
Some users may not prefer the record helper and may find this an annoyance while others may enjoy it, but all consume from the same instance. 

Separating this may be of use to end users.

**Comment by ngoduykhanh** [comment]
It makes sense. If we implement this feature, we can extend the user profile to have their own "settings" I guess, then override the global ones.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
