### ISSUE TITLE
flask db upgrade fail

### ISSUE THREAD

**Issue by ppcharli** [PowerDNS-Admin/PowerDNS-Admin#630]
(flask) [root@srv1 pdns]# `export FLASK_APP=powerdnsadmin/__init__.py`
(flask) [root@srv1 pdns]# `flask db upgrade`
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: Could not import "powerdnsadmin".

**Comment by ppcharli** [comment]
(flask) [root@srv1 pdns]# export FLASK_APP=powerdnsadmin/__init__.py
(flask) [root@srv1 pdns]# flask db upgrade
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: Could not import "powerdnsadmin".

**Comment by ngoduykhanh** [comment]
Can you share more information about your system? What have you done before DB migration?

**Comment by sshipway** [comment]
Looking at the clip above I would guess that shell cwd is not in the PowerDNS-Admin install directory when running the command, IE not in the directory containing powerdnsadmin directory.  Hence the FLASK_APP path could not be found

**Comment by ppcharli** [comment]
My system is Centos7 with Mysql
I have followed the steps on the page
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7

**Comment by keesbos** [comment]
What's in the directory where you run the `flask db upgrade`? (i.e. show the output of `ls -l`)

**Comment by ppcharli** [comment]
Is the directory where I download from git
These are the steps that I follow
```
#  git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git /u01/app/powerdns-admin
# cd /u01/app/powerdns-admin
#  virtualenv -p python3 flask
#  . ./flask/bin/activate
> (flask) [root@server powerdns-admin]# pip install python-dotenv
> (flask) [root@server powerdns-admin]# pip install -r requirements.txt
> (flask) [root@server powerdns-admin]# export FLASK_APP=powerdnsadmin/__init__.py
> (flask) [root@server powerdns-admin]# flask db upgrade
Usage: flask db upgrade [OPTIONS] [REVISION]
Error: Could not import "powerdnsadmin".
```

**Comment by keesbos** [comment]
What's the output from:
```
ls -l powerdnsadmin
which flask
python3 -c 'import powerdnsadmin;print(powerdnsadmin.__file__)'
python3 -c 'import sys;print(sys.path)'
echo $PYTHONPATH
```

**Comment by ppcharli** [comment]
```
export INST=pdnsauthint
git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git /u01/app/powerdns-admin/$INST
cd /u01/app/powerdns-admin/$INST
virtualenv -p python3 flask
. ./flask/bin/activate
(flask) [root@srv-vln pdnsauthvpn]# pip install python-dotenv
...
(flask) [root@srv-vln pdnsauthvpn]# pip install -r requirements.txt
...
(flask) [root@srv-vln pdnsauthint]# export FLASK_APP=powerdnsadmin/__init__.py
(flask) [root@srv-vln pdnsauthint]# flask db upgrade
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: Could not import "powerdnsadmin".
(flask) [root@srv-vln pdnsauthint]# ls -l powerdnsadmin
total 76
-rw-r--r-- 1 root root  3049 Jan 14 11:52 assets.py
-rw-r--r-- 1 root root  7989 Jan 14 11:52 decorators.py
-rw-r--r-- 1 root root  3841 Jan 14 11:54 default_config.py
-rw-r--r-- 1 root root   673 Jan 14 11:54 default_config.py.org
-rwxr-xr-x 1 root root  3111 Jan 14 11:52 __init__.py
drwxr-xr-x 2 root root   125 Jan 14 11:52 lib
drwxr-xr-x 2 root root  4096 Jan 14 11:52 models
drwxr-xr-x 2 root root   130 Jan 14 11:52 routes
drwxr-xr-x 2 root root   143 Jan 14 11:52 services
drwxr-xr-x 3 root root    37 Jan 14 11:52 static
-rw-r--r-- 1 root root 42746 Jan 14 11:52 swagger-spec.yaml
drwxr-xr-x 4 root root  4096 Jan 14 11:54 templates
(flask) [root@srv-vln pdnsauthint]# which flask
/u01/app/powerdns-admin/pdnsauthint/flask/bin/flask
(flask) [root@srv-vln pdnsauthint]# python3 -c 'import powerdnsadmin;print(powerdnsadmin.__file__)'
/u01/app/powerdns-admin/pdnsauthint/powerdnsadmin/__init__.py
(flask) [root@srv-vln pdnsauthint]# python3 -c 'import sys;print(sys.path)'
['', '/u01/app/powerdns-admin/pdnsauthint/flask/lib64/python36.zip', '/u01/app/powerdns-admin/pdnsauthint/flask/lib64/python3.6', '/u01/app/powerdns-admin/pdnsauthint/flask/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6', '/usr/lib/python3.6', '/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages']
(flask) [root@srv-vln pdnsauthint]# echo $PYTHONPATH

(flask) [root@srv-vln pdnsauthint]#
```

**Comment by keesbos** [comment]
That looks OK (directories, import of powerdnsadmin in python3)

So, I suspect there's something strange with your flask installation (should be able to import powerdnsadmin, just like python3).

You might retry `flask db upgrade` with setting the `PYTHONPATH`
```
export PYTHONPATH="/u01/app/powerdns-admin/pdnsauthint"
flask db upgrade
```

Or you could dig into flask.

**Comment by ppcharli** [comment]
Now the error changes. It says that the migrations directory does not exist but as you can see it does exist.

```
(flask) [root@srv-vln-zabbix2 pdnsauthint]#  export PYTHONPATH="/u01/app/powerdns-admin/pdnsauthint"
(flask) [root@srv-vln-zabbix2 pdnsauthint]#  flask db upgrade
error : Unknown IO error
[2020-01-15 12:38:58,805] [__init__.py:97] ERROR - Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
(flask) [root@srv-vln-zabbix2 pdnsauthint]# ls -l
total 76
drwxr-xr-x 2 root root    64 Jan 14 11:52 configs
drwxr-xr-x 2 root root    43 Jan 14 11:52 docker
-rw-r--r-- 1 root root   600 Jan 14 11:52 docker-compose-test.yml
-rw-r--r-- 1 root root   396 Jan 14 11:52 docker-compose.yml
drwxr-xr-x 2 root root   115 Jan 14 11:52 docker-test
drwxr-xr-x 2 root root    57 Jan 14 11:52 docs
drwxr-xr-x 6 root root    64 Jan 14 11:55 flask
-rw-r--r-- 1 root root  1102 Jan 14 11:52 LICENSE
drwxr-xr-x 3 root root    86 Jan 14 11:52 migrations
-rw-r--r-- 1 root root   308 Jan 14 11:52 package.json
drwxr-xr-x 9 root root  4096 Jan 14 11:56 powerdnsadmin
-rw-r--r-- 1 root root  1896 Jan 14 11:52 README.md
-rw-r--r-- 1 root root   480 Jan 14 11:52 requirements.txt
-rwxr-xr-x 1 root root   224 Jan 14 11:52 run.py
drwxr-xr-x 4 root root    71 Jan 14 11:52 tests
-rw-r--r-- 1 root root  1199 Jan 14 11:52 update_zones.py
-rw-r--r-- 1 root root 39951 Jan 14 11:52 yarn.lock

```

**Comment by keesbos** [comment]
Check/analize your flask file (`/u01/app/powerdns-admin/pdnsauthint/flask/bin/flask`). It looks like it is changing the current work directory.

**Comment by ppcharli** [comment]
This is  the /u01/app/powerdns-admin/pdnsauthint/flask/bin/flask file. 
```
#!/u01/app/powerdns-admin/pdnsauthint/flask/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from flask.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

**Comment by keesbos** [comment]
What's the output of `strace -f flask db upgrade 2>&1 | grep getcwd`
That should give an idea of what flask thinks what it's current work directory is.

**Comment by ppcharli** [comment]
```
strace -f flask db upgrade 2>&1 | grep getcwd
getcwd("/u01/app/powerdns-admin/pdnsauthint", 1024) = 36
getcwd("/u01/app/powerdns-admin/pdnsauthint", 1024) = 36
getcwd("/u01/app/powerdns-admin/pdnsauthint", 1024) = 36
getcwd("/u01/app/powerdns-admin/pdnsauthint", 1024) = 36
[pid  3643] getcwd("/u01/app/powerdns-admin", 4096) = 24
getcwd("/u01/app/powerdns-admin", 1024) = 24
getcwd("/u01/app/powerdns-admin", 1024) = 24
```

**Comment by keesbos** [comment]
Right. Apparently the cwd gets changed (what was the suspected). Maybe you can track from the strace output where/why this happens:
```
strace -o /tmp/flask.strace -f flask db upgrade
less /tmp/flask.strace
```
There should be a `chdir` call somewhere, but why... I guess there will be a fork of a new process somewhere.

**Comment by ppcharli** [comment]
```
17787 getcwd("/u01/app/powerdns-admin/pdnsauthint", 1024) = 36
17787 stat("/u01/app/powerdns-admin/pdnsauthint", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint/.flaskenv", 0x7ffd86356590) = -1 ENOENT (No such file or directory)
17787 stat("/u01/app/powerdns-admin/.flaskenv", 0x7ffd86356590) = -1 ENOENT (No such file or directory)
17787 stat("/u01/app/.flaskenv", 0x7ffd86356590) = -1 ENOENT (No such file or directory)
17787 stat("/u01/.flaskenv", 0x7ffd86356590) = -1 ENOENT (No such file or directory)
17787 stat("/.flaskenv", 0x7ffd86356590) = -1 ENOENT (No such file or directory)
17787 getcwd("/u01/app/powerdns-admin/pdnsauthint", 1024) = 36
17787 chdir("/u01/app/powerdns-admin")  = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib64/python3.6", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib64/python3.6/lib-dynload", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
17787 stat("/usr/lib64/python3.6", {st_mode=S_IFDIR|0755, st_size=8192, ...}) = 0
17787 stat("/usr/lib/python3.6", {st_mode=S_IFDIR|0755, st_size=26, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages", {st_mode=S_IFDIR|0755, st_size=8192, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages/pkg_resources/__init__.cpython-36m-x86_64-linux-gnu.so", 0x7ffd863547f0) = -1 ENOENT (No such file or directory)
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages/pkg_resources/__init__.abi3.so", 0x7ffd863547f0) = -1 ENOENT (No such file or directory)
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages/pkg_resources/__init__.so", 0x7ffd863547f0) = -1 ENOENT (No such file or directory)
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", {st_mode=S_IFREG|0644, st_size=108386, ...}) = 0
17787 stat("/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages/pkg_resources/__init__.py", {st_mode=S_IFREG|0644, st_size=108386, ...}) = 0
17787 open("/u01/app/powerdns-admin/pdnsauthint/flask/lib/python3.6/site-packages/pkg_resources/__pycache__/__init__.cpython-36.pyc", O_RDONLY|O_CLOEXEC) = 4
17787 fstat(4, {st_mode=S_IFREG|0644, st_size=99814, ...}) = 0
17787 lseek(4, 0, SEEK_CUR)             = 0
17787 fstat(4, {st_mode=S_IFREG|0644, st_size=99814, ...}) = 0
17787 read(4, "3\r\r\n\367\235\35^b\247\1\0\343\0\0\0\0\0\0\0\0\0\0\0\0g\0\0\0@\0\0"..., 99815) = 99814
17787 read(4, "", 1)                    = 0
17787 close(4)                          = 0

```

**Comment by ppcharli** [comment]
Following your suggestions, I have specified the path in the "db upgrade" and it works.
The error "error: Unknown IO error" I don't know if it will be important or not but the process continues
```
(flask) [root@srv-vln-zabbix2 pdnsauthint]# flask db upgrade -d /u01/app/powerdns-admin/pdnsauthint/migrations
error : Unknown IO error
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 654298797277 -> 0fb6d23a4863, Remove user avatar
INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
INFO  [alembic.runtime.migration] Running upgrade 856bb94b7040 -> b0fea72a3f20, Update domain serial columns type
INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column

```

**Comment by keesbos** [comment]
Good to know you have a work-around, although we still don't know why this `chdir` happens.

**Comment by WUPTRaXX** [comment]
I have a similar problem. Haven't found a solution yet.

`
(flask) root@dns:/opt/web/powerdns-admin# flask db upgrade
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 31a4ed468b18 -> 654298797277, Upgrade DB Schema
Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1050, "Table 'apikey' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/opt/web/powerdns-admin/migrations/versions/654298797277_add_apikey_schema.py", line 28, in upgrade
    sa.UniqueConstraint('key')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/operations/ops.py", line 1250, in create_table
    return operations.invoke(op)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/ddl/impl.py", line 252, in create_table
    self._exec(schema.CreateTable(table))
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1050, "Table 'apikey' already exists")
[SQL:
CREATE TABLE apikey (
        id INTEGER NOT NULL AUTO_INCREMENT,
        `key` VARCHAR(255) NOT NULL,
        description VARCHAR(255),
        role_id INTEGER,
        PRIMARY KEY (id),
        FOREIGN KEY(role_id) REFERENCES `role` (id),
        UNIQUE (`key`)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
`

**Comment by keesbos** [comment]
> I have a similar problem. Haven't found a solution yet.
> 
> ``
> (flask) root@dns:/opt/web/powerdns-admin# flask db upgrade
> INFO [alembic.runtime.migration] Context impl MySQLImpl.
> INFO [alembic.runtime.migration] Will assume non-transactional DDL.
> INFO [alembic.runtime.migration] Running upgrade 31a4ed468b18 -> 654298797277, Upgrade DB Schema
> Traceback (most recent call last):
> File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
> cursor, statement, parameters, context
> File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
> cursor.execute(statement, parameters)
> File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
> res = self._query(query)
> File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
> db.query(q)
> File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
> _mysql.connection.query(self, query)
> MySQLdb._exceptions.OperationalError: (1050, "Table 'apikey' already exists")
> ...

This is not similar. Don't hijack this issue...

**Comment by johnwarburton** [comment]
Just doing an upgrade this weekend. I think the issue is that the powerdnsadmin directory has been renamed "app"

This works for me:
```
(flask) /opt/powerdns-admin# export FLASK_APP=app/__init__.py
(flask) /opt/powerdns-admin# flask db upgrade
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian#running-powerdns-admin will need to be updated

**Comment by jbe-dw** [comment]
Hello,

I think we can close this discussion. If you still have trouble please reopen a new issue.

Regards
