### ISSUE TITLE
Feature Request: Allow changing domain type and update masters after creation

### ISSUE THREAD

**Issue by VBustamante** [PowerDNS-Admin/PowerDNS-Admin#634]
It would be nice being able to change domain configurations after their creation. I've came up with an implementation suggestion based on the current domain creation forms below:
 
![image](https://user-images.githubusercontent.com/6564471/71990127-a0184780-3211-11ea-9346-ccaa84e57f8c.png)

Since this would be a feature not likely to be used all the time the idea is that the gear icon near the domain name would toggle this form.

**Comment by ngoduykhanh** [comment]
Hi,

Actually those setting are already available in the Domain's Admin page.
