### ISSUE TITLE
Feature Request: Allow short names for CNAME in the GUI

### ISSUE THREAD

**Issue by td00** [PowerDNS-Admin/PowerDNS-Admin#636]
When adding a CNAME to an DNS entry a trailing dot is added automatically.
Please consider a routine, where it's possible to decide wether you want to activate the function or not.
The trailing dot prohibits to add records like "foo CNAME bar".
Instead you're forced to use "foo CNAME bar.veryverylongdomainname.xyz.".

**Comment by td00** [comment]
Part in sourcecode regarding that behavior:
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/models/record.py#L171-L174

**Comment by ngoduykhanh** [comment]
Hi,

Can you give me an example of a record where we don't need to put the trailing point? As I can see from PDNS API, it will throw an error if we don't have it in CNAME record data.

**Comment by td00** [comment]
CNAMEs without trailing dot's should be perfectly fine and should extend
`foo CNAME bar`
to
`foo CNAME bar.example.com.`

(https://stackexchange.github.io/dnscontrol/why-the-dot)

**Comment by splog123** [comment]
Just an opinion: Speaking as a sysadmin who has users, I don't think we should support short names in CNAME content during data entry. I know why it's there - so you can type the short name and without a trailing dot, PDNS will evaluate and append "@".

This can get real confusing real fast as users can get confused about when you have a dot and what it does, and the linked stackexchange article shows how this can go so wrong. My users will never grok this, so I simply make them enter the FQDN. They learned to copy paste the zone name from the top of the page.

A good compromise might be to have a boolean config option "ALLOW SHORT NAMES IN CNAME" default to off. The OP, who does seem to understand the problem and knows what he is doing, can then enable it knowing that if he breaks it he keeps the two shiny pieces.

**Comment by bbchase** [comment]
The current behavior breaks handling of relative names as described in [RFC1033](https://www.ietf.org/rfc/rfc1033.txt). 

> Domain names in the zone files can be one of two types, either absolute or relative.  An absolute name is the fully qualified domain name and is terminated with a period.  A relative name does not terminate with a period, and the current default domain is appended to it.

I agree that this can be very confusing for users, but I don't think the solution should break the standard (or make things confusing for administrators!). I think any of these would be preferable:

- Expand names in the Data field in the GUI so users can see how their entry will be resolved in a query. e.g. an entered value of "host" could be displayed as `host (host.example.com.)` with "(host.example.com)" in grey italic type or something similar to distinguish it from the entered value.
- Values that contain at least one dot, but lack a trailing dot could prompt the user: "This will resolve to host.example.com.example.com, is this correct?"
- Other checks could be added to look for repeating portions of the fqdn or nonexistant TLDs (seems like this could get fiddly and difficult to maintain)

An "ALLOW SHORT NAMES IN CNAME" boolean could also be nice, but I think it should default to ON, to adhere to the RFC by default.

**Comment by mrfrenzy** [comment]
The suggestions from bbchase seems like the best solution.

If you don't want to implement that atleast the current behaviour needs to be improved so it is clear to the user what is happening.
When entering for example:
"foo CNAME bar" and clicking save everything looks ok. The field just has the text "bar" inside.
Even after applying changes it looks correct. You exit the web interface and think you have done your changes.
Next time the domain is opened, a dot is magically there, ruining your day!

If you want to add the dot without warning, it should appear as soon as clicking save, don't wait until after reloading the domain from dashboard. This way any user could understand what is happening regardless of what nameserver or UI they have used before.

**Comment by jbe-dw** [comment]
Hello there,

What happens in PowerDNS Admin when you edit a domain through the gui:

- Its content is fetched from PDNS API an rendered in the table
- When you click on apply button the table content is converted to an update API request

Adding a CNAME via PDA API just forwards the request to PDNS that requires fqdn with the trailing dot.

What can be added easily is an automatic domain expansion when you click on save button if there is no trailing dot, just adding the trailing dot if the value ends with the domain name.

This would directly show the user what will be added. It may be annoying if one frequently forgots the dot and have to edit it a second time.

That will be discussed whenever we will have a look.

Regarding our policy to cleanup this project, I am closing it. As this is a Feature Request, it will be listed in #1178 for reference and later decision of the outcome.

Regards
See #1153 for the policy
