### ISSUE TITLE
Feature Request: Allow per Zone ALLOW-AXFR-FROM for MASTER Zones

### ISSUE THREAD

**Issue by petzsch** [PowerDNS-Admin/PowerDNS-Admin#637]
It would be nice to edit the domain metadata for MASTER Zones to specify valid IPs/subnets for AXFR Transfers. Would have hoped to find something like this in the admin section of a MASTER zone.

See: https://doc.powerdns.com/authoritative/domainmetadata.html#allow-axfr-from

**Comment by splog123** [comment]
+1

My DNS operators will thank a coder for this. Several customers have many domains and often want copies of all of them. Operators have to manually AXFR and mail the results, letting the customer do it themselves from their office would be a big help.

**Comment by jbe-dw** [comment]
Same as #395
