### ISSUE TITLE
running the WebUI under a subdirectory? aka www.example.com/dnsadmin/

### ISSUE THREAD

**Issue by digitalhome** [PowerDNS-Admin/PowerDNS-Admin#638]
i have installed it using the doc "Running PowerDNS Admin with Systemd, Gunicorn and Nginx" and with:
https://dnsadmin.example.com
it works fine.
But i want / need the WebUI under 
https://www.example.com/dnsadmin/

i have seen there is a variable called SCRIPT_ROOT, but where to set the right path/directory if not /?

Pls help.

**Comment by joshuaboniface** [comment]
Doing this with `run.py` is probably possible, but I found that doing a production Gunicorn run and exposing the `SCRIPT_ROOT` environment variable worked. For instance, assuming I cloned the repo in to `/srv/powerdns-admin`, config at `/srv/powerdns-admin/config.py`, venv at `/srv/powerdns-admin/flask`, etc., the following systemd unit will do what you want:

```
# PowerDNS Admin service unit

[Unit]
Description=PowerDNS Admin WebUI
After=network.target

[Service]
User=pdns
Group=pdns
WorkingDirectory=/srv/powerdns-admin
Environment=PYTHON_UNBUFFERED=True
Environment=SCRIPT_NAME=/dns
ExecStart=/srv/powerdns-admin/flask/bin/gunicorn --workers 2 --log-level info --pid /srv/powerdns-admin/pid --bind 0.0.0.0:9191 "powerdnsadmin:create_app(config='/srv/powerdns-admin/config.py')"
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
