### ISSUE TITLE
Wiki update: How to use templates, first login etc.

### ISSUE THREAD

**Issue by Torxed** [PowerDNS-Admin/PowerDNS-Admin#641]
There's no information on what to do on first start.
Unless you go in under for instance "Installing on Ubuntu" and there's a little note about the first user being the admin one.

Further more, there's no information on how to use basic templates.
What do I write as a placeholder for the domain name?
if `name` is `%` will the future domain name be inserted automatically? What's the usage here?

**Comment by splog123** [comment]
First user being an admin is quite normal and routine for modern webby apps. You need an admin user so create everything else, and there's no installer program as such to prompt you for the admin username/password, so it's done at first login.

Templates are nothing more than a bunch of records added to a new zone that uses that template. They are most useful for adding your standard NS records (NS being the only record that is usually common across all zones at a site). The placeholder for the zone name is the conventional "@" in the name field.

**Comment by Torxed** [comment]
> First user being an admin is quite normal and routine for modern webby apps. You need an admin user so create everything else, and there's no installer program as such to prompt you for the admin username/password, so it's done at first login.
> 
> Templates are nothing more than a bunch of records added to a new zone that uses that template. They are most useful for adding your standard NS records (NS being the only record that is usually common across all zones at a site). The placeholder for the zone name is the conventional "@" in the name field.

My short answer to that is is: You're assuming a hell of a lot, and this is only obvious if you've worked with this particular of "best practice" before. This is not clear for everyone and adding a "get started" guide containing these two things would help a lot.

Not so PK answer:

I know how to do it now, I got it working after/before posting the question.
That's not the point, the point is that the world changes - and every week there's a new "best practices" to things. Or you've worked with so many different systems and they all have their own way that finding the "right way" in this software might take a while (hours). Not documenting how to get started with anything is childish and irresponsible if you cater to the masses.

The product is great, it's clearly written by someone with experience in web-frontends. There's some glitches and non-intuative things when adding records etc. But one thing that is extremely unclear is whether or not it uses `%`, `@`, `.` or empty string notation as a "domain name placeholder" when creating the templates. All the example templates were empty when I installed it with the latest release, which made it even more confusing. There for, the thing you see as "conventional" is probably because you've worked in one or two more tools that had this, where as some one else like myself come from a background where template doesn't exist at all or `.` for instance in my case was the thing I'm used to. Over my 20+ years of setting s*** like this up, `.` has been the common way, and only bind9 has used `@` of all the software I've used, but that was some 9 years ago and I didn't remember `@` was a thing. Having a "getting started" would have saved a lot of headache.. 

Last note, not everyone is a web-app person, or a front-end person. Going from the CLI world into the web-frontend world to try to speed up the every day stuff, is a pain in the ass, this experience didn't help one bit.

**Comment by jbe-dw** [comment]
We have a huge work on Documentation coming. We will make it clearer than what it is now (it may be better than 2y ago now but still lacks hell of a lot).

Regards

**Comment by AzorianSolutions** [comment]
Another one maybe for documentation David? @dmcken

**Comment by dmcken** [comment]
Yeah, already started the "Using PowerDNS-Admin" section for this type of documentation.
