### ISSUE TITLE
API max retrys

### ISSUE THREAD

**Issue by pctec2012** [PowerDNS-Admin/PowerDNS-Admin#653]
Hi
I have a fresh install of powerdns & powerdnsadmin on my server - api works via ssh but not though web gui ?
Here is the output of the error i keep getting below

powerdns_admin | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3e360bf10>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by ngoduykhanh** [comment]
Hi, What do you mean by "api works via ssh"?
Please make sure the PDNS API is listening on 127.0.0.1:8081 and the API key is correct.

**Comment by pctec2012** [comment]
sorry i mean the api works in the command line but not in the gui .

**Comment by ngoduykhanh** [comment]
How did you verify it works in the cmd? Can you show more information?
