### ISSUE TITLE
Feature Request: Add a validation step before actually enabling 2FA

### ISSUE THREAD

**Issue by msu-ts** [PowerDNS-Admin/PowerDNS-Admin#654]
Currently, when going to My Profile>Authentication and ticking the "Enable Two Factor Authentication" checkbox, the 2FA gets instantly enabled.

This should happen in 2 Steps:
- First you get the QR-Code Displayed and put it in to your Authenticator-App
- Then the User should be required to enter one 2FA Code for confirmation (to make sure he has set up the 2FA App correctly) 
- After successfully entering the first Code for confirmation the 2FA should actually be enabled and enforced

If the entered 2FA-Code is wrong show an error to the User and don't enable the 2FA.

This would prevent users from locking themselfes out (if one accidentaly closes their browser or whatever error could happen while setting up 2FA)

**Comment by ngoduykhanh** [comment]
Agreed. This is what I thought about but haven't implemented yet...

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. This is not quite a Feature Request, but it will be listed as one in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
