### ISSUE TITLE
Nginx 502 error

### ISSUE THREAD

**Issue by joshbgosh10592** [PowerDNS-Admin/PowerDNS-Admin#657]
Sorry for the issue spam... This time, I've done a decent amount of research and haven't found any answer.
Now that I've installed PowerDNS-Admin and everything appears to be running, when I go to powerdns.domain.com, I'm receiving a 502 error.
This error is in /var/log/nginx/powerdns-admin.local.error.log:
```
cat /var/log/nginx/powerdns-admin.local.error.log 
2020/02/05 05:31:07 [crit] 2680#2680: *1 connect() to unix:/opt/web/powerdns-admin/powerdns-admin.sock failed (2: No such file or directory) while connecting to upstream, client: 10.9.0.241, server: powerdns.domain.com, request: "GET / HTTP/1.1", upstream: "http://unix:/opt/web/powerdns-admin/powerdns-admin.sock:/", host: "powerdns.domain.com"
```
I'm assuming this might be because on another guide I had to follow to get even this far, I was told to disable /etc/resolv.conf. After every command, I was receiving an error about not being able to resolve powerdns (hostname of the server). I added it back and set the nameserver back to 127.0.0.1 with option edns0.

cat /etc/hosts
```
127.0.0.1	localhost.localdomain	localhost
::1		localhost6.localdomain6	localhost6

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
### The following lines, Josh entered
127.0.0.1	powerdns.domain.com	powerdns
127.0.0.1	pdns.domain.com		pdns
```
**Nginx Config:**
```
server {
  listen *:80;
#  server_name               powerdns-admin.example.com www.powerdns-admin.example.com;
  server_name               powerdns.domain.com www.powerdns.domain.com;
  index                     index.html index.htm index.php;
  root                      /opt/web/powerdns-admin;
  access_log                /var/log/nginx/powerdns-admin.local.access.log combined;
  error_log                 /var/log/nginx/powerdns-admin.local.error.log;

  client_max_body_size              10m;
  client_body_buffer_size           128k;
  proxy_redirect                    off;
  proxy_connect_timeout             90;
  proxy_send_timeout                90;
  proxy_read_timeout                90;
  proxy_buffers                     32 4k;
  proxy_buffer_size                 8k;
  proxy_set_header                  Host $host;
  proxy_set_header                  X-Real-IP $remote_addr;
  proxy_set_header                  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_headers_hash_bucket_size    64;

  location ~ ^/static/  {
    include  /etc/nginx/mime.types;
    root /opt/web/powerdns-admin/app;

    location ~*  \.(jpg|jpeg|png|gif)$ {
      expires 365d;
    }

    location ~* ^.+.(css|js)$ {
      expires 7d;
    }
  }

  location / {
    proxy_pass            http://unix:/opt/web/powerdns-admin/powerdns-admin.sock;
    proxy_read_timeout    120;
    proxy_connect_timeout 120;
    proxy_redirect        off;
  }
}
```

Thoughts? I'm finally so close to having this up and running...
If it means anything, on my client machine, I modified the hosts file to point to the server's IP using it's hostname. I currently don't have an internal DNS server.
Going to the server's IP address brings up the default Nginx web page.

**Comment by harrismarg** [comment]
Same issue here.

**Comment by cleminan** [comment]
I'm having this issue too, I don't think it is nginx at fault.

For me the uWSGI service is failing to start with a 'missing callable' error in the `uwsgi.log` file:

```
Mon Feb 10 12:22:48 2020 - *** Starting uWSGI 2.0.15-debian (64bit) on [Mon Feb 10 12:22:48 2020] ***
Mon Feb 10 12:22:48 2020 - compiled with version: 7.3.0 on 28 September 2018 15:41:15
Mon Feb 10 12:22:48 2020 - os: Linux-4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
Mon Feb 10 12:22:48 2020 - nodename: dnsadmin
Mon Feb 10 12:22:48 2020 - machine: x86_64
Mon Feb 10 12:22:48 2020 - clock source: unix
Mon Feb 10 12:22:48 2020 - pcre jit disabled
Mon Feb 10 12:22:48 2020 - detected number of CPU cores: 2
Mon Feb 10 12:22:48 2020 - current working directory: /
Mon Feb 10 12:22:48 2020 - writing pidfile to /run/uwsgi/app/powerdns-admin/powerdns-admin.pid
Mon Feb 10 12:22:48 2020 - detected binary path: /usr/bin/uwsgi-core
Mon Feb 10 12:22:48 2020 - chdir() to /var/www/powerdns-admin/
Mon Feb 10 12:22:48 2020 - your processes number limit is 7728
Mon Feb 10 12:22:48 2020 - your memory page size is 4096 bytes
Mon Feb 10 12:22:48 2020 - detected max file descriptor number: 1024
Mon Feb 10 12:22:48 2020 - lock engine: pthread robust mutexes
Mon Feb 10 12:22:48 2020 - thunder lock: disabled (you can enable it with --thunder-lock)
Mon Feb 10 12:22:48 2020 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/powerdns-admin/socket fd 3
Mon Feb 10 12:22:48 2020 - uwsgi socket 1 bound to UNIX address /run/uwsgi/app/powerdns-admin/powerdns-admin.socket fd 5
Mon Feb 10 12:22:48 2020 - dropping root privileges after socket binding
Mon Feb 10 12:22:48 2020 - setgid() to 33
Mon Feb 10 12:22:48 2020 - setuid() to 33
Mon Feb 10 12:22:48 2020 - Python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
Mon Feb 10 12:22:48 2020 - Set PythonHome to /var/www/powerdns-admin/flask/
Mon Feb 10 12:22:49 2020 - Python main interpreter initialized at 0x55ad96c87140
Mon Feb 10 12:22:49 2020 - dropping root privileges after plugin initialization
Mon Feb 10 12:22:49 2020 - python threads support enabled
Mon Feb 10 12:22:49 2020 - your server socket listen backlog is limited to 100 connections
Mon Feb 10 12:22:49 2020 - your mercy for graceful operations on workers is 60 seconds
Mon Feb 10 12:22:49 2020 - mapped 328896 bytes (321 KB) for 2 cores
Mon Feb 10 12:22:49 2020 - *** Operational MODE: preforking ***
Mon Feb 10 12:22:49 2020 - added /var/www/powerdns-admin/ to pythonpath.
Mon Feb 10 12:22:49 2020 - mounting run.py on /pdns
Mon Feb 10 12:22:49 2020 - unable to find "application" callable in file run.py
Mon Feb 10 12:22:49 2020 - VACUUM: unix socket /run/uwsgi/app/powerdns-admin/socket removed.
Mon Feb 10 12:22:49 2020 - VACUUM: unix socket /run/uwsgi/app/powerdns-admin/powerdns-admin.socket removed.
```

Aside from moving the install base to /var/www/powerdns-admin/ every other element matches the working test configuration I built a few months ago, though the run.py file has changed notably and the `app` folder looks to have been renamed `powerdnsadmin`.


The  installation works fine as a Flask app.

```
# source ./flask/bin/activate
(flask) root@dnsadmin:/var/www/powerdns-admin# ./run.py 
 * Serving Flask app "powerdnsadmin" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
[2020-02-10 12:11:44,083] [_internal.py:122] INFO -  * Running on http://0.0.0.0:9191/ (Press CTRL+C to quit)
[2020-02-10 12:11:44,085] [_internal.py:122] INFO -  * Restarting with stat
[2020-02-10 12:11:44,908] [_internal.py:122] WARNING -  * Debugger is active!
[2020-02-10 12:11:44,998] [_internal.py:122] INFO -  * Debugger PIN: 758-022-169
```

**uWSGI configuration**

/etc/uwsgi/apps-enabled/powerdns-admin.ini

```
; PowerDNS-Admin
[uwsgi]
plugins = python3

uid=www-data
gid=www-data

chdir = /var/www/powerdns-admin/
pythonpath = /var/www/powerdns-admin/
virtualenv = /var/www/powerdns-admin/flask/

mount = /pdns=run.py
manage-script-name = true
callable = app
;callable = powerdnsadmin

vacuum = true
harakiri = 20
buffer-size = 32768
post-buffering = 8192

socket = /run/uwsgi/app/%n/%n.socket
chown-socket = www-data

pidfile = /run/uwsgi/app/%n/%n.pid

daemonize = /var/log/uwsgi/app/%n.log

enable-threads =
```

I tried altering the `callable` entry but it made no difference to the logged error.


I've fiddled around the edges, tweaked bits here and there but not managed to get the uWSGI service any closer than the 'callable' error.

**Comment by Armadill0** [comment]
@joshbgosh10592 Your error clearly states that the pda socket is not available which means that it is not running. This doesn't have anything to do with DNS.

**Comment by Armadill0** [comment]
@cleminan You issue seems quite different from the OP's one. I think there was a change how to start PDA. I got that sorted via setting some environment variables:

> FLASK_CONF=../config.py
> FLASK_APP=powerdnsadmin/__init__.py

But I'm setting those in an environment and starting it with systemd instead of uwsgi. maybe have a look at this docs how to start a Flask app with uwsgi: https://flask.palletsprojects.com/en/1.1.x/deploying/uwsgi/

**Comment by joshbgosh10592** [comment]
> @joshbgosh10592 Your error clearly states that the pda socket is not available which means that it is not running. This doesn't have anything to do with DNS.

Any idea how to get the pda socket to run with this method then?

**Comment by Armadill0** [comment]
> > @joshbgosh10592 Your error clearly states that the pda socket is not available which means that it is not running. This doesn't have anything to do with DNS.
> 
> Any idea how to get the pda socket to run with nginx on boot then?

Well, does PDA start at least? Do you have logs from it? And what is your actual uswgi config?

**Comment by florianbeer** [comment]
I think I am hitting the same error as @cleminan (my issue #669). As a workaround I've now started `run.py` directly via systemd and proxied to 127.0.0.1:9191 in nginx, but that's not a viable long term solution since it is running in a single threaded development server.

Was anybody else successful in using uWSGI with PowerDNS-Admin?

**Comment by florianbeer** [comment]
@cleminan please refer to #669 and see if that fix works for you as well. It solved my problem.

**Comment by joshbgosh10592** [comment]
@Armadill0 Sorry for the delay...
PowerDNS is running, yes. Systemctl status pdns shows active. What logs from PDNS would be needed to help? And, because I have never worked with uswgi before, where would I get the config? If you need the nginx powerdns-admin.conf:
```
`cat /etc/nginx/conf.d/powerdns-admin.conf
server {
  listen *:80;
#  server_name               powerdns-admin.example.com www.powerdns-admin.example.com;
  server_name               powerdns.mydomain.com www.powerdns.mydomain.com;
  index                     index.html index.htm index.php;
  root                      /opt/web/powerdns-admin;
  access_log                /var/log/nginx/powerdns-admin.local.access.log combined;
  error_log                 /var/log/nginx/powerdns-admin.local.error.log;

  client_max_body_size              10m;
  client_body_buffer_size           128k;
  proxy_redirect                    off;
  proxy_connect_timeout             90;
  proxy_send_timeout                90;
  proxy_read_timeout                90;
  proxy_buffers                     32 4k;
  proxy_buffer_size                 8k;
  proxy_set_header                  Host $host;
  proxy_set_header                  X-Real-IP $remote_addr;
  proxy_set_header                  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_headers_hash_bucket_size    64;

  location ~ ^/static/  {
    include  /etc/nginx/mime.types;
    root /opt/web/powerdns-admin/app;

    location ~*  \.(jpg|jpeg|png|gif)$ {
      expires 365d;
    }

    location ~* ^.+.(css|js)$ {
      expires 7d;
    }
  }

  location / {
    proxy_pass            http://unix:/opt/web/powerdns-admin/powerdns-admin.sock;
    proxy_read_timeout    120;
    proxy_connect_timeout 120;
    proxy_redirect        off;
  }
}`
```

**Comment by Grommor** [comment]
@joshbgosh10592 
Hi I encountered a similar problem, solved when I put the nginx config and official documentation ( see close to proxy_pass directive ) 
`https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian`
But I encountered another error
```PermissionError: [Errno 13] Permission denied: '/opt/web/powerdns-admin/powerdnsadmin/static/.webasset```

helped crutch in the form of chmod 777 in the powerdnsadmin folder, maybe who knows the answer why this happens

**Comment by kainjinez** [comment]
@Grommor I faced same problem like OP. After chmod 777 in .webasset then it works. Thanks.

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to clean up this project, we're closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
