### ISSUE TITLE
Active Directory Authentication issue

### ISSUE THREAD

**Issue by czickler** [PowerDNS-Admin/PowerDNS-Admin#659]
Hello,

we have a new installation of PowerDNS-Admin in version 0.2.1 and were facing problems with LDAP Active Directory authentication.
After configuration of the LDAP authentication settings 
![image](https://user-images.githubusercontent.com/60773034/74011528-652c3f80-4988-11ea-9b55-5751c14cd2c3.png)

and testing the login we received the following error message in /var/log/syslog:

gunicorn[677]: [2020-02-06 13:46:26,512] [user.py:169] ERROR - {'desc': 'Invalid credentials', 'info': '80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839'}
gunicorn[677]: [2020-02-06 13:46:26,512] [user.py:240] ERROR - User "test.user" input a wrong LDAP password. Authentication request from xxx.xxx.xxx.xxx
gunicorn[677]: [2020-02-06 13:46:26,512] [index.py:396] WARNING - User test.user failed to authenticate via LOCAL from xxx.xxx.xxx.xxx

The reason for this behavoiur seems to be in our Active Directory environment. We have an Microsoft Exchange Server and multiple E-Mail Domains (@domain.com; @mydomain-gmbh.de; @company.org). To get Exchange autconfiguration to work properly, we set the UserPrincipalName for our users corresponding to their primary e-mail address. 
The internal Active Directory doman name is company.local. 

When i look in /opt/web/powerdns-admin/powerdnsadmin/models/user.py in line 233 it seems that the username for LDAP authentication is build of the "Username Field" (which we set to SamAccountName) plus "@" followed by "Active Directory Domain" (which would in our cas be domain.local). So a username would always be <username>@domain.local which in our case is always wrong.
Our users will have usernames like user1@domain.com, user2@mydomain-gmbh.de or user3@company.org

Our solution now was to change the following section in /opt/web/powerdns-admin/powerdnsadmin/models/user.py (line 233) from

# validate AD user password
if Setting().get('ldap_type') == 'ad':
    ldap_username = "{0}@{1}".format(self.username,
                                     Setting().get('ldap_domain'))# validate AD user password

to

if Setting().get('ldap_type') == 'ad':
    ldap_username = "{1}\\{0}".format(self.username,
                                     Setting().get('ldap_domain'))

and enter the NETBIOS Domain Name in the "Active Directory Domain" field in PowerDNS-Admin

This way the username wil be build in format <domain>\<username>, which ist valid for all domain users. After that authentication with LDAD Active Directory User was successfull.

Can we leave the modification this way, or will this maybe lead to ohter issues we did not face right now?

**Comment by ngoduykhanh** [comment]
Does the `user1@domain.com@company.local` work without modify the code?

Depends on your setup, the login name may be different. With your modification, I don't see any problem for now. I just don't like the idea of using slash `\` character in the login name although AD supports it :).

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Regarding our policy to clean up this project, we're closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy

**Comment by wHiteeeeeeeee** [comment]
Hi,
I have the same problem:
Jun 05 11:02:52 test-pdnsadmin02 gunicorn[85377]: [2024-06-05 11:02:52,638] [user.py:230] ERROR - User "test\sglock.admin" input a wrong LDAP password. Authentication request from 
User test\sglock.admin failed to authenticate via LDAP from

{'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563'}

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/75625585/75f2bc1c-200a-40c7-ad9a-3e654c9370db)


pdns.conf file:

launch+=ldap
ldap-host=ldap://xxx.xxx.xxx:389/
#ldap-starttls=yes
ldap-bindmethod=tree
ldap-basedn=OU=test,dc=test,dc=software
ldap-binddn=CN=svc_pdns,OU=test1,DC=test,DC=software
ldap-secret=pass
ldap-method=simple

pdns version:
PowerDNS Authoritative Server 5.0.0-alpha0.963.master.g03c640456

pdnsadmin version: 
Version 0.4.2
I have no idea what could be the cause anymore.
