### ISSUE TITLE
Feature request: Make some Settings available to administrator only

### ISSUE THREAD

**Issue by splog123** [PowerDNS-Admin/PowerDNS-Admin#660]
The PowerDNSAdmin settings in sidebars -> Settings -> Basic are available to Administrators and Operators alike, some of them are not appropriate for Operators. 

Examples:
- Operators can set default_domain_table_size, default_record_table_size and ttl_options - that works for me
- allow_user_create_domain, auto_ptr and site_name are setting I reserve for myself.

Proposal:
There are only 19 settings so a layout like sidebar -> Settings -> Records with tickboxes (columns are Administrators and Operators) would suit, I can enable the settings I want the Operators to have. The Settings page will only show those to a logged in Operator.

No settings permissions at all for Users suits me fine. I would be OK with a third column for them.
This might tie in with #628

**Comment by ngoduykhanh** [comment]
I think the proper way to do this is creating a Role's permission setting page where Admin (or super Admin) can grant whatever privileges to a particular Role.

**Comment by splog123** [comment]
I agree that is an elegant medium-term solution, and we have discussed this at least once before :-)

The reality though is that the listed items in "Settings" on the sidebar seem fine (no-one is saying that doesn't suit their needs), it's just that the details inside "Basic" are a bit coarse - it's all or nothing if a user can edit them or not.

I have to defer to a real python dev here, I'm a sysadmin and my python code is awful.
Meanwhile I can always adopt a BOFH stance and any user who touches something I don't want them touching needs to answer up and explain.

**Comment by jbe-dw** [comment]
Related to #1171

**Comment by jbe-dw** [comment]
@splog123 If this feature still interests you can you look at the PR and give a feedback on what is proposed.

Regards
