### ISSUE TITLE
SAML Authentication Error

### ISSUE THREAD

**Issue by minhlepham** [PowerDNS-Admin/PowerDNS-Admin#662]
Hello, I have this error when use sso with keycloak:
![image](https://user-images.githubusercontent.com/60643891/74208891-06cccd00-4cb8-11ea-9fef-779b20a9cdca.png)

**Debug:**
pdnsadmin            | [2020-02-11 03:34:16 +0000] [11] [DEBUG] POST /saml/authorized
pdnsadmin            | [2020-02-11 03:34:16 +0000] [11] [INFO] SAML: IDP Metadata successfully retrieved from: https://sso-test.com/auth/realms/dns/protocol/saml/descriptor
pdnsadmin            | [2020-02-11 03:34:16,694] [saml.py:67] INFO - SAML: IDP Metadata successfully retrieved from: https://sso-test.com/auth/realms/dns/protocol/saml/descriptor

**Env:**
SAML_ENABLED='True'
SAML_DEBUG='True'
SAML_PATH=os.path.join(os.path.dirname(__file__), 'saml')
SAML_METADATA_URL=https://sso-test.com/auth/realms/dns/protocol/saml/descriptor
SAML_METADATA_CACHE_LIFETIME=1
SAML_SP_ENTITY_ID=dns-saml
SAML_SP_CONTACT_NAME=me
SAML_SP_CONTACT_MAIL=me
SAML_SIGN_REQUEST='True'

**SAML Request:**
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="ONELOGIN_9200991dccb56c1b7c4560759b5e1ffffd12d15b"
                    Version="2.0"
                    ProviderName="PowerDNS-Admin"
                    IssueInstant="2020-02-11T03:34:15Z"
                    Destination="https://sso-test.com/auth/realms/dns/protocol/saml"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    AssertionConsumerServiceURL="http://localhost:9191/saml/authorized"
                    >
    <saml:Issuer>dns-saml</saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
                        AllowCreate="true"
                        />
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>

**SAML response from keycloak:**
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                Destination="http://localhost:9191/saml/authorized"
                ID="ID_41340308-9150-4dd9-98e3-9a93a12a4cf4"
                InResponseTo="ONELOGIN_9200991dccb56c1b7c4560759b5e1ffffd12d15b"
                IssueInstant="2020-02-11T03:34:15.999Z"
                Version="2.0"
                >
    <saml:Issuer>https://sso-test.com/auth/realms/dns</saml:Issuer>
    <dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
        <dsig:SignedInfo>
            <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
            <dsig:Reference URI="#ID_41340308-9150-4dd9-98e3-9a93a12a4cf4">
                <dsig:Transforms>
                    <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                </dsig:Transforms>
                <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                <dsig:DigestValue>5iV+wVjPHWCGV5ErEml0FVjv9HKxFZQJ5MLeESwyX7k=</dsig:DigestValue>
            </dsig:Reference>
        </dsig:SignedInfo>
        <dsig:SignatureValue>JNNmVCFw6zaq6LkE4VQqVyUBF6MV30nmzMbgFqgLd15adL6zx5R3XsNYBg0hcMCld3M/askDrWjs4Cup4KrHGtY+MFhe/WsvUN6hzi4YOHaXo3+6h9Mq8CRpsotEjIl+a/74mQqyjkYc3sZzCqaNLl0i/4HKNfcj8N/aZGYiNcmndyis1NCcj1ka7I6bu2wa2eJOdEz3dGoa9l9yrO6wOyrEloG2utpuRdJ8mS+nfrmUF6ZYaJvOWP9kjxqFVRmziLAIYieCwUpydmUMV++F/VMXsrOi+0ZKK2anKI7aGEA7Tp85s0v+XwKshAiHjgqol/52RIcU0gtXxNfQ9mdd8A==</dsig:SignatureValue>
        <dsig:KeyInfo>
            <dsig:KeyName>XBayf6nCLiZwvo26LAJLF16KCxNcQKW-Oqqs19UbHFw</dsig:KeyName>
            <dsig:X509Data>
                <dsig:X509Certificate>MIIClTCCAX0CBgFvjbM9LzANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDDANsYm4wHhcNMjAwMTEwMDQyMzUxWhcNMzAwMTEwMDQyNTMxWjAOMQwwCgYDVQQDDANsYm4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCKIpxCXTZby9YhRekYk/Mn3L9wCUeIShgO9E7r28fKPqLSHnx/mEkxgviVBRClTUryIB/ET6cZm6dXnsBGVCrAww125difdOw7UZ9DFTUEfxABq7Wtj3oIRVJHvAFwV79GMDBbDIHJvb7xysmDBjsvcI/vbMGkFNJug+pOMnt112Zpi08O52Nfnjn3yk5LC/ZHleWygYCkNoWs/zR6lkPU6hPSg1rMTwujpIPWyNdyatdlSHwRkPVFfWduLRlvFgEt685e79xnKpVNe2zlG41+Ekk/MR3ZNgYyHrEzf/BgjG/BwLWQmvUEx7LKIYLelI3JntdgLeVXyX01+cLkNmP3AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAAQrWCHxwwCaREh1TORtlH9+xR8gvmP0C4v7nYl3Y5MyFleXO2MQzqdbXBANCHxmYNMCJfYIpjz4j38UpIdhMFlo2cXdN1LdwbiAC7GAcxiI+81JzWlXuiTLp74YpCoB7tm+yCUD8k3hufEr5i88HTCwGzrN4Rq4D7MvEPxFwU6/bVP6rMRZTeBB60ZwwuttXsl0aslChMMTwhdCnl9Vp7U5kvn3MzFXhlbKqXblnsE81GZCQ/rsnRiIdbuygtivsgnKBol5IeSVYKaPvZL7fDDluMPbWxsW55kQttWt6DVEijBqO5EAKVbLLgtFwaFi6n1t2ncABnxCIzqyF/73BOQ=</dsig:X509Certificate>
            </dsig:X509Data>
            <dsig:KeyValue>
                <dsig:RSAKeyValue>
                    <dsig:Modulus>iiKcQl02W8vWIUXpGJPzJ9y/cAlHiEoYDvRO69vHyj6i0h58f5hJMYL4lQUQpU1K8iAfxE+nGZunV57ARlQqwMMNduXYn3TsO1GfQxU1BH8QAau1rY96CEVSR7wBcFe/RjAwWwyByb2+8crJgwY7L3CP72zBpBTSboPqTjJ7dddmaYtPDudjX54598pOSwv2R5XlsoGApDaFrP80epZD1OoT0oNazE8Lo6SD1sjXcmrXZUh8EZD1RX1nbi0ZbxYBLevOXu/cZyqVTXts5RuNfhJJPzEd2TYGMh6xM3/wYIxvwcC1kJr1BMeyyiGC3pSNyZ7XYC3lV8l9NfnC5DZj9w==</dsig:Modulus>
                    <dsig:Exponent>AQAB</dsig:Exponent>
                </dsig:RSAKeyValue>
            </dsig:KeyValue>
        </dsig:KeyInfo>
    </dsig:Signature>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <saml:Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="ID_4dd3ff88-47b4-46f0-85c0-90ecec509b06"
                    IssueInstant="2020-02-11T03:34:15.999Z"
                    Version="2.0"
                    >
        <saml:Issuer>https://sso-test.com/auth/realms/dns</saml:Issuer>
        <dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
            <dsig:SignedInfo>
                <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                <dsig:Reference URI="#ID_4dd3ff88-47b4-46f0-85c0-90ecec509b06">
                    <dsig:Transforms>
                        <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </dsig:Transforms>
                    <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <dsig:DigestValue>+Z4TV37e7masiRQNfoB1nghGUpbiT8hwvyyodTiw+gY=</dsig:DigestValue>
                </dsig:Reference>
            </dsig:SignedInfo>
            <dsig:SignatureValue>Fonlu0L81//Qk7Qxd8bz2T9JxpLWcJqy299mvm7RCR1VUnCMqyYWiLWYC2E2pNk7jGPiM6BxhxPkpRm5pNQOwnmfy6xeMaqxV6V+2VLqRat9SpWoeYV19UcSmBEWt6HAdWBKmWNp/RcorI5E/kcBSWoNBDsQPrMHTMGTHSthTVkvbNWOHOBCjyKU14ko5WpKDPF52sEsrHITrehy6CpB2odqTCrNcSRboajquQeF5Onu1W9BjikMfqMdSPc4ox/UYS5t0ViGQeI+FaBmNmodE9mSZfmKlkVmClqO+6knfp6XxD27t/btaEGqzbNafXZswogCHr5g8uaqWSCPgxhEig==</dsig:SignatureValue>
            <dsig:KeyInfo>
                <dsig:KeyName>XBayf6nCLiZwvo26LAJLF16KCxNcQKW-Oqqs19UbHFw</dsig:KeyName>
                <dsig:X509Data>
                    <dsig:X509Certificate>MIIClTCCAX0CBgFvjbM9LzANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDDANsYm4wHhcNMjAwMTEwMDQyMzUxWhcNMzAwMTEwMDQyNTMxWjAOMQwwCgYDVQQDDANsYm4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCKIpxCXTZby9YhRekYk/Mn3L9wCUeIShgO9E7r28fKPqLSHnx/mEkxgviVBRClTUryIB/ET6cZm6dXnsBGVCrAww125difdOw7UZ9DFTUEfxABq7Wtj3oIRVJHvAFwV79GMDBbDIHJvb7xysmDBjsvcI/vbMGkFNJug+pOMnt112Zpi08O52Nfnjn3yk5LC/ZHleWygYCkNoWs/zR6lkPU6hPSg1rMTwujpIPWyNdyatdlSHwRkPVFfWduLRlvFgEt685e79xnKpVNe2zlG41+Ekk/MR3ZNgYyHrEzf/BgjG/BwLWQmvUEx7LKIYLelI3JntdgLeVXyX01+cLkNmP3AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAAQrWCHxwwCaREh1TORtlH9+xR8gvmP0C4v7nYl3Y5MyFleXO2MQzqdbXBANCHxmYNMCJfYIpjz4j38UpIdhMFlo2cXdN1LdwbiAC7GAcxiI+81JzWlXuiTLp74YpCoB7tm+yCUD8k3hufEr5i88HTCwGzrN4Rq4D7MvEPxFwU6/bVP6rMRZTeBB60ZwwuttXsl0aslChMMTwhdCnl9Vp7U5kvn3MzFXhlbKqXblnsE81GZCQ/rsnRiIdbuygtivsgnKBol5IeSVYKaPvZL7fDDluMPbWxsW55kQttWt6DVEijBqO5EAKVbLLgtFwaFi6n1t2ncABnxCIzqyF/73BOQ=</dsig:X509Certificate>
                </dsig:X509Data>
                <dsig:KeyValue>
                    <dsig:RSAKeyValue>
                        <dsig:Modulus>iiKcQl02W8vWIUXpGJPzJ9y/cAlHiEoYDvRO69vHyj6i0h58f5hJMYL4lQUQpU1K8iAfxE+nGZunV57ARlQqwMMNduXYn3TsO1GfQxU1BH8QAau1rY96CEVSR7wBcFe/RjAwWwyByb2+8crJgwY7L3CP72zBpBTSboPqTjJ7dddmaYtPDudjX54598pOSwv2R5XlsoGApDaFrP80epZD1OoT0oNazE8Lo6SD1sjXcmrXZUh8EZD1RX1nbi0ZbxYBLevOXu/cZyqVTXts5RuNfhJJPzEd2TYGMh6xM3/wYIxvwcC1kJr1BMeyyiGC3pSNyZ7XYC3lV8l9NfnC5DZj9w==</dsig:Modulus>
                        <dsig:Exponent>AQAB</dsig:Exponent>
                    </dsig:RSAKeyValue>
                </dsig:KeyValue>
            </dsig:KeyInfo>
        </dsig:Signature>
        <saml:Subject>
            <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">G-1794718f-94ab-4dfa-a5b4-03867ca53a5e</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData InResponseTo="ONELOGIN_9200991dccb56c1b7c4560759b5e1ffffd12d15b"
                                              NotOnOrAfter="2020-02-11T03:39:13.999Z"
                                              Recipient="http://localhost:9191/saml/authorized"
                                              />
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2020-02-11T03:34:13.999Z"
                         NotOnOrAfter="2020-02-11T03:35:13.999Z"
                         >
            <saml:AudienceRestriction>
                <saml:Audience>dns-saml</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2020-02-11T03:34:15.999Z"
                             SessionIndex="b8aafc76-a304-446b-b898-a3637c69963b::7bdbd9c7-5d25-4cd0-b633-3e351a91749e"
                             SessionNotOnOrAfter="2020-02-11T13:34:15.999Z"
                             >
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >read-token</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >dns_client</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >view-profile</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >Administrator</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >admin</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >manage-account</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >uma_authorization</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >offline_access</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >manage-account-links</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >dns_user</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>

**Comment by ngoduykhanh** [comment]
Hi @minhlepham ,

The Onelogin saml lib gave the error that you can see from the PDA's web page, `invalid response`. I think there might some misconfiguration in your IDP side. Not sure what it is, I never use keycloak before.
btw, please format your code.

**Comment by minhlepham** [comment]
Can I chat with you on the email? my email is minh.hcm1993@gmail.com

**Comment by OliverW87** [comment]
Hi,
i was running in the same error yesterday.

After some analyse i found an unducumented SAML Value which i needed to adjust.

SAML_WANT_MESSAGE_SIGNED = False

i hope thats the same issue

kind regards
Oliver

**Comment by vmarkop** [comment]
Hello,

are you still running into this problem?

A SAML Configuration UI Update (#1082) is on the way, including minor bugfixes. If this issue is still relevant, a fix can be included in this upcoming update, otherwise it can be closed.

**Comment by vmarkop** [comment]
Closing this stale issue. Remember that PRs #1189 and #1203 include SAML bugfixes. If this problem persists, do not hesitate to open a new Issue.

Thank you.
