### ISSUE TITLE
Feature Request: Ability to set a default account for users automatically applied to domains

### ISSUE THREAD

**Issue by sonics6** [PowerDNS-Admin/PowerDNS-Admin#667]
hello

if a user adds a dns zone with his login and does not manually choos the account, the admin can not see that this zone belongs to that user at the dashboard.
i would suggest that if a user belongs to an account and adds a zone that this get added with the default account from that user.

**Comment by jbe-dw** [comment]
Hello

Sorry for the late answer, the team has changed. Today users are member of accounts. We have no obligation to set an account to a zone, and don't have such option to put a default.

This could be an option in a future release if it is requested.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
