### ISSUE TITLE
Login failure on oAuth user due to duplicate email gives unclear message

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#677]
When logging in as a new user (either by self-registration, or via one of the oAuth methods) the system will fail to log in if there already exists a user with the same email address (such as a local-database admin user).

However the error message generated is simply "Cannot create user" or "login failed".

The system ought to give a better indication of the root cause, such as "A user with this email address already exists, cannot create another"

This may be awkward as the create_user function only returns a failure and not a reason for that failure; maybe the code should first check for existence, or (better) the function should return a reason code on failure.

**Comment by ngoduykhanh** [comment]
Which oAuth method did you use? If there is a local user with the same email address as the user you are authenticated via OAuth, you will be logged as that user instead of creating a new account.

**Comment by sshipway** [comment]
This was when I was testing the Microsoft oAuth, and my tests failed because there was a local user with the same email address.  Changing that let it work as expected.  
This is probably because the code in index.py for azure tokens searches the database for a matching username rather than a matching email address, and Azure usernames are not just the email address.  The oidc code does the same, but the google and github code falls back to searching for a matching email if it cant match the username -- possibly, the oidc and azure sections should do the same?

**Comment by ngoduykhanh** [comment]
Yes, I think we should do the same for ODIC and Azure to allow users to login. Otherwise, we need a better error message :).
