### ISSUE TITLE
First request to OAuth routes might result in 404

### ISSUE THREAD

**Issue by eht16** [PowerDNS-Admin/PowerDNS-Admin#678]
The `/oidc/authorized` route is added dynamically on the first request using Flask's `before_app_first_request` decorator. However, this code is ran *after* the route matching of that very first request and so if this first request is for exactly this route, it will always end in a 404.

It happens with gunicorn and uwsgi (maybe more servers) if multiple workers are used and a fresh worker gets its first request for the `/oidc/authorized` route. For users this will look like intermittent 404s which might be hard to debug.

This is regardless of running the app with uwsgi, gunicorn or even the builtin debug server. It affects the Github, Google, Azure and OIDC OAuth mechanisms.

Without having tried it, I think defining the `/*/authorized` routes statically like all other routes will be a possible solution. We need just to find a clean way to access the later created `oidc` instance.

It is easy to reproduce:

Start the debug server like:
`FLASK_APP=powerdnsadmin venv/bin/flask run`

and then make requests to `/oidc/authorized`, e.g.:

```
[12:00:11] enrico@host (0) : ~% curl -si 'http://localhost:5000/oidc/authorized' | grep "^HTTP/"
HTTP/1.0 404 NOT FOUND
[12:00:17] enrico@host (0) : ~% curl -si 'http://localhost:5000/oidc/authorized' | grep "^HTTP/"
HTTP/1.0 400 BAD REQUEST
```

The first request is a 404, all following requests are properly handled (the 400 Bad Request is expected here as the curl request is not valid but good enough to demonstrate the issue).

**Comment by jodygilbert** [comment]
Any reason why these routes cannot be added statically with the rest of the routes?

**Comment by joachimtingvold** [comment]
@AzorianMatt, was this actually resolved? I just stumbled upon this as I can see the same behaviour myself on a fresh setup (using v0.4.1).

**Comment by AzorianMatt** [comment]
> @AzorianMatt, was this actually resolved? I just stumbled upon this as I can see the same behaviour myself on a fresh setup (using v0.4.1).

I doubt this was resolved. Many much older issues on the project were just closed in large batches due to inactivity and inability to address them with current resources.
