### ISSUE TITLE
ADFS Setup

### ISSUE THREAD

**Issue by Criz24** [PowerDNS-Admin/PowerDNS-Admin#682]
I am having some trouble configuring SAML with my ADFS IDP. 
I have the following configured in my default_config.py:

`# SAML Config
SAML_ENABLED = True
SAML_DEBUG = True
SAML_PATH = os.path.join(os.path.dirname(__file__), 'saml')
SAML_METADATA_URL = 'https://<redacted>/FederationMetadata/2007-06/FederationMetadata.xml'
SAML_METADATA_CACHE_LIFETIME = 1
SAML_IDP_SSO_BINDING = 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
SAML_IDP_ENTITY_ID = 'http://<redacted>/adfs/services/trust'
SAML_NAMEID_FORMAT = 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
#SAML_ATTRIBUTE_USERNAME = 'urn:oid:0.9.2342.19200300.100.1.1'
#SAML_ATTRIBUTE_ACCOUNT = 'https://dom/pdns-account'
SAML_SP_ENTITY_ID = 'https://<redacted>'
SAML_SP_CONTACT_NAME = '<redacted>'
SAML_SP_CONTACT_MAIL = '<redacted>'
#SAML_CERT_FILE = '/opt/web/powerdns-admin/<redacted>.cer'
#SAML_CERT_KEY = '/opt/web/powerdns-admin/<redacted>pem'
SAML_SIGN_REQUEST = False
SAML_LOGOUT = True
SAML_LOGOUT_URL = 'https://<redacted>/adfs/ls'
`
I have tried multiple difference claim issuance setting, but keep keeping invalid response errors from PDNS-Admin when testing logins. I also can't find any logs for SAML that help identify what the issue is to help narrow it down. 

Is there anyone, or any better documentation on what settings need to be, what claims need to be setup and where there are logs to help?

Thanks in advance.

**Comment by ngoduykhanh** [comment]
Please try to run with `./run.py` and get the logs from stdout if any. I never try with ADFS SAML before, but I tried with samlidp.io and it worked fine.
