### ISSUE TITLE
Allow Multiple PDNS api end points so we can remove zones on all servers

### ISSUE THREAD

**Issue by telefax** [PowerDNS-Admin/PowerDNS-Admin#687]
Thanks for this awesome and most excellent work bringing this tool to us! :)

**I have a feature request:**
Would it be possible to allow multiple Powerdns servers API end points?
This would allow us to have PowerDNS Admin delete zones on **all** servers from the web interface.
That would circumvent the problem where PDNS (super)master provisions Zones, but cannot delete them automatically when deleted from master.

Also, I guess this would allow us to skip setting up slave PDNS servers as well, since PowerDNS-admin will work as a master and send identical data to all API end points.

This would be different from other requests since it will only handle the DNS servers with the same content.

Thanks

**Comment by sshipway** [comment]
Support for multiple backends would be a great idea.  In many cases, you will have a master and at least one slave (the slave probably creating new zones using the supermaster feature of pdns) but there is no way to view and manage the slave form the same UI.  Having a selector (in the top bar?) to choose one of multiple backends would be very helpful.

**Comment by jbe-dw** [comment]
Same as #489

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
