### ISSUE TITLE
Dashboard not showing any domains

### ISSUE THREAD

**Issue by spadazz** [PowerDNS-Admin/PowerDNS-Admin#692]
Hello, my powerdns-admin instance became unusable after I changed the external proxy calling the site.
I can reach & authenticate correctly powerdns-admin, but the dashboard is not showing any domains.
Powerdns itself works correctly and the api too.
Data in powerdns mysql db is populated.
It seems that something prevents to get the domain query from powerdnsadmin database (populated too).

Please help, 'cause I'm stuck here.
Henry

**Comment by ngoduykhanh** [comment]
Do you see any log from PDA? Also, try to catch the js error from your browser when visiting the domain page. In chrome, right click on the page -> Inspect -> Console.

**Comment by spadazz** [comment]
Thanks for your reply.
I already checked the logfile.log and it didn't show any error : 
`2020-04-06 08:52:38,408 - root - INFO - User "admin" logged in successfully. Authentication request from 192.168.10.4
2020-04-06 08:52:38,525 - app.views - DEBUG - Update domains in foreground
2020-04-06 08:52:38,530 - root - INFO - 14 Entrys in pdnsADMIN
2020-04-06 08:52:38,532 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8081
2020-04-06 08:52:38,574 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8081 "GET /api/v1/servers/localhost/zones HTTP/1.1" 200 3354
2020-04-06 08:52:38,575 - root - INFO - 14 Entrys in PDNSApi
2020-04-06 08:52:38,576 - root - INFO - Update finished
2020-04-06 08:52:38,587 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8081
2020-04-06 08:52:38,591 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8081 "GET /api/v1/servers/localhost/statistics HTTP/1.1" 200 3796
`
The javascript console instead showed errors related to pagespeed : 
`Loading failed for the <script> with source “http://dns.gruppo4.it/_.pagespeed.jo.oGOFbNCkw9.js”. dashboard:31:1
Loading failed for the <script> with source “http://dns.gruppo4.it/_.pagespeed.jo.1onXg_v8V7.js”. dashboard:1:1
PSA ERROR: Exception while evaluating.pagespeed.CriticalImages is undefined 
`
So I added 'pagespeed off' in my nginx proxy config and now it's working !!
I just did a general check adding/deleting domains/record and everything seems OK.

Thanks a lot. :)

**Comment by spadazz** [comment]
I'm just curios about this...how can a javascript error prevent a backend query to get the data ?
Maybe during the rendering of template an exception occurred and exited before the query ?

**Comment by ngoduykhanh** [comment]
I don't think it prevents the backend query. It was the issue with rendering due to the JS error I think. The domain table relies on JS a lot.

**Comment by Nemega** [comment]
I do have the same issue. I am not using docker. 
Pressing F12 shows me a ERR_CONNECTION_RESET request:

http://10.10.10.150/dashboard/domains-custom/forward?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns... (even longer)

Any help would be appreciated.
