### ISSUE TITLE
Feature request: Customizable Logo and Title

### ISSUE THREAD

**Issue by righter83** [PowerDNS-Admin/PowerDNS-Admin#694]
Hi

First of all great and best project for PDNS-GUI!!

It would be great if there would be a config file for furthermore site modifications:

- Site Logo
- Site Title (not Tab Header)

I know you can change this in the templates.
But every update or changing the docker container you have to change it again.

Thanks

**Comment by sshipway** [comment]
Yes; the Site Title should also be displayed in the top bar of the UI and the Login Screen, not just in the window title.  Allowing for an optional Logo would be a good idea as well - and if you're doing that, then also allowing customisation of the colour scheme via CSS would be a good idea.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
