### ISSUE TITLE
Feature Request: External Provider avatar support

### ISSUE THREAD

**Issue by righter83** [PowerDNS-Admin/PowerDNS-Admin#695]
Hi

Maybe another small Feature Request:
It would be great to use an LDAP Avatar instead of Gravatar.

**Comment by sshipway** [comment]
If this is added, it might mean having to hold the avatar locally in the database, and so allow uploads.  However we could then also link to the Azure avatar for people using that authentication method.  It could be a can of worms though with all the different potential avatar shapes, sizes, formats and aspect ratios, I think

**Comment by righter83** [comment]
Hmm that's true, maybe an option to don't show an Avatar would be another option.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
