### ISSUE TITLE
Password reset option

### ISSUE THREAD

**Issue by TacoScheltema** [PowerDNS-Admin/PowerDNS-Admin#70]
Hi,

I'm missing an option to reset the password for a user when logged in as administrator.

I think it would be nice to have an option where an administrator can send an email with new (generated) password to a user. 

Also would be nice to have a 'forgot password' option on the login page so that a user can have a password reset url sent to his email address.

**Comment by madpsy** [comment]
Password reset links are the way to go rather than sending passwords in plain text over e-mail... apart from that this sounds good to me too.

**Comment by SIXwishlist** [comment]
Option "forgot password" is available?

**Comment by MakselPr** [comment]
Plus, it would be very helpful.

**Comment by jbe-dw** [comment]
Hello,

We are cleaning the issue tracker and closing your issue. You can follow the status here: #1178 

Regards
PowerDNS Admin Team
