### ISSUE TITLE
Feature Request: Add LDAP startTLS option

### ISSUE THREAD

**Issue by birkb** [PowerDNS-Admin/PowerDNS-Admin#701]
My LDAP server is configured to require startTLS on port 389. In the PowerDNS-Admin LDAP config i'm just using `ldap://ldapserver.fqdn` and than the user logins are failing with:
```
ldap.CONFIDENTIALITY_REQUIRED: {'desc': 'Confidentiality required', 'info': 'confidentiality required'}
```
Is startTLS activated in [user.py](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/models/user.py#L120)?

**Comment by ngoduykhanh** [comment]
I haven't tried with LDAP startTLS, however, I think after we initialize the LDAP connection, we need to call `start_tls_s` as well. 
https://www.python-ldap.org/en/latest/reference/ldap.html#ldap.LDAPObject.start_tls_s

**Comment by aretaja** [comment]
`--- /PowerDNS-Admin/powerdnsadmin/models/user.py_orig    2020-05-04 16:41:42.848518232 +0300
+++ /PowerDNS-Admin/powerdnsadmin/models/user.py         2020-05-06 16:45:46.765120569 +0300
@@ -126,6 +126,7 @@
         conn.set_option(ldap.OPT_X_TLS_DEMAND, True)
         conn.set_option(ldap.OPT_DEBUG_LEVEL, 255)
         conn.protocol_version = ldap.VERSION3
+        conn.start_tls_s()
         return conn`
Works for me.

**Comment by aretaja** [comment]
```
--- /PowerDNS-Admin/powerdnsadmin/models/user.py_orig    2020-05-04 16:41:42.848518232 +0300
+++ /PowerDNS-Admin/powerdnsadmin/models/user.py         2020-05-06 16:45:46.765120569 +0300
@@ -126,6 +126,7 @@
         conn.set_option(ldap.OPT_X_TLS_DEMAND, True)
         conn.set_option(ldap.OPT_DEBUG_LEVEL, 255)
         conn.protocol_version = ldap.VERSION3
+        conn.start_tls_s()
         return conn
```
Works for me.

**Comment by birkb** [comment]
Hi @aretaja and @ngoduykhanh 
This patch will make StartTLS mandatory, or? I will test it also in my environment, but a config option for users without an StartTLS LDAP setup would be good or?
> ```
> --- /PowerDNS-Admin/powerdnsadmin/models/user.py_orig    2020-05-04 16:41:42.848518232 +0300
> +++ /PowerDNS-Admin/powerdnsadmin/models/user.py         2020-05-06 16:45:46.765120569 +0300
> @@ -126,6 +126,7 @@
>          conn.set_option(ldap.OPT_X_TLS_DEMAND, True)
>          conn.set_option(ldap.OPT_DEBUG_LEVEL, 255)
>          conn.protocol_version = ldap.VERSION3
> +        conn.start_tls_s()
>          return conn
> ```
> 
> Works for me.

**Comment by sshipway** [comment]
There should be a new configuration option for ldap to enable TLS like this, rather than enforce it.  Also, this does not take into account if the LDAP is using LDAPS in which case starttls is not necessary.

**Comment by gondaz** [comment]
Adding LDAPS or LDAP with STARTTLS support looks like a feature request. Please, consider it to be implemented in one of the next versions. It would be very useful for me and other people who wants to use PowerDNS-Admin securely.
Subscribed.

**Comment by jbe-dw** [comment]
Hello,

Currently it works with LDAPS. We can change this to a feature Request to allow StartTLS.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
