### ISSUE TITLE
Add support to configure SLAVE-RENOTIFY per zone

### ISSUE THREAD

**Issue by Perflyst** [PowerDNS-Admin/PowerDNS-Admin#704]
Would be nice if SLAVE-RENOTIFY (with a checkbox or similar) could be enabled per zone through the frontend.

**Comment by florianbeer** [comment]
And also add the option to the API, so we could set it when creating a new zone :)

**Comment by sshipway** [comment]
Yes, this would be useful to have as a button on every Master zone.

**Comment by ngoduykhanh** [comment]
I see this option is available from [version 4.3.0](https://doc.powerdns.com/authoritative/domainmetadata.html#metadata-slave-renotify). Before having it, I think we need to consider how to handle different API versions first. The previous implementation didn't work well :)

**Comment by sshipway** [comment]
I think I've misunderstood the OP's request.  I was thinking of a button on the zone records list page that would call `PUT /servers/{server_id}/zones/{zone_id}/notify`, forcing a manual notify to all name servers.  Having read the doc above I see that slave-notify is something else.
... it might still be a good idea to have a way to manually force an immediate notify to all slaves though.

**Comment by Perflyst** [comment]
@sshipway that is something different, maybe open a new issue about your request?

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
