### ISSUE TITLE
[bug] Deleting zone does not cause return to zone list and refresh

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#707]
As it says.  When you delete a zone using the Admin option, the UI remains on the Admin page for the now-deleted zone.  Returning to the list shows that the zone was deleted correctly; however once a delete succeeds, the UI should automatically return to the list page and refresh to show the zone gone.

**Comment by ngoduykhanh** [comment]
Not sure how it could happen to you. Because we already handle the redirection after deleting the zone. [The code here](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/1d973d16141a6830d119cf1fe2802f56125e2957/powerdnsadmin/templates/domain_setting.html#L296).
Try to use the browser console (debug mode) to see if there is any js error when you delete the domain.

**Comment by sshipway** [comment]
The console shows:
"Blocked loading mixed active content "http://dnsadmin.smxemail.com/dashboard/""

This must be due to our having an https-proxy over the top, and the powerdns generating http URLs (which are then redirected to https by our proxy).  I had a similar issue with the Azure oAuth, where generated URLs had to be https for anything to work.  I suspect most users would want to use https when there is login data being sent, and so this will affect anyone using SSL offloading.

I think the only solution would be to make a flag in the configuration options for 'Use https URLs' that causes all generated URLs to have the `_scheme='https'` option added to all the `url_for()` calls.

**Comment by sshipway** [comment]
Come to think of it, in order to support all reverse proxies (not just SSL-offloading), it might be a good idea to allow the user to configure a Base URL to be used by `url_for()` instead of the default.

It might be that setting this in the config.py is enough
`  PREFERRED_URL_SCHEME = 'https'`

https://stackoverflow.com/questions/14810795/flask-url-for-generating-http-url-instead-of-https

**Comment by righter83** [comment]
got the same here, but haven't debugged it yet in firefox

**Comment by sshipway** [comment]
I've tried making the settings in the config file -- the `PREFERRED_URL_SCHEME` -- but this doesn't seem to correct the issue, probably because the `_external=True` is missing from most of the `url_for()` calls.  However, adding `, _external=True, _scheme='https'` to all the url_for calls does fix things, though it makes for a lot of changes. 

Ideally pdnsa should be flexible enough to support being behind an https reverse proxy without requiring code modification.  It might be that just adding the `_external=True` is sufficient for this, but it would need a lot of testing.

**Comment by Azylog** [comment]
Hello,
Same thing happens to us here. Same symtoms, same error (mixed content).
Pdnsa could also use a defined header from the reverse proxy.
For example, in nginx, we always set up rproxy with this line :
`proxy_set_header                X-Scheme $scheme;`
which should instruct the application that we're doing ssl offloading.

That's only a matter of a if testing the header and generating URLs scheme with the content of the header.

I'm not capable of this change but it would probably only take one our or two to a maintainer of the project.

Thanks

**Comment by jbe-dw** [comment]
Hello,

Does this still happends ?

Regards

**Comment by jbe-dw** [comment]
No answer within 10d, closing.
