### ISSUE TITLE
Templates are not properly syntax checked, causing new zone deployments based on them to be empty

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#708]
If you create a template with a minor syntax error - for example, omitting the double-quotes in a TXT record - and then deploy a new Zone based on that template, then the zone deploys but is empty.  This is presumably because the deployment of the template items to the zone fails; however, there is no error message displayed.

Ideally, in order of preference, one or more of these should happen --
* The template should properly syntax check and alert to the error (syntax prompts should apply to templates as well)
* The zone deployment should completely fail if the template is invalid, rather than deploying an empty zone
* A failed zone deployment should result in a visible error message to inform the user of template issues

**Comment by jbe-dw** [comment]
Hello,

This occurs because the zone is created in two steps, the zone, then the records. Adding invalid txt records indeed fails.

We should focus on syntax validation, in both edition and templates, to prevent these behaviours.
