### ISSUE TITLE
How to apply custom branding

### ISSUE THREAD

**Issue by terbolous** [PowerDNS-Admin/PowerDNS-Admin#716]
Hi,

I would like to do some minor tweaks to the layout to conform to company design guidelines.
What is the currently best way to do this? I am hoping to not have to keep my own branch up to date with upstream, but I am not familiar with python web frameworks.

**Comment by ngoduykhanh** [comment]
I don't your company design guidelines. However, except branding "PowerDNS-Admin" on the title, we don't have flexibility in other parts of UI. You have to modify the css/html code anyway.
They are in `templates` directory. `base.html` is the base layout. Other HTML files will extend this layout to have a full-page render.

**Comment by sshipway** [comment]
There's a certain amount you can do by modifying the CSS in custom.css, adding whatever is necessary.  This would allow colour changes and possibly background images in some cases.  You can change the displayed name as well, but there is not much scope for personalisation of the login page or placing a company logo there.

There is another feature request for company logo and heading customisation in #694

**Comment by mchlrv** [comment]
There seems to be no 'custom.css' file/folder in the docker build. Also there is no include for this file in the docker build. Can you please explain how to import it.

**Comment by jbe-dw** [comment]
Hello

@terbolous As explained, there is currently only a setting for adding custom CSS. There are other requests to customize Logo and Title, and, we duly note those many requests and will add it for sure in the roadmap.

@mchlrv I know it has been 1 year but here we are: You can set the filename in the custom_css fields in Basic Settings, and add the configured filename into powerdnsadmin/static/custom folder (which do not exist by default)
