### ISSUE TITLE
Feature Request: Provide an easier method for deployment (packages or ansible)

### ISSUE THREAD

**Issue by ffrediani** [PowerDNS-Admin/PowerDNS-Admin#719]
Isn't there an easier way to have it running on Ubuntu or Debian (and other distros) ? Perhaps via a .deb (or .rpm) package.

The current setup process (https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-or-Debian) isn't the simplest and more friendly which could be abstracted a lot via a simple apt/yum install.

If there isn't currently are there any plan to make this process in such way ?
Thanks

**Comment by terbolous** [comment]
Using snap could be an option? https://snapcraft.io/docs/snapcraft-overview 

I don't know if that exists on debian

**Comment by ffrediani** [comment]
I don't think so.
I mean either via package manager (whatever the distribution is) or via a .tar.gz file when it's the case.

Imagine every time someone need to install that have to do through all those steps, builds, pip, vitualenv, export, generate files, etc. It isn't the more friendly really.

**Comment by terbolous** [comment]
For the end user it is simply a `snap install powerdns-admin`.
Snap is becoming the standard way for many applications to distribute on ubuntu, especially for applications that may require packages or versions not available in the regular repository

**Comment by ffrediani** [comment]
Yeah, snap could certainly help. It would be better than the current way, but having it in the package managers is even better as natural to most people if possible. I guess the main issue as you mentioned is the dependency on specific packages and versions not always available in regular repositories. Perhaps that can be worked out as well.

**Comment by Arteneko** [comment]
I mean, this tool uses both Python and NodeJS.

Why not just package it using respective tools?

Both pip and npm are made for efficient server-oriented package deployment and setup, there is no need for either snap or the system's package manager.

**Comment by ffrediani** [comment]
Exactly, make it easier for most users in general to install, not just for developers.

**Comment by jbe-dw** [comment]
Hello,

You can use docker instead. To give a short answer:

- snap is natively available on ubuntu. It can be used on debian but it is not adopted, so targeting snap is not matching most of the audience
- packaging is not quite hard, but is not as easy as doing a zipfile. Considering it includes a virtualenv with many libraries (python, npm), it is not straightforward.
- packaging python and npm is not a good idea either, as it wouldn't work out of the box.

We are aware that the installation is relatively complex. It can be leveraged by automation tools like ansible, or disappear by using docker images. As we don't have skills to implement a steady packaging process, we can't do it now. But we hear you.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
