### ISSUE TITLE
Can't add ALIAS record

### ISSUE THREAD

**Issue by krismach** [PowerDNS-Admin/PowerDNS-Admin#726]
Trying to add ALIAS record through powerdns-admin fails with:

Record domain.org./ALIAS microsoft.com: Not in expected format (parsed as microsoft.com.)

Using pdnsutil adds it correctly:

pdnsutil add-record domain.org @ ALIAS microsoft.com
New rrset:
domain.org. 3600 IN ALIAS microsoft.com

Once it's added with pdnsutil it can be edited by powerdns-admin. But if it doesn't exists, it fails to create it.

PowerDNS-ADMIN: latest master
PDNS: 4.3.0

**Comment by RoeiGanor** [comment]
Try to enable record helper in the settings.

**Comment by krismach** [comment]
Record helper is already enabled.

**Comment by vdchuyen** [comment]
Well, you should add a **Period**  after the value domain. 

domain.org. 3600 IN ALIAS microsoft.com.
