### ISSUE TITLE
Creating a user without filling email should not be allowed

### ISSUE THREAD

**Issue by brlumen** [PowerDNS-Admin/PowerDNS-Admin#728]
The error occurs if there is already a user in the system without a completed email field.

![image](https://user-images.githubusercontent.com/26021974/81770070-616d0380-9509-11ea-884e-b9c51000b87a.png)

Error!
Email address is already in use

**Comment by ngoduykhanh** [comment]
This should not be allowed. We will need to adjust the code to always ask for an email when creating a user from the portal.
