### ISSUE TITLE
[feature] Display current SOA-EDIT-API setting in zone admin page

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#730]
Currently, the zone admin page only shows 'Unchanged' for both SOA-EDIT-API and Domain Type.  It would be much better to have these displaying the current value of the setting - particularly for SOA-EDIT-API where it is not always clear what the current setting is.

**Comment by jbe-dw** [comment]
This is a good idea. It may require to store them in the db, I have to check.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy

**Comment by subbink** [comment]
I would like to implement this feature.
