### ISSUE TITLE
[bug] Get zone with user API key by the zones id (with ending dot)

### ISSUE THREAD

**Issue by zwiy** [PowerDNS-Admin/PowerDNS-Admin#732]
Hi,
I created a user API Key with access to the domain `testing.example.org`.
This works fine.
```
{
    "description": "test user key",
    "domains": [
        "testing.example.org"
    ],
    "role": "User"
}
```
With this API key I'm able to get this specific zone if there is NO ending dot "." in the URL (.../localhost/zones/testing.example.org).
```
curl --location --request GET 'https://powerdns-admin/api/v1/servers/localhost/zones/testing.example.org' \
--header 'X-API-KEY: <my-api-key>'
```
If there is an ending dot i get the following answer:
```
curl --location --request GET 'https://powerdns-admin/api/v1/servers/localhost/zones/testing.example.org.' \
--header 'X-API-KEY: <my-api-key>'

403 Forbidden
{"msg": "Domain access not allowed"}
```
But if I use an `Admin API Key` it's possible to get the zone in both ways.

My problem is that some libraries (for example https://github.com/ffledgling/pdns-go) are using the ending dot to request a zone.

Thanks!

**Comment by danijelt** [comment]
I have the same issue with acme.sh using PDNS API. Another issue is that PowerDNS-Admin expects `Content-Type: application/json` which acme.sh isn't sending.

I fixed it by rewriting the URL in Nginx like this:
```
location /api/v1/servers/localhost {
	rewrite 		^/(.*)\.$ /$1 permanent; # Remove trailing dot
	proxy_set_header	Content-Type "application/json"; # Set content type header
	proxy_pass		http://powerdns-admin;
}
```

**Comment by jbe-dw** [comment]
Hello,

This should work as intended now. 

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
