### ISSUE TITLE
OIDC - User update and role/account mapping

### ISSUE THREAD

**Issue by maximumG** [PowerDNS-Admin/PowerDNS-Admin#740]
As discussed in #718 I'd like to propose enhancements regarding OIDC concerning the following points.

### OIDC role mapping

The User's role (Operator, Administrator) could be mapped to a claim in the ID token/user info endpoint of the OIDC provider. This feature allows to create the User and its authorization directly on the OIDC provider and have the User fully created on first login (identity + role).

#### Implementation

Create an additionnal setting in the OpenID Connect OAuth tab to specify in which claim to find the user role with the same syntax as [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc/wiki/Authorization#claims-as-nested-array) to traverse nested claims

As example Keycloak OIDC provider use the following structure for OIDC roles

```json
{
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
    ]
  },
  "resource_access": {
    "powerdns": {
      "roles": [
        "operator"
      ]
    }
  }
}
```
The settings could have a value of `ressource_access.powerdns.role`. The code will then check for the first role in the array which has a mapping in the PowerDNS admin roles.

### OIDC Account mapping

The Account a user belongs to could be mapped to a claim in the ID token/user info endpoint of the OIDC provider. On first User login,  this will allow the automatic creation of:
* Account (e.g departement/company)
* User in powerDNS-Admin during first login with their Primary Account

#### Implementation

Create an additionnal setting in the OpenID Connect OAuth tab to specify in which claim to find the user Account with the same syntax as [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc/wiki/Authorization#claims-as-nested-array) to traverse nested claims

As example:

```json
{
  "company": "super-company"
}
```
The settings could have a value of `company`. The code will then create the account automatically, create the user automatically and associate the use to the Account.

### OIDC User update

The [code regarding OIDC](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/0ef132a7be7a3c8b21809c1570a4e8a98a8343c2/powerdnsadmin/routes/index.py#L293) is not updating user attributes each times he connects. It could be useful to update user attributes at each login in case the user changes its email.

I can work on a pull request if @ngoduykhanh is interested in this ?

**Comment by ngoduykhanh** [comment]
Hi @maximumG ,

Thank you for giving me the idea about OIDC enhancement. Yes, role mapping is helpful. As long as the new improvement can fit the generic use case, I am happy to merge it.

Your approach looks good to me. Feel free to submit your PR :-).

btw, regarding the ODIC User update, it is nice to have user-profile auto-update every time they log in. However, we need to handle it properly. Especially the email and username which are unique. Please make sure the new user's email isn't used in other PDA users yet.

**Comment by iceman91176** [comment]
We are also interested in this. Passing the roles in the token is the right approach in my opinion. Mapping the OIDC-roles to the powerdns-admin roles can be done in the same way  azure-mapping is done. First look for admin role, then for operator....
Updating the userprofile should be a nice enhancement.

Duplicate username/eMail: There should be an error-message at least (User with eMail/username ... already exists). I don't think there is an use case with multiple OIDC-Providers, or loging with local user AND SSO-User, so duplicate eMails won't happen to often.

@maximumG do you plan to submit a PR ?

**Comment by jbe-dw** [comment]
@vmarkop Can you take a look ?

**Comment by jbe-dw** [comment]
#1002 should do what you expected. If so, please wait that it get merged.

Regards

**Comment by vmarkop** [comment]
Hello. Indeed, role/account automatic mapping on login is handled by PR #1002.

Thank you
