### ISSUE TITLE
[feature] Show changes summary in confirmation window before Apply

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#741]
When applying changes, you get a confirmation window but this does not show you what you are about to apply.  This makes it hard to be able to confirm as you don't know for sure what you are confirming...

It would be much better if the popup "Are you sure you want to apply?" window also included a summary of the changes - possibly as a small scrolling area containing the JSON, as you would see in the History logs, since the JSON would likely be too large to show without scrolling.

**Comment by a1d3s** [comment]
Would be nice

**Comment by sshipway** [comment]
I'm not completely clear on how the system works, but I think the confirmation window is generated by the Javascript only - IE locally - and the JSON for the apply is only calculated when the backend is called to do it for real.  So this might be a bit more complex as an additional call to the backend would need to be made to request the proposed JSON, before calling 'for real'.  The functions at the moment calculate what will be applied (by comparing the returned data and the database query) just before applying, so there would be a potential race condition -- if the database were changed between displaying the proposed changes, and actually doing it, it is possible that more could be applied than predicted.  It does check for a SN change but that doesn't catch changes such as someone using pdnsutil on the host to make updates.

**Comment by zoeller-freinet** [comment]
Related: #92

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. #92 is listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
