### ISSUE TITLE
only optic request

### ISSUE THREAD

**Issue by a1d3s** [PowerDNS-Admin/PowerDNS-Admin#743]
![image](https://user-images.githubusercontent.com/9554318/82784593-294ab680-9e61-11ea-94ab-4cd92bdc89f6.png)
Users are synced from Active Directory 
The Lastname field is empty and the full Name is under first name

**Comment by jbe-dw** [comment]
Hello,

Does it still occur ?

Regards

**Comment by a1d3s** [comment]
Will have a Look at monday. After so long time i forgot this request

**Comment by a1d3s** [comment]
ok now i had a look and the "error" persist.
yesterday i install a new pdns and pdns-admin (docker:latest) , same thing
but i think you can get it a low prio :)

**Comment by jbe-dw** [comment]
I'm not sure that the docker container is up to date, i still don't have time to dive in docker stuff.

Thanks for the feedback.

**Comment by a1d3s** [comment]
your bug #1181 is in the docker latest version  included ;)
