### ISSUE TITLE
Feature Request: Support multiple ldap backends

### ISSUE THREAD

**Issue by a1d3s** [PowerDNS-Admin/PowerDNS-Admin#748]
A second or third ldap maybe possible?
One for Administration and one for Users. 
I think its more secure.  I have an ldap for Support/Admin Users internal an the Users are external. 
Only other Idea is Setup a second docker for users

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
