### ISSUE TITLE
Auto PTR Replication to Slave Server

### ISSUE THREAD

**Issue by alexpablo** [PowerDNS-Admin/PowerDNS-Admin#750]
When I create a record on a zone it replicated to slave server and create auto PTR on master, but the PTR zone is not replicate to the slave server because is new and is create without NS records on the zone. It’s possible to replicate on slave servers the new PTR zones create automatically on master server without NS records?.

**Comment by jbe-dw** [comment]
Hello,

Sadly the auto_ptr feature is not complete. It is not possible to make it happen, because your slaves must be autosecondary in it relies on the zone NS record.

This bug is known and we will decide later to improve it or drop support.

Regards
