### ISSUE TITLE
Active Directory depending on OpenLDAP config options in order to enable Active Directory

### ISSUE THREAD

**Issue by trenb** [PowerDNS-Admin/PowerDNS-Admin#753]
**UPDATE**: Turns out the OpenLDAP "Group filter" and "Group name field" need to be populated before you can enable Active Directory LDAP. Don't need to be valid, just need to exist. Tested this in 0.2.2 and lastest master, had to do the same workaround.

Original Issue:
Trying to enable Active Directory Auth on v0.2.2. I fill in:

Enable LDAP Authentication checked
Active Directory selected

LDAP URI: ldap://x.x.x.x:389
LDAP Base DN: OU=Staff,DC=domain,DC=com
Active Directory Domain: domain.com

Basic Filter: (objectClass=organizationalPerson)
Username Field: sAMAccountName

Group Security: OFF

But the Save button is greyed out and hovering over it gives a crossed circle. No errors are being given. Why won't it let me save? I'm logged in with a local admin account.

Nothing is logged by the application. Running in gunicorn mode, with nginx in front. Any ideas why this won't save?

**Comment by trenb** [comment]
Is this supposed to work? No matter what values I use, it won't let me save an AD config

**Comment by trenb** [comment]
Correct that, I can save if I uncheck "Enable LDAP Authentication". But as soon as I check "Enable LDAP Authentication", I cannot save.

**Comment by trenb** [comment]
I pulled the latest master, and same issue. Unable to enable LDAP Authentication.

**Comment by trenb** [comment]
It seems like "Group filter" and "Group name field" needs to be filled in for some reason. If I change the Type radio to OpenLDAP, and fill in "Group filter" as "zzz" and "Group name field" as "zzz" and then change the radio back to "Active Directory", I can now save, and use AD LDAP Auth.

Feels like this is a bug. Same on v0.2.2 and master.

**Comment by trenb** [comment]
Yeah, everything works as expected, so long as "Group filter" and "Group name field" have a value set. Once that's the case, I'm able to save my Active Directory config, and it works as expected.

Same on v0.2.2 and master.

**Comment by firthmj** [comment]
I believe the patch needed to fix this is:

```
--- aaa/powerdnsadmin/templates/admin_setting_authentication.html	2020-07-06 11:03:39.060386389 +0100
+++ bbb/powerdnsadmin/templates/admin_setting_authentication.html	2020-07-07 09:49:16.241830814 +0100
@@ -613,15 +613,17 @@
                 $('#ldap_admin_username').prop('required', true);
                 $('#ldap_admin_password').prop('required', true);
                 $('#ldap_domain').prop('required', false);
+                $('#ldap_filter_group').prop('required', true);
+                $('#ldap_filter_groupname').prop('required', true);
             } else {
                 $('#ldap_admin_username').prop('required', false);
                 $('#ldap_admin_password').prop('required', false);
                 $('#ldap_domain').prop('required', true);
+                $('#ldap_filter_group').prop('required', false);
+                $('#ldap_filter_groupname').prop('required', false);
             }
             $('#ldap_filter_basic').prop('required', true);
-            $('#ldap_filter_group').prop('required', true);
             $('#ldap_filter_username').prop('required', true);
-            $('#ldap_filter_groupname').prop('required', true);

             if ($('#ldap_sg_on').is(":checked")) {
                 $('#ldap_admin_group').prop('required', true);
```

**Comment by jbe-dw** [comment]
Hello,

It has been refactored since. Please open a new issue if you still encounter problem using Active Directory.

Regards
