### ISSUE TITLE
API SRV and MX Record

### ISSUE THREAD

**Issue by TheKingOfChaos** [PowerDNS-Admin/PowerDNS-Admin#757]
i can't find any information how to use the api to create MX and SRV records

**Comment by jbe-dw** [comment]
Hello @TheKingOfChaos 

Sorry for the late answer, staff has changed and we're cleaning the tracker. I know that document improvments are still needed, so to be short here: The PDA API to manage content just forwards to PowerDNS API. Please look at the PowerDNS documentation.

Basically the records should be sent in a RRSET dict with the name, type and value (which is a list of strings). For a domain MX record, the rrset name should be the domain, the type "MX" and the value could be like `["10 mx1.example.org.", "20 mx2.example.org."].

Be aware that PowerDNS always expects fqdns with the trailing dot.

Regards
