### ISSUE TITLE
Recursivity can fail

### ISSUE THREAD

**Issue by karasz** [PowerDNS-Admin/PowerDNS-Admin#764]
ad_recursive_groups is a recursive function. It will fail with "maximum recursion depth exceeded" if there are cyclic groups. Since cyclic groups are allowed by AD the function should have  a safeguard. Probably it would be beneficial to check first if the users direct groups are the ones we want and begin recursive only if neither of the three groups is directly in the users groups.

**Comment by jbe-dw** [comment]
This is fixed in current version. See #1118
