### ISSUE TITLE
Feature Request: Bulk domain creation with a template

### ISSUE THREAD

**Issue by XeryusTC** [PowerDNS-Admin/PowerDNS-Admin#767]
Sometimes we need to add multiple different domains (variants and to prevent typo squatting) with different TLDs. This means that sometimes we have to add multiple domains in one go. For some domains this means that we need to add 70+ domains at a time. All of the domains use the same template and settings so it would be nice if the interface allowed entering multiple domain names to be added.

**Comment by jbe-dw** [comment]
Good idea, we keep track.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
