### ISSUE TITLE
[feature] Make Disabled records more visual

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#770]
PowerDNS supports 'disabled' records, where a flag indicates that a record is in the database, but not served.  However PowerDNS-Admin does not recognise this, and disabled records are displayed as normal.

Ideally, disabled records would be in some way highlighted (displayed in italics, or grey font?) and there would be a disable/enable button next to the Edit and Delete buttons to manage this.

**Comment by jbe-dw** [comment]
The option for disable records exists now, however it could be more visual. I take not for this as well

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
