### ISSUE TITLE
[feature] Make it possible to set "auto ptr" per record creation

### ISSUE THREAD

**Issue by firthmj** [PowerDNS-Admin/PowerDNS-Admin#778]
Hi,

Currently there are two auto ptr options, one global and one per domain.

One feature that another PowerDNS client has that PDA lacks is the ability to request this per record at creation / update time.

Sometimes you want to have multiple A records for the same system, but only want the PTR to attempt to be set for one of them. Obviously if you create / update in the right order, the last will win, but it means unnecessary updates to the reverse DNS tables.

Having a check box somehow to allow this to be toggled as records are changed would be good.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
