### ISSUE TITLE
How do the different auto_ptr settings interact

### ISSUE THREAD

**Issue by firthmj** [PowerDNS-Admin/PowerDNS-Admin#779]
Hi,

There is a global "auto_ptr" configuration item, and a per domain check box for "Auto PTR creation". Which one takes precedence?

I guess I could experiment to see, but this should really be documented somewhere!

**Comment by jbe-dw** [comment]
The global setting enables it on every domain. If toggled off, the auto_ptr feature could be enabled per domain.

Regards
