### ISSUE TITLE
Feature Request: Description column for each Basic Settings

### ISSUE THREAD

**Issue by firthmj** [PowerDNS-Admin/PowerDNS-Admin#780]
The Basic settings screen seems to have no guidance for what any of the settings here mean or do. Some are probably relatively obvious, but it seems to be about the only part of the GUI where there are no explanations or examples for the fields.

Would it be possible to add a "Description" column, or at least a "tooltip" for each setting?

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
