### ISSUE TITLE
[feature] Read only mode and role defaults

### ISSUE THREAD

**Issue by firthmj** [PowerDNS-Admin/PowerDNS-Admin#781]
It looks like currently the three roles that are available are:

Administrator: Can Control everything
Operator: Can change some settings, by default can manage all domains (but other operators or administrators can remove)
Users: By default, can do nothing, operators or administrators can give "full control" to some domains

(again, is this documented anywhere?)

For my use case having an option where it was possible for some users to see and search the contents of domains, but not to be able to edit them.

So having the option of setting "read only" in the per domain access control would be a big feature improvement.

Having a way of controlling the default access settings for the different roles would also be a great enhancement - being able to somehow say that "operators can edit all domains by default, but not create new ones or delete them, and users have read only access to all domains" would give a great way of customising the access policy.

**Comment by dmgeurts** [comment]
I had interpreted the user role as read-only. Only to find that the permissions are pretty much on how much full access an account has.

My preference would be that Operators can't change pdns settings, but they can. Can this be disabled?
And for users to be able to see all domains, and the records contained in them, but no edit rights.

**Comment by jbe-dw** [comment]
Hello,

This will be supported by #1171

**Comment by jbe-dw** [comment]
#1099
