### ISSUE TITLE
Update frameworks in PowerDNS

### ISSUE THREAD

**Issue by the-missing-pink** [PowerDNS-Admin/PowerDNS-Admin#782]
At the moment PowerDNS has admin-lte 2.4.9 and bootstrap 3.4.1 as framework. These are both released in february 2019. Meanwhile stable major versions of admin-lte (current 3.05) and bootstrap (current 4.5.0) have been released. I would like to see these to be updated. If help is needed, i can help.

Especially since bootstrap 4 runs the styling in scss in stead of less, which makes it easier to customize colors etc.

**Comment by ngoduykhanh** [comment]
Sorry for the late response. I didn't have much time for this project. Yes, It is nice to keep the versions up-to-date. Feel free to submit your contribution with a PR. Thanks.

**Comment by jbe-dw** [comment]
@the-missing-pink Maybe you could help @RGanor with #1173 ?

The new maintainer team is not well versed in UI things.

**Comment by RGanor** [comment]
Hey @the-missing-pink, i started working on updating those, but as @jbe-dw said we are not really an UI experts and it giving me some problem.
I’ll be greateful for any help in #1170

**Comment by Metrax** [comment]
@RGanor i would help, but i have only limited time (some hours per week). I've started on my local dev to adapt the header and menu.
