### ISSUE TITLE
Instructions Incomplete on page Running PowerDNS Admin with Systemd, Gunicorn and Apache

### ISSUE THREAD

**Issue by jalberts9** [PowerDNS-Admin/PowerDNS-Admin#785]
I'm running Debian 10.  I followed the instructions to set up PowerDNS-Admin on the wiki page "Running PowerDNS Admin on Ubuntu or Debian".  Everything worked fine through the included web browser that comes up after running ./run.py.  However, I then followed the instructions on the wiki page "Running PowerDNS Admin with Systemd, Gunicorn and Apache" and I ran into several issues.  I decided against updating the wiki myself because perhaps I just goofed up.  However, it seems to me that the documentation is incomplete and I hope I can help with some specific feedback.

* The file/etc/systemd/system/powerdns-admin.service on the wiki page is set up to run as user pdnsa, but the instructions do not give steps that outline how to set up this user account.  The systemctl script fails because this account does not exist.  It would be helpful to include steps that show how to create this account

* Since the service/unit is running as this pdnsa user, the directories and files in /opt/powerdns-admin as well as /run/powerdns-admin need to be accessible by this user.  It would be helpful to include steps to chown and chgrp these locations to pdnsa because the systemctl script failed in my case because the directories were owned by root.

* In my situation, the provided ExecStart did not work because I did not have /usr/bin/gunicorn-3.6.  I updated ExecStart to run gunicorn at /opt/powerdns-admin/flask/bin/gunicorn.  That worked fine.

* I feel that the documentation is inconsistent insofar as the default configuration uses default_config.py as the config file, yet the included systemctl service file uses config.py.  To maintain consistency throughout the documentation, I feel that default_config.py should be provided in the example, along with a note to adjust the file to your own config if you are not using the default.

* For completeness sake, here's my ExecStart line showing both modifications:

`ExecStart=/opt/powerdns-admin/flask/bin/gunicorn --workers 4 --log-level info --pid /run/powerdns-admin/pid --bind unix:/run/powerdns-admin/socket "powerdnsadmin:create_app(config='default_config.py')"`

I ran into these problems several months ago and I totally gave up on installing PowerDNS-Admin because I could not solve them.  I came back to it yesterday and this time I was able to push through.  For me, a big problem was that I followed the steps in the documentation to the letter but frustratingly, still had issues.  I hope that someone will be interested in improving the documentation based on the feedback I am providing.  I may have had to do something else but forgot to put it here.  I spent several hours trying to get this working so it's entirely possible I forgot something that was critical to arriving at the solution.  I would be glad to answer any additional questions.

**Comment by mattg66** [comment]
What permissions did you set for the /opt/powerdns-admin and /run/powerdns-admin for the pdnsa user?

**Comment by mattg66** [comment]
What permissions did you set?

**Comment by jalberts9** [comment]
I'm pretty sure I kept the permissions as-is and only did chown and chgrp.

I'm not sure what you mean when you say solved. Not all of the issues I
discussed were related to the username.

I believe this is the page I referred to in my original post that shows the
user pdnsa:

https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Systemd-example

**Comment by opentokix** [comment]
I followed the nginx, systemd and gunicorn example - but the app seems to ignore the default_config.py and tries to create a sqlite-database. 

I have tried with bost adding a config='default_config.py' in systemd, and following the example exactly.
