### ISSUE TITLE
Feature Request: Add Templates placeholder for domain name

### ISSUE THREAD

**Issue by EasyNetDev** [PowerDNS-Admin/PowerDNS-Admin#788]
Hello everybody,

I'm wondering if the templates contain some keywords that they can be automatically changed when a new site is create.
I'm trying to achieve something like this:

Template:

www | CNAME | 300 | [DOMAIN]

After creating a domain this is automatically translated to:

www | CNAME | 300 | mydomain.ext

Kind regards,
Adrian

**Comment by Metrax** [comment]
+1
would also be useful for MX entries: mail.[DOMAIN] -> mail.example.com

**Comment by jgomila** [comment]
+1

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
