### ISSUE TITLE
[feature] Allow each DynDNS have its their own basic authentication

### ISSUE THREAD

**Issue by ASoTNetworks** [PowerDNS-Admin/PowerDNS-Admin#789]
It would be nice to have each DynDNS hostname have their own pair of user and password auth that could be set by the admin or if not defined it will generate the values randomly.

It would increase security than using the domain's admin account and a single password across different hosts that are outside of our control.

**Comment by dbenoy** [comment]
This goal could also be achieved by increasing the granularity for modification rights down to a per-record level (or perhaps regular expression? Like: `^(_acme_challenge\.)?managedname.example.com$` or `^www[0-9].example.com$`

But indeed, your suggestion might be better. It'd be nice to just click a button for 'make a dyndns2 username and password for this entry' and just have it spit out a randomly generated one, then paste that into your dyndns script on that specific server. That certainly would cut back on management effort.

Maybe both?

**Comment by ASoTNetworks** [comment]
Yup I was thinking about an option that clicking on a button that will generate a dyndns2 username and password or prompt for a manual user and password that can be set manually allowing scripts to update records with one set of login, with would be useful if #790 gets implemented too.

**Comment by jbe-dw** [comment]
Hello,

We didn't add this in the priorities since the maintaining team has changed (and are currently not that available). To give a neat answer: resources !

If someone can propose a PR I'd be happy to review.

Regards

**Comment by AzorianSolutions** [comment]
> any news on this?

The team of contributors is actively changing and a full project analysis is underway to bring progress back in. This feature request will certainly be considered and properly addressed for the overhaul that is pending. I can not make any promises or set any expectations on the timing of completion for this at this time. Just know, there are plans taking shape.
