### ISSUE TITLE
[feature]: Support for multiple PowerDNS servers

### ISSUE THREAD

**Issue by samip5** [PowerDNS-Admin/PowerDNS-Admin#791]
Use Case A: A user wants to be able to administer multiple PowerDNS servers from the same frontend, but the nameservers have nothing to do with each other.

Use Case B: A user wants to be able to administer multiple PowerDNS servers from one WebUI.

**Comment by iceman91176** [comment]
👍 

We need it for a split-dns scenario, but basically the same the same request.  Currently we are running multiple instances of powerdns-admin.

**Comment by Hedgehog57** [comment]
+1 for this FR. Split-dns is usual case IMHO.

**Comment by nwhisper2014** [comment]
+1 for this. I have 5 different PowerDNS Authoritative Server instances. It would be very nice to manage them from one PowerDNS Admin instance.

**Comment by sbeccato** [comment]
+1 fot his, we are currently using multiple PowerDNS instance for manage a split-dns scenario but would be fantastic to use just one web portal to manage multiple PowerDNS servers

**Comment by sbeccato** [comment]
Hi guys, is there a chance to see this implemented?

**Comment by mboy-rnd** [comment]
+100500 Manage multiple PowerDNS servers

**Comment by samip5** [comment]
I don't know how it's not understood that +1's mean nothing and only cause unnesseary chatter. Just the +1 on the first message is probably enough.

**Comment by jbe-dw** [comment]
Duplicate of #489
Already referenced in #1178
