### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by obi12341** [PowerDNS-Admin/PowerDNS-Admin#792]
We are currently using master, so we should have the latest code. Domains with txt record set got 500 error on detail page:

```
Jul 22 08:22:17 powerdns gunicorn[11437]: ValueError: not enough values to unpack (expected 2, got 0)
Jul 22 08:22:17 powerdns gunicorn[11437]:     r['records'], r['comments'] = (list(t) for t in zip(*sorted(zip(r['records'], r['comments']), key=by_record_content_pair)))
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/powerdnsadmin/models/record.py", line 70, in get_rrsets
Jul 22 08:22:17 powerdns gunicorn[11437]:     rrsets = Record().get_rrsets(domain.name)
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/powerdnsadmin/routes/domain.py", line 60, in domain
Jul 22 08:22:17 powerdns gunicorn[11437]:     return f(*args, **kwargs)
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/powerdnsadmin/decorators.py", line 60, in decorated_function
Jul 22 08:22:17 powerdns gunicorn[11437]:     return func(*args, **kwargs)
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
Jul 22 08:22:17 powerdns gunicorn[11437]:     return self.view_functions[rule.endpoint](**req.view_args)
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
Jul 22 08:22:17 powerdns gunicorn[11437]:     rv = self.dispatch_request()
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
Jul 22 08:22:17 powerdns gunicorn[11437]:     raise value
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
Jul 22 08:22:17 powerdns gunicorn[11437]:     reraise(exc_type, exc_value, tb)
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
Jul 22 08:22:17 powerdns gunicorn[11437]:     rv = self.handle_user_exception(e)
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
Jul 22 08:22:17 powerdns gunicorn[11437]:     response = self.full_dispatch_request()
Jul 22 08:22:17 powerdns gunicorn[11437]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
Jul 22 08:22:17 powerdns gunicorn[11437]: Traceback (most recent call last):
Jul 22 08:22:17 powerdns gunicorn[11437]: [2020-07-22 08:22:17,402] [app.py:1891] ERROR - Exception on /domain/**** [GET]
```

i already looked into it and this code seems to cause the problem: 
File `/opt/web/powerdns-admin/powerdnsadmin/models/record.py` in Line 70
```
 r['records'], r['comments'] = (list(t) for t in zip(*sorted(zip(r['records'], r['comments']), key=by_record_content_pair)))
```

If it helps this is what we got from the pdns api (i have removed personal data):

```
root@powerdns:/opt/web/powerdns-admin/powerdnsadmin# curl -v -H "X-API-Key: ***" http://localhost:8081/api/v1/servers/localhost/zones/*** | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /api/v1/servers/localhost/zones/*** HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.58.0
> Accept: */*
> X-API-Key: ***
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 1860
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Content-Type: application/json
< Server: PowerDNS/4.1.1
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
<
{ [1860 bytes data]
100  1860  100  1860    0     0   151k      0 --:--:-- --:--:-- --:--:--  151k
* Closing connection 0
{
  "account": "",
  "api_rectify": true,
  "dnssec": true,
  "id": "***.de.",
  "kind": "Master",
  "last_check": 0,
  "masters": [],
  "name": "***",
  "notified_serial": 2020072201,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [
    {
      "comments": [
        {
          "account": "",
          "content": "",
          "modified_at": 1595405471
        }
      ],
      "name": "***.",
      "records": [],
      "ttl": 0,
      "type": "TXT"
    },
    {
      "comments": [],
      "name": "**.***.de.",
      "records": [
        {
          "content": "xxx.xxx.xxx.xxx",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "***.***.de.",
      "records": [
        {
          "content": "xxx.xxx.xxx.xxx",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "***.***.de.",
      "records": [
        {
          "content": "xxx.xxx.xxx.xxx",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "***.***.de.",
      "records": [
        {
          "content": "xxx.xxx.xxx.xxx",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "***.",
      "records": [
        {
          "content": "\"v=spf1 a mx -all\"",
          "disabled": false
        }
      ],
      "ttl": 60,
      "type": "TXT"
    },
    {
      "comments": [],
      "name": "***.",
      "records": [
        {
          "content": "***. ***. 2020072201 10800 3600 604800 3600",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "SOA"
    },
    {
      "comments": [],
      "name": "***.",
      "records": [
        {
          "content": "***.",
          "disabled": false
        },
        {
          "content": "***.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "NS"
    }
  ],
  "serial": 2020072201,
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
  "url": "/api/v1/servers/localhost/zones/***.de."
}
```

i am not sure but i think the `\"` could cause the error.

**Comment by obi12341** [comment]
switching back to commit: `0ef132a7be7a3c8b21809c1570a4e8a98a8343c2` everything is working

**Comment by obi12341** [comment]
bug is probably introduced with commit https://github.com/ngoduykhanh/PowerDNS-Admin/commit/3476c8a9ec19d76156d58ec2f7c9621ed43a63fd#diff-f4f97de4a373573d84d038f6226d00dc

**Comment by Stat-Kaya** [comment]
I have the same error, if i delete over nsupdate more then 1 Entry.

**Comment by svaio** [comment]
As this seem not to be fixed let me add my observations:
1. Change "A" record with name docker e.g. TTL field -> save
2. Change "AAAA" record with name docker e.g. TTL field -> save
3. Save changes to PDNS

---> Error 500 !!!

Analysing files:
Output of API via CURL gives three records, where there should only be two?! The comments for the AAAA record are split in two pieces. 

"rrsets": [
    {
      "comments": [
        {
          "account": "",
          "content": "",
          "modified_at": 1598362663
        }
      ],
      "name": "docker.",
      "records": [],
      "ttl": 0,
      "type": "AAAA"
    },
    {
      "comments": [],
      "name": "docker.",
      "records": [
        {
          "content": "2a00::1234",
          "disabled": false
        }
      ],
      "ttl": 1800,
      "type": "AAAA"
    },
    {
      "comments": [
        {
          "account": "",
          "content": "",
          "modified_at": 1598362663
        }
      ],
      "name": "docker.",
      "records": [
        {
          "content": "1.2.3.4",
          "disabled": false
        }
      ],
      "ttl": 1800,
      "type": "A"
    },
...

May this be the error we are looking for. 

A fix is easy, "pdnsutil list-zone name.txt", "pdnsutil del-zone name" and "pdnsutil load-zone name name.txt --> error fixed till next change!!!

**Comment by KlaasT** [comment]
Is there any way to fix this bug except for deleting the zone and loading it again? Unfortunately the bug made this frontend useless for us :(

**Comment by luomoxu** [comment]
The table comments map records has some problem for not A records

**Comment by florianbeer** [comment]
Same problem here with some zones.
Deleting and reloading the zone via pdnsutil works as a quickfix.

But it would be interesting to know what causes this and to fix this bug.

PowerDNS-Admin was freshly updated from git today.

**Comment by ngoduykhanh** [comment]
Hi guys,
Sorry for my late response to this topic. Can someone help me with the steps to reproduce the issue? I tried with a few ones but didn't get the error. I'd love to fix this. Just let me know. Thanks.

**Comment by svaio** [comment]
You can test with ipv6. 
1. Create an AAAA record
2. Delete AAAA record
That should do it, if not, please activate "automatic reverse entry" in preferences and try again

**Comment by ngoduykhanh** [comment]
@svaio I tried with ipv6 adding. It looked good to me. (In both case of "automatic reverse entry").

**Comment by Stat-Kaya** [comment]
@ngoduykhanh Delete over nsupdate more then 1 Entry. Then you get a Page 500 Error and ValueError: not enough values to unpack (expected 2, got 0) inside the logs.

**Comment by dthuering** [comment]
Same issue here using the current docker latest image. Did add multiple AAAA records and changed TTLs.

**Comment by Tira007** [comment]
> Есть ли способ исправить эту ошибку, кроме удаления зоны и ее повторной загрузки? К сожалению, ошибка сделала этот интерфейс бесполезным для нас :(

To make PDNS-Admin useful, I had to roll back to the code in the code that are listed here in the record.py file https://github.com/ngoduykhanh/powerdns-admin/commit/3476c8a9ec19d76156d58c19d7c9621ed43a63fd#diff-f4f97de4a373573d84d038f6226d00dc

**Comment by SkylerNL** [comment]
I fixed this by removing all the comments from the pdns database itself.

**Comment by Daniel15** [comment]
Does anyone have a workaround for this bug? I just hit it with one of my zones :(

**Comment by Prandur** [comment]
@SkylerNL I can confirm this workaround.
I've got 6 domains in the frontend and have set 2 entries with it. Both entries got comments in the comments pdns db looking like this:

```
+----+-----------+----------------------+------+-------------+---------+---------+
| id | domain_id | name                 | type | modified_at | account | comment |
+----+-----------+----------------------+------+-------------+---------+---------+
|  1 |         1 | domainA | A    |  1601646612 |         |         |
|  2 |         5 | domainB     | A    |  1606999033 |         |         |
+----+-----------+----------------------+------+-------------+---------+---------+
```

When using the frontend, 4 domains worked as intended. DomainA and domainb both got an error 500 when trying to access with the stacktrace op posted.
After deleting both entries, the frontends for the affected domains worked again.


@ngoduykhanh maybe this helps to narrow down the reported issue.

**Comment by bynicolas** [comment]
I'm getting this issue too. I've noticed that the problem happens on the slave server after updating a record on the master server through the PowerDNS web API

**Comment by Daniel15** [comment]
@Prandur Thanks for the tip. I deleted some records from the `comments` table for the broken zone, and now I can load it again.

**Comment by Net-Felix** [comment]
quick and dirty fix is to disable the display of comments:
```
diff --git a/powerdnsadmin/models/record.py b/powerdnsadmin/models/record.py
index 536aa70..f3b22df 100644
--- a/powerdnsadmin/models/record.py
+++ b/powerdnsadmin/models/record.py
@@ -67,7 +67,7 @@ class Record(object):
         for r in jdata['rrsets']:
             while len(r['comments'])<len(r['records']):
                 r['comments'].append({"content": "", "account": ""})
-            r['records'], r['comments'] = (list(t) for t in zip(*sorted(zip(r['records'], r['comments']), key=by_record_content_pair)))
+#            r['records'], r['comments'] = (list(t) for t in zip(*sorted(zip(r['records'], r['comments']), key=by_record_content_pair)))
             rrsets.append(r)

         return rrsets
```
the comments will be saved, but not shown...

**Comment by WizRd0** [comment]
I'm experiencing the same issue with TXT records

Example: domain.net    3600    IN      TXT     "v=spf1 mx a ip4:nnn.nnn.nnn.nnn/32 -all"
When the above record is in the zone it throws an internal server error 500.  The fix from https://github.com/ngoduykhanh/PowerDNS-Admin/issues/792#issuecomment-801880972 has fixed the 500 error and allowing me to manage the domain via the web interface.

**Comment by pschiffe** [comment]
I also hit this bug. Noticed that when it happens, there are empty comments stored in the `comments` mysql table of pdns admin. Deleting those records also servers as a workaround.

**Comment by bundabrg** [comment]
Wrapping a try: except: will solve this issue

```
diff --git a/powerdnsadmin/models/record.py b/powerdnsadmin/models/record.py
index e0b507c..1296bd4 100644
--- a/powerdnsadmin/models/record.py
+++ b/powerdnsadmin/models/record.py
@@ -67,8 +67,11 @@ class Record(object):
         for r in jdata['rrsets']:
             while len(r['comments'])<len(r['records']):
                 r['comments'].append({"content": "", "account": ""})
-            r['records'], r['comments'] = (list(t) for t in zip(*sorted(zip(r['records'], r['comments']), key=by_record_content_pair)))
-            rrsets.append(r)
+            try:
+                r['records'], r['comments'] = (list(t) for t in zip(*sorted(zip(r['records'], r['comments']), key=by_record_content_pair)))
+                rrsets.append(r)
+            except:
+                pass
 
         return rrsets
```

**Comment by rootbdfy** [comment]
@bundabrg  thanx, worked for me !

**Comment by AiYoriAoshi** [comment]
> I also hit this bug. Noticed that when it happens, there are empty comments stored in the `comments` mysql table of pdns admin. Deleting those records also servers as a workaround.

Problem for me was, that there were still comments in the `comments` mysql table of pdns but the records they belonged to where already gone. After deleting the comments in the DB all zones that had comment on non-existing records could be displayed again.

**Comment by duviful** [comment]
Hello, I'm experiencing the same problem after having my installation updated to 0.2.3
I got `error 500` when I try to access a zone from WebUI.
Same error as the opening message for the issue.

What I've noticed:

I was able to clear the table from the database and restore functionality to the WebUI, but when I add a new record, even if I leave the comment section blank, a new entry is stored in the comments table on the database, breaking the WebUI again.

**Comment by duviful** [comment]
Quick update on my side.
I was able to fix the error by setting the correct PDNS Version under Settings -> PDNS

The upgrade to the latest release of powerdnsadmin, set the version to a more recent than my running pdns package.

I cleared the comments table inside the DB before doing this, so I'm not sure this step is required or not...

anyhow, everything is working just fine again!
Best!
