### ISSUE TITLE
Feature Request: Automatically generete a user/password for dyndns usage

### ISSUE THREAD

**Issue by celevra** [PowerDNS-Admin/PowerDNS-Admin#794]
Hi,

it would be great to faster create a User für DynDNS.
I just need a user and password, a simple dyndns user doesnt need a e-mail

it would be great if the password would be created automaticly:
```
function generatePassword() {
    var length = 8,
        charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
        retVal = "";
    for (var i = 0, n = charset.length; i < length; ++i) {
        retVal += charset.charAt(Math.floor(Math.random() * n));
    }
    return retVal;
}
```

it would be perfekt if i could order the user directly to a domain in the create user interface

and the world would be perfekt if a user could only update an entry and not the every entry in a domain.

regards

Celevra

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
