### ISSUE TITLE
Problem installing PowerDNS-Admin on existing running pdns server

### ISSUE THREAD

**Issue by prakash9999in** [PowerDNS-Admin/PowerDNS-Admin#802]
Hi Khanh Ngo,

I appreciate the time you’ve taken to build this wonderful UI. This is really good with so many features. I have been using powerdns and all these days was using poweradmin (https://github.com/poweradmin/poweradmin). 

After coming across PowerDNS-Admin, I was excited to use it and have installed if for testing for my existing powerdns server snapshot. I could install it and is functional. Now I have some challenges while exploring it, I hope there will be some solution (Please rectify me if I miss anything) : 

1.   If the session expires and I login back, I get **403 error- Oops! Access denied
You don't have permission to access this page You may return to the dashboard.**

In logs I see:
_gunicorn[15009]: [2020-08-07 17:22:52,965] [flask_seasurf.py:282] WARNING - Forbidden (CSRF token missing or incorrect.): /login_

If I click on home link, It logs me out and takes me to login page. On second login, I get the home page.

2. If I go to Global Search and search for existing domains and records (was present earlier before installing PowerDNS-Admin), I get the record. But if I click on any searched domain , I get the error 

**"404 Oops! You're lost
The page you requested could not be found."**

In Log I see:
_gunicorn[15009]: [2020-08-07 17:34:13,125] [domain.py:169] ERROR - Can not update domain table. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)_

If I create new domains and records using PowerDNS-Admin, I get the desired results. So what I feel that the existing pdns domain data is not synced with PowerDNS-Admin domain database. 

Please correct me If I missed any step while configuring it.

Hope to overcome these issues soon.

Thanks
Regards

**Comment by jbe-dw** [comment]
Hello,

This has been fixed since by adding an automatic reload timeout on the login page.

Regards
