### ISSUE TITLE
Unable to login mysql and dns-lookup not working.

### ISSUE THREAD

**Issue by gnanasankar** [PowerDNS-Admin/PowerDNS-Admin#807]
# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                NAMES
d1b01e5560b9        aescanero/powerdns-admin     "/entrypoint.sh"         4 seconds ago       Up 3 seconds        0.0.0.0:9191->9191/tcp                               docker-powerdns-admin-alpine_powerdns-admin_1
87b346efbc06        pschiffe/pdns-mysql:alpine   "/docker-entrypoint.…"   5 seconds ago       Up 4 seconds        0.0.0.0:53->53/tcp, 53/udp, 0.0.0.0:8081->8081/tcp   docker-powerdns-admin-alpine_powerdns_1
7fd322e48f66        mariadb                      "docker-entrypoint.s…"   5 seconds ago       Up 4 seconds        0.0.0.0:3306->3306/tcp                               docker-powerdns-admin-alpine_mysql_1

After start above docker container unable to login mysql and dns-lookup not working from base machine and outside network..But same working in inside docker container.please help me to fix this issue..

# mysql -u root -p
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)

# docker exec -it 7fd322e48f66 /bin/sh
# mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 22
Server version: 10.5.5-MariaDB-1:10.5.5+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>

**Comment by jbe-dw** [comment]
Hello,

Since you're using pschiffe setup, you should open an issue there.

Regards
