### ISSUE TITLE
[feature, PTR records]: Ability to enter the IPv6 address directly

### ISSUE THREAD

**Issue by samip5** [PowerDNS-Admin/PowerDNS-Admin#808]
Let's say I have a IP address of: 2001:DB8::1, that I want to have a reverse of: unknown.example.org, I want to be able to insert that directly to the record name, and have it automatically populate it's correct entry name according to the zone name.

I mean like this: 2001:DB8::1 -> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa and if the zone is 8.b.d.0.1.0.0.2.ip6.arpa, it would just snip that part out of the record name, and insert the rest.

**Comment by jbe-dw** [comment]
Hello,

Is your request about being able to enter hexadecimal format in the GUI and let PDA convert it to the requested format automatically ?

Regards

**Comment by samip5** [comment]
> Hello,
> 
> Is your request about being able to enter hexadecimal format in the GUI and let PDA convert it to the requested format automatically ?
> 
> Regards

Request is about being able to insert the record as `2001:DB8::1` directly, without first converting to the long format. :)
