### ISSUE TITLE
Subdomain records break hostname lookups for specific host.

### ISSUE THREAD

**Issue by helpquick** [PowerDNS-Admin/PowerDNS-Admin#811]
I have a wilcard A record for a zone, which has been working very well for some time.

I recently upgraded to the latest powerdns server and PowerDNS-Admin, then tried to renew a wildcard SSL from LetsEncrypt:

So, by way of example:

`*.example.com   A   192.168.1.1`

now, `tt.example.com` resolves to `192.168.1.1`

Also, `xx.tt.example.com` also resolves to `192.168.1.1`

If I then create a LetsEncrypt wildcard cert using "tt.example.com", it requests for a txt record to be added:

`_acme-challenge.tt   TXT   "somerandomchars"`

Certificate creation succeeds and all is well with that, however `*.tt.example.com` and `tt.example.com` no longer resolve to ip address.

In the MySQL back end, i can see records have been created for tt.example.com with NULL for everything:

`MariaDB [powerdns]> select * from records where name like "%example.com";
+-------+-----------+--------------------------------+------+------------------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| id    | domain_id | name                           | type | content                                                                                  | ttl  | prio | change_date | disabled | ordername | auth |
+-------+-----------+--------------------------------+------+------------------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| 11457 |       768 | *.example.com                  | A    | 192.168.1.1                                                                              |   60 |    0 |        NULL |        0 | NULL      |    1 |
| 11459 |       768 | _acme-challenge.tt.example.com | TXT  | "asdasdasg"                                                                              |   60 |    0 |        NULL |        0 | NULL      |    1 |
| 11460 |       768 | example.com                    | SOA  | a.misconfigured.powerdns.server hostmaster.example.com 2020090202 10800 3600 604800 3600 | 3600 |    0 |        NULL |        0 | NULL      |    1 |
| 11461 |       768 | tt.example.com                 | NULL | NULL                                                                                     | NULL | NULL |        NULL |        0 | NULL      |    1 |
+-------+-----------+--------------------------------+------+------------------------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
4 rows in set (0.002 sec)
`

Removing the NULL entry manually returns to full functioning system.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. You should seek for help with PowerDNS IRC chatroom.

Regards
PowerDNS Admin Team
See #1153 for the policy
