### ISSUE TITLE
400 instead of being able to create domain on a fresh install @latest

### ISSUE THREAD

**Issue by mikeSGman** [PowerDNS-Admin/PowerDNS-Admin#816]
1st time user, I am seeing a 400 when I try to create a test domain after a fresh install (docker run based NOT docker-compose based).

![image](https://user-images.githubusercontent.com/398394/93151408-da53b600-f6c9-11ea-9fb1-14e90a675ec6.png)

**Comment by mikeSGman** [comment]
Side note: I am navigating to the IP of the VM that hosts my container, not http://localhost:9191/

Here's the output of the sucessful docker run:

[root@pdns PowerDNS-Admin]# docker run -d -v pda-data:/data -p 9191:80 ngoduykhanh/powerdns-admin:latest
Unable to find image 'ngoduykhanh/powerdns-admin:latest' locally
latest: Pulling from ngoduykhanh/powerdns-admin
cbdbe7a5bc2a: Pull complete 
829ba215ee9a: Pull complete 
360d33f04364: Pull complete 
ed46bcb1a527: Pull complete 
af90ca11d45a: Pull complete 
72807209c1d8: Pull complete 
Digest: sha256:b6a50cce89ecec4e3786a77f326735064ed6464be74f2c4f5ff73bfc34d153bd
Status: Downloaded newer image for ngoduykhanh/powerdns-admin:latest
5f40f27d8add4fda584708ae747a104325dbb9c89bbc4c8b089d76aa08ea90b5
[root@pdns PowerDNS-Admin]#

**Comment by avsdev-cw** [comment]
Can confirm I am also getting this behaviour:
```
[2020-09-16 12:13:11,824] [_internal.py:113] INFO - 192.168.20.104 - - [16/Sep/2020 12:13:11] "POST /domain/add HTTP/1.1" 400 -
```

**Comment by avsdev-cw** [comment]
Further inspection, this is related to https://github.com/PowerDNS/pdns/issues/7557 and the solution seems to be to install the 4.1.x schema: https://github.com/PowerDNS/pdns/blob/rel/auth-4.1.x/modules/gmysqlbackend/schema.mysql.sql

**Comment by alex1702** [comment]
look here:
https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/4.2.0_to_4.3.0_schema.mysql.sql

possibly also install the following updates:
https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/4.1.0_to_4.2.0_schema.mysql.sql
https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/3.4.0_to_4.1.0_schema.mysql.sql

**Comment by ngoduykhanh** [comment]
Hi guys. Was it an issue with PDNS schema or PDA itself? I didn't get a chance to test the new version of PDNS yet.

**Comment by alex1702** [comment]
With the PDNS schema. When you update PDNS, you also have to migrate their database. With the docker setup you can forget about that.
Maybe you can somehow intercept something like this.
For example that powerdns admin remembers the version and displays a hint if the version is higher at the next start?

**Comment by ngoduykhanh** [comment]
Well, as an administrator of the DNS system, we should already aware of the upgrading of our PDNS server and check the compatibility. I think for now we can have some enhancement in showing API version/healcheck from PDA.

**Comment by ManuDIY** [comment]
Hello guys. is there any solution for error 400 when trying to create a new domain?
I have installed successfully the PowerDNS v4.4.0-alpha1 and PowerDNS-Admin and the only issue is that error at least for now.

Thanks in advance!

**Comment by avsdev-cw** [comment]
Yes:

> Further inspection, this is related to [PowerDNS/pdns#7557](https://github.com/PowerDNS/pdns/issues/7557) and the solution seems to be to install the 4.1.x schema: https://github.com/PowerDNS/pdns/blob/rel/auth-4.1.x/modules/gmysqlbackend/schema.mysql.sql

> look here:
> https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/4.2.0_to_4.3.0_schema.mysql.sql
> 
> possibly also install the following updates:
> https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/4.1.0_to_4.2.0_schema.mysql.sql
> https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/3.4.0_to_4.1.0_schema.mysql.sql

In essence, make sure you have created the PowerDNS database with the correct schema for the version of PowerDNSAdmin you are using

**Comment by ManuDIY** [comment]
> Yes:
> 
> > Further inspection, this is related to [PowerDNS/pdns#7557](https://github.com/PowerDNS/pdns/issues/7557) and the solution seems to be to install the 4.1.x schema: https://github.com/PowerDNS/pdns/blob/rel/auth-4.1.x/modules/gmysqlbackend/schema.mysql.sql
> 
> > look here:
> > https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/4.2.0_to_4.3.0_schema.mysql.sql
> > possibly also install the following updates:
> > https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/4.1.0_to_4.2.0_schema.mysql.sql
> > https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/3.4.0_to_4.1.0_schema.mysql.sql
> 
> In essence, make sure you have created the PowerDNS database with the correct schema for the version of PowerDNS and PowerDNSAdmin you are using. Inversely, depending on the schema you have installed, make sure you have told PowerDNSAdmin which version you are connecting to.

@avsdev-cw, I have already tried also those possible solutions regarding the PowerDNS schema and also i have properly configured PowerDNS-Admin regarding the version of PowerDNS but is not working for me.

**Comment by ManuDIY** [comment]
I forgot to mention that i have installed PowerDNS on a Centos 8 server with gmysql as backend

**Comment by ManuDIY** [comment]
![image](https://user-images.githubusercontent.com/37869585/96473360-39ad6480-123a-11eb-8844-2ef8a6dd71ab.png)

**Comment by ManuDIY** [comment]
![image](https://user-images.githubusercontent.com/37869585/96473521-6c575d00-123a-11eb-8dad-46dff0fc0cac.png)

**Comment by avsdev-cw** [comment]
Run PowerDNSAdmin in interactive mode/with logging on. When the 400 error occurs, check the logging output. If it's the same error as this thread you should see something about a missing column.

**Comment by ManuDIY** [comment]
i did docker logs -f <container_id> and got the following errors, and i don;t know why "localhost" is present in the API Uri. not sure if that is correct or not. What is your opinion?
![image](https://user-images.githubusercontent.com/37869585/96476435-d9b8bd00-123d-11eb-9224-a9a95779c75b.png)

**Comment by alex1702** [comment]
The way I see it, PowerDNSAdmin cannot connect to your PowerDNS host. Can you reach the PowerDNS from your Docker Host?

**Comment by ManuDIY** [comment]
@alex1702, yes i can.
![image](https://user-images.githubusercontent.com/37869585/96479260-6022ce00-1241-11eb-9692-7d9d480630a5.png)

**Comment by BadikovVV** [comment]
Sorry guys for my English.
I spent 5 hours solving the same f****ng problem!
And i solved it!
If you install PowerDNSAdmin as container be careful with  PowerDNS webserver parameters.
```
vi /etc/powerdns/pdns.conf
webserver=yes
#webserver-address=127.0.0.1
webserver-address=192.168.0.1  # your real ip  not localhost
webserver-allow-from=127.0.0.1,192.168.0.1,172.17.0.2  # last address is your docker container address
systemctl restart pdns.service
```

And in PowerDNSAdmin  
http://192.168.0.1:8081/  - PDNS API URL
PDNS VERSION - 4.1.1 

**And after that i can create a new domain**

**Comment by mohamedmshokry** [comment]
Hello guys, Have you managed to solve it?
I've tried BadikovVV guide in the last comment but seems not working with my installation.
I've followed this guide to install it on ubuntu 20.04  `https://www.howtoforge.com/how-to-install-powerdns-admin-on-ubuntu-20-04/`

Below are more details about the PDNS versions I'm using and PDNS Admin parameters:
```
 root@powerdns-home:/var/www/html/pdns/powerdnsadmin/models# pdns_control version
4.2.1
root@powerdns-home:~# cat /etc/powerdns/pdns.conf | grep -v '^#' | grep -i '[a-z]'
api=yes
api-key=pdns_key
include-dir=/etc/powerdns/pdns.d
launch=
security-poll-suffix=
setgid=pdns
setuid=pdns
webserver=yes
webserver-address=192.168.1.252
webserver-allow-from=127.0.0.1,::1,192.168.1.252,182.168.1.1,192.168.1.0/24
```

I was able to create a zone manually using PDNS APIs but even the newly created zone doesn't appear on the PowerDNS Admin UI:
```
root@powerdns-home:/var/www/html/pdns/powerdnsadmin/models# curl -s -H 'X-API-Key: pdns_key' http://127.0.0.1:8081/api/v1/servers/localhost/zones | jq
[
  {
    "account": "",
    "dnssec": false,
    "edited_serial": 2021061201,
    "id": "lab.local.",
    "kind": "Native",
    "last_check": 0,
    "masters": [],
    "name": "lab.local.",
    "notified_serial": 0,
    "serial": 2021061201,
    "url": "/api/v1/servers/localhost/zones/lab.local."
  }
]
```
Tried to restart the pdnsadmin service with no luck. 
I've noticed that there is an issue with the host URL from the output of pdsadmin service:
```
root@powerdns-home:/var/www/html/pdns/powerdnsadmin/models# systemctl status pdnsadmin
● pdnsadmin.service - PowerDNS-Admin
     Loaded: loaded (/etc/systemd/system/pdnsadmin.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-06-12 13:24:34 UTC; 16min ago
TriggeredBy: ● pdnsadmin.socket
   Main PID: 39481 (gunicorn)
      Tasks: 2 (limit: 4617)
     Memory: 69.0M
     CGroup: /system.slice/pdnsadmin.service
             ├─39481 /var/www/html/pdns/flask/bin/python /var/www/html/pdns/flask/bin/gunicorn --pid /run/pdnsadmin/pid --bind unix:/run/pdnsadmin/socket powerdnsadmin:create_app()
             └─39490 /var/www/html/pdns/flask/bin/python /var/www/html/pdns/flask/bin/gunicorn --pid /run/pdnsadmin/pid --bind unix:/run/pdnsadmin/socket powerdnsadmin:create_app()

Jun 12 13:24:34 powerdns-home systemd[1]: Started PowerDNS-Admin.
Jun 12 13:24:35 powerdns-home gunicorn[39481]: [2021-06-12 13:24:35 +0000] [39481] [INFO] Starting gunicorn 20.0.4
Jun 12 13:24:35 powerdns-home gunicorn[39481]: [2021-06-12 13:24:35 +0000] [39481] [INFO] Listening at: unix:/run/pdnsadmin/socket (39481)
Jun 12 13:24:35 powerdns-home gunicorn[39481]: [2021-06-12 13:24:35 +0000] [39481] [INFO] Using worker: sync
Jun 12 13:24:35 powerdns-home gunicorn[39490]: [2021-06-12 13:24:35 +0000] [39490] [INFO] Booting worker with pid: 39490
Jun 12 13:24:38 powerdns-home gunicorn[39490]: [2021-06-12 13:24:38,312] [domain.py:168] ERROR - Cannot update domain table. Error: Invalid URL 'http:///api/v1/servers/localhost/zones': No host supplied
Jun 12 13:24:38 powerdns-home gunicorn[39490]: [2021-06-12 13:24:38,344] [server.py:60] ERROR - Can not get server statistics. DETAIL: Invalid URL 'http:///api/v1/servers/localhost/statistics': No host supplied
Jun 12 13:24:44 powerdns-home gunicorn[39490]: [2021-06-12 13:24:44,406] [domain.py:252] ERROR - Cannot add domain homelab.local. Invalid URL 'http:///api/v1/servers/localhost/zones': No host supplied
Jun 12 13:24:45 powerdns-home gunicorn[39490]: [2021-06-12 13:24:45,550] [domain.py:168] ERROR - Cannot update domain table. Error: Invalid URL 'http:///api/v1/servers/localhost/zones': No host supplied
Jun 12 13:24:45 powerdns-home gunicorn[39490]: [2021-06-12 13:24:45,578] [server.py:60] ERROR - Can not get server statistics. DETAIL: Invalid URL 'http:///api/v1/servers/localhost/statistics': No host supplied
```
I verified the PDNS version and API key as in my installation configuration 
![image](https://user-images.githubusercontent.com/58613193/121777920-bf4c9e80-cb94-11eb-9074-f47232d0a515.png)

Check the PDNS Admin setting.py and hardcoded the below parameters and restarted PDNS admin:
```
'pdns_api_url': '127.0.0.1',
'pdns_api_key': 'pdns_key'
```

I get the same issue when I trey to create account from UI.
I'm using MariaDB as backend. Below are my DBs and tables created:
```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| pdns               |
| performance_schema |
+--------------------+
MariaDB [pdns]> show tables;
+------------------------+
| Tables_in_pdns         |
+------------------------+
| account                |
| account_user           |
| alembic_version        |
| apikey                 |
| comments               |
| cryptokeys             |
| domain                 |
| domain_apikey          |
| domain_setting         |
| domain_template        |
| domain_template_record |
| domain_user            |
| domainmetadata         |
| domains                |
| history                |
| records                |
| role                   |
| setting                |
| supermasters           |
| tsigkeys               |
| user                   |
+------------------------+
MariaDB [pdns]> select * from setting;
+----+--------------+---------------------+
| id | name         | value               |
+----+--------------+---------------------+
| 47 | pdns_api_url | http:127.0.0.1:8081 |
| 48 | pdns_api_key | pdns_key            |
| 49 | pdns_version | 4.2.1               |
+----+--------------+---------------------+
MariaDB [pdns]> select * from apikey;
+----+--------------------------------------------------------------+-------------+---------+
| id | key                                                          | description | role_id |
+----+--------------------------------------------------------------+-------------+---------+
|  1 | $2b$12$yLUMTIfl21FKJQpTkRQXCuPHWyrNk3MYQN9ffuBQbX3/GueOvtliG |             |       1 |
+----+--------------------------------------------------------------+-------------+---------+
```


The strange thing I]m trying to understand is that I can't find anything in comments table despite the manual creation of zone:
Below is the comments table:

```
MariaDB [pdns]> select * from comments;
Empty set (0.001 sec)
```

And this is the how I created the zone:
```
root@powerdns-home:~# curl -s -H 'X-API-Key: pdns_key' --data @/tmp/zone http://127.0.0.1:8081/api/v1/servers/localhost/zones | jq
{
  "account": "",
  "api_rectify": false,
  "dnssec": false,
  "edited_serial": 2021061201,
  "id": "lab.local.",
  "kind": "Native",
  "last_check": 0,
  "master_tsig_key_ids": [],
  "masters": [],
  "name": "lab.local.",
  "notified_serial": 0,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [
    {
      "comments": [],
      "name": "lab.local.",
      "records": [
        {
          "content": "a.misconfigured.powerdns.server. hostmaster.lab.local. 2021061201 10800 3600 604800 3600",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "SOA"
    },
    {
      "comments": [],
      "name": "lab.local.",
      "records": [
        {
          "content": "ns1.lab.local.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "NS"
    }
  ],
  "serial": 2021061201,
  "slave_tsig_key_ids": [],
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
  "url": "/api/v1/servers/localhost/zones/lab.local."
}

root@powerdns-home:~# cat /tmp/zone 
{
    "comments": [
        {
            "account": "JP",
            "content": "My first API-created zone",
            "name": "uhuh",
            "type": "dunno"
        }
    ],
    "kind": "Native",
    "masters": [],
    "name": "lab.local.",
    "nameservers": [
        "ns1.lab.local."
    ],
    "records": [
        {
            "content": "nsi.lab.local. hostmaster.lab.local. 1 1800 900 604800 86400",
            "disabled": false,
            "name": "lab.local",
            "ttl": 86400,
            "type": "SOA"
        },
        {
            "content": "192.168.1.42",
            "disabled": false,
            "name": "www.lab.local",
            "ttl": 3600,
            "type": "A"
        }
    ]
}

```


Any idea what is missing? or where to look to get closer to the issue?

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
