### ISSUE TITLE
Set default TSIG-key upon domain creation

### ISSUE THREAD

**Issue by joachimtingvold** [PowerDNS-Admin/PowerDNS-Admin#82]
Hi,

Whenever the metadata-API is made available, PDA should make related metadata-entries upon creation of the domain (and even better; make them editable). Specifically TSIG-information, so that zone transfers are signed.

https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzoneszone95namemetadata

> TODO: Not yet implemented.

**Comment by Rico29** [comment]
Is this planned ?

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, I'm closing it. A recent feature request arround domain metadat is opened (#1133)

Regards
PowerDNS Admin Team
See #1153 for the policy
