### ISSUE TITLE
Attempting to update several entries by DynDNS2 only updates one

### ISSUE THREAD

**Issue by PauloHeaven** [PowerDNS-Admin/PowerDNS-Admin#822]
I use ddclient to update the IP address in 3 records. However, only one is effectively updated, even though PowerDNS Admin tells me all 3 have been.

`DynDNS update: created record host.abc,another.abc,ns2.abc in zone abc.abc successfully`

Only host.abc is updated.

5 minutes after that, it tells me the same line with only the two last entries. They still aren't updated.

ddclient configuration:

```daemon=300
syslog=yes
ssl=yes
protocol=dyndns2
use=web
server=abc.com
login=user
password='abcdef'
host.abc
another.abc
ns2.abc```

**Comment by jbe-dw** [comment]
Hello,

Do you still experience this bug ?

Regards

**Comment by PauloHeaven** [comment]
Hello,

Yes, I still do

**Comment by jbe-dw** [comment]
Nice to hear from you. We'll take a look into this then. There may be some delay as we don't have enough free time to clear a huge backlog in time.
