### ISSUE TITLE
LDAP Issue, Authenticator in History always shows LOCAL even when using LDAP

### ISSUE THREAD

**Issue by xeynx0579** [PowerDNS-Admin/PowerDNS-Admin#829]
I have gone through the setup process and have set up all the settings accordingly in PowerDNS-Admin for LDAP but whenever I try and test a logon even when using LDAP Authentication it always says "Invalid Credentials" and when I check the history it says the Authenticator is using LOCAL even when I chose LDAP authentication.  I have both options enabled in Authentication.  Can someone help me with what I'm doing wrong.  I can provide configurations and screenshots if needed.

**Comment by dmgeurts** [comment]
I see the same, LDAP auth works fine, but the logs report that LOCAL auth was used when in fact it was LDAP.

**Comment by vmarkop** [comment]
Fixed by #1122.
