### ISSUE TITLE
LDAP authentication to AD times out without apparent cause

### ISSUE THREAD

**Issue by drbw** [PowerDNS-Admin/PowerDNS-Admin#830]
We're authenticating to AD via LDAP from two PowerDNS-Admin nodes, one operating in master mode an one as a slave. The master has unfortunately started timing out without any apparent cause - local auth still works. Invalid authentication is also rejected. Once logged in with a local account, everything works as normal. The slave also authenticates users without delays or any sign that something may have gone wrong.

If I look at the Windows authentication logs, I can see that there's a successful authentication request from PowerDNS, and looking at a tcpdump everything seems normal as well. In the history available from the admin console, there is no authentication attempt logged for successful logins. Invalid authentication is logged correctly.

In the logs for the uWSGI container, I just see this:

```
[pid: 30|app: 0|req: 114/110] 172.30.31.2 () {60 vars in 1171 bytes} [Thu Oct 22 16:59:18 2020] POST /login => generated 5938 bytes in 20 msecs (HTTP/1.1 403) 5 headers in 384 bytes (1 switches on core 0)
[pid: 30|app: 0|req: 115/111] 172.30.31.2 () {54 vars in 1147 bytes} [Thu Oct 22 16:59:21 2020] GET /dashboard/ => generated 219 bytes in 5 msecs (HTTP/1.1 302) 6 headers in 524 bytes (1 switches on core 0)
[pid: 30|app: 0|req: 116/112] 172.30.31.2 () {54 vars in 1200 bytes} [Thu Oct 22 16:59:21 2020] GET /login => generated 3331 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 479 bytes (1 switches on core 0)
Thu Oct 22 17:00:09 2020 - *** HARAKIRI ON WORKER 1 (pid: 30, try: 1) ***
Thu Oct 22 17:00:09 2020 - HARAKIRI !!! worker 1 status !!!
Thu Oct 22 17:00:09 2020 - HARAKIRI [core 0] 172.30.31.2 - POST /login since 1603385968
Thu Oct 22 17:00:09 2020 - HARAKIRI !!! end of worker 1 status !!!
DAMN ! worker 1 (pid: 30) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 31)
```

That sounds like a timeout to me, but I'm unsure how to debug this further. Is this a behavior that occurs under known circumstances, or are there any debugging facilities for the process available? Deleting the containers had no effect, and I'm hesitant to screw with the database without knowing what that could do.

I'm unaware of any relevant changes, this started happening after I recreated all my PowerDNS containers to include an additional local zone for the recursor. Both the master and the slave were rebuilt so this is unlikely to be the cause.

I'm using @pschiffe's containers if it matters, but as far as I can tell there's very little special sauce that goes into them. Unfortunately, they're not versioned, though, so I can't be sure if something  may have changed that is relevant to the issue.

**Comment by jbe-dw** [comment]
Hello,

Do you still experience that kind of issue with recent release ?

Regards
