### ISSUE TITLE
Feature Request: CockroachDB support

### ISSUE THREAD

**Issue by hcsaustrup** [PowerDNS-Admin/PowerDNS-Admin#831]
**Has anyone tried** using CockroachDB as the database backend, or do you know of **any potential issues preventing** it? PowerDNS itself works fine with CockroachDB - now we just need PowerDNS Admin ;-)

PS: Thanks for all the good work - PowerDNS Admin looks awesome and professional!

**Comment by hcsaustrup** [comment]
Did some testing, and as it turns out, it's pretty easy to use CockroachDB as the database backend for PowerDNS-Admin. I'm using the Docker image, so I had to 1) make sure the image also had the sqlalchemy-cockroachdb Python module (please include this in the standard Docker image) and 2) change the backend to "cockroachdb" instead of "postgressql" which I used previously.

Directly pg_dump'ing the old PostgreSQL database and loading it into CockroachDB didn't work, as CockroachDB doesn't support the full PostgreSQL feature set. Loading the COPY parts of the dump seems to work fine though.

**Comment by jbe-dw** [comment]
Hello,

It should be possible, you just need to test on a new install with adding python sqlalchemy-cockroachdb to the virtualenv and run the `flask db upgrade` and check wether the app works or not.

Please give us a feedback if you are still interested.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
