### ISSUE TITLE
[Feature]: Apply records restriction to API

### ISSUE THREAD

**Issue by ArnGa** [PowerDNS-Admin/PowerDNS-Admin#832]
Hi,
We use the record restriction system to only offer a few types of records to our users in PowerDNS-Admin.
Obviously, these restrictions do not apply when using the API. A user can create a type of record (with a user level key on a given domain), which he could not create if he went through the web interface.
Is it possible to ensure that the same restrictions are applied?
Regards,

**Comment by jbe-dw** [comment]
Hello,

It is going to happen soon in #1171

Thanks for the request. I'm closing this stale issue.
