### ISSUE TITLE
CCA-Record:  CAA Value is not transferred to the input wizard. 

### ISSUE THREAD

**Issue by christianbur** [PowerDNS-Admin/PowerDNS-Admin#834]
If I want to change an existing CCA record, only the fields "CAA Flag" and "CAA Tag" are transferred to the input wizard, "CAA Value" is never transferred. I suspect that this is an error.

I am using the current Docker Image with Firefox 81.0.2.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
