### ISSUE TITLE
Enable DNSSEC creates CSK DNSKEY instead of ZSK/KSK

### ISSUE THREAD

**Issue by martijngoorman** [PowerDNS-Admin/PowerDNS-Admin#842]
Hi,

I'm playing around with a new PowerDNS + PowerDNS-Admin installation on our new DNS servers, but got a nasty issue and I can't solve it.

When I use the Enable DNSSEC option, a CSK Key is created instead of ZSK/KSK.
In my domain.py the value is ` post_data = {"keytype": "ksk", "active": True}`
When I do a `pdnsutil secure-zone ZONE` then a ZSK and KSK key is created.

Can anyone point me in the right direction where I have to find the solution for this issue?

**Comment by mwen** [comment]
I was able to enable DNSSEC from within PowerDNS-Admin without having to fall back on PowerDNS, so the only record I have is also a CSK.

Those DS records contain:
keytag algorithm hashtype digest

And they contain all the values that you have to enter at your domain registrar to get DNSSEC working.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
