### ISSUE TITLE
Api key authentication consistence

### ISSUE THREAD

**Issue by alxhlz** [PowerDNS-Admin/PowerDNS-Admin#847]
Hey guys,

I was trying to fetch all zones of a user via api and found out, that this is only possible via `/pdnsadmin/zones` endpoint. Sadly this endpoint has to be authenticated by basic auth and not via api key.

Now my question is, why no consistence? Is there a particular reason for that?

Regards,
Alex

**Comment by jbe-dw** [comment]
Hello,

With the latest version (master, maybe 0.2.4), users can list their zones via the /server/../zones endpoint.

Regards
