### ISSUE TITLE
Feature Request: Add a configuration API endpoint with initial admin and/or apikey setup

### ISSUE THREAD

**Issue by itbane** [PowerDNS-Admin/PowerDNS-Admin#848]
Hi,

by trying to automate the deployment of PowerDNS-Admin, I noticed some showstoppers in regards of API usage. I have a couple of suggegstions that would allow for a much easier setup.

* Allow the API-key, created as in [1], to be used on all endpoints (either exclusively or parallel with the basic auth)
* Allow user registration via a new API endpoint to allow a hands-free initial installation
* Allow PDNS-Admin configuration via API (PDNS settings, Authentication, etc.)

As I am not a python developer, I think I can't contribute any actual code for this. If I can support in another way to help further this topic, please let me know.

KR, itbane

[1] https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docs/API.md

**Comment by jbe-dw** [comment]
Hello,

We have a plan to implement such things later. A configuration endpoint, and at least another one to create the initial admin.
I'm not quite sure if we want to allow the API Key for all endpoints (/powerdnsadmin) but we will decide it then.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
