### ISSUE TITLE
PDNS LUA CNAME

### ISSUE THREAD

**Issue by nranetworks** [PowerDNS-Admin/PowerDNS-Admin#853]
Hello,

I have tried all the ways but I didn't get it.

I am trying to send traffic to different countries but I don't know how to make this topology works.

***.org.xxx.com  CNAME      ";if(country{'IQ'}) then return 'iq.xxxx.com'  " " else return 'nl.xxxx.com' end;
;if(country{'BE'}) then return 'be.xxxx.com'  " " else return 'nl.xxxx.com' end;
"**

I wanna use one CNAME LUA record Ex: *.org.xxx.com pointing to different countries as shown above. 

Thanks for your help in advance!

**Comment by jbe-dw** [comment]
Hello,

You should look at what's inserted into PowerDNS itself first, and ask for help to the PowerDNS team though. It may be either a misuse that would not get answered here or a bug in PowerDNS Admin leading to incorrect entries in PowerDNS that could be checked here.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
