### ISSUE TITLE
Feature request: Allow Multi Arch Docker Support (arm64)

### ISSUE THREAD

**Issue by mzac** [PowerDNS-Admin/PowerDNS-Admin#854]
Hi, I would like to run this project as a docker container on arm64 however I noticed that the Docker Hub builds are x64 only.  Would you consider setting up multi arch builds?  There is a good guide here:

https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

This will allow users on Raspberry Pi to run this container!

Thanks!

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
