### ISSUE TITLE
Letsencrypt and lego error - /api nout found

### ISSUE THREAD

**Issue by Cyr-ius** [PowerDNS-Admin/PowerDNS-Admin#865]
The registration of certificates via the LEGO module is impossible because the path http: //xxxxx/api does not return the API version as can PowerDNS on its administration port

Is it possible to modify the reverse proxy to return this information ?

**Comment by Syntax3rror404** [comment]
Use a nginx or traefik reverse proxy ...

**Comment by jbe-dw** [comment]
#1206 (replaces #1115) has been merged to master.

Please use master branch or wait for next release.

Feel free to reopen if you still have issue with this.
