### ISSUE TITLE
lots of records removed after trying to add record with invalid charachters

### ISSUE THREAD

**Issue by fredmu87** [PowerDNS-Admin/PowerDNS-Admin#871]
Dear creator! I really like your software and we have adoptet it to production.

But we've had two nearly identical issues recently where a user adds a record and gets a prompt saying that the DNS name is invalid (see screenshot). after this he closed the dialog box, and refreshed the page, and tried to add it again with success and applied the change. In the history we can then see that his user is logged as having remove a whole bunch of DNS names, including NS records for a zone - which he did not do.

Could this be similar to #744 ?

We're running mysql backend.

Not sure which version of your program we're running or how to check that, but we have upgraded it once in the past.

Kind regards,
Fredrik

**Comment by fredmu87** [comment]
![powerdns-admin-error](https://user-images.githubusercontent.com/43840906/105145624-496d6b00-5aff-11eb-8c69-af75be73155a.PNG)

**Comment by fredmu87** [comment]
![powerdns-admin-error](https://user-images.githubusercontent.com/43840906/105147030-e4b31000-5b00-11eb-96a0-0eb5e7705d85.PNG)

**Comment by steschuser** [comment]
Maybe related to #935 ?
