### ISSUE TITLE
about account restrict for per user

### ISSUE THREAD

**Issue by adnnoky** [PowerDNS-Admin/PowerDNS-Admin#873]
Hi Everybody,

Firstly, Thanks for this great project.  I want to install pdns server with pdns-admin for our customer usage. I've installed but I have problem with the limitation for user. As below you can see customer3 can see other customers account. Also customer3 can add a domain for the other account. I couldn't find any solution. Is anyone can help me? Is there any solution for this?

Thanks in advance.
![image](https://user-images.githubusercontent.com/4419138/105571552-d4e63680-5d61-11eb-838d-7d81c7635915.png)

**Comment by jbe-dw** [comment]
I guess it's not enforced yet. This application has a great potential but needs improvement.

**Comment by jbe-dw** [comment]
Hello,

The accounts available in the list should now be the ones the user is beloging to.

Can you confirm ?

Regards
