### ISSUE TITLE
PTR Domain default to master

### ISSUE THREAD

**Issue by RGanor** [PowerDNS-Admin/PowerDNS-Admin#876]
I came across an issue which is not really a bug, but when auto ptr is on, it automatically create the reverse domain with replication type of MASTER.
Maybe it should be a setting or open this ticket to a debate but i think it should be created as native.
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/3a4efebf954da533b3df1a7fca375ce68b47285e/powerdnsadmin/models/domain.py#L419

**Comment by jbe-dw** [comment]
I've tried it and the soa is misconfigured. It indeed will never work if not native.

Setting it to native can be a quick fix but in any case your zone will be not properly configured (it will lack a correct SOA and NS servers). It means that you should not expose public range reverse zone this way. (it is not important for private ranges as you have to forward it so no dns resolution is done).

If the zone is created automatically by PDNS then it needs a clean way to initialize it (ie add the ability to configure "default NS" servers and "default SOA options" for these zones in the interface and correctly compute the SOA.

**Comment by jbe-dw** [comment]
We have a lot of work regarding this autoptr option for a future release. I'm closing
