### ISSUE TITLE
Comments shuffled per-RRset

### ISSUE THREAD

**Issue by Korkman** [PowerDNS-Admin/PowerDNS-Admin#880]
The UI allows editing comments per record, which is possibly incorrect? As stated in the [PowerDNS docs](https://doc.powerdns.com/recursor/http-api/zone.html#zone):

"Comments are per-RRset"

Which makes me think **one** comment for all records of one type is supported. What's odd is that at the same time, a list of comments is accepted in the API. I can see the correct ordering in the list of changes on the dashboard. But the order is not preserved. Attempts to attach unique comments to different records of the same name and type results in more or less randomly shuffled record / comment pairs.

Using pdns MySQL backend.

Edit: PowerDNS-Admin version is latest from docker hub, PDNS is 4.1.6
Edit 2: Still happening with PowerDNS-Admin 0.2.4 (latest) and PDNS 4.5.2

**Comment by Korkman** [comment]
Taking a deep dive into the API and DB I found the following:
 - The records and comments are sent to the pdns API in sync
 - They are stored in the MySQL DB in the correct order
 - They are queried by pdns in a way that luckily preserves primary key ordering (I say luckily, they should add 'order by id', ...)
 - The pdns API changes the ordering of the records list, but the comments list is unchanged
 - PowerDNS-Admin combines the de-synchronized pairs, then sorts by record content alphabetically

Ugh. The bug here lies in the sparse documentation of the comments feature and their intended use. Comments are a series of lines, kept in order, attached to the RRset - not the individual record.

Here's two edge cases:
 1. There may be 20 comment lines and only two records
 2. When a record is deleted, the RRset comments shall be unaffected by that

This means the current user interface for editing comments is broken by design. It wouldn't be able to properly display case 1. It is one editor table where, in fact, two tables are stored.

The annoying thing here is that the typical use case is to comment individual records, so the UI makes more sense than the pdns comment feature.

Anyways. Proposed fix:
- Decouple the comments column from the rest of the table
- Make it one field per RRset, spanning all its records
- Join all comment lines of the RRset with newlines as glue in that field
- When saving, split on newlines and send them as individual comment lines\*

\*As I said, the way pdns queries the DB does not guarantee preservation of order. In particular, custom index fields, when used by the query optimizer, can disturb the sequence. To make sure the order is preserved until this detail is fixed in pdns, one could argue **not** splitting on newlines and instead always submitting exactly one comment per RRset would be best. The field type in the database is TEXT, so it is **huge**, 64KB. I cannot speak for other backends, though. So until people actually run into this problem, splitting on newlines seems to be the safest way.

**Comment by spp2** [comment]
Same problem here, especially when migrating from heavily commented bind files; 
I thought it would be simple to extend the composite index for the comments to (name, type, Rdata) instead of the seemingly actual (name, type, order of appearance).

**Comment by Korkman** [comment]
I see PowerDNS Admin has a new popup entry for TXT records. The same popup could be used for comments, merging all comments from the same RRset into one text input and splitting on newlines as proposed previously. Output still poses a challenge, though. How about showing the first line from the comments in the first record, with an option to expand into a popup, and only the expansion link for following records?

**Comment by schwindp** [comment]
Sorry to bother, but this is a still existing issue, it just went stale...
