### ISSUE TITLE
unable to see the domains

### ISSUE THREAD

**Issue by ericcotelnu** [PowerDNS-Admin/PowerDNS-Admin#885]
Even though I'm the only user, and admin. Also, End of last year, I was able to access the domains in pDNS, and now, I can't. I've eliminated the only problem - the backend - and it's not pDNS itself. I could've missed something, but I doubt it right now.

**Comment by norve** [comment]
I have observed the same behavior when I encountered this issue @ #893 
Can you verify if you get the same error messages?

**Comment by jbe-dw** [comment]
I think domains on the dashboard page are loaded from the PDNS API each time you refresh the page. Check the url and key settings, and try to see in pdns if there are api request incoming.
It can be the pdns admin source address not allowed to access pdns api as well.
