### ISSUE TITLE
Cannot update domain table.

### ISSUE THREAD

**Issue by norve** [PowerDNS-Admin/PowerDNS-Admin#893]
```
[2021-03-02 05:28:05 +0000] [12] [ERROR] Cannot update domain table. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: domain.name
[SQL: INSERT INTO domain (name, master, type, serial, notified_serial, last_check, dnssec, account_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('example.com', '[]', 'Master', 1, 1, 0, 0, None)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2021-03-02 05:28:05,046] [domain.py:168] ERROR - Cannot update domain table. Error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: domain.name
[SQL: INSERT INTO domain (name, master, type, serial, notified_serial, last_check, dnssec, account_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('example.com', '[]', 'Master', 1, 1, 0, 0, None)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

I am running PowerDNS-Admin 0.2.3 with PowerDNS Authoritative Server 4.2.3.
I made some alterations to the docker-compose.yml and Dockerfile so that it uses SQLite instead of MySQL, the revisions are shown in the attached patch.
[PowerDNS-Admin-0.2.3_SQLite_docker.patch.txt](https://github.com/ngoduykhanh/PowerDNS-Admin/files/6078399/PowerDNS-Admin-0.2.3_SQLite_docker.patch.txt)

I checked /data/pda.db, and the domain table appears to be empty.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
