### ISSUE TITLE
Can't find a suitable configuration file in this directory 

### ISSUE THREAD

**Issue by jeevesmoss** [PowerDNS-Admin/PowerDNS-Admin#897]
When using the git clone I am getting the following error;

root@ns1:/opt/PowerDNS-Admin# docker-compose up
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

root@ns1:/opt/PowerDNS-Admin# ls docker-compose.yml
docker-compose.yml

When trying to get the image to work as a container to auto launch on boot, the container is not listed (as stated above).

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
