### ISSUE TITLE
Updating FreeBSD install instructions

### ISSUE THREAD

**Issue by LukaszMoskala** [PowerDNS-Admin/PowerDNS-Admin#899]
Hello everyone,

Since pull requests for github pages are not supported I belive, I wanted to share with you how I installed powerdns-admin on FreeBSD.
So, my PowerDNS-Admin is running on FreeBSD 12.2-RELEASE, so currently supported version, vs 12.1-RELEASE, which is EOL now.

Following instructions [here](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-on-FreeBSD) I found problem with python-ldap, as author of original instruction did. Instead of commenting it out using suggested
```bash
perl -pi -e 's,^python-ldap,\# python-ldap,' requirements.txt 
```
I set environment variable during pip install, like so:
```bash
C_INCLUDE_PATH=/usr/local/include pip3 install -r requirements.txt
```
I did everything else exactly as stated by the instructions, and it works. 
The envvar to set I found [here](https://github.com/python-ldap/python-ldap/issues/273/#issuecomment-621570517)

Finally, I decided to use gunicorn instead of run.py for running the app.

Following instructions from [here](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx) I wrote a script called `/opt/powerdns-admin/run-gunicorn.sh` with content:
```bash
#!/usr/local/bin/bash
cd /usr/local/PowerDNS-Admin
. /web/python/bin/activate
gunicorn --pid /var/run/powerdns-admin/pid --bind unix:/var/run/powerdns-admin/socket 'powerdnsadmin:create_app()'
```
I installed `py37-gunicorn` and used following initscript, at `/usr/local/etc/rc.d/pdnsadm`
```bash
#!/bin/sh

# PROVIDE: pdnsadm
# REQUIRE: LOGIN cleanvar sshd
# KEYWORD: shutdown


. /etc/rc.subr

name=pdnsadm
rcvar="${name}_enabled"
pidfile="/tmp/${name}.pid"
command="/usr/sbin/daemon"

command_args="-f -P ${pidfile} -u pdnsadm -r -R 10 /usr/local/PowerDNS-Admin/run-gunicorn.sh"

load_rc_config $name
run_rc_command "$1"
```
(note that this initscript runs powerdns-admin as user pdnsadm, specified by -u option).

And then I changed paths (/run to /var/run) in nginx config, started nginx and pdnsadm, and my web interface was accessible on port 80.

So with that said, I can clone wiki repo, update raw markdown file, and possibly upload it somewhere, so you can easily merge it into wiki's repo. Let me know, how I need to submit update for wiki.

**Comment by jbe-dw** [comment]
Thanks @LukaszMoskala we will update the docs

**Comment by AzorianSolutions** [comment]
Interested in a follow-up on this @dmcken?

**Comment by dmcken** [comment]
Sure, I can try to run this up although at this point looking at the FreeBSD site (https://www.freebsd.org/where/) the current Production Releases are 12.3 and 13.1 so I would say we should test against that.

**Comment by AzorianSolutions** [comment]
@dmcken That's what I was thinking as well. These will copy over to the next-gen project as well so no loss of value there.
