### ISSUE TITLE
"Help" button does not exist on pages

### ISSUE THREAD

**Issue by falz** [PowerDNS-Admin/PowerDNS-Admin#901]
It would be nice to have a config knob to enable a "Help" link on all unique page types.

This does not mean that inline help has to be created on this project however.

A quick fix would be to have this help hyperlink to a user configurable prefix, where the suffix is the type of page you're on. It's up to the admins to ensure that this link exists. This is trivial if using a wiki of some sort to host the help website.

**Comment by jbe-dw** [comment]
Hello,

Thanks, and sorry for the late answer. I will add this request to the pending list and close the issue, but before, I'd like to clear the request.

You want to add a toggle setting to enable a "help" button on each page type (domain, api keys, users, etc ...) that would redirect the user on a help page with detailed instructions ? And the link should live on the same host than PDA but with a configurable path ? Pointing to the included doc with an html compatible format ?

Can you give more details ?
Regards

**Comment by falz** [comment]
I am envisioning a 'help' button that links to a configureable URL that will give help on that specific page. 

Perhaps configure the tld

`helpurlbase = 'help.myorg.com/dns/'`

So, if you are at `/domain/` powerdns-admin page, the help page may link to helpbaseurl + '/domain/' ending up as help.myorg.com/dns/domain/

Unsure if it needs to be this configureable, or just have a help link that persists across ALL pages that you can point to.. something. In our case, it's to a wiki with further detailed instructions for end users.
