### ISSUE TITLE
history detail info is empty when api user

### ISSUE THREAD

**Issue by hailong1004** [PowerDNS-Admin/PowerDNS-Admin#904]
normal user can log detail，but api user's detail is empty. confirm api user has actuually taken effect.

![image](https://user-images.githubusercontent.com/18435715/110926854-deeae580-835f-11eb-9949-f637bfbb397a.png)

**Comment by jodygilbert** [comment]
I believe PR #890 resolves this issue

**Comment by hailong1004** [comment]
I think it is not the same problem as PR #980. My problem is that ordinary users can modify the dns record, and the detail information can be normally recorded in the history table of the database, but the dns record is modified by the api user, and the history table of the database is also recorded An operation message is sent, but the detail is empty

**Comment by jodygilbert** [comment]
Apologies, I should have been clearer, whilst working on the PR to allow the user role to view history, I noticed the issue you raised and fixed it in the PR I mentioned.

**Comment by jbe-dw** [comment]
Burn a candle to have your PR merged quickly. I hope it may invoke @ngoduykhanh a few moments to have a look at the last PRs and do a new release !
