### ISSUE TITLE
"Apply Changes" silently fails if browser doesn't send referrer

### ISSUE THREAD

**Issue by cboltz** [PowerDNS-Admin/PowerDNS-Admin#911]
For privacy reasons, I have my browser configured to never send a referrer.

Login to PowerDNS-Admin works, I can also do changes in a zone - but when I click "Apply Changes" and confirm that with "Apply", the changes do _not_ get saved. To make things even worse, there is no error message. The only difference is that the green "Success" box doesn't get displayed - but that's something you'll only notice if you know that it should be there.

Please improve this behaviour - options would be
* allow applying changes if no referrer is sent (only block "wrong" referrers, but not empty/missing ones) or
* display an error message (maybe already on login) so that the user knows what's going on, and can change to a different browser profile with referrer enabled

**Comment by jbe-dw** [comment]
Hello,

Thank you for the feedback. We will look into this once we will have reduced the ticket queue.

Regards

**Comment by meineerde** [comment]
The logs contain the following message when this occurs:

```
[flask_seasurf.py:307] WARNING - Forbidden (Referer checking failed: no referer.): /domain/example.com/apply
```
Flask-SeaSurf allows to configure [an app option](https://github.com/maxcountryman/flask-seasurf/blob/8b97bc64ad1c57a805c09006965a9dd9cff99316/flask_seasurf.py#L152) to disable this behavior with the `CSRF_CHECK_REFERER` option (defaults to `True`)

As such, you can entirely disable the checking of the Referer header by setting

```
CSRF_CHECK_REFERER = False
```

in your `FLASK_CONF` configuration file. This resolved the issue for me.

In the docker environment, this is not easily possible today, however, as the option is not an allowed environment variable in the [docker_config.py](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/configs/docker_config.py) file. The option (along with [the others](https://github.com/maxcountryman/flask-seasurf/blob/8b97bc64ad1c57a805c09006965a9dd9cff99316/flask_seasurf.py#L140-L152) could be easily added there though.
