### ISSUE TITLE
PowerDNS Admin configuration for LDAP backend

### ISSUE THREAD

**Issue by sharbich** [PowerDNS-Admin/PowerDNS-Admin#914]
Hello,
can I also administer PowerDNS with the GUI PowerDNS Admin if I use LDAP as the backend? In the documentation for PowerDNS Admin I can only find instructions for database backends.
I would be very happy about your support.
Greetings from Stefan Harbich

**Comment by jbe-dw** [comment]
Hello,

PDA is managing PowerDNS via its API, regardless of which backend is used. You have to enable PDNS API and configure PDA with url dans API Key.

The instructions are about the PDA database that must either be sqlite, mysql or postgresl.

Regards
