### ISSUE TITLE
slower behind reverse proxy, doesn't work with many dns entries

### ISSUE THREAD

**Issue by helmut72** [PowerDNS-Admin/PowerDNS-Admin#922]
I've configured PDA to work behind a Reverse Proxy. But then it getting noticable slower. On the main domain with many entries (nearly 400) it doesn't finish when clicking "Apply":

<img width="614" alt="Bildschirmfoto 2021-04-15 um 15 24 37" src="https://user-images.githubusercontent.com/1388751/114878678-c78c9580-9e00-11eb-9797-a1eff2a52d2f.png">

This will never be shown:

<img width="612" alt="Bildschirmfoto 2021-04-15 um 15 24 46" src="https://user-images.githubusercontent.com/1388751/114878722-d3785780-9e00-11eb-9635-3a50d20d59b3.png">

I've added all the Headers:
```
X-Forwarded-For:
X-Forwarded-Host:
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server:
X-Real-Ip:
```

Reverse Proxy (Apache) works fast for many other Webapplications.

**Comment by jbe-dw** [comment]
Hello,

Have you been able to fix your issue since ?

Regards

**Comment by helmut72** [comment]
Sorry, no. But I don't have wasted much time since then.

**Comment by helmut72** [comment]
I setup caddy in front of powerdns-admin docker container on the same machine. Since then it works.
