### ISSUE TITLE
Oops! Bad request Cannot add this domain. You may return to the dashboard.

### ISSUE THREAD

**Issue by yawdeals** [PowerDNS-Admin/PowerDNS-Admin#925]
I am getting this error and also not able to add a domain. What could i be doing wrong?

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
