### ISSUE TITLE
"OTP token" field suggests previous entries/values as autocompletion

### ISSUE THREAD

**Issue by sellerie98** [PowerDNS-Admin/PowerDNS-Admin#933]
Firefox 88.0 and Chromium 89 suggest autocompletion from previous entries to the "OTP token" field in the login form.
I would suggest disabling this since its pretty unlikely that OTP codes from previous entries/sessions/logins are ever relevant again.

**Comment by zoeller-freinet** [comment]
This should be implemented now by 7808feb.
