### ISSUE TITLE
API / account

### ISSUE THREAD

**Issue by verder** [PowerDNS-Admin/PowerDNS-Admin#934]
Hey, is it possible to add an API key from docker-compose and creating a user?  I saw https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/configs/docker_config.py#L5-L46  but nothing about API key, port and IP from powerdns server. 

I try 

envirnoment:
- PDNS_HOST=http://127.0.0.1:8080
- PDNS_API_KEY=changeme

but still nothing 

table settings is empty

**Comment by verder** [comment]
anyone?

**Comment by steschuser** [comment]
No, this is not possible yet.

Should be doable by hacking __init__.py tho

**Comment by jbe-dw** [comment]
Hello,

We plan to add further configuration through API and something to init the APP. We have no roadmap as the maintaining team is not heavily staffed.

Regards
