### ISSUE TITLE
PowerDNS-Admin stops responding if utf-8 decode fails

### ISSUE THREAD

**Issue by steschuser** [PowerDNS-Admin/PowerDNS-Admin#935]
The data from Powerdns is parsed to json with  json.loads(r.content.decode('utf-8'))
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/32983635c6bc51d2ca74496aa9cb0cf834fe2563/powerdnsadmin/lib/utils.py#L106

If this decoding step fails PowerDNS-Admin is unusable.

`powerdns_admin | [2021-05-21 12:49:53,756] [domain.py:119] INFO - Found 3033 domains in PowerDNS-Admin                                                                                       
powerdns_admin | [2021-05-21 12:49:54 +0000] [11] [ERROR] Cannot update domain table. Error: Error while loading JSON data from http://hostsystem:8081/api/v1/servers/localhost/zones        
powerdns_admin | [2021-05-21 12:49:54,394] [domain.py:168] ERROR - Cannot update domain table. Error: Error while loading JSON data from http://hostsystem:8081/api/v1/servers/localhost/zones
`

`powerdns_admin |   File "/app/powerdnsadmin/lib/utils.py", line 107, in fetch_json
powerdns_admin |     data = json.loads(r.content.decode('utf-8'))
powerdns_admin | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 504465: invalid continuation byte
`

**Comment by jbe-dw** [comment]
Hello,

Are you still able to reproduce ?

Thank you
