### ISSUE TITLE
API - Long response time due to GET (all zones) after single PATCH

### ISSUE THREAD

**Issue by FunRaiser1** [PowerDNS-Admin/PowerDNS-Admin#948]
Hello,

We have an issue with the PowerDNS-Admin API.  

As you can see in the debug log below, we perform a PATCH request to the PowerDNS-Admin API.  
The API command is instantly forwarded to the PowerDNS API.

After this transaction, PowerDNS-Admin performs a full GET for all zones to the PowerDNS-Admin API, which takes 6 seconds to finish.  After these 6 seconds, PowerDNS API is sending a response back to the API client.

Knowing that we are continuously performing many DNS updates using the API, this task is very slow.

Is there any way to avoid that PowerDNS-Admin performs a full GET after a PATCH API command?  We already tried to turn off bg_domain_updates, but that does not seem to help.

Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,710] [helper.py:18] DEBUG - Sending request to powerdns API {'rrsets': [{'name': '13.1.168.192.in-addr.arpa.', 'type': 'PTR', 'ttl': 86400, 'changetype': 'REPLACE', 'records': [{'content': 'michael7.test.eu.'}]}]}
Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,712] [connectionpool.py:226] DEBUG - Starting new HTTP connection (1): 127.0.0.1:8081
Jun  4 13:59:16  pdns_server[1111]: gmysql Connection successful. Connected to database 'powerdns' on '127.0.0.1'.
Jun  4 13:59:16  pdns_server[1111]: [webserver] 7fb24af0-cef1-49f2-8dda-46c9e8393123 127.0.0.1:34448 "PATCH /api/v1/servers/localhost/zones/1.168.192.in-addr.arpa HTTP/1.1" 204 337
Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,735] [connectionpool.py:433] DEBUG - http://127.0.0.1:8081 "PATCH /api/v1/servers/localhost/zones/1.168.192.in-addr.arpa HTTP/1.1" 204 0
Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,777] [domain.py:119] INFO - Found 1972 domains in PowerDNS-Admin
Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,781] [connectionpool.py:226] DEBUG - Starting new HTTP connection (1): 127.0.0.1:8081
Jun  4 13:59:16  pdns_server[1111]: gmysql Connection successful. Connected to database 'powerdns' on '127.0.0.1'.
Jun  4 13:59:16  pdns_server[1111]: [webserver] 36bc618f-2d06-4538-8704-f6dbe9316709 127.0.0.1:34452 "GET /api/v1/servers/localhost/zones HTTP/1.1" 200 550063
Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,845] [connectionpool.py:433] DEBUG - http://127.0.0.1:8081 "GET /api/v1/servers/localhost/zones HTTP/1.1" 200 549697
Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,847] [utils.py:54] DEBUG - Querying remote server "http://127.0.0.1:8081/api/v1/servers/localhost/zones" (GET) finished with code 200 (took 0.064254s)
Jun  4 13:59:16  gunicorn[2534]: [2021-06-04 13:59:16,854] [domain.py:130] INFO - Found 1972 zones in PowerDNS server
Jun  4 13:59:22  gunicorn[2534]: [2021-06-04 13:59:22,395] [domain.py:161] INFO - Update domain finished
Jun  4 13:59:22  gunicorn[2534]: [2021-06-04 13:59:22,399] [api.py:980] DEBUG - Request to powerdns API successful

Thank you.

**Comment by steschuser** [comment]
Hello,

I tried to replicate this but Im not seeing it.

Can you provide your request as a curl command?

**Comment by FunRaiser1** [comment]
Hello Steschuser,

We are perfoming the following:

curl -v -X PATCH --data '{"rrsets": [ {"name": "13.1.168.192.in-addr.arpa.", "type": "PTR", "ttl": 86400, "changetype": "REPLACE", "records": [ {"content": "michael7.test.eu." } ] } ] }' -H 'X-API-Key: <MYKEY>' -H 'Content-Type: application/json'  https://<IPADDR>/api/v1/servers/localhost/zones/1.168.192.in-addr.arpa/13
 

Kind Regards
Kristof van den Bergh

**Comment by steschuser** [comment]
Hello again,

I see it now, there is domain.update in that endpoint
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/32983635c6bc51d2ca74496aa9cb0cf834fe2563/powerdnsadmin/routes/api.py#L977

Not sure why its there or if it can be removed without side issues.
Can you outcomment that line and see if that works for you

```diff --git a/powerdnsadmin/routes/api.py b/powerdnsadmin/routes/api.py
index 6435261..720d635 100644
--- a/powerdnsadmin/routes/api.py
+++ b/powerdnsadmin/routes/api.py
@@ -974,7 +974,7 @@ def api_zone_subpath_forward(server_id, zone_id, subpath):
 def api_zone_forward(server_id, zone_id):
     resp = helper.forward_request()
     domain = Domain()
-    domain.update()
+    #domain.update()
     status = resp.status_code
     if 200 <= status < 300:
```

**Comment by steschuser** [comment]
I guess the correct way to handle this would be to check the "bg_domain_updates" switch.
If that setting is enabled, this api call should not force update

**Comment by FunRaiser1** [comment]
Hello,

Changing the bg_domain_updates parameter does not change anything.  It keeps on performing that domain.update() function.

Kind Regards
Kristof

**Comment by steschuser** [comment]
Yes, you need the https://github.com/ngoduykhanh/PowerDNS-Admin/pull/962
Its merged into master now, so simply update your PowerDNS-Admin
