### ISSUE TITLE
Feature: Allow per User Setting to create and remove domains

### ISSUE THREAD

**Issue by steschuser** [PowerDNS-Admin/PowerDNS-Admin#955]
Instead of a global User settings, allow creation and removing of domains on a per user basis

**Comment by steschuser** [comment]
#954

**Comment by falz** [comment]
how would one restrict what domains they can add? what if they add 'google.com', for example?

This doesn't sound like a feature that should be available to general users, where a user is perhaps a customer and not a trusted employee.

**Comment by steschuser** [comment]
Hello,

well, there is nothing to prevent users from adding whatever they want.

However, this is already possible with PowerDNS-Admin. In Settings->Basic is a switch that allows regular Users to create Domains.
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/32983635c6bc51d2ca74496aa9cb0cf834fe2563/powerdnsadmin/models/setting.py#L28
If you enable that setting, *all* Users may create Domains.

This PR adds per-User permissions, enabling *some* Users to create Domains.

Regards,
Steffen

**Comment by falz** [comment]
Is this what the "Operator" level is for? I'm not finding any docs on it.

**Comment by steschuser** [comment]
It depends a bit on your use-case.
The Operator has rights to every Domain, whereas User are limited to the Domains they are associated with.

So, its either limit the Operators to some Domains or grant some Users more power...

**Comment by jbe-dw** [comment]
Supported in #1171
