### ISSUE TITLE
Mechanism for Just-in-Time Provisioning of roles from external sources

### ISSUE THREAD

**Issue by KostasMparmparousis** [PowerDNS-Admin/PowerDNS-Admin#956]
Hello,
Our organisation (https://www.gunet.gr/en/) is considering adding a mechanism responsible for the just-in-time provisioning of powerdns-admin roles from external sources, like Lightweight Directory Access Protocol, Single sign-on and etc.

Larger organisations often have many active applications such as PowerDns-Admin. Therefore, we think that the need arises for there to be a central management mechanism that monitors every application available. That being said, we would like to attempt to add a new feature to powerdns-admin that supports the just-in-time provisioning from an external central management mechanism.

We think this could be possible by, depending on urn based values gathered from a release mechanism that PDNS Admin already supports, i.e LDAP, SSO, etc., POWERDNS-Admin will try to map it's user's roles  to any domain or account referenced.
This could be applied to users that have admin or operating rights in every domain, or users that only have access to specific domains/accounts.

Is this change in line with the general philosophy of powerdns-admin, and if so, shall we proceed implementing it?

**Comment by jbe-dw** [comment]
Hello,

Can you update this talk since you have pushed many PR related to this. If it became irrelevant because everything is coded you can close the issue.

Regards

**Comment by KostasMparmparousis** [comment]
Hello @jbe-dw 

You make a fair point and I will indeed close this issue. However, I would appreciate it if issue #1085 were to remain open (since it's thematically relevant), at least until a decision has been made in regards to PR [#1002](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1002) , PR #1083 and PR #1084, that are still pending.
