### ISSUE TITLE
Apply template to existing domain zone

### ISSUE THREAD

**Issue by usrflo** [PowerDNS-Admin/PowerDNS-Admin#959]
I could not find a way to apply a template to an existing domain zone: I guess this feature doesn't exist (yet)?

I'd like to see a template application function with an optional zone reset and merge of records into an existing zone.

**Comment by steschuser** [comment]
How much time do you spend on this if you do it manually?

This sounds like it would take some time to code, but is hardly ever used

**Comment by usrflo** [comment]
My use case is a frequent mailserver switch; see the records below. Currently I delete the old zone an re-create it with the template shown below.

```
		IN	A	123.123.123.123
		IN	MX	100	mail
		IN	TXT	"v=spf1 mx a include:spf.some.de include:_spf.another.net -all"

www		IN	A	123.123.123.123

mail		IN	A	213.213.213.213
mail		IN	AAAA	2a00:2a00:1000:2462::2

autoconfig	IN	CNAME	webhosting-autoconfig.another.de.
autodiscover.tcp IN	SRV	0 0 443 webhosting-autoconfig.another.de.
submission.tcp	 IN	SRV	0 1 587 mail.another.de.
imaps.tcp	 IN	SRV	0 1 993 mail.another.de.
imap.tcp	 IN	SRV	0 1 143 mail.another.de.
pop3s.tcp	 IN	SRV	10 1 995 mail.another.de.
pop3.tcp	 IN	SRV	10 1 110 mail.another.de.
```

**Comment by mrfrenzy** [comment]
It would be really nice if a domain could include autoconfig and SRV records from a domain/template similar to how SPF include works.
Something which would have to be abstracted by powerdns-admin or powerdns whenever the main "server" domain is updated.

In the meantime I use the script pdns-search-replace.sh by Claudio Kuenzler to search and replace all old records from template.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
