### ISSUE TITLE
Feature Request: When domain type MASTER add field to specify SLAVES (per zone metadata: ALLOW-AXFR-FROM)

### ISSUE THREAD

**Issue by arbaldin** [PowerDNS-Admin/PowerDNS-Admin#961]
When we add a slave domain (or change a domain type to slave) to PowerDNS-Admin we have a field in the Manage Domain view that allow us to specify the Master IP address. This request is to add a similar field to the master type, where we could specify the slaves IP addresses, editing the zone metadata ALLOW-AXFR-FROM.

**Comment by steschuser** [comment]
It seems like this cannot be set at all right now.
How do you set ALLOW-AXFR-FROM ?

**Comment by arbaldin** [comment]
It is possible to set this value from the linux shell where pdns is running. In the following doc page from pdns you can see it:

https://doc.powerdns.com/authoritative/domainmetadata.html

There are other metadata besides ALLOW-AXFR-FROM.

**Comment by Zetanova** [comment]
It should be easily be possible to extend the UI
It is the same as the `SOA-EDIT-API` setting

I would do it but my python skill is none existent.

powerdns admin: `domain manage`
![image](https://user-images.githubusercontent.com/1385312/133329215-0973eebe-57ef-471c-b0df-865782d5aae6.png)

phpmyadmin:
![image](https://user-images.githubusercontent.com/1385312/133329034-eac56932-5de1-4c6c-a602-8768836edd96.png)

**Comment by jbe-dw** [comment]
This could be part of #395

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Mentioned request #395 is already listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
