### ISSUE TITLE
Bug: Applying Templates can fail silently

### ISSUE THREAD

**Issue by steschuser** [PowerDNS-Admin/PowerDNS-Admin#963]
Its possible for records in a template to be invalid.
If the user tries to apply that template, that will fail without any visual hints, creating an empty domain instead

https://github.com/ngoduykhanh/PowerDNS-Admin/blob/32983635c6bc51d2ca74496aa9cb0cf834fe2563/powerdnsadmin/routes/domain.py#L237

**Comment by 7c** [comment]
I can confirm this behavior with current version 32983635c6bc51d2ca74496aa9cb0cf834fe2563 - if template has invalid record(s) then applying fails silently.

I also would love to see a version at UI to reference instead of commit hash

Thanks for great product.

**Comment by jbe-dw** [comment]
Hello,

This bug is still present, because we don't do record input validation and the template is applied in two steps (create domain then insert records).

Regards

**Comment by mzch** [comment]
I have the same issue in the latest, f6289d140cfa9f1c4ff9537d871ccbeec5483742.
