### ISSUE TITLE
ImportError undefined symbol: xmlSecCryptoAppKeysMngrCertLoad

### ISSUE THREAD

**Issue by duwenjun** [PowerDNS-Admin/PowerDNS-Admin#969]
ImportError: /data/wwwroot/powerdns-admin/flask/lib64/python3.6/site-packages/xmlsec.cpython-36m-x86_64-linux-gnu.so: undefined symbol: xmlSecCryptoAppKeysMngrCertLoad

centos8

**Comment by jbe-dw** [comment]
Hello,

I've run the [setup for CentOS 7](https://github.com/PowerDNS-Admin/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Centos-7) inside a CentOS 8 container successfully.

Regards

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
