### ISSUE TITLE
Huge number of records per domain -  PowerDNS Admin crashed

### ISSUE THREAD

**Issue by BadikovVV** [PowerDNS-Admin/PowerDNS-Admin#982]
I have more then 100 000 diff records per one zone (domain)
And when i`m trying to manage that zone -  PowerDNS Admin freezes.
Helps only "stop" loading page and Press "Home" link.
Server GET /domain/zzz.ru => generated 206733590 bytes in 90055 msecs (HTTP/1.1 200) 5 headers in 619 bytes (960 switches on core 0) (log from uwsgi)
Memory on client PC - 16GB
OS - Ubuntu 20.04 64bit
FireFox 90.0

**Comment by jbe-dw** [comment]
Have you tried to increase loglevel in gunicorn and your webserver (apache/nginx/...). There may be config limitation with a timeout or a memory limit.

This project is not particularily active and may not be sized to such a big deployment.

**Comment by steschuser** [comment]
Have you tried enable the Update in Background switch?

By default, PowerDNSAdmin will try to sync with the PowerDNS Server when you hit dashboard.
Switching to background_sync should keep frontend rresponsive

**Comment by steschuser** [comment]
![image](https://user-images.githubusercontent.com/28826568/132500359-8259f56c-e6c9-4b0f-9867-bb65ae67be52.png)

**Comment by BadikovVV** [comment]
Thank you, i'll try it after vocation (on Monday).Viacheslav.8 сент. 2021 г. 14:19 пользователь steschuser ***@***.***> написал:
Have you tried enable the Update in Background switch?
By default, PowerDNSAdmin will try to sync with the PowerDNS Server when you hit dashboard.
Switching to background_sync should keep frontend rresponsive

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
