### ISSUE TITLE
Feature Request: Support OpenLDAP nested group membership

### ISSUE THREAD

**Issue by dmgeurts** [PowerDNS-Admin/PowerDNS-Admin#987]
I've just installed and tested PDA with OpenLDAP using a FreeIPA. And nested group membership isn't working. Is there a flag that can be set to enable traversing nested groups for finding users?

**Comment by steschuser** [comment]
Hello,

can you provide an example?
How is your LDAP Tree, what error message do you get?

Regards,
Steffen

**Comment by dmgeurts** [comment]
Apologies for the late reply. The error in the web interface is invalid credentials. If there's a good way of troubleshooting this from the pdns-admin server please let me know.

I'm using FreeIPA, in pdns-admin group security is enabled and the paths of the groups are configured like so:
Admin group: cn=powerdns-admin,cn=groups,cn=accounts,dc=EXAMPLE,dc=COM
Operator group: cn=powerdns-ops,cn=groups,cn=accounts,dc=EXAMPLE,dc=COM
User group: cn=powerdns-ro,cn=groups,cn=accounts,dc=EXAMPLE,dc=COM

If I add a user to these groups they can login to PowerDNS-admin. However, if I add a group to these groups then the user cannot login. I'm testing single a tier hierarchy at the moment. Aka group 'engineering' is part of 'powerdns-admin'. All groups involved are posix. If I check indirect membership in FreeIPA the users show up under the powerdns-admin group.

Apologies if this is not the best description, I'm by no means well versed in LDAP.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
