### ISSUE TITLE
Feature Request: Allow posixGroup support in LDAP GROUP SECURITY

### ISSUE THREAD

**Issue by CheBushe** [PowerDNS-Admin/PowerDNS-Admin#991]
Hi.
when I try to use "GROUP SECURITY" I get "Invalid credentials" but without "GROUP SECURITY" I successfully login.
By setting "GUNICORN_LOGLEVEL=DEBUG" I see:
- ERROR - User testuser3 is not part of the "cn=admins,ou=groups,dc=domain,dc=tld", "cn=IT_DEPT,ou=groups,dc=domain,dc=tld" or "cn=users,ou=groups,dc=domain,dc=tld" groups that allow access to PowerDNS-Admin 
- [DEBUG] Ldap groupSearchFilter (&(memberUid=uid=testuser3,ou=users,dc=domain,dc=tld)(objectClass=posixGroup))

but my opinion is that the filter should be:
(&(memberUid=testuser3)(objectClass=posixGroup))

**Comment by Hatzl** [comment]
I have the same problem..

**Comment by CheBushe** [comment]
This is because we are using posixGroup instead of groupOfNames.
As I understood from reading: https://ldapwiki.com/wiki/GroupOfUniqueNames%20vs%20groupOfNames

groupOfNames stores its members in the Member attribute using FDN as the value, but posixGroup stores its members in the Uid attribute using RDN.

But PowerDNS-Admin doesnt care about differ of LDAP schemes and mandatory use FDN for filter.

**Comment by jbe-dw** [comment]
You're absolutely right about this. But adding what you're asking is not just about changing the filter, as groupOfNames wouldn't work anymore. An option should be added to use posixGroups or groupOfNames, the requires modifying the gui, the database, and the source code !

Someone can propose a PR to do this, until then you have to stick to groupOfNames instead.

**Comment by steschuser** [comment]
Im confused
You should be able to change that in the settings
![image](https://user-images.githubusercontent.com/28826568/132503297-fa500426-d41e-4c46-bf31-a365439612e4.png)

Whats missing?

**Comment by jbe-dw** [comment]
```
                    ldap_username = ldap.filter.escape_filter_chars(
                        ldap_result[0][0][0])
```
I guess that the user's DN is returned, and the member field in a group of name is a list of DNs, but in the memberuid field of a posixGroup it is the uid, so

```
groupSearchFilter = "(&({0}={1}){2})".format(LDAP_FILTER_GROUPNAME, ldap_username, LDAP_FILTER_GROUP)
```
is triggering the log posted `[DEBUG] Ldap groupSearchFilter (&(memberUid=uid=testuser3,ou=users,dc=domain,dc=tld)(objectClass=posixGroup))`

**Comment by jbe-dw** [comment]
Hello,

I'm changing this issue to a feature request. I think it is not included yet.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy
