### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by cto741** [PowerDNS-Admin/PowerDNS-Admin#995]
On URL: 
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Using-PowerDNS-Admin-with-PostgreSQL

It says: "In your config.py file, make sure you have".
**Where is the config.py?** 
E.g. vi /path/to/config.py 

Rather than put: 

---BEGIN---
You might need to adjust your PostgreSQL's pg_hba.conf config file to allow password authentication for networks.
---END---

Put in: 
```
[root@host ~]$  sudo su - postgres
[postgres@host ~]$  vi ~/data/pg_hba.conf
# add 'local all powerdnsadmin md5' line **before** 'local all all peer' line
# (typical mistake is "just" appending the line at the and of the file)

local   all             powerdnsadmin                           md5
local   all             all                                     peer


##   # TYPE  DATABASE    USER            ADDRESS                 METHOD
##                    
##-> local   all         testuser                                md5
##-> local   all         all                                     peer
## 
##   # "local" is for Unix domain socket connections only
##   local   all         all                                     peer

# On this line change the word "ident" to "trust"
##   # IPv4 local connections:
##-> host    all         all             127.0.0.1/32            trust

# save and quit (Esc:wq)

[postgres@host ~]$ exit
[root@host ~]$  sudo systemctl restart postgresql
```

Oh and change the order to group the database items together.

**Comment by jbe-dw** [comment]
Hello,

We will check sooner or later the documentation. 

Thanks for the feedback.

**Comment by dmcken** [comment]
The config.py may not actually exist it is supposed to refer to the file pointed to by FLASK_CONF which is a file in the configs directory (e.g. /configs/production.py).

**Comment by AzorianSolutions** [comment]
This has been resolved by [PR 1302](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1302).
